server {
    listen 80;
    server_name dev.lets-git-it.kr
                api-dev.lets-git-it.kr
                redis-dev.lets-git-it.kr
                grafana-dev.lets-git-it.kr
                agent-dev.lets-git-it.kr;
    return 301 https://$host$request_uri;
}
