# Rate Limit 설정
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=30r/s;
limit_req_zone $binary_remote_addr zone=ws_limit:10m rate=10r/s;

# HTTP → HTTPS 리다이렉트
server {
    listen 80;
    server_name dev.lets-git-it.kr redis-dev.lets-git-it.kr api-dev.lets-git-it.kr;
    return 301 https://$host$request_uri;
}

# 개발계 서비스 (FE)
server {
    listen 443 ssl;
    server_name dev.lets-git-it.kr;
    ssl_certificate /etc/letsencrypt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/privkey.pem;

    # React 정적 파일 서빙
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

# 개발계 서비스 (BE)
server {
    listen 443 ssl;
    server_name api-dev.lets-git-it.kr;
    ssl_certificate /etc/letsencrypt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/privkey.pem;

    location / {
        limit_req zone=api_limit burst=50 nodelay;
        proxy_pass http://spring:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSocket 라우팅
    #location /ws/ {
    #    limit_req zone=ws_limit burst=20 nodelay;
    #    proxy_pass http://spring:8080;
    #    proxy_http_version 1.1;
    #    proxy_set_header Upgrade $http_upgrade;
    #    proxy_set_header Connection "upgrade";
    #    proxy_set_header Host $host;
    #    proxy_read_timeout 3600s;
    #}
}

# RedisInsight GUI
server {
    listen 443 ssl;
    server_name redis-dev.lets-git-it.kr;
    ssl_certificate /etc/letsencrypt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/privkey.pem;

    location / {
        proxy_pass http://redisinsight:5540;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
