server {
    listen 443 ssl;
    server_name redis-dev.lets-git-it.kr;

    ssl_certificate /etc/letsencrypt/live/dev.lets-git-it.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.lets-git-it.kr/privkey.pem;

    location / {
        proxy_pass http://redisinsight:5540;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
