spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

redis:
  auth:
    host: ${DEV_REDIS_AUTH_HOST}
    port: ${DEV_REDIS_AUTH_PORT}

  game:
    host: ${DEV_REDIS_GAME_HOST}
    port: ${DEV_REDIS_GAME_PORT}

  ranking:
    host: ${DEV_REDIS_RANKING_HOST}
    port: ${DEV_REDIS_RANKING_PORT}