spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  h2:
    console:
      enabled: false

server:
  port: 8080

logging:
  level:
    com.gitcat.letsgitit: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

redis:
  auth:
    host: ${PROD_REDIS_AUTH_HOST}
    port: ${PROD_REDIS_AUTH_PORT}

  game:
    host: ${PROD_REDIS_GAME_HOST}
    port: ${PROD_REDIS_GAME_PORT}

  ranking:
    host: ${PROD_REDIS_RANKING_HOST}
    port: ${PROD_REDIS_RANKING_PORT}