spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.gitlab.letsgitit: DEBUG