/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TimeattackRouteImport } from './routes/timeattack'
import { Route as SingleRouteImport } from './routes/single'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MultiRouteImport } from './routes/multi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CoopRouteImport } from './routes/coop'
import { Route as ContributionRouteImport } from './routes/contribution'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultiRoomIdRouteImport } from './routes/multi.$roomId'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth.callback.google'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeattackRoute = TimeattackRouteImport.update({
  id: '/timeattack',
  path: '/timeattack',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleRoute = SingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoute = MultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CoopRoute = CoopRouteImport.update({
  id: '/coop',
  path: '/coop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionRoute = ContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoomIdRoute = MultiRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => MultiRoute,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribution': typeof ContributionRoute
  '/coop': typeof CoopRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/multi': typeof MultiRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/single': typeof SingleRoute
  '/timeattack': typeof TimeattackRoute
  '/tutorial': typeof TutorialRoute
  '/multi/$roomId': typeof MultiRoomIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribution': typeof ContributionRoute
  '/coop': typeof CoopRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/multi': typeof MultiRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/single': typeof SingleRoute
  '/timeattack': typeof TimeattackRoute
  '/tutorial': typeof TutorialRoute
  '/multi/$roomId': typeof MultiRoomIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribution': typeof ContributionRoute
  '/coop': typeof CoopRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/multi': typeof MultiRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/single': typeof SingleRoute
  '/timeattack': typeof TimeattackRoute
  '/tutorial': typeof TutorialRoute
  '/multi/$roomId': typeof MultiRoomIdRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribution'
    | '/coop'
    | '/home'
    | '/login'
    | '/multi'
    | '/onboarding'
    | '/single'
    | '/timeattack'
    | '/tutorial'
    | '/multi/$roomId'
    | '/auth/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribution'
    | '/coop'
    | '/home'
    | '/login'
    | '/multi'
    | '/onboarding'
    | '/single'
    | '/timeattack'
    | '/tutorial'
    | '/multi/$roomId'
    | '/auth/callback/google'
  id:
    | '__root__'
    | '/'
    | '/contribution'
    | '/coop'
    | '/home'
    | '/login'
    | '/multi'
    | '/onboarding'
    | '/single'
    | '/timeattack'
    | '/tutorial'
    | '/multi/$roomId'
    | '/auth/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributionRoute: typeof ContributionRoute
  CoopRoute: typeof CoopRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MultiRoute: typeof MultiRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SingleRoute: typeof SingleRoute
  TimeattackRoute: typeof TimeattackRoute
  TutorialRoute: typeof TutorialRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeattack': {
      id: '/timeattack'
      path: '/timeattack'
      fullPath: '/timeattack'
      preLoaderRoute: typeof TimeattackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single': {
      id: '/single'
      path: '/single'
      fullPath: '/single'
      preLoaderRoute: typeof SingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi': {
      id: '/multi'
      path: '/multi'
      fullPath: '/multi'
      preLoaderRoute: typeof MultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coop': {
      id: '/coop'
      path: '/coop'
      fullPath: '/coop'
      preLoaderRoute: typeof CoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribution': {
      id: '/contribution'
      path: '/contribution'
      fullPath: '/contribution'
      preLoaderRoute: typeof ContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi/$roomId': {
      id: '/multi/$roomId'
      path: '/$roomId'
      fullPath: '/multi/$roomId'
      preLoaderRoute: typeof MultiRoomIdRouteImport
      parentRoute: typeof MultiRoute
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MultiRouteChildren {
  MultiRoomIdRoute: typeof MultiRoomIdRoute
}

const MultiRouteChildren: MultiRouteChildren = {
  MultiRoomIdRoute: MultiRoomIdRoute,
}

const MultiRouteWithChildren = MultiRoute._addFileChildren(MultiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributionRoute: ContributionRoute,
  CoopRoute: CoopRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MultiRoute: MultiRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SingleRoute: SingleRoute,
  TimeattackRoute: TimeattackRoute,
  TutorialRoute: TutorialRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
