/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeattackRouteImport } from './routes/timeattack'
import { Route as SingleRouteImport } from './routes/single'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as MultiRouteImport } from './routes/multi'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as CoopRouteImport } from './routes/coop'
import { Route as ContributionRouteImport } from './routes/contribution'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MultiRoomIdRouteImport } from './routes/multi.$roomId'

const TimeattackRoute = TimeattackRouteImport.update({
  id: '/timeattack',
  path: '/timeattack',
  getParentRoute: () => rootRouteImport,
} as any)
const SingleRoute = SingleRouteImport.update({
  id: '/single',
  path: '/single',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoute = MultiRouteImport.update({
  id: '/multi',
  path: '/multi',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const CoopRoute = CoopRouteImport.update({
  id: '/coop',
  path: '/coop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributionRoute = ContributionRouteImport.update({
  id: '/contribution',
  path: '/contribution',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiRoomIdRoute = MultiRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => MultiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contribution': typeof ContributionRoute
  '/coop': typeof CoopRoute
  '/dictionary': typeof DictionaryRoute
  '/home': typeof HomeRoute
  '/multi': typeof MultiRouteWithChildren
  '/mypage': typeof MypageRoute
  '/ranking': typeof RankingRoute
  '/single': typeof SingleRoute
  '/timeattack': typeof TimeattackRoute
  '/multi/$roomId': typeof MultiRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contribution': typeof ContributionRoute
  '/coop': typeof CoopRoute
  '/dictionary': typeof DictionaryRoute
  '/home': typeof HomeRoute
  '/multi': typeof MultiRouteWithChildren
  '/mypage': typeof MypageRoute
  '/ranking': typeof RankingRoute
  '/single': typeof SingleRoute
  '/timeattack': typeof TimeattackRoute
  '/multi/$roomId': typeof MultiRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contribution': typeof ContributionRoute
  '/coop': typeof CoopRoute
  '/dictionary': typeof DictionaryRoute
  '/home': typeof HomeRoute
  '/multi': typeof MultiRouteWithChildren
  '/mypage': typeof MypageRoute
  '/ranking': typeof RankingRoute
  '/single': typeof SingleRoute
  '/timeattack': typeof TimeattackRoute
  '/multi/$roomId': typeof MultiRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contribution'
    | '/coop'
    | '/dictionary'
    | '/home'
    | '/multi'
    | '/mypage'
    | '/ranking'
    | '/single'
    | '/timeattack'
    | '/multi/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contribution'
    | '/coop'
    | '/dictionary'
    | '/home'
    | '/multi'
    | '/mypage'
    | '/ranking'
    | '/single'
    | '/timeattack'
    | '/multi/$roomId'
  id:
    | '__root__'
    | '/'
    | '/contribution'
    | '/coop'
    | '/dictionary'
    | '/home'
    | '/multi'
    | '/mypage'
    | '/ranking'
    | '/single'
    | '/timeattack'
    | '/multi/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContributionRoute: typeof ContributionRoute
  CoopRoute: typeof CoopRoute
  DictionaryRoute: typeof DictionaryRoute
  HomeRoute: typeof HomeRoute
  MultiRoute: typeof MultiRouteWithChildren
  MypageRoute: typeof MypageRoute
  RankingRoute: typeof RankingRoute
  SingleRoute: typeof SingleRoute
  TimeattackRoute: typeof TimeattackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeattack': {
      id: '/timeattack'
      path: '/timeattack'
      fullPath: '/timeattack'
      preLoaderRoute: typeof TimeattackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/single': {
      id: '/single'
      path: '/single'
      fullPath: '/single'
      preLoaderRoute: typeof SingleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi': {
      id: '/multi'
      path: '/multi'
      fullPath: '/multi'
      preLoaderRoute: typeof MultiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coop': {
      id: '/coop'
      path: '/coop'
      fullPath: '/coop'
      preLoaderRoute: typeof CoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribution': {
      id: '/contribution'
      path: '/contribution'
      fullPath: '/contribution'
      preLoaderRoute: typeof ContributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi/$roomId': {
      id: '/multi/$roomId'
      path: '/$roomId'
      fullPath: '/multi/$roomId'
      preLoaderRoute: typeof MultiRoomIdRouteImport
      parentRoute: typeof MultiRoute
    }
  }
}

interface MultiRouteChildren {
  MultiRoomIdRoute: typeof MultiRoomIdRoute
}

const MultiRouteChildren: MultiRouteChildren = {
  MultiRoomIdRoute: MultiRoomIdRoute,
}

const MultiRouteWithChildren = MultiRoute._addFileChildren(MultiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContributionRoute: ContributionRoute,
  CoopRoute: CoopRoute,
  DictionaryRoute: DictionaryRoute,
  HomeRoute: HomeRoute,
  MultiRoute: MultiRouteWithChildren,
  MypageRoute: MypageRoute,
  RankingRoute: RankingRoute,
  SingleRoute: SingleRoute,
  TimeattackRoute: TimeattackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
