services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-dev-data:/var/lib/mysql
    restart: always
    networks:
      - letsgit-dev
    environment:
      - TZ=Asia/Seoul

  redis-auth:
    image: redis:7-alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
    volumes:
      - redis-auth-dev-data:/data
    command: >
      redis-server
      --appendonly yes
      --save 300 1
    restart: always
    networks:
      - letsgit-dev
    environment:
      - TZ=Asia/Seoul

  redis-game:
    image: redis:7-alpine
    container_name: redis-game
    ports:
      - "6380:6380"
    command: >
      redis-server
      --save ""
      --appendonly no
      --port 6380
    restart: always
    networks:
      - letsgit-dev
    environment:
      - TZ=Asia/Seoul

  redis-ranking:
    image: redis:7-alpine
    container_name: redis-ranking
    ports:
      - "6381:6381"
    volumes:
      - redis-ranking-dev-data:/data
    command: >
      redis-server
      --appendonly yes
      --save 300 1
      --port 6381
    restart: always
    networks:
      - letsgit-dev
    environment:
      - TZ=Asia/Seoul

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-dev-data:/data
    restart: always
    networks:
      - letsgit-dev
    environment:
      - TZ=Asia/Seoul

volumes:
  mysql-dev-data:
  redis-auth-dev-data:
  redis-ranking-dev-data:
  redisinsight-dev-data:

networks:
  letsgit-dev:
    name: letsgit-dev
    external: true
