services:
  nginx:
    build:
      context: ..
      dockerfile: INFRA/Dockerfile.fe
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - letsgit-dev
    environment:
      - TZ=Asia/Seoul
networks:
  letsgit-dev:
    name: letsgit-dev
    external: true
