services:

  spring:
    build:
      context: ../BE/letsgitit
      dockerfile: ../../INFRA/Dockerfile.be
    container_name: spring
    ports:
      - "8080:8080"
    env_file:
      - ../BE/letsgitit/.env
    environment:
      - REDIS_AUTH_HOST=redis-auth
      - REDIS_GAME_HOST=redis-game
      - REDIS_RANKING_HOST=redis-ranking
      - MYSQL_HOST=mysql
      - TZ=Asia/Seoul
      - JAVA_TOOL_OPTIONS=-Duser.timezone=Asia/Seoul
    restart: always
    networks:
      - letsgit-dev

networks:
  letsgit-dev:
    name: letsgit-dev
    external: true
