git-show-ref(1)
===============

NAME
----
git-show-ref - 로컬 저장소의 참조를 나열합니다

SYNOPSIS
--------
[verse]
'git show-ref' [--head] [-d | --dereference]
	     [-s | --hash[=<n>]] [--abbrev[=<n>]] [--branches] [--tags]
	     [--] [<pattern>...]
'git show-ref' --verify [-q | --quiet] [-d | --dereference]
	     [-s | --hash[=<n>]] [--abbrev[=<n>]]
	     [--] [<ref>...]
'git show-ref' --exclude-existing[=<pattern>]
'git show-ref' --exists <ref>

DESCRIPTION
-----------

로컬 저장소에서 사용 가능한 참조와 해당 커밋 ID를 표시합니다. 결과는 패턴을 사용하여 필터링할 수 있으며, 태그는 객체 ID로 역참조될 수 있습니다. 또한, 특정 ref가 존재하는지 테스트하는 데 사용할 수 있습니다.

기본적으로 태그, 헤드, 원격 ref를 표시합니다.

`--exclude-existing` 형식은 반대 역할을 하는 필터입니다. stdin으로부터 한 줄에 하나의 ref씩 읽어와 로컬 저장소에 존재하지 않는 ref를 표시합니다.

`--exists` 형식은 단일 ref의 존재 여부를 확인하는 데 사용할 수 있습니다. 이 형식은 실제 객체로 확인되는 참조인지 검증하지 않습니다.

`.git` 디렉토리 아래의 파일을 직접 접근하는 대신 이 유틸리티의 사용을 권장합니다.

OPTIONS
-------

--head::

	HEAD 참조를 표시합니다. 일반적으로 필터링되는 경우에도 표시됩니다.

--branches::
--tags::

	각각 로컬 브랜치와 로컬 태그로 제한합니다. 이 옵션들은 상호 배타적이지 않으며, 둘 다 지정하면 "refs/heads"와 "refs/tags"에 저장된 참조가 표시됩니다. `--heads`는 `--branches`의 폐기된 동의어이며 향후 제거될 수 있습니다.

-d::
--dereference::

	태그를 객체 ID로도 역참조합니다. `^{}`이 appended되어 표시됩니다.

-s::
--hash[=<n>]::

	OID만 표시하고 참조 이름은 표시하지 않습니다. `--dereference`와 함께 사용될 때, 역참조된 태그는 여전히 OID 뒤에 표시됩니다.

--verify::

	정확한 ref 경로를 요구하여 더 엄격한 참조 검사를 활성화합니다.
	종료 코드 1을 반환하는 것 외에도, `--quiet`이 지정되지 않은 경우 오류 메시지를 인쇄합니다.

--exists::

	주어진 참조가 존재하는지 확인합니다. 참조가 존재하면 종료 코드 0을 반환하고, 누락된 경우 2를 반환하며, 참조 누락 외의 오류로 확인에 실패하면 1을 반환합니다.

--abbrev[=<n>]::

	객체 이름을 약칭합니다. `--hash`를 사용할 때 `--hash --abbrev`를 따로 말할 필요 없이 `--hash=n`으로 충분합니다.

-q::
--quiet::

	stdout으로 결과를 출력하지 않습니다. `--verify`와 함께 사용하여 참조가 존재하는지 조용히 확인할 수 있습니다.

--exclude-existing[=<pattern>]::

	`git show-ref`가 `^(?:<anything>\s)?<refname>(?:\^{})?$` 형식으로 stdin에서 ref를 읽어오는 필터로 작동하게 합니다.
	각각에 대해 다음 작업을 수행합니다:
	(1) 행 끝의 `^{}`를 제거 (있는 경우);
	(2) 패턴이 제공되고 refname과 일치하지 않으면 무시;
	(3) refname이 올바른 refname이 아니면 경고하고 건너뜀;
	(4) refname이 로컬 저장소에 있는 ref이면 무시;
	(5) 그렇지 않으면 해당 줄을 출력.


<pattern>...::

	하나 이상의 패턴과 일치하는 참조를 표시합니다. 패턴은 전체 이름의 끝에서부터 일치하며, 완전한 부분만 일치합니다. 예를 들어, 'master'는 'refs/heads/master', 'refs/remotes/origin/master', 'refs/tags/jedi/master'와 일치하지만 'refs/heads/mymaster' 또는 'refs/remotes/master/jedi'와는 일치하지 않습니다.

OUTPUT
------

출력 형식은 다음과 같습니다:

------------
<oid> SP <ref> LF
------------

예시:

-----------------------------------------------------------------------------
$ git show-ref --head --dereference
832e76a9899f560a90ffd62ae2ce83bbeff58f54 HEAD
832e76a9899f560a90ffd62ae2ce83bbeff58f54 refs/heads/master
832e76a9899f560a90ffd62ae2ce83bbeff58f54 refs/heads/origin
3521017556c5de4159da4615a39fa4d5d2c279b5 refs/tags/v0.99.9c
6ddc0964034342519a87fe013781abf31c6db6ad refs/tags/v0.99.9c^{}
055e4ae3ae6eb344cbabf2a5256a49ea66040131 refs/tags/v1.0rc4
423325a2d24638ddcc82ce47be5e40be550f4507 refs/tags/v1.0rc4^{}
...
-----------------------------------------------------------------------------

`--hash` (그리고 `--dereference`가 아닌 경우)를 사용할 때, 출력 형식은 다음과 같습니다:

------------
<oid> LF
------------

예시:

-----------------------------------------------------------------------------
$ git show-ref --branches --hash
2e3ba0114a1f52b47df29743d6915d056be13278
185008ae97960c8d551adcd9e23565194651b5d1
03adf42c988195b50e1a1935ba5fcbc39b2b029b
...
-----------------------------------------------------------------------------

EXAMPLES
--------

"master"라고 불리는 모든 참조를 태그, 헤드 또는 다른 무엇이든 상관없이,
참조 명명 계층의 깊이에 상관없이 표시하려면 다음을 사용합니다:

-----------------------------------------------------------------------------
	git show-ref master
-----------------------------------------------------------------------------

이것은 "refs/heads/master" 뿐만 아니라 "refs/remote/other-repo/master"도 표시합니다.
그러한 참조가 존재하는 경우.

`--verify` 플래그를 사용할 때, 명령은 정확한 경로를 요구합니다:

-----------------------------------------------------------------------------
	git show-ref --verify refs/heads/master
-----------------------------------------------------------------------------

은 "master"라는 정확한 브랜치만 일치시킵니다.

일치하는 것이 없으면, `git show-ref`는 오류 코드 1을 반환하고,
검증의 경우 오류 메시지를 표시합니다.

스크립팅을 위해 `--quiet` 플래그를 사용하여 조용하게 만들 수 있으며,
이를 통해 다음과 같은 작업을 수행할 수 있습니다:

-----------------------------------------------------------------------------
	git show-ref --quiet --verify -- "refs/heads/$headname" ||
		echo "$headname is not a valid branch"
-----------------------------------------------------------------------------

특정 브랜치가 존재하는지 여부를 확인합니다 (실제로 결과를 표시하고 싶지 않으며,
모호한 부분 일치로 인한 문제를 피하기 위해 전체 refname을 사용합니다).

태그만 표시하거나, 올바른 브랜치 헤드만 표시하려면 각각 `--tags` 및/또는 `--branches`를 사용합니다.
(두 개를 모두 사용하면 태그와 브랜치를 표시하지만, "refs/" 하위 디렉토리의 다른 임의 참조는 표시하지 않습니다).

자동 태그 객체 역참조를 수행하려면 `-d` 또는 `--dereference` 플래그를 사용합니다.
그러면 다음과 같이 할 수 있습니다:

-----------------------------------------------------------------------------
	git show-ref --tags --dereference
-----------------------------------------------------------------------------

모든 태그 목록과 해당 역참조 대상의 목록을 얻을 수 있습니다.

FILES
-----
`.git/refs/*`, `.git/packed-refs`

SEE ALSO
--------
linkgit:git-for-each-ref[1],
linkgit:git-ls-remote[1],
linkgit:git-update-ref[1],
linkgit:gitrepository-layout[5]

GIT
---
linkgit:git[1] 제품군의 일부