git-repo(1)
===========

NAME
----
git-repo - 저장소에 대한 정보 검색

SYNOPSIS
--------
[synopsis]
git repo info [--format=(lines|nul) | -z] [--all | <key>...]
git repo info --keys [--format=(lines|nul) | -z]
git repo structure [--format=(table|lines|nul) | -z]

DESCRIPTION
-----------
저장소에 대한 정보를 검색합니다.

이 명령어는 실험적인 기능입니다. 동작이 변경될 수 있습니다.

COMMANDS
--------
`info [--format=(lines|nul) | -z] [--all | <key>...]`::
	현재 저장소에 대한 메타데이터 관련 정보를 검색합니다. 요청된 키에 따라 (아래 "INFO KEYS" 섹션 참조) 요청된 데이터만 반환됩니다.
+
값은 해당 키가 요청된 순서대로 반환됩니다. `--all` 플래그는 사용 가능한 모든 키에 대한 값을 요청합니다.
+
출력 형식은 `--format` 플래그를 통해 선택할 수 있습니다. 두 가지 형식이 지원됩니다:
+

`lines`:::
	키-값 쌍을 한 줄에 하나씩 출력하며, 키와 값 사이의 구분자로 `=` 문자를 사용합니다. "특이한" 문자를 포함하는 값은 `core.quotePath` 설정 변수에 대해 설명된 대로 따옴표로 묶입니다 (linkgit:git-config[1] 참조). 이것이 기본값입니다.

`nul`:::
	`lines`와 유사하지만, 키와 값 사이의 구분자로 하이픈 문자를 사용하고 각 값 뒤에 _NUL_ 문자를 사용합니다. 이 형식은 `lines` 형식보다 다른 애플리케이션에서 구문 분석하기에 더 적합합니다. `lines` 형식과 달리 값에는 따옴표가 붙지 않습니다.
+
`-z`는 `--format=nul`의 별칭입니다.

`info --keys [--format=(lines|nul) | -z]`::
	사용 가능한 모든 키를 한 줄에 하나씩 나열합니다. 출력 형식은 `--format` 플래그를 통해 선택할 수 있습니다. 다음 형식이 지원됩니다:
+
`lines`:::
	키를 한 줄에 하나씩 출력합니다. 이것이 기본값입니다.

`nul`:::
	`lines`와 유사하지만, 각 값 뒤에 _NUL_ 문자를 사용합니다.

`structure [--format=(table|lines|nul) | -z]`::
	현재 저장소 구조에 대한 통계를 검색합니다. 다음과 같은 종류의 정보가 보고됩니다:
+
* 유형별 참조 카운트
* 유형별 도달 가능한 객체 카운트
* 유형별 도달 가능한 객체의 총 압축 해제 크기
* 유형별 도달 가능한 객체의 총 디스크 크기
* 유형별 저장소에서 가장 큰 도달 가능한 객체
+
출력 형식은 `--format` 플래그를 통해 선택할 수 있습니다. 세 가지 형식이 지원됩니다:
+
`table`:::
	저장소 통계를 사람이 읽기 쉬운 테이블 형식으로 출력합니다. 이 형식은 변경될 수 있으며 기계적 구문 분석을 위한 것이 아닙니다. 이것이 기본 형식입니다.

`lines`:::
	출력의 각 줄은 저장소 통계에 대한 키-값 쌍을 포함합니다. 키와 값 사이의 구분자로 '=' 문자가 사용됩니다. "특이한" 문자를 포함하는 값은 `core.quotePath` 설정 변수에 대해 설명된 대로 따옴표로 묶입니다 (linkgit:git-config[1] 참조).

`nul`:::
	`lines`와 유사하지만, 하이픈 대신 키-값 쌍 사이를 구분하기 위해 _NUL_ 문자를 사용합니다. 또한 '=' 대신 키와 값 사이를 구분하기 위해 하이픈 문자를 사용합니다. `lines` 형식과 달리 "특이한" 문자를 포함하는 값에는 절대로 따옴표가 붙지 않습니다.
+
`-z`는 `--format=nul`의 별칭입니다.

INFO KEYS
---------
`git repo info`에서 값을 얻으려면 해당 값을 식별하는 키를 제공해야 합니다. 다음은 사용 가능한 키와 해당 키가 반환하는 값 목록입니다:

`layout.bare`::
	{true}이면 베어 저장소이고, 그렇지 않으면 {false}입니다.

`layout.shallow`::
	{true}이면 얕은 저장소이고, 그렇지 않으면 {false}입니다.

`object.format`::
	저장소에서 사용되는 객체 형식 (해시 알고리즘)입니다.

`references.format`::
	참조 저장 형식입니다. 유효한 값은 다음과 같습니다:
+
include::ref-storage-format.adoc[]

EXAMPLES
--------

* 현재 저장소의 참조 형식을 검색합니다:
+
------------
git repo info references.format
------------
+

* `nul` 형식을 사용하여 현재 저장소가 베어인지 그리고 얕은지 검색합니다:
+
------------
git repo info --format=nul layout.bare layout.shallow
------------

SEE ALSO
--------
linkgit:git-rev-parse[1]

GIT
---
linkgit:git[1] 제품군의 일부입니다.