git-commit-graph(1)
===================

NAME
----
git-commit-graph - Git 커밋-그래프 파일 작성 및 검증


SYNOPSIS
--------
[verse]
'git commit-graph verify' [--object-dir <dir>] [--shallow] [--[no-]progress]
'git commit-graph write' [--object-dir <dir>] [--append]
			[--split[=<strategy>]] [--reachable | --stdin-packs | --stdin-commits]
			[--changed-paths] [--[no-]max-new-filters <n>] [--[no-]progress]
			<split-options>


DESCRIPTION
-----------

직렬화된 커밋-그래프 파일을 관리합니다.


OPTIONS
-------
--object-dir::
	팩파일 및 커밋-그래프 파일의 위치로 지정된 디렉토리를 사용합니다. 이 매개변수는 완전한 `.git` 디렉토리가 아닌 objects 디렉토리만 가진 대체 위치를 지정하기 위해 존재합니다. 커밋-그래프 파일은 `<dir>/info` 디렉토리에 있고, 팩파일은 `<dir>/pack`에 있는 것으로 예상됩니다. 디렉토리를 절대 경로로 만들 수 없거나 알려진 객체 디렉토리와 일치하지 않으면 `git commit-graph ...`는 0이 아닌 상태 코드로 종료됩니다.

--progress::
--no-progress::
	진행 상황 표시를 명시적으로 켜거나 끕니다. 둘 다 지정되지 않은 경우, 표준 에러가 터미널에 연결되어 있으면 진행 상황이 표시됩니다.

COMMANDS
--------
'write'::

팩파일에서 발견된 커밋을 기반으로 커밋-그래프 파일을 작성합니다. `core.commitGraph` 설정 옵션이 비활성화된 경우, 이 명령어는 경고를 출력하고 커밋-그래프 파일을 작성하지 않고 성공적으로 반환합니다.
+
`--stdin-packs` 옵션을 사용하면, 지정된 팩-인덱스의 객체만 탐색하여 새 커밋 그래프를 생성합니다. (`--stdin-commits` 또는 `--reachable`과 함께 사용할 수 없습니다.)
+
`--stdin-commits` 옵션을 사용하면, 표준 입력으로 지정된 커밋에서 시작하여 16진수 OID 목록으로, 각 OID는 한 줄에 표시됩니다. 커밋이 아닌 것으로 해석되는 OID (직접 또는 태그를 벗겨냄으로써)는 조용히 무시됩니다. 잘못 형식이 지정되었거나 존재하지 않는 OID는 오류를 생성합니다. (`--stdin-packs` 또는 `--reachable`과 함께 사용할 수 없습니다.)
+
`--reachable` 옵션을 사용하면, 모든 ref에서 시작하여 커밋을 탐색하여 새 커밋 그래프를 생성합니다. (`--stdin-commits` 또는 `--stdin-packs`와 함께 사용할 수 없습니다.)
+
`--append` 옵션을 사용하면, 기존 커밋-그래프 파일에 있는 모든 커밋을 포함합니다.
+
`--changed-paths` 옵션을 사용하면, 커밋과 그 첫 번째 부모 간의 경로에 대한 정보를 계산하고 작성합니다. 이 작업은 대규모 저장소에서 시간이 오래 걸릴 수 있습니다. `git log -- <path>`를 사용하여 디렉토리 또는 파일의 이력을 얻는 데 상당한 성능 향상을 제공합니다. 이 옵션이 주어지면, 향후 커밋-그래프 작성 시 이 옵션이 의도된 것으로 자동 가정됩니다. 이 데이터 저장을 중지하려면 `--no-changed-paths`를 사용하십시오. `--changed-paths`는 `commitGraph.changedPaths=true` 설정에 의해 암시됩니다.
+
`--max-new-filters=<n>` 옵션을 사용하면, 최대 `n`개의 새 Bloom 필터( `--changed-paths`가 지정된 경우)를 생성합니다. `n`이 `-1`이면 제한이 적용되지 않습니다. 새 레이어에 존재하는 커밋만 이 제한에 포함됩니다. 이전 레이어에 대한 Bloom 필터를 소급하여 계산하려면 `--split=replace`를 사용하는 것이 좋습니다. `commitGraph.maxNewFilters` 설정을 재정의합니다.
+
`--split[=<strategy>]` 옵션을 사용하면, 커밋-그래프를 `<dir>/info/commit-graphs`에 저장된 여러 커밋-그래프 파일의 체인으로 작성합니다. 커밋-그래프 레이어는 전략 및 기타 분할 옵션에 따라 병합됩니다. 커밋-그래프에 이미 없는 새 커밋은 새 "팁" 파일에 추가됩니다. 이 파일은 다음 병합 조건이 충족되면 기존 파일과 병합됩니다.
+
* `--split=no-merge`가 지정된 경우, 병합은 수행되지 않으며 나머지 옵션은 무시됩니다. `--split=replace`는 기존 체인을 새 체인으로 덮어씁니다. 베어 `--split`은 나머지 옵션으로 넘어갑니다. (커밋 그래프 체인을 병합하면 기존 체인이 길이 1의 체인으로 대체되며, 첫 번째와 유일한 증분화된 부분이 전체 그래프를 가지고 있다고 주장합니다).
+
* `--size-multiple=<X>`가 지정되지 않은 경우, `X`를 2로 설정합니다. 새 팁 파일이 `N`개의 커밋을 가지고 있고 이전 팁이 `M`개의 커밋을 가지고 있으며 `X` 곱하기 `N`이 `M`보다 크면, 대신 두 파일을 하나의 파일로 병합합니다.
+
* `M`이 양의 정수인 `--max-commits=<M>`이 지정되고 새 팁 파일이 `M`개보다 많은 커밋을 포함하게 되면, 대신 새 팁을 이전 팁과 병합합니다.
+
마지막으로, `--expire-time=<datetime>`이 지정되지 않은 경우, `datetime`을 현재 시간으로 설정합니다. 분할된 커밋-그래프를 작성한 후, 수정 시간이 `datetime`보다 오래된 사용되지 않는 모든 커밋-그래프를 삭제합니다.

'verify'::

커밋-그래프 파일을 읽고 객체 데이터베이스에 대한 내용을 검증합니다. 손상된 데이터를 확인하는 데 사용됩니다.
+
`--shallow` 옵션을 사용하면, 분할된 커밋-그래프 체인에서 팁 커밋-그래프 파일만 확인합니다.


EXAMPLES
--------

* 로컬 `.git` 디렉토리의 팩된 커밋에 대한 커밋-그래프 파일을 작성합니다.
+
------------------------------------------------
$ git commit-graph write
------------------------------------------------

* 현재 커밋-그래프 파일을 확장하면서 `<pack-index>`의 커밋을 사용하는 커밋-그래프 파일을 작성합니다.
+
------------------------------------------------
$ echo <pack-index> | git commit-graph write --stdin-packs
------------------------------------------------

* 도달 가능한 모든 커밋을 포함하는 커밋-그래프 파일을 작성합니다.
+
------------------------------------------------
$ git show-ref -s | git commit-graph write --stdin-commits
------------------------------------------------

* 현재 커밋-그래프 파일의 모든 커밋과 `HEAD`에서 도달 가능한 커밋을 포함하는 커밋-그래프 파일을 작성합니다.
+
------------------------------------------------
$ git rev-parse HEAD | git commit-graph write --stdin-commits --append
------------------------------------------------

CAVEATS
-------

대체 객체 또는 커밋 그래프의 존재는 커밋-그래프 읽기 또는 쓰기를 비활성화합니다. linkgit:git-replace[1]을 참조하십시오.

CONFIGURATION
-------------
include::includes/cmd-config-section-all.adoc[]

include::config/commitgraph.adoc[]


FILE FORMAT
-----------

linkgit:gitformat-commit-graph[5]를 참조하십시오.

GIT
---
linkgit:git[1] 제품군의 일부