git-blame(1)
============

NAME
----
git-blame - Show what revision and author last modified each line of a file

SYNOPSIS
--------
[synopsis]
git blame [-c] [-b] [-l] [--root] [-t] [-f] [-n] [-s] [-e] [-p] [-w] [--incremental]
	  [-L <range>] [-S <revs-file>] [-M] [-C] [-C] [-C] [--since=<date>]
	  [--ignore-rev <rev>] [--ignore-revs-file <file>]
	  [--color-lines] [--color-by-age] [--progress] [--abbrev=<n>]
	  [ --contents <file> ] [<rev> | --reverse <rev>..<rev>] [--] <file>

DESCRIPTION
-----------

주어진 파일의 각 줄이 마지막으로 수정된 커밋에서의 정보로 주석을 답니다. 선택적으로, 지정된 커밋부터 주석을 시작할 수 있습니다.

`-L`을 하나 이상 지정하면 요청된 줄로만 주석을 제한합니다.

줄의 출처는 전체 파일 이름 변경에서도 자동으로 추적됩니다 (현재 이름 변경 추적을 끄는 옵션은 없습니다). 다른 파일로 이동된 줄을 추적하거나, 다른 파일에서 복사하여 붙여넣은 줄을 추적하려면 `-C` 및 `-M` 옵션을 참조하십시오.

보고서는 삭제되거나 대체된 줄에 대해서는 아무것도 알려주지 않습니다. `git diff`와 같은 도구나 다음 단락에서 간략하게 언급된 "피크액스" 인터페이스를 사용해야 합니다.

파일 주석을 지원하는 것 외에도, Git은 코드 조각이 변경 사항에서 발생한 시점을 추적하는 기록을 검색하는 것도 지원합니다. 이를 통해 코드 조각이 파일에 추가된 시점, 파일 간에 이동하거나 복사된 시점, 그리고 최종적으로 삭제되거나 대체된 시점을 추적할 수 있습니다. 이는 diff에서 텍스트 문자열을 검색하여 작동합니다. `blame_usage`를 검색하는 피크액스 인터페이스의 작은 예시는 다음과 같습니다:

-----------------------------------------------------------------------------
$ git log --pretty=oneline -S'blame_usage'
5040f17eba15504bad66b14a645bddd9b015ebb7 blame -S <ancestry-file>
ea4c7f9bf69e781dd0cd88d2bccb2bf5cc15c9a7 git-blame: Make the output
-----------------------------------------------------------------------------

OPTIONS
-------
include::blame-options.adoc[]

`-c`::
	`linkgit:git-annotate[1]`와 동일한 출력 모드를 사용합니다 (기본값: 꺼짐).

`--score-debug`::
	파일 간 줄 이동 ( `-C` 참조) 및 파일 내 줄 이동 ( `-M` 참조)과 관련된 디버깅 정보를 포함합니다. 처음에 나열된 숫자는 점수입니다. 이 숫자는 `git blame`이 해당 코드 줄을 이동한 것으로 간주하기 위해 넘어야 하는 특정 임계값입니다.
	이것은 파일 간에 또는 파일 내에서 이동한 것으로 감지된 영숫자 문자의 수입니다.

`-f`::
`--show-name`::
	원본 커밋에서 파일 이름을 표시합니다. 기본적으로 이름 변경 감지로 인해 다른 이름의 파일에서 온 줄이 있으면 파일 이름이 표시됩니다.

`-n`::
`--show-number`::
	원본 커밋에서 줄 번호를 표시합니다 (기본값: 꺼짐).

`-s`::
	출력에서 작성자 이름과 타임스탬프를 억제합니다.

`-e`::
`--show-email`::
	작성자 이름 대신 작성자 이메일을 표시합니다 (기본값: 꺼짐).
	이것은 `blame.showEmail` 설정 옵션을 통해 제어할 수도 있습니다.

`-w`::
	부모 버전과 자식 버전을 비교하여 줄이 어디에서 왔는지 찾을 때 공백을 무시합니다.

include::diff-algorithm-option.adoc[]

`--abbrev=<n>`::
	기본 _7+1_ 개의 16진수 자릿수 대신, _<m>_+1 개의 자릿수를 사용합니다. 여기서 _<m>_ 은 적어도 _<n>_ 이지만 커밋 객체 이름을 고유하게 만듭니다.
	주의: 1개의 열은 캐럿을 사용하여 경계 커밋을 표시하는 데 사용됩니다.


THE DEFAULT FORMAT
------------------

`--porcelain` 또는 `--incremental` 옵션이 지정되지 않은 경우,
`git blame`은 각 줄에 대해 다음과 같은 주석을 출력합니다:

- 줄이 나온 커밋의 약칭 객체 이름;
- 작성자 식별자 (기본값은 작성자 이름과 날짜이며, `-s` 또는 `-e`가 지정된 경우는 제외); 그리고
- 줄 번호

줄 내용 앞에 나옵니다.

THE PORCELAIN FORMAT
--------------------

이 형식에서는 각 줄이 헤더 다음에 출력됩니다. 최소한 다음을 포함하는 첫 번째 줄이 헤더에 있습니다:

- 줄이 속한 커밋의 40바이트 SHA-1;
- 원본 파일의 해당 줄의 줄 번호;
- 최종 파일의 해당 줄의 줄 번호;
- 이전 커밋과 다른 커밋에서 온 줄 그룹을 시작하는 줄에는 이 그룹의 줄 수가 있습니다. 후속 줄에는 이 필드가 없습니다.

이 헤더 줄 다음에는 각 커밋에 대해 최소 한 번 다음 정보가 나옵니다:

- 작성자 이름 (`author`), 이메일 (`author-mail`), 시간 (`author-time`), 및 시간대 (`author-tz`); 커미터에 대해서도 유사합니다.
- 줄이 속한 커밋에서의 파일 이름.
- 커밋 로그 메시지의 첫 번째 줄 (`summary`).

실제 줄의 내용은 위의 헤더 다음에 _TAB_으로 접두사가 붙어 출력됩니다. 이것은 나중에 더 많은 헤더 요소를 추가할 수 있도록 하기 위함입니다.

Porcelain 형식은 일반적으로 이미 본 커밋 정보를 억제합니다. 예를 들어, 같은 커밋으로 blame된 두 줄이 모두 표시되지만, 해당 커밋에 대한 세부 정보는 한 번만 표시됩니다. 개별 줄에 특정한 정보는 그룹화되지 않습니다. 예를 들어, `ignored` 또는 `unblamable`로 표시될 커밋들은 그렇지 않습니다. 이것은 더 효율적이지만, 읽는 쪽에서 더 많은 상태를 유지해야 할 수 있습니다. `--line-porcelain` 옵션을 사용하여 각 줄에 대한 전체 커밋 정보를 출력할 수 있어, 다음과 같이 더 간단하지만 (덜 효율적인) 사용이 가능합니다:

	# 각 작성자에게 속한 줄 수를 셉니다
	git blame --line-porcelain file |
	sed -n 's/^author //p' |
	sort | uniq -c | sort -rn


SPECIFYING RANGES
-----------------

이전 버전의 git에서 `git blame` 및 `git annotate`와 달리, 주석의 범위는 줄 범위 및 커밋 범위 모두로 제한될 수 있습니다. `-L` 옵션은 줄 범위로 주석을 제한하며, 여러 번 지정할 수 있습니다.

`foo` 파일의 40-60번 줄의 출처를 찾는 데 관심이 있다면, 다음과 같이 `-L` 옵션을 사용할 수 있습니다 (둘은 같은 의미입니다 -- 둘 다 40번 줄에서 시작하는 21개 줄을 요청합니다):

	git blame -L 40,60 foo
	git blame -L 40,+21 foo

정규 표현식을 사용하여 줄 범위를 지정할 수도 있습니다:

	git blame -L '/^sub hello {/,/^}$/' foo

이는 `hello` 서브루틴의 본문으로 주석을 제한합니다.

v2.6.18 버전보다 오래된 변경 사항이나 3주보다 오래된 변경 사항에 관심이 없다면, `git rev-list`와 유사한 커밋 범위 지정자를 사용할 수 있습니다:

	git blame v2.6.18.. -- foo
	git blame --since=3.weeks -- foo

범위 지정자를 사용하여 주석을 제한할 때, 범위 경계 (위 예시에서 v2.6.18 커밋 또는 3주보다 오래되지 않은 가장 최근 커밋) 이후로 변경되지 않은 줄은 해당 범위 경계 커밋에 대해 blame됩니다.

특히 유용한 방법은 추가된 파일에 기존 파일에서 복사-붙여넣기로 생성된 줄이 있는지 확인하는 것입니다. 때로는 개발자가 게으르거나 코드를 제대로 리팩토링하지 않았음을 나타낼 수 있습니다. 먼저 파일을 도입한 커밋을 다음과 같이 찾을 수 있습니다:

	git log --diff-filter=A --pretty=short -- foo

그런 다음 커밋과 그 부모 간의 변경 사항을 $commit^! 표기법을 사용하여 주석 처리할 수 있습니다:

	git blame -C -C -f $commit^! -- foo


INCREMENTAL OUTPUT
------------------

`--incremental` 옵션으로 호출되면, 명령어는 빌드되는 대로 결과를 출력합니다. 출력은 일반적으로 최근 커밋에서 처리된 줄에 대해 먼저 이야기합니다 (즉, 줄은 순서대로 주석 처리되지 않으며) 인터랙티브 뷰어에서 사용하도록 의도되었습니다.

출력 형식은 Porcelain 형식과 유사하지만, 주석 처리되는 파일의 실제 줄은 포함하지 않습니다.

. 각 blame 항목은 항상 다음 줄로 시작합니다:
+
[synopsis]
<40-byte-hex-sha1> <sourceline> <resultline> <num-lines>
+
줄 번호는 1부터 시작합니다.

. 커밋이 스트림에 처음 표시될 때, 각 줄의 시작 부분에 한 단어로 태그가 붙은 다양한 추가 정보 (작성자, 이메일, 커미터, 날짜, 요약 등)가 출력됩니다.

. Porcelain 형식과 달리, 파일 이름 정보는 항상 제공되며 항목을 종료합니다:
+
[synopsis]
filename <whitespace-quoted-filename-goes-here>
+
따라서 스크립팅 언어에 익숙한 줄 및 단어 지향 파서가 쉽게 파싱할 수 있습니다.
+
[NOTE]
파싱하는 사람들을 위해: 더 견고하게 하려면, 첫 번째 줄 (_<40-byte-hex-sha1>_)과 마지막 줄 (`filename`) 사이의 줄 중에서 태그 단어를 인식하지 못하거나 (또는 해당 태그 하나에 관심이 없는) "확장 정보" 줄의 시작 부분을 무시하십시오. 이런 식으로, 커밋 인코딩이나 확장 커밋 논평과 같은 정보가 추가되더라도 blame 뷰어는 신경 쓰지 않을 것입니다.


MAPPING AUTHORS
---------------

linkgit:gitmailmap[5] 를 참조하십시오.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/blame.adoc[]

SEE ALSO
--------
linkgit:git-annotate[1]

GIT
---
linkgit:git[1] 제품군의 일부