git-check-ignore(1)
===================

NAME
----
git-check-ignore - gitignore / exclude 파일 디버깅

SYNOPSIS
--------
[verse]
'git check-ignore' [<options>] <pathname>...
'git check-ignore' [<options>] --stdin

DESCRIPTION
-----------

명령줄 또는 `--stdin`을 통해 파일로부터 주어진 각 pathname에 대해,
파일이 .gitignore (또는 exclude 메커니즘의 다른 입력 파일)에 의해 제외되는지 확인하고,
제외되는 경우 해당 경로를 출력합니다.

기본적으로 추적된 파일은 제외 규칙의 대상이 아니므로 전혀 표시되지 않습니다.
하지만 `--no-index` 옵션을 참조하십시오.

OPTIONS
-------
-q::
--quiet::
	아무것도 출력하지 않고 종료 상태만 설정합니다.
	이것은 단일 pathname에 대해서만 유효합니다.

-v::
--verbose::
	제외되는 경로를 출력하는 대신, 제외 패턴과 일치하는 각 경로에 대해
	해당 경로와 함께 제외 패턴을 출력합니다.
	(제외 패턴과 일치한다는 것은 일반적으로 해당 경로가 제외된다는 것을 의미하지만,
	패턴이 "`!`"로 시작하는 경우 이는 부정된 패턴이며,
	이것과 일치하면 해당 경로는 제외되지 않음을 의미합니다.)
+
내부 및 제외 소스 간의 우선순위 규칙은 linkgit:gitignore[5]를 참조하십시오.

--stdin::
	명령줄 대신 표준 입력으로부터 한 줄에 하나씩 pathname을 읽어옵니다.

-z::
	출력 형식이 기계가 파싱할 수 있도록 수정됩니다 (아래 참조).
	`--stdin`도 함께 주어진 경우, 입력 경로는 줄바꿈 문자 대신 NUL 문자로 구분됩니다.

-n::
--non-matching::
	어떤 패턴과도 일치하지 않는 주어진 경로를 표시합니다.
	이것은 `--verbose`가 활성화된 경우에만 의미가 있습니다.
	그렇지 않으면 패턴과 일치하는 경로와 일치하지 않는 경로를 구별할 수 없을 것입니다.

--no-index::
	확인을 수행할 때 인덱스를 검색하지 않습니다.
	예를 들어 `git add .`에 의해 경로가 추적되어 예상대로 사용자 패턴에 의해 무시되지 않은 이유를
	디버깅하거나, 이전에 `git add -f`로 추가된 경로와 일치시키기 위해
	부정을 포함하는 패턴을 개발할 때 사용할 수 있습니다.

OUTPUT
------

기본적으로, 주어진 pathname 중 무시 패턴과 일치하는 것은 한 줄에 하나씩 출력됩니다.
주어진 경로에 패턴이 일치하지 않으면 해당 경로에 대해 아무것도 출력되지 않습니다.
이는 해당 경로가 무시되지 않음을 의미합니다.

`--verbose`가 지정되면, 출력은 다음과 같은 형식의 일련의 줄입니다:

<source> <COLON> <linenum> <COLON> <pattern> <HT> <pathname>

`<pathname>`은 쿼리 중인 파일의 경로이고, `<pattern>`은 일치하는 패턴이며,
`<source>`는 패턴의 소스 파일이고, `<linenum>`은 해당 소스 내에서 패턴의 줄 번호입니다.
패턴에 "`!`" 접두사 또는 "`/`" 접미사가 포함된 경우 출력에 유지됩니다.
`<source>`는 `core.excludesFile`에 의해 구성된 파일을 참조할 때 절대 경로가 되거나,
`.git/info/exclude` 또는 디렉토리별 제외 파일을 참조할 때 저장소 루트에 상대적인 경로가 됩니다.

`-z`가 지정되면, 출력의 pathname은 null 문자로 구분됩니다.
`--verbose`도 함께 지정된 경우 null 문자가 콜론과 탭 대신 사용됩니다:

<source> <NULL> <linenum> <NULL> <pattern> <NULL> <pathname> <NULL>

`-n` 또는 `--non-matching`이 지정되면, 일치하지 않는 pathname도 출력됩니다.
이 경우 각 출력 레코드에서 `<pathname>`을 제외한 모든 필드는 비어 있습니다.
이것은 비대화형으로 실행할 때 유용할 수 있습니다.
파일을 점진적으로 긴 시간 실행되는 check-ignore 프로세스의 STDIN으로 스트리밍할 수 있으며,
이러한 각 파일에 대해 STDOUT은 해당 파일이 패턴과 일치했는지 여부를 표시합니다.
(이 옵션이 없으면, 주어진 파일에 대한 출력의 부재가 패턴과 일치하지 않았다는 것인지,
또는 출력이 아직 생성되지 않았다는 것인지 구별할 수 없을 것입니다.)

버퍼링은 linkgit:git[1]의 `GIT_FLUSH` 옵션에 문서화된 대로 발생합니다.
호출자는 입력 버퍼를 과도하게 채우거나 빈 출력 버퍼에서 읽는 것으로 인한
교착 상태를 피할 책임이 있습니다.

EXIT STATUS
-----------

0::
	제공된 경로 중 하나 이상이 무시됩니다.

1::
	제공된 경로 중 어느 것도 무시되지 않습니다.

128::
	치명적인 오류가 발생했습니다.

SEE ALSO
--------
linkgit:gitignore[5]
linkgit:git-config[1]
linkgit:git-ls-files[1]

GIT
---
linkgit:git[1] 제품군의 일부입니다.