git-cvsexportcommit(1)
======================

NAME
----
git-cvsexportcommit - 단일 커밋을 CVS 체크아웃으로 내보내기


SYNOPSIS
--------
[verse]
'git cvsexportcommit' [-h] [-u] [-v] [-c] [-P] [-p] [-a] [-d <cvsroot>]
	[-w <cvs-workdir>] [-W] [-f] [-m <msgprefix>] [<parent-commit>] <commit-id>


DESCRIPTION
-----------
Git에서 커밋을 CVS 체크아웃으로 내보내어 Git 저장소의 패치를 CVS 저장소로 병합하는 작업을 용이하게 합니다.

-w 스위치를 사용하여 CVS 체크아웃의 이름을 지정하거나 CVS 작업 복사본의 루트에서 실행하십시오. 후자의 경우 GIT_DIR이 정의되어야 합니다. 아래 예제를 참조하십시오.

이 스크립트는 안전한 작업을 최선으로 수행하며, 파일이 변경되지 않았고 CVS 체크아웃에서 최신 상태인지 확인하며, 기본적으로 자동 커밋을 수행하지 않습니다.

파일 추가, 제거 및 바이너리 파일에 영향을 미치는 커밋을 지원합니다.

커밋이 병합 커밋인 경우, 변경 세트가 어떤 부모를 기준으로 수행되어야 하는지 'git cvsexportcommit'에 알려주어야 합니다.

OPTIONS
-------

-c::
	패치가 깔끔하게 적용되면 자동으로 커밋합니다. 패치 덩어리 적용에 실패하거나 다른 문제가 발생하면 커밋하지 않습니다.

-p::
	패치 적용 시 상세하게(편집증적) 수행합니다. `--fuzz=0`으로 patch를 호출합니다.

-a::
	작성자 정보를 추가합니다. 작성자 줄과 커미터(작성자와 다른 경우)를 메시지에 추가합니다.

-d::
	사용할 대안 CVSROOT를 설정합니다. 이는 CVS `-d` 매개변수에 해당합니다. 일반적으로 비대칭 방식으로 CVS를 사용하는 경우가 아니면 사용자는 이를 설정할 필요가 없습니다.

-f::
	파일이 최신 상태가 아니더라도 병합을 강제 실행합니다.

-P::
	직접적인 부모가 아니더라도 부모 커밋을 강제 실행합니다.

-m::
	제공된 접두사로 커밋 메시지를 앞에 붙입니다.
	패치 시리즈 등에 유용합니다.

-u::
	내보내기를 시도하기 전에 CVS 저장소에서 영향을 받은 파일을 업데이트합니다.

-k::
	작업 중인 CVS 체크아웃에서 CVS 키워드 확장을 반전시킵니다 (예: $Revision: 1.2.3.4$가 $Revision$이 됨). 패치를 적용하기 전에 수행합니다.

-w::
	내보내기에 사용할 CVS 체크아웃의 위치를 지정합니다. 이 옵션은 현재 디렉토리가 Git 저장소 내에 있는 경우 실행 전에 GIT_DIR을 설정할 필요가 없습니다. 기본값은 'cvsexportcommit.cvsdir'의 값입니다.

-W::
	현재 작업 디렉토리가 Git 체크아웃뿐만 아니라 CVS 체크아웃이기도 함을 cvsexportcommit에 알립니다. 따라서 Git은 진행하기 전에 작업 디렉토리를 부모 커밋으로 리셋합니다.

-v::
	상세하게 출력합니다.

CONFIGURATION
-------------
cvsexportcommit.cvsdir::
	내보내기에 사용할 CVS 체크아웃의 기본 위치입니다.

EXAMPLES
--------

하나의 패치를 CVS로 병합::
+
------------
$ export GIT_DIR=~/project/.git
$ cd ~/project_cvs_checkout
$ git cvsexportcommit -v <commit-sha1>
$ cvs commit -F .msg <files>
------------

패치를 CVS로 병합 (-c 및 -w 옵션 사용). 작업 디렉토리는 Git 저장소 내에 있습니다::
+
------------
	$ git cvsexportcommit -v -c -w ~/project_cvs_checkout <commit-sha1>
------------

보류 중인 패치를 CVS로 자동 병합 -- 정말로 무엇을 하고 있는지 알고 있는 경우에만::
+
------------
$ export GIT_DIR=~/project/.git
$ cd ~/project_cvs_checkout
$ git cherry cvshead myhead | sed -n 's/^+ //p' | xargs -l1 git cvsexportcommit -c -p -v
------------

GIT
---
linkgit:git[1] 제품군의 일부입니다.