git-diff-tree(1)
================

NAME
----
git-diff-tree - Compares the content and mode of blobs found via two tree objects


SYNOPSIS
--------
[verse]
'git diff-tree' [--stdin] [-m] [-s] [-v] [--no-commit-id] [--pretty]
	      [-t] [-r] [-c | --cc] [--combined-all-paths] [--root] [--merge-base]
	      [<common-diff-options>] <tree-ish> [<tree-ish>] [<path>...]

DESCRIPTION
-----------
두 개의 트리 객체를 통해 찾은 blob의 내용과 모드를 비교합니다.

`<tree-ish>`가 하나만 주어진 경우, 해당 커밋은 부모와 비교됩니다 (아래 `--stdin` 참조).

`git diff-tree`는 커밋 객체에 캡슐화된 트리를 사용할 수 있습니다.

OPTIONS
-------
include::diff-options.adoc[]

<tree-ish>::
	트리 객체의 ID입니다.

<path>...::
	제공된 경우, 결과는 제공된 pathspec 중 하나와 일치하는 파일의 하위 집합으로 제한됩니다.

-r::
	하위 트리로 재귀합니다.

-t::
	하위 트리뿐만 아니라 트리 항목 자체도 표시합니다. `-r`을 암시합니다.

--root::
	`--root`가 지정되면 초기 커밋이 큰 생성 이벤트로 표시됩니다. 이는 NULL 트리와의 diff와 동일합니다.

--merge-base::
	`<tree-ish>`를 직접 비교하는 대신, 두 `<tree-ish>` 간의 머지 베이스를 "이전" 측으로 사용합니다.
	두 개의 `<tree-ish>`가 주어져야 하며 둘 다 커밋이어야 합니다.

--stdin::
	`--stdin`이 지정되면, 이 명령어는 커맨드 라인에서 `<tree-ish>` 인자를 받지 않습니다.
	대신, 표준 입력에서 두 개의 `<tree>`, 하나의 `<commit>`, 또는 `<commit>` 목록을 포함하는 줄을 읽습니다. (구분자로 단일 공백을 사용합니다.)
+
두 개의 트리가 주어지면, 첫 번째 트리를 두 번째 트리와 비교합니다.
단일 커밋이 주어지면, 해당 커밋을 부모와 비교합니다.
그 다음 커밋들은 첫 번째 커밋의 부모인 것처럼 사용됩니다.
+
두 트리를 비교할 때, 두 트리의 ID (공백으로 구분되고 줄 끝 문자로 종료됨)가 차이점 전에 출력됩니다.
커밋을 비교할 때, 첫 번째 (또는 유일한) 커밋의 ID가 줄 바꿈과 함께 출력됩니다.
+
다음 플래그는 커밋 (하지만 트리 아님)을 비교할 때 동작에 추가적인 영향을 줍니다.

-m::
	기본적으로 `git diff-tree --stdin`은 머지 커밋에 대한 차이를 표시하지 않습니다.
	이 플래그를 사용하면 해당 커밋과 모든 부모 간의 차이를 표시합니다. `-c`도 참조하십시오.

-s::
	기본적으로 `git diff-tree --stdin`은 머신이 읽을 수 있는 형식 (`-p` 없음) 또는 패치 형식 (`-p` 있음)으로 차이를 표시합니다.
	이 출력은 억제될 수 있습니다. `-v` 플래그와 함께 사용할 때만 유용합니다.

-v::
	이 플래그는 `git diff-tree --stdin`이 차이점 앞에 커밋 메시지도 표시하도록 합니다.

include::pretty-options.adoc[]

--no-commit-id::
	`git diff-tree`는 해당되는 경우 커밋 ID가 포함된 줄을 출력합니다.
	이 플래그는 커밋 ID 출력을 억제합니다.

-c::
	이 플래그는 머지 커밋이 표시되는 방식을 변경합니다 (즉, 명령에 `<tree-ish>`가 하나 주어지거나 `--stdin`이 사용될 때만 유용합니다).
	이는 부모들 각각의 결과와의 차이를 한 번에 하나씩 ( `-m` 옵션이 하는 일) 표시하는 대신,
	결과와의 차이를 동시에 표시합니다.
	더욱이, 모든 부모로부터 수정된 파일들만 나열합니다.

--cc::
	이 플래그는 `-c` 옵션과 유사하게 머지 커밋 패치가 표시되는 방식을 변경합니다.
	`-c`와 `-p` 옵션을 암시하며, 부모에게서 발견되는 두 가지 변형만 있고 머지 결과가 수정 없이 그 중 하나를 선택하는 경우,
	관심 없는 덩어리(hunk)를 생략함으로써 패치 출력을 더욱 압축합니다.
	모든 덩어리가 관심 없으면, 다른 "빈 diff" 경우와 마찬가지로 커밋 자체와 커밋 로그 메시지는 표시되지 않습니다.

--combined-all-paths::
	이 플래그는 결합된 diff (머지 커밋에 사용됨)가 모든 부모의 파일 이름을 나열하도록 합니다.
	따라서 `-c` 또는 `--cc`가 지정된 경우에만 효과가 있으며, 파일 이름 변경이 감지되었을 때 (즉, 이름 변경 또는 복사 감지가 요청되었을 때)만 유용할 가능성이 높습니다.

--always::
	diff 자체는 비어 있더라도 커밋 자체와 커밋 로그 메시지를 계속 표시합니다.


include::pretty-formats.adoc[]

include::diff-format.adoc[]

GIT
---
linkgit:git[1] 제품군의 일부입니다.