git-bisect(1)
=============

NAME
----
git-bisect - Use binary search to find the commit that introduced a bug


SYNOPSIS
--------
[verse]
'git bisect' start [--term-(bad|new)=<term-new> --term-(good|old)=<term-old>]
		   [--no-checkout] [--first-parent] [<bad> [<good>...]] [--] [<pathspec>...]
'git bisect' (bad|new|<term-new>) [<rev>]
'git bisect' (good|old|<term-old>) [<rev>...]
'git bisect' terms [--term-(good|old) | --term-(bad|new)]
'git bisect' skip [(<rev>|<range>)...]
'git bisect' next
'git bisect' reset [<commit>]
'git bisect' (visualize|view)
'git bisect' replay <logfile>
'git bisect' log
'git bisect' run <cmd> [<arg>...]
'git bisect' help

DESCRIPTION
-----------
This command uses a binary search algorithm to find which commit in
your project's history introduced a bug. You use it by first telling
it a "bad" commit that is known to contain the bug, and a "good"
commit that is known to be before the bug was introduced. Then `git
bisect` picks a commit between those two endpoints and asks you
whether the selected commit is "good" or "bad". It continues narrowing
down the range until it finds the exact commit that introduced the
change.

In fact, `git bisect` can be used to find the commit that changed
*any* property of your project; e.g., the commit that fixed a bug, or
the commit that caused a benchmark's performance to improve. To
support this more general usage, the terms "old" and "new" can be used
in place of "good" and "bad", or you can choose your own terms. See
section "Alternate terms" below for more information.

Basic bisect commands: start, bad, good
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

As an example, suppose you are trying to find the commit that broke a
feature that was known to work in version `v2.6.13-rc2` of your
project. You start a bisect session as follows:

------------------------------------------------
$ git bisect start
$ git bisect bad                 # Current version is bad
$ git bisect good v2.6.13-rc2    # v2.6.13-rc2 is known to be good
------------------------------------------------

Once you have specified at least one bad and one good commit, `git
bisect` selects a commit in the middle of that range of history,
checks it out, and outputs something similar to the following:

------------------------------------------------
Bisecting: 675 revisions left to test after this (roughly 10 steps)
------------------------------------------------

You should now compile the checked-out version and test it. If that
version works correctly, type

------------------------------------------------
$ git bisect good
------------------------------------------------

If that version is broken, type

------------------------------------------------
$ git bisect bad
------------------------------------------------

Then `git bisect` will respond with something like

------------------------------------------------
Bisecting: 337 revisions left to test after this (roughly 9 steps)
------------------------------------------------

Keep repeating the process: compile the tree, test it, and depending
on whether it is good or bad run `git bisect good` or `git bisect bad`
to ask for the next commit that needs testing.

Eventually there will be no more revisions left to inspect, and the
command will print out a description of the first bad commit. The
reference `refs/bisect/bad` will be left pointing at that commit.


Bisect reset
~~~~~~~~~~~~

After a bisect session, to clean up the bisection state and return to
the original HEAD, issue the following command:

------------------------------------------------
$ git bisect reset
------------------------------------------------

By default, this will return your tree to the commit that was checked
out before `git bisect start`.  (A new `git bisect start` will also do
that, as it cleans up the old bisection state.)

With an optional argument, you can return to a different commit
instead:

------------------------------------------------
$ git bisect reset <commit>
------------------------------------------------

For example, `git bisect reset bisect/bad` will check out the first
bad revision, while `git bisect reset HEAD` will leave you on the
current bisection commit and avoid switching commits at all.


Alternate terms
~~~~~~~~~~~~~~~

Sometimes you are not looking for the commit that introduced a
breakage, but rather for a commit that caused a change between some
other "old" state and "new" state. For example, you might be looking
for the commit that introduced a particular fix. Or you might be
looking for the first commit in which the source-code filenames were
finally all converted to your company's naming standard. Or whatever.

In such cases it can be very confusing to use the terms "good" and
"bad" to refer to "the state before the change" and "the state after
the change". So instead, you can use the terms "old" and "new",
respectively, in place of "good" and "bad". (But note that you cannot
mix "good" and "bad" with "old" and "new" in a single session.)

In this more general usage, you provide `git bisect` with a "new"
commit that has some property and an "old" commit that doesn't have that
property. Each time `git bisect` checks out a commit, you test if that
commit has the property. If it does, mark the commit as "new";
otherwise, mark it as "old". When the bisection is done, `git bisect`
will report which commit introduced the property.

To use "old" and "new" instead of "good" and bad, you must run `git
bisect start` without commits as argument and then run the following
commands to add the commits:

------------------------------------------------
git bisect old [<rev>]
------------------------------------------------

to indicate that a commit was before the sought change, or

------------------------------------------------
git bisect new [<rev>...]
------------------------------------------------

to indicate that it was after.

To get a reminder of the currently used terms, use

------------------------------------------------
git bisect terms
------------------------------------------------

You can get just the old term with `git bisect terms --term-old`
or `git bisect terms --term-good`; `git bisect terms --term-new`
and `git bisect terms --term-bad` can be used to learn how to call
the commits more recent than the sought change.

If you would like to use your own terms instead of "bad"/"good" or
"new"/"old", you can choose any names you like (except existing bisect
subcommands like `reset`, `start`, ...) by starting the
bisection using

------------------------------------------------
git bisect start --term-old <term-old> --term-new <term-new>
------------------------------------------------

For example, if you are looking for a commit that introduced a
performance regression, you might use

------------------------------------------------
git bisect start --term-old fast --term-new slow
------------------------------------------------

Or if you are looking for the commit that fixed a bug, you might use

------------------------------------------------
git bisect start --term-new fixed --term-old broken
------------------------------------------------

Then, use `git bisect <term-old>` and `git bisect <term-new>` instead
of `git bisect good` and `git bisect bad` to mark commits.

Bisect visualize/view
~~~~~~~~~~~~~~~~~~~~~

To see the currently remaining suspects in 'gitk', issue the following
command during the bisection process (the subcommand `view` can be used
as an alternative to `visualize`):

------------
$ git bisect visualize
------------

Git detects a graphical environment through various environment variables:
`DISPLAY`, which is set in X Window System environments on Unix systems.
`SESSIONNAME`, which is set under Cygwin in interactive desktop sessions.
`MSYSTEM`, which is set under Msys2 and Git for Windows.
`SECURITYSESSIONID`, which may be set on macOS in interactive desktop sessions.

If none of these environment variables is set, 'git log' is used instead.
You can also give command-line options such as `-p` and `--stat`.

------------
$ git bisect visualize --stat
------------

Bisect log and bisect replay
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

After having marked revisions as good or bad, issue the following
command to show what has been done so far:

------------
$ git bisect log
------------

If you discover that you made a mistake in specifying the status of a
revision, you can save the output of this command to a file, edit it to
remove the incorrect entries, and then issue the following commands to
return to a corrected state:

------------
$ git bisect reset
$ git bisect replay that-file
------------

Avoiding testing a commit
~~~~~~~~~~~~~~~~~~~~~~~~~

If, in the middle of a bisect session, you know that the suggested
revision is not a good one to test (e.g. it fails to build and you
know that the failure does not have anything to do with the bug you
are chasing), you can manually select a nearby commit and test that
one instead.

For example:

------------
$ git bisect good/bad			# previous round was good or bad.
Bisecting: 337 revisions left to test after this (roughly 9 steps)
$ git bisect visualize			# oops, that is uninteresting.
$ git reset --hard HEAD~3		# try 3 revisions before what
					# was suggested
------------

Then compile and test the chosen revision, and afterwards mark
the revision as good or bad in the usual manner.

Bisect skip
~~~~~~~~~~~

Instead of choosing a nearby commit by yourself, you can ask Git to do
it for you by issuing the command:

------------
$ git bisect skip                 # Current version cannot be tested
------------

However, if you skip a commit adjacent to the one you are looking for,
Git will be unable to tell exactly which of those commits was the
first bad one.

You can also skip a range of commits, instead of just one commit,
using range notation. For example:

------------
$ git bisect skip v2.5..v2.6
------------

This tells the bisect process that no commit after `v2.5`, up to and
including `v2.6`, should be tested.

Note that if you also want to skip the first commit of the range you
would issue the command:

------------
$ git bisect skip v2.5 v2.5..v2.6
------------

This tells the bisect process that the commits between `v2.5` and
`v2.6` (inclusive) should be skipped.

Bisect next
~~~~~~~~~~~

Normally, after marking a revision as good or bad, Git automatically
computes and checks out the next revision to test. However, if you need to
explicitly request the next bisection step, you can use:

------------
$ git bisect next
------------

You might use this to resume the bisection process after interrupting it
by checking out a different revision.

Cutting down bisection by giving more parameters to bisect start
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can further cut down the number of trials, if you know what part of
the tree is involved in the problem you are tracking down, by specifying
pathspec parameters when issuing the `bisect start` command:

------------
$ git bisect start -- arch/i386 include/asm-i386
------------

If you know beforehand more than one good commit, you can narrow the
bisect space down by specifying all of the good commits immediately after
the bad commit when issuing the `bisect start` command:

------------
$ git bisect start v2.6.20-rc6 v2.6.20-rc4 v2.6.20-rc1 --
                   # v2.6.20-rc6 is bad
                   # v2.6.20-rc4 and v2.6.20-rc1 are good
------------

Bisect run
~~~~~~~~~~

If you have a script that can tell if the current source code is good
or bad, you can bisect by issuing the command:

------------
$ git bisect run my_script arguments
------------

Note that the script (`my_script` in the above example) should exit
with code 0 if the current source code is good/old, and exit with a
code between 1 and 127 (inclusive), except 125, if the current source
code is bad/new.

Any other exit code will abort the bisect process. It should be noted
that a program that terminates via `exit(-1)` leaves $? = 255, (see the
exit(3) manual page), as the value is chopped with `& 0377`.

The special exit code 125 should be used when the current source code
cannot be tested. If the script exits with this code, the current
revision will be skipped (see `git bisect skip` above). 125 was chosen
as the highest sensible value to use for this purpose, because 126 and 127
are used by POSIX shells to signal specific error status (127 is for
command not found, 126 is for command found but not executable--these
details do not matter, as they are normal errors in the script, as far as
`bisect run` is concerned).

You may often find that during a bisect session you want to have
temporary modifications (e.g. s/#define DEBUG 0/#define DEBUG 1/ in a
header file, or "revision that does not have this commit needs this
patch applied to work around another problem this bisection is not
interested in") applied to the revision being tested.

To cope with such a situation, after the inner 'git bisect' finds the
next revision to test, the script can apply the patch
before compiling, run the real test, and afterwards decide if the
revision (possibly with the needed patch) passed the test and then
rewind the tree to the pristine state.  Finally the script should exit
with the status of the real test to let the `git bisect run` command loop
determine the eventual outcome of the bisect session.

OPTIONS
-------
--no-checkout::
+
현재 반복마다 새 워킹 트리를 체크아웃하지 않습니다. 대신 테스트해야 할 커밋을 가리키도록 `BISECT_HEAD`라는 참조를 업데이트합니다.
+
이 옵션은 각 단계에서 수행할 테스트가 체크아웃된 트리를 필요로 하지 않을 때 유용할 수 있습니다.
+
저장소가 bare인 경우 `--no-checkout`이 가정됩니다.

--first-parent::
+
머지 커밋을 보았을 때 첫 번째 부모 커밋만 따라갑니다.
+
브랜치 병합을 통해 도입된 회귀를 감지할 때, 머지 커밋은 버그 도입으로 식별되며 해당 조상은 무시됩니다.
+
이 옵션은 병합된 브랜치가 깨지거나 빌드가 불가능한 커밋을 포함했지만 머지 자체는 괜찮았던 경우 잘못된 양성 반응을 피하는 데 특히 유용합니다.

EXAMPLES
--------

* v1.2와 HEAD 간의 깨진 빌드를 자동으로 bisect하기:
+
------------
$ git bisect start HEAD v1.2 --      # HEAD는 bad, v1.2는 good
$ git bisect run make                # "make"로 앱 빌드
$ git bisect reset                   # bisect 세션 종료
------------

* origin과 HEAD 간의 테스트 실패를 자동으로 bisect하기:
+
------------
$ git bisect start HEAD origin --    # HEAD는 bad, origin은 good
$ git bisect run make test           # "make test"로 빌드 및 테스트
$ git bisect reset                   # bisect 세션 종료
------------

* 깨진 테스트 케이스를 자동으로 bisect하기:
+
------------
$ cat ~/test.sh
#!/bin/sh
make || exit 125                     # 빌드가 깨진 경우 건너뜀
~/check_test_case.sh                 # 테스트 케이스 통과 여부 확인
$ git bisect start HEAD HEAD~10 --   # 마지막 10개 커밋 내에서 발생
$ git bisect run ~/test.sh
$ git bisect reset                   # bisect 세션 종료
------------
+
여기서는 `test.sh` 사용자 스크립트를 사용합니다. 이 스크립트에서 `make`가 실패하면 현재 커밋을 건너뜁니다.
`check_test_case.sh`는 테스트 케이스가 통과하면 `exit 0`을, 그렇지 않으면 `exit 1`을 반환해야 합니다.
+
bisect, make 및 테스트 프로세스와 스크립트 간의 상호 작용을 방지하기 위해 `test.sh` 및 `check_test_case.sh` 모두 저장소 외부에 있는 것이 더 안전합니다.

* 임시 수정 사항(핫픽스)을 사용하여 자동으로 bisect하기:
+
------------
$ cat ~/test.sh
#!/bin/sh

# 핫픽스 브랜치를 병합하여 워킹 트리를 조정하고
# 그런 다음 빌드를 시도합니다.
if	git merge --no-commit --no-ff hot-fix &&
	make
then
	# 프로젝트별 테스트를 실행하고 상태를 보고합니다.
	~/check_test_case.sh
	status=$?
else
	# 호출자에게 테스트 불가능함을 알립니다.
	status=125
fi

# 다음 커밋으로 깨끗하게 전환할 수 있도록 조정 사항을 되돌립니다.
git reset --hard

# 제어권을 반환합니다.
exit $status
------------
+
이것은 각 테스트 실행 전에 핫픽스 브랜치의 수정 사항을 적용합니다. 예를 들어 빌드 또는 테스트 환경이 변경되어 최신 버전에는 이미 있는 수정 사항이 이전 버전에 필요한 경우입니다. (핫픽스 브랜치가 bisect 중인 모든 커밋을 포함하는 커밋을 기반으로 하므로 머지가 너무 많이 가져오지 않도록 하거나 `git cherry-pick`을 `git merge` 대신 사용하십시오.)

* 깨진 테스트 케이스를 자동으로 bisect하기:
+
------------
$ git bisect start HEAD HEAD~10 --   # 마지막 10개 커밋 내에서 발생
$ git bisect run sh -c "make || exit 125; ~/check_test_case.sh"
$ git bisect reset                   # bisect 세션 종료
------------
+
이것은 테스트를 단일 줄에 작성하는 경우 실행 스크립트 없이도 할 수 있음을 보여줍니다.

* 손상된 저장소에서 객체 그래프의 올바른 영역 찾기
+
------------
$ git bisect start HEAD <known-good-commit> [ <boundary-commit> ... ] --no-checkout
$ git bisect run sh -c '
	GOOD=$(git for-each-ref "--format=%(objectname)" refs/bisect/good-*) &&
	git rev-list --objects BISECT_HEAD --not $GOOD >tmp.$$ &&
	git pack-objects --stdout >/dev/null <tmp.$$
	rc=$?
	rm -f tmp.$$
	test $rc = 0'

$ git bisect reset                   # bisect 세션 종료
------------
+
이 경우 'git bisect run'이 완료되면 bisect/bad는 'git pack objects'에 필요한 방식으로 도달 가능한 그래프의 부모 중 하나가 완전히 통과 가능한 커밋을 참조합니다.

* 회귀 대신 수정 사항 찾기
+
------------
$ git bisect start
$ git bisect new HEAD    # 현재 커밋을 new로 표시
$ git bisect old HEAD~10 # 현재에서 10번째 커밋을 old로 표시
------------
+
또는:
+
------------
$ git bisect start --term-old broken --term-new fixed
$ git bisect fixed
$ git bisect broken HEAD~10
------------

Getting help
~~~~~~~~~~~~

`git bisect`를 사용하여 간단한 사용법 설명을 얻고, `git bisect
help` 또는 `git bisect -h`를 사용하여 긴 사용법 설명을 얻습니다.

SEE ALSO
--------
link:git-bisect-lk2009.html[Fighting regressions with git bisect],
linkgit:git-blame[1].

GIT
---
Part of the linkgit:git[1] suite