git-sh-setup(1)
===============

NAME
----
git-sh-setup - 통합 Git 쉘 스크립트 설정 코드

SYNOPSIS
--------
[verse]
'. "$(git --exec-path)/git-sh-setup"'

DESCRIPTION
-----------

이것은 사용자가 직접 실행하도록 의도된 명령이 아닙니다. 절대로요.
이 문서는 Porcelain 스크립트를 연구하거나 새로운 스크립트를 작성하는 사람들을 위한 것입니다.

'git sh-setup' 스크립트릿은 다른 쉘 스크립트에서 (`.` 를 사용하여) 소싱되어 일반 Git 디렉토리를 가리키는 몇 가지 변수와 몇 가지 헬퍼 쉘 함수를 설정하도록 설계되었습니다.

이것을 소싱하기 전에, 당신의 스크립트는 몇 가지 변수를 설정해야 합니다. `USAGE` (그리고 `LONG_USAGE`가 있다면)는 `usage()` 쉘 함수가 제공하는 메시지를 정의하는 데 사용됩니다. `SUBDIRECTORY_OK`는 스크립트가 워킹 트리의 하위 디렉토리에서 실행될 수 있다면 설정할 수 있습니다 (일부 명령은 그렇지 않습니다).

스크립트릿은 `GIT_DIR` 및 `GIT_OBJECT_DIRECTORY` 쉘 변수를 설정하지만, 환경으로 내보내지는 *않습니다*.

FUNCTIONS
---------

die::
	표준 오류 스트림에 제공된 오류 메시지를 출력한 후 종료합니다.

usage::
	사용법 메시지와 함께 종료합니다.

set_reflog_action::
	`GIT_REFLOG_ACTION` 환경 변수를 주어진 문자열(일반적으로 프로그램 이름)로 설정합니다. 설정되어 있지 않은 경우에만 그렇습니다. 스크립트가 ref를 업데이트하는 `git` 명령을 실행할 때마다, 이 문자열의 값을 사용하여 reflog 항목이 생성되어 어떤 명령이 ref를 업데이트했는지에 대한 기록을 남깁니다.

git_editor::
	주어진 파일에 대해 사용자가 선택한 편집기(GIT_EDITOR, core.editor, VISUAL 또는 EDITOR)를 실행합니다. 하지만 편집기가 지정되지 않고 터미널이 dumb한 경우 오류를 발생시킵니다.

is_bare_repository::
	저장소가 bare 저장소인지(예: 연결된 워킹 트리가 없는 저장소) 여부를 나타내기 위해 표준 출력 스트림에 `true` 또는 `false`를 출력합니다.

cd_to_toplevel::
	워킹 트리의 최상위 디렉토리로 chdir(change directory)을 실행합니다.

require_work_tree::
	현재 디렉토리가 저장소의 워킹 트리 내에 있는지 확인하고, 그렇지 않으면 종료합니다.

require_work_tree_exists::
	저장소와 연관된 워킹 트리가 존재하는지 확인하고, 그렇지 않으면 종료합니다. 워킹 트리가 존재하지 않으면 `cd_to_toplevel`을 호출할 수 없으므로 종종 `cd_to_toplevel`을 호출하기 전에 수행됩니다.

require_clean_work_tree <action> [<hint>]::
	저장소와 연관된 워킹 트리 및 인덱스에 추적된 파일에 대한 커밋되지 않은 변경 사항이 없는지 확인합니다. 그렇지 않으면 `Cannot <action>: <reason>. <hint>` 형식의 오류 메시지를 출력하고 종료합니다. 예:
+
----------------
require_clean_work_tree rebase "Please commit or stash them."
----------------

get_author_ident_from_commit::
	주어진 커밋에 대해 GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL 및 GIT_AUTHOR_DATE 변수를 설정하기 위해 `eval`과 함께 사용할 수 있는 코드를 출력합니다.

create_virtual_base::
	첫 번째 파일을 수정하여 두 번째 파일과 공통된 줄만 남깁니다. 공통된 내용이 충분하지 않으면 첫 번째 파일은 비어 있게 됩니다. 결과는 3-way merge를 위한 가상 베이스 입력으로 적합합니다.

GIT
---
linkgit:git[1] 제품군의 일부