회귀를 git bisect로 해결하기
====================================
:Author: Christian Couder
:Email: chriscool@tuxfamily.org
:Date: 2009/11/08

개요
--------

"git bisect"는 소프트웨어 사용자 및 개발자가 회귀를 발생시킨 커밋을 쉽게 찾을 수 있도록 합니다. 회귀를 해결하기 위해 좋은 도구를 갖는 것이 왜 중요한지 설명합니다. "git bisect"가 외부에서 어떻게 작동하고 내부에 사용하는 알고리즘을 설명합니다. 그런 다음 "git bisect"를 활용하여 현재 관행을 개선하는 방법을 설명합니다. 그리고 "git bisect"가 미래에 어떻게 개선될 수 있는지 논의합니다.


"git bisect" 소개
----------------------------

Git은 Linus Torvalds가 만든 분산 버전 관리 시스템(DVCS)이며 Junio Hamano가 유지보수합니다.

Git과 같은 많은 다른 버전 관리 시스템(VCS)에서 시스템에 의해 관리되는 데이터의 다양한 상태를 커밋이라고 합니다. 그리고 VCS는 대부분 소프트웨어 소스 코드를 관리하는 데 사용되므로 때로는 소프트웨어의 "흥미로운" 동작 변경이 일부 커밋에 도입됩니다.

실제로 사람들은 "나쁜" 동작, 즉 버그 또는 회귀를 발생시키는 커밋에 특히 관심을 갖습니다. 이 커밋에 관심이 있는 이유는 커밋이 (희망적으로) 매우 작은 양의 소스 코드 변경을 포함하기 때문입니다. 그리고 처음에는 어디를 봐야 할지 모르는 것보다 훨씬 적은 양의 변경 사항만 확인하면 문제를 이해하고 제대로 수정하기가 훨씬 쉽습니다.

따라서 "나쁜" 동작을 발생시키는 커밋을 찾는 데 도움이 되도록 "git bisect" 명령 세트가 발명되었습니다. 그리고 당연히 "git bisect" 용어에서 "흥미로운 동작"이 존재하는 커밋을 "나쁜" 커밋이라고 하고 다른 커밋을 "좋은" 커밋이라고 합니다. 우리가 관심 있는 동작을 발생시키는 커밋을 "최초의 나쁜 커밋"이라고 합니다. 우리가 검색하는 커밋 공간에 "최초의 나쁜 커밋"이 하나 이상 있을 수 있다는 점에 유의하십시오.

따라서 "git bisect"는 "최초의 나쁜 커밋"을 찾는 데 도움이 되도록 설계되었습니다. 그리고 가능한 한 효율적으로 이진 검색을 수행하려고 합니다.


회귀 해결 개요
-----------------------------

회귀: 큰 문제
~~~~~~~~~~~~~~~~~~~~~~~~~~

회귀는 소프트웨어 산업에서 큰 문제입니다. 하지만 이 주장에 대한 실제 수치를 뒷받침하기는 어렵습니다.

일반적인 버그에 대한 수치가 있으며, 2002년 NIST 연구 <<1>>에서는 다음과 같이 말했습니다.

_____________
소프트웨어 버그, 즉 오류는 너무 널리 퍼져 있고 너무 해롭기 때문에 미 상무부 산하 국립 표준 기술 연구소(NIST)가 의뢰한 새로 발표된 연구에 따르면 연간 약 $595억, 즉 국내총생산(GDP)의 약 0.6%에 달하는 비용이 듭니다. 국가적 차원에서 비용의 절반 이상은 소프트웨어 사용자가 부담하고 나머지는 소프트웨어 개발자/공급업체가 부담합니다. 이 연구는 모든 오류를 제거할 수는 없지만, 이러한 비용의 3분의 1 이상, 즉 추정 $222억은 개발 단계에 도입된 소프트웨어 결함을 더 조기에 효과적으로 식별하고 제거할 수 있는 향상된 테스트 인프라를 통해 제거할 수 있다고 밝혔습니다. 이는 증가된 비율(100%는 아님)의 오류를 도입된 개발 단계에 더 가깝게 찾는 것과 관련된 절감액입니다. 현재 모든 오류의 절반 이상은 개발 프로세스의 "하류" 또는 판매 후 소프트웨어 사용 중에 발견되지 않습니다.
_____________

그리고 다음으로:

_____________
소프트웨어 개발자는 이미 결함을 식별하고 수정하는 데 개발 비용의 약 80%를 지출하고 있지만, 소프트웨어를 제외한 거의 모든 유형의 제품은 이와 같이 높은 수준의 오류를 가지고 출시됩니다.
_____________

궁극적으로 결론은 다음과 같이 시작되었습니다.

_____________
더 높은 소프트웨어 품질로 가는 길은 상당한 소프트웨어 테스트 개선입니다.
_____________

소프트웨어 관련 비용의 80%가 유지보수에 해당한다는 다른 추정치도 있습니다 <<2>>.

그러나 위키피디아 <<3>>에 따르면 다음과 같습니다.

_____________
유지보수에 대한 일반적인 인식은 단순히 버그를 수정하는 것입니다. 그러나 수년간의 연구 및 조사에 따르면 유지보수 노력의 대다수, 즉 80% 이상이 비수정 조치에 사용됩니다(Pigosko 1997). 이러한 인식은 실제로는 시스템의 기능 향상인 문제 보고서를 제출하는 사용자에 의해 영속됩니다.
_____________

하지만 기존 소프트웨어 개선은 회귀를 주의해야 하므로 매우 비용이 많이 든다고 추측할 수 있습니다. 최소한 이렇게 하면 위의 연구들이 서로 일관성을 갖게 됩니다.

물론 일부 종류의 소프트웨어는 개발된 다음 상당한 개선 없이 일정 기간 사용된 다음 결국 폐기됩니다. 이 경우 물론 회귀는 큰 문제가 아닐 수 있습니다. 그러나 다른 한편으로는 수년 또는 수십 년 동안 많은 사람들이 지속적으로 개발하고 유지보수하는 대규모 소프트웨어가 많이 있습니다. 그리고 종종 이러한 소프트웨어에 (때로는 비판적으로) 의존하는 사람이 많기 때문에 회귀는 정말 큰 문제입니다.

이러한 소프트웨어 중 하나가 Linux 커널입니다. 그리고 Linux 커널을 보면 회귀를 해결하기 위해 많은 시간과 노력이 투입된다는 것을 알 수 있습니다. 릴리스 주기는 2주간의 병합 창으로 시작합니다. 그런 다음 첫 번째 릴리스 후보(rc) 버전이 태그됩니다. 그 후 각각 약 일주일 간격으로 7~8개의 추가 rc 버전이 출시된 후 최종 릴리스가 됩니다.

첫 번째 rc 릴리스와 최종 릴리스 사이의 시간은 rc 버전을 테스트하고 버그, 특히 회귀를 해결하는 데 사용됩니다. 그리고 이 시간은 릴리스 주기 시간의 80% 이상입니다. 하지만 이것이 아직 싸움의 끝이 아닙니다. 물론 릴리스 후에도 계속되기 때문입니다.

그리고 여기에 유명한 Linux 커널 개발자인 Ingo Molnar가 git bisect 사용에 대해 말한 내용이 있습니다.

_____________
저는 병합 창(많은 트리들이 업스트림으로 병합되고 버그 유입이 가장 높은 시기) 동안 가장 적극적으로 사용하며, 실제로 하루에 여러 번 사용한 경우가 있습니다. 평균적으로 하루에 약 한 번입니다.
_____________

따라서 회귀는 개발자가 항상 해결하고 있으며, 발견되는 즉시 버그는 가능한 한 빨리 수정해야 한다는 것이 잘 알려져 있습니다. 이것이 이 목적을 위한 좋은 도구를 갖는 것이 흥미로운 이유입니다.

회귀 해결을 위한 다른 도구
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

그렇다면 회귀를 해결하는 데 사용되는 도구는 무엇일까요? 거의 일반 버그를 해결하는 데 사용되는 도구와 동일합니다. 유일한 특정 도구는 테스트 스위트와 "git bisect"와 유사한 도구입니다.

테스트 스위트는 매우 좋습니다. 하지만 단독으로 사용하면 각 커밋 후에 모든 테스트가 확인되도록 사용해야 합니다. 이는 많은 테스트가 흥미로운 결과 없이 실행되고 조합 폭발로 고통받기 때문에 비효율적입니다.

사실 문제는 대규모 소프트웨어가 종종 많은 다른 구성 옵션을 갖고 있으며 각 테스트 케이스는 각 커밋 후에 각 구성에 대해 통과해야 한다는 것입니다. 따라서 각 릴리스에 대해: N개의 구성, M개의 커밋 및 T개의 테스트 케이스가 있으면 다음을 수행해야 합니다.

-------------
N * M * T 테스트
-------------

여기서 N, M, T는 모두 소프트웨어 크기에 따라 증가합니다.

따라서 곧 모든 것을 완전히 테스트하는 것이 불가능해질 것입니다.

그리고 테스트 스위트를 통과하는 버그가 있다면 테스트 스위트에 테스트를 추가할 수 있습니다. 하지만 이 새롭고 개선된 테스트 스위트를 사용하여 버그가 어디에서 유입되었는지 찾으려면 이분법 프로세스를 에뮬레이트하거나 "나쁜" 커밋에서 시작하여 각 커밋을 역순으로 테스트해야 할 수 있으며 이는 매우 낭비적일 수 있습니다.

"git bisect" 개요
---------------------

이분법 시작
~~~~~~~~~~~~~~~~~~~~

사용해야 할 첫 번째 "git bisect" 하위 명령은 검색을 시작하기 위해 "git bisect start"입니다. 그런 다음 커밋 공간을 제한하기 위해 경계를 설정해야 합니다. 일반적으로 하나 이상의 "나쁜" 커밋과 하나 이상의 "좋은" 커밋을 제공하여 수행됩니다. 초기 "git bisect start" 호출에서 다음과 같이 전달할 수 있습니다.

-------------
$ git bisect start [BAD [GOOD...]]
-------------

또는 다음과 같이 설정할 수 있습니다.

-------------
$ git bisect bad [COMMIT]
-------------

그리고:

-------------
$ git bisect good [COMMIT...]
-------------

여기서 BAD, GOOD 및 COMMIT은 모두 커밋으로 확인할 수 있는 이름입니다.

그런 다음 "git bisect"는 선택한 커밋을 체크아웃하고 사용자에게 테스트하도록 요청합니다.

-------------
$ git bisect start v2.6.27 v2.6.25
Bisecting: 10928 revisions left to test after this (roughly 14 steps)
[2ec65f8b89ea003c27ff7723525a2ee335a2b393] x86: clean up using max_low_pfn on 32-bit
-------------

사용할 예제는 정말 장난감 예제라는 점에 유의하십시오. "git blame" 또는 "git log -S<string>"과 같이 "git bisect"보다 Git을 사용하여 이 커밋을 찾을 더 좋은 방법이 있습니다. "SUBLEVEL = 26" 줄이 맨 위 Makefile에 있는 커밋, 즉 "2.6.26-something"과 같은 버전을 가진 첫 번째 커밋을 찾을 것입니다. 이는 장난감 예제입니다.

수동으로 이분법 실행
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

이 지점에서 검색을 실행하는 기본적으로 2가지 방법이 있습니다. 사용자가 수동으로 실행하거나 스크립트 또는 명령으로 자동 실행할 수 있습니다.

사용자가 실행하는 경우 검색의 각 단계에서 사용자는 현재 커밋을 테스트하고 위에서 설명한 "git bisect good" 또는 "git bisect bad" 명령을 사용하여 "좋음" 또는 "나쁨"을 지정해야 합니다. 예를 들면 다음과 같습니다.

-------------
$ git bisect bad
Bisecting: 5480 revisions left to test after this (roughly 13 steps)
[66c0b394f08fd89236515c1c84485ea712a157be] KVM: kill file->f_count abuse in kvm
-------------

이와 같은 몇 단계 후 "git bisect"는 결국 최초의 나쁜 커밋을 찾습니다.

-------------
$ git bisect bad
2ddcca36c8bcfa251724fe342c8327451988be0d is the first bad commit
commit 2ddcca36c8bcfa251724fe342c8327451988be0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat May 3 11:59:44 2008 -0700

    Linux 2.6.26-rc1

:100644 100644 5cf82581... 4492984e... M      Makefile
-------------

이 시점에서 커밋이 수행하는 작업을 확인하고(이미 체크아웃되지 않은 경우) 체크아웃하거나 다음과 같이 수정할 수 있습니다.

-------------
$ git show HEAD
commit 2ddcca36c8bcfa251724fe342c8327451988be0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat May 3 11:59:44 2008 -0700

    Linux 2.6.26-rc1

diff --git a/Makefile b/Makefile
index 5cf8258..4492984 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 VERSION = 2
PATCHLEVEL = 6
-SUBLEVEL = 25
-EXTRAVERSION =
+SUBLEVEL = 26
+EXTRAVERSION = -rc1
 NAME = Funky Weasel is Jiggy wit it

 # *DOCUMENTATION*
-------------

완료되면 "git bisect reset"을 사용하여 이분법을 시작하기 전의 브랜치로 돌아갈 수 있습니다.

-------------
$ git bisect reset
Checking out files: 100% (21549/21549), done.
Previous HEAD position was 2ddcca3... Linux 2.6.26-rc1
Switched to branch 'master'
-------------

자동으로 이분법 실행
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

이분법 프로세스를 실행하는 다른 방법은 각 이분법 단계에서 스크립트 또는 명령을 실행하도록 "git bisect"에 지시하여 현재 커밋이 "좋음" 또는 "나쁨"인지 알아보는 것입니다. 이를 위해 "git bisect run" 명령을 사용합니다. 예를 들어:

-------------
$ git bisect start v2.6.27 v2.6.25
Bisecting: 10928 revisions left to test after this (roughly 14 steps)
[2ec65f8b89ea003c27ff7723525a2ee335a2b393] x86: clean up using max_low_pfn on 32-bit
$
$ git bisect run grep '^SUBLEVEL = 25' Makefile
running grep ^SUBLEVEL = 25 Makefile
Bisecting: 5480 revisions left to test after this (roughly 13 steps)
[66c0b394f08fd89236515c1c84485ea712a157be] KVM: kill file->f_count abuse in kvm
running grep ^SUBLEVEL = 25 Makefile
SUBLEVEL = 25
Bisecting: 2740 revisions left to test after this (roughly 12 steps)
[671294719628f1671faefd4882764886f8ad08cb] V4L/DVB(7879): Adding cx18 Support for mxl5005s
...
...
running grep ^SUBLEVEL = 25 Makefile
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[2ddcca36c8bcfa251724fe342c8327451988be0d] Linux 2.6.26-rc1
running grep ^SUBLEVEL = 25 Makefile
2ddcca36c8bcfa251724fe342c8327451988be0d is the first bad commit
commit 2ddcca36c8bcfa251724fe342c8327451988be0d
Author: Linus Torvalds <torvalds@linux-foundation.org>
Date:   Sat May 3 11:59:44 2008 -0700

    Linux 2.6.26-rc1

:100644 100644 5cf82581... 4492984e... M      Makefile
bisect run success
-------------

이 예제에서는 "git bisect run"에 매개변수로 "grep '^SUBLEVEL = 25' Makefile"을 전달했습니다. 이는 각 단계에서 grep 명령이 실행된다는 것을 의미합니다. 그리고 exit 코드가 0(성공을 의미)으로 종료되면 git bisect는 현재 상태를 "좋음"으로 표시합니다. exit 코드가 1(또는 125라는 특별한 코드를 제외하고 1에서 127 사이의 코드)이면 현재 상태는 "나쁨"으로 표시됩니다.

128에서 255 사이의 exit 코드는 "git bisect run"에 특별합니다. 이 코드는 이분법 프로세스를 즉시 중지시킵니다. 예를 들어 전달된 명령을 완료하는 데 너무 오래 걸리는 경우 신호를 사용하여 중지하고 이분법 프로세스를 중지할 수 있습니다.

"git bisect run"에 전달된 스크립트에서 매우 비정상적인 상황이 감지되면 "exit 255"를 사용하여 유용할 수도 있습니다.

테스트 불가능한 커밋 피하기
~~~~~~~~~~~~~~~~~~~~~~~~~~~

때때로 현재 상태를 테스트할 수 없는 경우가 있습니다. 예를 들어 당시 버그로 인해 컴파일되지 않는 경우입니다. 이것이 특별 exit 코드 125가 있는 이유입니다. "git bisect run"에 현재 커밋을 테스트 불가능한 것으로 표시하고 다른 커밋을 선택하고 체크아웃하도록 지시합니다.

이분법 프로세스가 수동으로 실행되는 경우 동일한 작업을 수행하기 위해 "git bisect skip"을 사용할 수 있습니다. (실제로 특별 exit 코드 125는 "git bisect run"이 백그라운드에서 "git bisect skip"을 사용하게 합니다.)

또는 더 많은 제어가 필요한 경우 "git bisect visualize"와 같은 것을 사용하여 현재 상태를 검사할 수 있습니다. gitk (또는 `DISPLAY` 환경 변수가 설정되지 않은 경우 "git log")를 실행하여 더 나은 이분법 지점을 찾는 데 도움이 됩니다.

어느 쪽이든, 테스트 불가능한 커밋의 문자열이 있는 경우 찾고 있는 회귀가 이러한 테스트 불가능한 커밋 중 하나에 의해 발생했을 수 있습니다. 이 경우 회귀를 발생시킨 커밋을 확실하게 알 수 없습니다.

따라서 "git bisect skip"을 사용했거나(실행 스크립트가 특별 코드 125로 종료된 경우) 다음과 같은 결과를 얻을 수 있습니다.

-------------
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
15722f2fa328eaba97022898a305ffc8172db6b1
78e86cf3e850bd755bb71831f42e200626fbd1e0
e15b73ad3db9b48d7d1ade32f8cd23a751fe0ace
070eab2303024706f2924822bfec8b9847e4ac1b
We cannot bisect more!
-------------

로그 저장 및 재생
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

다른 사람에게 이분법 프로세스를 보여주고 싶다면 예를 들어 다음과 같이 로그를 얻을 수 있습니다.

-------------
$ git bisect log > bisect_log.txt
-------------

그리고 다음과 같이 다시 재생할 수 있습니다.

-------------
$ git bisect replay bisect_log.txt
-------------


"git bisect" 세부 정보
--------------------

이분법 알고리즘
~~~~~~~~~~~~~~~~~~~

Git 커밋은 방향성 비순환 그래프(DAG)를 형성하므로 각 단계에서 최적의 이분법 커밋을 찾는 것은 그리 간단하지 않습니다. 어쨌든 Linus는 상당히 잘 작동하는 "진정으로 터무니없는" 알고리즘을 발견하고 구현했으며, 이후 Junio Hamano가 개선했습니다.

따라서 건너뛴 커밋이 없을 때 최적의 이분법 커밋을 찾는 "git bisect"에서 사용하는 알고리즘은 다음과 같습니다.

1) 다음을 만족하는 커밋만 유지합니다.

a) "나쁜" 커밋의 조상( "나쁜" 커밋 자체 포함)
b) "좋은" 커밋의 조상이 아닌 것 ( "좋은" 커밋 제외).

이는 DAG에서 흥미롭지 않은 커밋을 제거한다는 의미입니다.

예를 들어 다음과 같은 그래프로 시작하는 경우:

-------------
G-Y-G-W-W-W-X-X-X-X
           \ /
            W-W-B
           /
Y---G-W---W
 \ /   \
Y-Y     X-X-X-X

-> 시간은 이 방향으로 흘러갑니다 ->
-------------

여기서 B는 "나쁜" 커밋이고, "G"는 "좋은" 커밋이며, W, X, Y는 다른 커밋인 경우 첫 번째 단계 후에 다음과 같은 그래프를 얻게 됩니다.

-------------
W-W-W
     \
      W-W-B
     /
W---W
-------------

따라서 W와 B 커밋만 유지됩니다. X와 Y 커밋은 각각 규칙 a)와 b)에 의해 제거되고 G 커밋도 규칙 b)에 의해 제거되기 때문입니다.

Git 사용자의 경우 다음으로 제공되는 커밋만 유지하는 것과 같습니다.

-------------
git rev-list BAD --not GOOD1 GOOD2...
-------------

또한 유지되는 커밋이 "좋은" 커밋의 후손일 필요는 없습니다. 따라서 다음 예에서 W와 Z 커밋이 유지됩니다.

-------------
G-W-W-W-B
   /
Z-Z
-------------

2) "좋은" 끝에서 시작하여 각 커밋에 조상 수를 더한 1을 연결합니다.

예를 들어, H가 "나쁜" 커밋이고 A와 D가 "좋은" 커밋의 일부 부모인 다음 그래프의 경우:

-------------
A-B-C
     \
      F-G-H
     /
D---E
-------------

이는 다음을 제공합니다.

-------------
1 2 3
A-B-C
     \6 7 8
      F-G-H
1   2/
D---E
-------------

3) 각 커밋에 다음을 연결합니다: min(X, N - X)

여기서 X는 2단계에서 커밋에 연결된 값이고 N은 그래프의 총 커밋 수입니다.

위 예제에서는 N = 8이므로 다음과 같이 됩니다.

-------------
1 2 3
A-B-C
     \2 1 0
      F-G-H
1   2/
D---E
-------------

4) 최적의 이분법 지점은 가장 높은 연결 값이 있는 커밋입니다.

따라서 위 예제에서 최적의 이분법 지점은 커밋 C입니다.

5) 알고리즘을 빠르게 하기 위해 몇 가지 바로가기가 구현되었다는 점에 유의하십시오.

N을 처음부터 알고 있으므로 min(X, N - X)는 N/2보다 클 수 없습니다. 따라서 2단계와 3단계에서 커밋에 N/2를 연결하면 이것이 최적의 이분법 지점임을 알 수 있습니다. 따라서 이 경우 다른 커밋 처리를 중지하고 현재 커밋을 반환하기만 하면 됩니다.

이분법 알고리즘 디버깅
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

모든 커밋 그래프에 대해 "git rev-list --bisect-all"을 사용하여 각 커밋에 연결된 수를 볼 수 있습니다.

예를 들어 위 그래프의 경우 다음과 같은 명령:

-------------
$ git rev-list --bisect-all BAD --not GOOD1 GOOD2
-------------

다음과 같이 출력됩니다.

-------------
e15b73ad3db9b48d7d1ade32f8cd23a751fe0ace (dist=3)
15722f2fa328eaba97022898a305ffc8172db6b1 (dist=2)
78e86cf3e850bd755bb71831f42e200626fbd1e0 (dist=2)
a1939d9a142de972094af4dde9a544e577ddef0e (dist=2)
070eab2303024706f2924822bfec8b9847e4ac1b (dist=1)
a3864d4f32a3bf5ed177ddef598490a08760b70d (dist=1)
a41baa717dd74f1180abf55e9341bc7a0bb9d556 (dist=1)
9e622a6dad403b71c40979743bb9d5be17b16bd6 (dist=0)
-------------

이분법 알고리즘 논의
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

먼저 "최적 이분법 지점"을 정의해 보겠습니다. 커밋 X가 그 상태("좋음" 또는 "나쁨")를 아는 것이 상태가 "좋음" 또는 "나쁨"인지 여부에 대한 정보를 최대량 제공하는 최적 이분법 지점 또는 최적 이분법 커밋이라고 말할 것입니다.

이는 최적 이분법 커밋이 다음 함수가 최대인 커밋을 의미합니다.

-------------
f(X) = min(information_if_good(X), information_if_bad(X))
-------------

여기서 information_if_good(X)는 X가 좋으면 얻는 정보이고 information_if_bad(X)는 X가 나쁘면 얻는 정보입니다.

이제 "최초의 나쁜 커밋"이 하나 있다고 가정합니다. 이는 모든 후손이 "나쁨"이고 나머지 커밋은 "좋음"임을 의미합니다. 그리고 모든 커밋이 좋거나 나쁘거나 최초의 나쁜 커밋일 확률이 동일하다고 가정하므로, c개의 커밋 상태를 아는 것이 그래프의 어디에 있든 c가 무엇이든 항상 동일한 정보량을 제공합니다. (따라서 이러한 커밋이 예를 들어 브랜치에 있거나 좋은 커밋 또는 나쁜 커밋 근처에 있는 것이 더 많은 또는 더 적은 정보를 제공하지 않는다고 가정합니다.)

또한 이분법 알고리즘의 1단계 이후와 같이 정리된 그래프가 있다고 가정합니다. 이는 그래프에서 커밋 수를 제거하는 측면에서 얻는 정보를 측정할 수 있음을 의미합니다.

그리고 그래프에서 커밋 X를 가져옵니다.

X가 "좋음"으로 판명되면 그 조상이 모두 "좋음"임을 알게 되므로 다음과 같이 말하고 싶습니다.

-------------
information_if_good(X) = number_of_ancestors(X)  (TRUE)
-------------

그리고 이것은 1단계 b)에서 "좋은" 커밋의 조상을 제거하기 때문입니다.

X가 "나쁨"으로 판명되면 그 후손이 모두 "나쁨"임을 알게 되므로 다음과 같이 말하고 싶습니다.

-------------
information_if_bad(X) = number_of_descendants(X)  (WRONG)
-------------

하지만 이것은 틀렸습니다. 1단계 a)에서 우리는 나쁜 커밋의 조상만 유지하기 때문입니다. 따라서 커밋이 "나쁨"으로 표시될 때 더 많은 정보를 얻습니다. 이전 "나쁜" 커밋의 조상 중 새 "나쁜" 커밋의 조상이 아닌 것은 최초의 나쁜 커밋이 아니라는 것을 알기 때문입니다. 그들이 좋거나 나쁜지 모르겠지만, 새 "나쁜" 커밋의 조상이 아니기 때문에 최초의 나쁜 커밋이 아니라는 것을 알고 있습니다.

따라서 커밋이 "나쁨"으로 표시되면 새 "나쁜" 커밋의 조상 외의 그래프의 모든 커밋을 제거할 수 있음을 알게 됩니다. 이는 다음을 의미합니다.

-------------
information_if_bad(X) = N - number_of_ancestors(X)  (TRUE)
-------------

여기서 N은 (정리된) 그래프의 커밋 수입니다.

결론적으로 최적의 이분법 커밋을 찾으려면 다음 함수를 최대화해야 합니다.

-------------
f(X) = min(number_of_ancestors(X), N - number_of_ancestors(X))
-------------

그리고 이것은 좋습니다. 2단계에서 number_of_ancestors(X)를 계산하고 3단계에서 f(X)를 계산하기 때문입니다.

다음 그래프를 예로 들어 보겠습니다.

-------------
            G-H-I-J
           /       \
A-B-C-D-E-F         O
           \       /
            K-L-M-N
-------------

다음과 같은 최적이 아닌 함수를 계산하면:

-------------
g(X) = min(number_of_ancestors(X), number_of_descendants(X))
-------------

결과는 다음과 같습니다.

-------------
            4 3 2 1
            G-H-I-J
1 2 3 4 5 6/       \0
A-B-C-D-E-F         O
           \       /
            K-L-M-N
            4 3 2 1
-------------

그러나 git bisect에서 사용하는 알고리즘을 사용하면 다음과 같은 결과를 얻습니다.

-------------
            7 7 6 5
            G-H-I-J
1 2 3 4 5 6/       \0
A-B-C-D-E-F         O
           \       /
            K-L-M-N
            7 7 6 5
-------------

따라서 F보다 나은 G, H, K 또는 L을 최적 이분법 지점으로 선택합니다. 왜냐하면 예를 들어 L이 나쁘다면 L, M, N이 나쁘다는 것뿐만 아니라 G, H, I, J가 최초의 나쁜 커밋이 아니라는 것도 알게 되기 때문입니다 (최초의 나쁜 커밋이 하나만 있고 L의 조상이어야 한다고 가정하므로).

따라서 현재 알고리즘은 처음에 가정한 것을 고려할 때 가능한 최선으로 보입니다.

건너뛰기 알고리즘
~~~~~~~~~~~~~~~~~~~~~~

일부 커밋이 건너뛴 경우("git bisect skip" 사용), 이분법 알고리즘은 1단계부터 3단계까지 동일합니다. 그러나 대략 다음 단계를 사용합니다.

6) 연결 값이 감소하는 순서대로 커밋을 정렬합니다.

7) 첫 번째 커밋이 건너뛰지 않았다면 반환하고 여기서 중지할 수 있습니다.

8) 그렇지 않으면 정렬된 목록에서 건너뛴 모든 커밋을 필터링합니다.

9) 의사 난수 생성기(PRNG)를 사용하여 0에서 1 사이의 난수를 생성합니다.

10) 이 난수에 제곱근을 곱하여 0으로 치우치게 합니다.

11) 결과를 필터링된 목록의 커밋 수에 곱하여 목록의 인덱스를 얻습니다.

12) 계산된 인덱스의 커밋을 반환합니다.

건너뛰기 알고리즘 논의
~~~~~~~~~~~~~~~~~~~~~~~~

7단계(건너뛰기 알고리즘) 후 두 번째 커밋이 건너뛰었는지 확인하고 그렇지 않은 경우 반환할 수 있습니다. 실제로 "git bisect skip"이 Git 버전 1.5.4(2008년 2월 1일 출시)부터 Git 버전 1.6.4(2009년 7월 29일 출시)까지 사용한 알고리즘입니다.

그러나 Ingo Molnar와 H. Peter Anvin(또는 다른 유명한 Linux 커널 개발자) 모두 때때로