git-p4(1)
=========

NAME
----
git-p4 - Import from and submit to Perforce repositories


SYNOPSIS
--------
[verse]
'git p4 clone' [<sync-options>] [<clone-options>] <p4-depot-path>...
'git p4 sync' [<sync-options>] [<p4-depot-path>...]
'git p4 rebase'
'git p4 submit' [<submit-options>] [<master-branch-name>]


DESCRIPTION
-----------
이 명령은 Git을 사용하여 p4 저장소와 상호 작용할 수 있는 방법을 제공합니다.

'git p4 clone'을 사용하여 기존 p4 저장소에서 새 Git 저장소를 생성하려면 하나 이상의 p4 저장소 경로를 제공해야 합니다. 'git p4 sync'를 사용하여 p4의 새 커밋을 통합합니다. 'sync' 명령은 다른 p4 저장소 경로에서 새 브랜치를 포함하는 데도 사용됩니다. 'git p4 submit'을 사용하여 Git 변경 사항을 p4로 다시 제출합니다. 'git p4 rebase' 명령은 sync를 수행하고 현재 브랜치를 업데이트된 p4 원격 브랜치 위에 리베이스합니다.


EXAMPLES
--------
* 저장소 복제:
+
------------
$ git p4 clone //depot/path/project
------------

* 새로 생성된 Git 저장소에서 작업 수행:
+
------------
$ cd project
$ vi foo.h
$ git commit -a -m "edited foo.h"
------------

* p4의 최신 변경 사항으로 Git 저장소를 업데이트하고 작업을 위에 리베이스합니다:
+
------------
$ git p4 rebase
------------

* 커밋을 p4로 다시 제출:
+
------------
$ git p4 submit
------------


COMMANDS
--------

Clone
~~~~~
일반적으로 'git p4 clone'은 기존 p4 저장소에서 새 Git 디렉토리를 만드는 데 사용됩니다:

------------
$ git p4 clone //depot/path/project
------------
이것은 다음을 수행합니다:

1. 'project'라는 하위 디렉토리에 빈 Git 저장소를 생성합니다.
+
2. 제공된 p4 저장소 경로의 헤드 리비전 전체 내용을 Git 브랜치 'refs/remotes/p4/master'의 단일 커밋으로 가져옵니다.
+
3. 이 원격에서 'master'라는 로컬 브랜치를 생성하고 체크아웃합니다.

p4 기록 전체를 Git으로 복제하려면 저장소 경로에 '@all' 수정자를 사용하십시오:

------------
$ git p4 clone //depot/path/project@all
------------


Sync
~~~~
p4 저장소에서 개발이 계속됨에 따라 해당 변경 사항을 다음을 사용하여 Git 저장소에 포함할 수 있습니다:

------------
$ git p4 sync
------------

이 명령은 p4에서 새 변경 사항을 찾아 Git 커밋으로 가져옵니다.

기존 Git 저장소에 P4 저장소를 추가하려면 'git p4 sync'를 사용할 수도 있습니다:

------------
$ mkdir repo-git
$ cd repo-git
$ git init
$ git p4 sync //path/in/your/perforce/depot
------------

이것은 지정된 저장소를 기존 Git 저장소의 'refs/remotes/p4/master'로 가져옵니다. `--branch` 옵션을 사용하여 p4 콘텐츠에 사용될 다른 브랜치를 지정할 수 있습니다.

Git 저장소에 'refs/remotes/origin/p4' 브랜치가 포함된 경우 'git p4 sync' 중에 먼저 가져와서 확인합니다. p4에서 직접 가져오는 것이 Git 원격에서 변경 사항을 가져오는 것보다 상당히 느리기 때문에 다중 개발자 환경에서 유용할 수 있습니다.

여러 브랜치가 있는 경우 'git p4 sync'를 수행하면 "BRANCH DETECTION" 알고리즘을 자동으로 사용하여 새 변경 사항을 올바른 브랜치로 분할하려고 시도합니다. 이는 업데이트할 단일 브랜치만 지정하는 `--branch` 옵션으로 재정의할 수 있습니다.


Rebase
~~~~~~
일반적인 작업 패턴은 최신 변경 사항을 p4 저장소에서 가져와 로컬 커밋되지 않은 변경 사항과 병합하는 것입니다. 종종 p4 저장소가 모든 코드의 최종 위치이므로 리베이스 워크플로우가 적합합니다. 이 명령은 'git p4 sync'를 실행한 다음 'git rebase'를 실행하여 로컬 커밋을 업데이트된 p4 변경 사항 위에 배치합니다.

------------
$ git p4 rebase
------------


Submit
~~~~~~
Git 저장소에서 p4 저장소로 변경 사항을 제출하려면 별도의 p4 클라이언트 작업 공간이 필요합니다. 이는 `P4CLIENT` 환경 변수 또는 Git 구성 변수 'git-p4.client'를 사용하여 지정해야 합니다. p4 클라이언트는 존재해야 하지만 클라이언트 루트는 존재하지 않는 경우 생성되고 채워집니다.

현재 Git 브랜치에 있지만 'p4/master' 브랜치에는 없는 모든 변경 사항을 제출하려면 다음을 사용하십시오:

------------
$ git p4 submit
------------

현재 브랜치 이외의 브랜치를 지정하려면 다음을 사용하십시오:

------------
$ git p4 submit topicbranch
------------

단일 커밋 또는 커밋 범위를 지정하려면 다음을 사용하십시오:

------------
$ git p4 submit --commit <sha1>
$ git p4 submit --commit <sha1..sha1>
------------

업스트림 참조는 일반적으로 'refs/remotes/p4/master'이지만 `--origin=` 명령줄 옵션을 사용하여 재정의할 수 있습니다.

p4 변경 사항은 'git p4 submit'을 호출한 사용자로 생성됩니다. `--preserve-user` 옵션은 Git 커밋의 작성자에 따라 소유권을 수정합니다. 이 옵션은 p4에서 관리자 권한이 필요하며 'p4 protect'를 사용하여 부여할 수 있습니다.

변경 사항을 제출하는 대신 스텔브(shelve)하려면 `--shelve` 및 `--update-shelve`을 사용하십시오:

----
$ git p4 submit --shelve
$ git p4 submit --update-shelve 1234 --update-shelve 2345
----


Unshelve
~~~~~~~~
스텔브 해제는 스텔브된 P4 변경 목록을 가져와 브랜치 refs/remotes/p4-unshelved/<changelist>에 해당하는 git 커밋을 생성합니다.

git 커밋은 현재 원점 리비전(기본값: HEAD)을 기준으로 생성됩니다. 원점을 기반으로 부모 커밋이 생성되고, 그 다음 해당 커밋을 기반으로 스텔브 해제 커밋이 생성됩니다.

원점 리비전은 "--origin" 옵션을 사용하여 변경할 수 있습니다.

refs/remotes/p4-unshelved의 대상 브랜치가 이미 존재하는 경우 이전 브랜치는 이름을 변경합니다.

----
$ git p4 sync
$ git p4 unshelve 12345
$ git show p4-unshelved/12345
<p4를 통해 동일한 파일에 더 많은 변경 사항 제출>
$ git p4 unshelve 12345
<git이 p4와 다시 동기화될 때까지 스텔브 해제를 거부함>

----

OPTIONS
-------

General options
~~~~~~~~~~~~~~~
clone을 제외한 모든 명령은 이러한 옵션을 허용합니다.

--git-dir <dir>::
	`GIT_DIR` 환경 변수를 설정합니다. linkgit:git[1]을 참조하십시오.

-v::
--verbose::
	더 많은 진행 정보 제공.

Sync options
~~~~~~~~~~~~
이러한 옵션은 초기 'clone'뿐만 아니라 후속 'sync' 작업에서도 사용할 수 있습니다.

--branch <ref>::
	refs/remotes/p4/master 대신 <ref>로 변경 사항을 가져옵니다.
	<ref>가 refs/로 시작하면 그대로 사용됩니다. 그렇지 않으면,
	p4/로 시작하지 않으면 해당 접두사가 추가됩니다.
+
기본적으로 refs/로 시작하지 않는 <ref>는 원격 추적 브랜치(refs/remotes/ 아래)의 이름으로 취급됩니다. 이 동작은 `--import-local` 옵션을 사용하여 수정할 수 있습니다.
+
기본 <ref>는 "master"입니다.
+
이 예제는 기존 Git 저장소로 새 원격 "p4/proj2"를 가져옵니다:
+
----
    $ git init
    $ git p4 sync --branch=refs/remotes/p4/proj2 //depot/proj2
----

--detect-branches::
	브랜치 감지 알고리즘을 사용하여 p4에서 새 경로를 찾습니다. "BRANCH DETECTION" 아래에 설명되어 있습니다.

--changesfile <file>::
	'file'에 나열된 p4 변경 번호만 가져옵니다. 일반적으로 'git p4'는 현재 p4 저장소 상태를 검사하고 가져와야 할 변경 사항을 감지합니다.

--silent::
	진행 정보를 인쇄하지 않습니다.

--detect-labels::
	저장소 경로와 관련된 레이블을 쿼리하기 위해 p4에 쿼리하고 Git에 태그로 추가합니다. 새 변경 목록과 관련된 레이블만 가져오므로 유용성이 제한됩니다. 더 이상 사용되지 않습니다.

--import-labels::
	p4에서 Git으로 레이블을 가져옵니다.

--import-local::
	기본적으로 p4 브랜치는 'refs/remotes/p4/'에 저장되며, 여기에서 linkgit:git-branch[1] 및 다른 명령에 의해 원격 추적 브랜치로 취급됩니다. 이 옵션은 대신 p4 브랜치를 'refs/heads/p4/'에 배치합니다. 향후 sync 작업은 p4 브랜치를 refs/heads에서 찾을 수 있도록 `--import-local` 옵션도 지정해야 합니다.

--max-changes <n>::
	제공된 리비전 지정자로 포함된 변경 사항 전체 범위 대신 최대 'n'개의 변경 사항을 가져옵니다. 일반적인 사용법은 리비전 지정자로 '@all'을 사용하는 것이지만, 전체 리비전 기록 대신 마지막 1000개의 리비전만 가져오기 위해 '--max-changes 1000'을 사용하는 것입니다.

--changes-block-size <n>::
	'@all'과 같은 리비전 지정자를 특정 변경 번호 목록으로 변환할 때 사용되는 내부 블록 크기입니다. 전체 변경 목록을 찾기 위해 'p4 changes'를 한 번 호출하는 대신, 주어진 크기의 변경 블록을 각각 요청하는 'p4 changes -m' 시퀀스가 있습니다. 기본 블록 크기는 500이며, 일반적으로 적합합니다.

--keep-path::
	p4 저장소 경로에서 Git으로의 파일 이름 매핑은 기본적으로 전체 저장소 경로를 제거하는 것을 포함합니다. 이 옵션을 사용하면 전체 p4 저장소 경로가 Git에 유지됩니다. 예를 들어, '//depot/main/'에서 가져온 경로는 '//depot/main/foo/bar.c'이고 'foo/bar.c'가 됩니다. `--keep-path`를 사용하면 대신 Git 경로는 'depot/main/foo/bar.c'가 됩니다.

--use-client-spec::
	p4에서 관심 있는 파일 목록을 찾기 위해 클라이언트 spec을 사용합니다. 아래 "CLIENT SPEC" 섹션을 참조하십시오.

-/ <path>::
	복제 또는 동기화 시 선택한 저장소 경로를 제외합니다.

Clone options
~~~~~~~~~~~~~
이러한 옵션은 위에 설명된 'sync' 옵션과 함께 초기 'clone'에서 사용할 수 있습니다.

--destination <directory>::
	Git 저장소를 생성할 위치입니다. 제공되지 않으면 p4 저장소 경로의 마지막 구성 요소가 새 디렉토리를 만드는 데 사용됩니다.

--bare::
	베어 복제를 수행합니다. linkgit:git-clone[1]을 참조하십시오.

Submit options
~~~~~~~~~~~~~~
이러한 옵션은 'git p4 submit' 동작을 수정하는 데 사용할 수 있습니다.

--origin <commit>::
	p4에 제출할 커밋을 식별하는 업스트림 위치입니다. 기본적으로 이는 `HEAD`에서 도달 가능한 가장 최근 p4 커밋입니다.

-M::
	이름 변경을 감지합니다. linkgit:git-diff[1]을 참조하십시오. 이름 변경은 명시적인 'move' 작업으로 p4에 표현됩니다. 복사를 감지하는 해당 옵션은 없지만 이동과 복사 모두에 대한 변수가 있습니다.

--preserve-user::
	p4에 제출하기 전에 p4 변경 사항을 다시 작성합니다. 이 옵션은 p4 관리자 권한이 필요합니다.

--export-labels::
	Git 태그를 p4 레이블로 내보냅니다. Git에서 찾은 태그는 perforce 작업 디렉토리에 적용됩니다.

-n::
--dry-run::
	p4에 제출될 커밋만 표시합니다. Git 또는 p4의 상태를 변경하지 않습니다.

--prepare-p4-only::
	커밋을 p4 작업 공간에 적용하여 일반 제출 작업과 같이 파일을 열고, 추가하고, 삭제합니다. 최종 "p4 submit"을 발행하지 않고 수동으로 제출하거나 되돌리는 방법에 대한 메시지를 인쇄합니다. 이 옵션은 항상 첫 번째(가장 오래된) 커밋 후에 중지됩니다. Git 태그는 p4로 내보내지지 않습니다.

--shelve::
	제출하는 대신 일련의 스텔브된 변경 목록을 생성합니다. 각 스텔브를 생성한 후 관련 파일은 되돌리거나 삭제됩니다. 여러 커밋이 보류 중이면 여러 스텔브가 생성됩니다.

--update-shelve CHANGELIST::
	기존 스텔브된 변경 목록을 이 커밋으로 업데이트합니다. `--shelve`를 의미합니다. 여러 스텔브된 변경 목록에 대해 반복합니다.

--conflict=(ask|skip|quit)::
	커밋을 p4에 적용할 때 충돌이 발생할 수 있습니다. 이 경우 기본 동작("ask")은 이 커밋을 건너뛰고 계속할지, 아니면 종료할지 묻는 것입니다. 이 옵션을 사용하여 프롬프트를 우회하고, 충돌하는 커밋을 자동으로 건너뛰거나, 묻지 않고 커밋 적용을 종료할 수 있습니다.

--branch <branch>::
	제출 후 기본 p4/master 대신 이 이름의 브랜치를 동기화합니다. 위 "Sync options" 섹션을 참조하십시오.

--commit (<sha1>|<sha1>..<sha1>)::
    현재 Git 브랜치에 있는 전체 변경 목록 대신 지정된 커밋 또는 커밋 범위를 제출합니다.

--disable-rebase::
    모든 커밋이 성공적으로 제출된 후 자동 리베이스를 비활성화합니다. git-p4.disableRebase로도 설정할 수 있습니다.

--disable-p4sync::
    커밋이 제출된 후 Perforce에서 p4/master를 자동으로 동기화하는 것을 비활성화합니다. `--disable-rebase`를 의미합니다. 가능한 경우 origin/master와의 동기화는 계속 진행됩니다.

Hooks for submit
----------------

p4-pre-submit
~~~~~~~~~~~~~

`p4-pre-submit` 훅은 존재하고 실행 가능한 경우 실행됩니다.
훅은 매개변수와 표준 입력을 받지 않습니다. 이 스크립트에서 0이 아닌 상태로 종료하면 `git-p4 submit`이 시작되지 않습니다. `--no-verify` 명령줄 옵션으로 우회할 수 있습니다.

한 가지 사용 시나리오는 훅에서 단위 테스트를 실행하는 것입니다.

p4-prepare-changelist
~~~~~~~~~~~~~~~~~~~~~

`p4-prepare-changelist` 훅은 기본 변경 목록 메시지를 준비한 직후 그리고 편집기가 시작되기 직전에 실행됩니다.
변경 목록 텍스트가 포함된 파일의 이름을 매개변수로 받습니다. 스크립트에서 0이 아닌 상태로 종료하면 프로세스가 중단됩니다.

훅의 목적은 메시지 파일을 제자리에서 편집하는 것이며 `--no-verify` 옵션으로 억제되지 않습니다. 이 훅은 `--prepare-p4-only`가 설정된 경우에도 호출됩니다.

p4-changelist
~~~~~~~~~~~~~

`p4-changelist` 훅은 사용자가 변경 목록 메시지를 편집한 후 실행됩니다. `--no-verify` 옵션으로 우회할 수 있습니다. 제안된 변경 목록 텍스트를 포함하는 파일의 이름을 단일 매개변수로 받습니다. 0이 아닌 상태로 종료하면 명령이 중단됩니다.

훅은 변경 목록 파일을 편집할 수 있으며 일부 프로젝트 표준 형식으로 텍스트를 정규화하는 데 사용할 수 있습니다. 또한 메시지 파일을 검사한 후 제출을 거부하는 데 사용할 수 있습니다.

p4-post-changelist
~~~~~~~~~~~~~~~~~~

`p4-post-changelist` 훅은 P4에서 제출이 성공적으로 발생한 후 호출됩니다. 매개변수를 받지 않으며 주로 알림용이며 git p4 submit 작업의 결과를 변경할 수 없습니다.



Rebase options
~~~~~~~~~~~~~~
이러한 옵션은 'git p4 rebase' 동작을 수정하는 데 사용할 수 있습니다.

--import-labels::
	p4 레이블을 가져옵니다.

Unshelve options
~~~~~~~~~~~~~~~~

--origin::
    스텔브된 P4 변경 목록과 비교할 git refspec을 설정합니다.
    기본값은 p4/master입니다.

DEPOT PATH SYNTAX
-----------------
'git p4 sync' 및 'git p4 clone'에 대한 p4 저장소 경로 인수는 하나 이상의 공백으로 구분된 p4 저장소 경로일 수 있으며, 끝에 선택적으로 p4 리비전 지정자를 붙일 수 있습니다:

"//depot/my/project"::
    해당 트리 아래의 '#head' 변경에서 모든 파일로 단일 커밋을 가져옵니다.

"//depot/my/project@all"::
    해당 저장소 경로 기록의 각 변경에 대한 단일 커밋을 가져옵니다.

"//depot/my/project@1,6"::
    변경 1부터 6까지만 가져옵니다.

"//depot/proj1@all //depot/proj2@all"::
    두 명명된 저장소 경로 모두에서 모든 변경 사항을 단일 저장소로 가져옵니다.
    "proj1" 및 "proj2" 각각에 대한 Git의 하위 디렉토리는 없습니다.
    두 개 이상의 저장소 경로를 지정할 때는 `--destination` 옵션을 사용해야 합니다. 리비전 지정자는 각 저장소 경로에 대해 동일하게 지정해야 합니다. 동일한 이름을 가진 저장소 경로에 파일이 있는 경우 가장 최근에 업데이트된 버전의 파일이 있는 경로가 Git에 나타납니다.

p4 리비전 지정자의 전체 구문은 'p4 help revisions'를 참조하십시오.


CLIENT SPEC
-----------
p4 클라이언트 사양은 'p4 client' 명령으로 유지 관리되며, 다른 필드 중에서도 저장소를 클라이언트 저장소로 매핑하는 방법을 지정하는 View를 포함합니다. 'clone' 및 'sync' 명령은 `--use-client-spec` 옵션이 제공되거나 useClientSpec 변수가 true인 경우 클라이언트 spec을 참조할 수 있습니다. 'git p4 clone' 후 useClientSpec 변수는 저장소 구성 파일에 자동으로 설정됩니다. 이렇게 하면 향후 'git p4 submit' 명령이 제대로 작동합니다. submit 명령은 변수만 확인하고 명령줄 옵션은 없습니다.

p4 view의 전체 구문은 'p4 help views'에 설명되어 있습니다. 'git p4'는 view 구문의 일부만 인식합니다. 멀티라인 매핑, '+'를 사용한 오버레이, '-'를 사용한 제외, 공백 주변의 이중 따옴표를 이해합니다. 가능한 와일드카드 중에서 'git p4'는 '...'만 처리하며, 경로 끝에 있을 때만 처리합니다. 'git p4'는 처리되지 않은 와일드카드를 발견하면 불평합니다.

오버랩 매핑 구현에 버그가 있습니다. 여러 저장소 경로가 오버레이를 통해 저장소의 동일한 위치로 매핑되는 경우 'git p4'가 잘못된 것을 선택할 수 있습니다. 이는 'git p4' 전용 클라이언트 spec을 사용하지 않고는 해결하기 어렵습니다.

클라이언트 이름은 여러 가지 방법으로 'git p4'에 제공될 수 있습니다. 'git-p4.client' 변수가 존재하면 우선합니다. 그렇지 않으면 일반 p4 메커니즘이 클라이언트를 결정합니다: 환경 변수 `P4CLIENT`, `P4CONFIG`에서 참조되는 파일 또는 로컬 호스트 이름.


BRANCH DETECTION
----------------
P4는 Git과 같은 브랜치의 개념을 가지고 있지 않습니다. 대신 p4는 저장소를 디렉토리 트리로 구성하며, 관례적으로 다른 논리적 브랜치는 트리 내의 다른 위치에 있습니다. 'p4 branch' 명령은 트리 내의 다른 영역 간의 매핑을 유지하고 관련 콘텐츠를 표시하는 데 사용됩니다. 'git p4'는 이러한 매핑을 사용하여 브랜치 관계를 결정할 수 있습니다.

관심 있는 모든 브랜치가 단일 저장소 경로의 하위 디렉토리로 존재하는 저장소가 있는 경우, 복제 또는 동기화 시 `--detect-branches`를 사용하여 'git p4'가 p4에서 하위 디렉토리를 자동으로 찾고 이를 Git의 브랜치로 생성할 수 있습니다.

예를 들어, P4 저장소 구조가 다음과 같은 경우:

----
//depot/main/...
//depot/branch1/...
----

"p4 branch -o branch1"이 다음과 같은 View 라인을 표시하는 경우:

----
//depot/main/... //depot/branch1/...
----

그러면 다음 'git p4 clone' 명령:

----
git p4 clone --detect-branches //depot@all
----

//depot/main에 대한 'master'라는 별도의 브랜치와 //depot/branch1에 대한 'depot/branch1'이라는 별도의 브랜치를 'refs/remotes/p4/'에 생성합니다.

그러나 브랜치처럼 사용하기 위해 p4에 브랜치를 만들 필요는 없습니다. 브랜치 관계를 자동으로 추론하기 어렵기 때문에 Git 구성 설정 'git-p4.branchList'를 사용하여 명시적으로 브랜치 관계를 식별할 수 있습니다. 이는 간단한 p4 브랜치 사양과 같은 "소스:대상" 쌍의 목록이며, "소스"와 "대상"은 p4 저장소의 경로 요소입니다. 위의 예는 p4 브랜치의 존재에 의존했습니다. p4 브랜치가 없으면 다음과 같은 경우에도 동일한 결과가 발생합니다:

----
git init depot
cd depot
git config git-p4.branchList main:branch1
git p4 clone --detect-branches //depot@all .
----


PERFORMANCE
-----------
'git p4'에서 사용하는 fast-import 메커니즘은 'git p4 sync'를 호출할 때마다 하나의 pack 파일이 생성됩니다. 일반적으로 Git 가비지 압축(linkgit:git-gc[1])은 자동으로 이러한 파일을 더 적은 pack 파일로 압축하지만, 'git repack -adf'를 명시적으로 호출하면 성능이 향상될 수 있습니다.


CONFIGURATION VARIABLES
-----------------------
다음 구성 설정을 사용하여 'git p4' 동작을 수정할 수 있습니다.
모두 'git-p4' 섹션에 있습니다.

General variables
~~~~~~~~~~~~~~~~~
git-p4.user::
	모든 p4 명령에 '-u <user>' 옵션으로 지정된 사용자입니다.
	`P4USER` 환경 변수를 대신 사용할 수 있습니다.

git-p4.password::
	모든 p4 명령에 '-P <password>' 옵션으로 지정된 비밀번호입니다.
	`P4PASS` 환경 변수를 대신 사용할 수 있습니다.

git-p4.port::
	모든 p4 명령에 '-p <port>' 옵션으로 지정된 포트입니다.
	`P4PORT` 환경 변수를 대신 사용할 수 있습니다.

git-p4.host::
	모든 p4 명령에 '-h <host>' 옵션으로 지정된 호스트입니다.
	`P4HOST` 환경 변수를 대신 사용할 수 있습니다.

git-p4.client::
	'-c <client>'를 포함한 모든 p4 명령에 지정된 클라이언트입니다.

git-p4.retries::
	네트워크 시간 초과 시 p4 명령(특히 'p4 sync')을 다시 시도할 횟수를 지정합니다. 기본값은 3입니다.
	재시도를 비활성화하려면 값을 0으로 설정하거나 p4 버전이 재시도를 지원하지 않는 경우(2012.2 이전) 값을 0으로 설정하십시오.

Clone and sync variables
~~~~~~~~~~~~~~~~~~~~~~~~
git-p4.syncFromOrigin::
	다른 Git 저장소에서 커밋을 가져오는 것이 p4에서 가져오는 것보다 훨씬 빠르므로, p4 변경 사항을 먼저 Git 원격에서 찾기 위한 메커니즘이 있습니다. 'refs/remote/origin/p4' 아래에 브랜치가 존재하면 해당 브랜치가 가져와져 p4에서 동기화할 때 사용됩니다. 이 변수를 'false'로 설정하여 이 동작을 비활성화할 수 있습니다.

git-p4.branchUser::
	브랜치 감지의 한 단계는 p4 브랜치를 조회하여 가져올 새 브랜치를 찾는 것을 포함합니다. 기본적으로 모든 브랜치가 검사됩니다. 이 옵션은 변수에 이름이 지정된 단일 사용자가 소유한 브랜치로 검색을 제한합니다.

git-p4.branchList::
	브랜치 감지가 활성화될 때 가져올 브랜치 목록입니다. 각 항목은 콜론(:)으로 구분된 브랜치 이름 쌍이어야 합니다. 이 예는 branchA와 branchB가 모두 main에서 생성되었음을 선언합니다:
+
-------------
git config       git-p4.branchList main:branchA
git config --add git-p4.branchList main:branchB
-------------

git-p4.ignoredP4Labels::
	무시할 p4 레이블 목록입니다. 가져올 수 없는 레이블이 발견됨에 따라 자동으로 빌드됩니다.

git-p4.importLabels::
	--import-labels와 마찬가지로 p4 레이블을 git으로 가져옵니다.

git-p4.labelImportRegexp::
	이 정규 표현식과 일치하는 p4 레이블만 가져옵니다.
	기본값은 '[a-zA-Z0-9_\-.]+$'입니다.

git-p4.useClientSpec::
	p4 클라이언트 spec을 사용하여 관심 있는 p4 저장소 경로를 식별하도록 지정합니다. `--use-client-spec` 옵션을 지정하는 것과 동일합니다. 위 "CLIENT SPEC" 섹션을 참조하십시오.
	이 변수는 p4 클라이언트의 이름이 아니라 부울 값입니다.

git-p4.pathEncoding::
	Perforce는 원본 OS에서 제공된 대로 경로의 인코딩을 유지합니다.
	Git은 UTF-8로 인코딩된 경로를 예상합니다. 이 구성은 git-p4에 Perforce가 경로에 사용한 인코딩을 알려주는 데 사용됩니다. 이 인코딩은 경로를 UTF-8로 트랜스코딩하는 데 사용됩니다. 예시로 Windows의 Perforce는 종종 경로 이름을 인코딩하기 위해 "cp1252"를 사용합니다. 이 옵션이 p4 clone 요청에 전달되면 결과 새 git 저장소에 유지됩니다.

git-p4.metadataDecodingStrategy::
	Perforce는 클라이언트가 지정된 OS에서 저장한 변경 목록 설명 및 사용자 전체 이름의 인코딩을 유지합니다. p4v 클라이언트는 OS 로컬 인코딩을 사용하므로 다른 사용자는 동일한 저장소에 대해 다른 인코딩으로 다른 변경 목록 설명 또는 사용자 전체 이름을 저장할 수 있습니다.
	Git은 커밋 메시지 및 작성자 이름의 불일치/잘못된 인코딩을 허용하지만 utf-8로 지정되기를 기대합니다.
	git-p4는 Perforce 인코딩 불확실성을 처리하기 위해 세 가지 다른 디코딩 전략을 사용할 수 있습니다: 'passthrough'는 Perforce에서 git으로 원본 바이트를 그대로 전달하여 Perforce 데이터가 utf-8이 아닌 다른 인코딩으로 인코딩된 경우에도 유용하지만 잘못 인코딩된 데이터를 생성합니다. 'strict'는 Perforce 데이터가 utf-8로 인코딩될 것으로 예상하며, 그렇지 않으면 가져오기에 실패합니다.
	'fallback'은 데이터를 utf-8으로 해석하려고 시도하고, 그렇지 않으면 대체 인코딩 - 기본적으로 일반적인
	Windows 인코딩 'cp-1252' - 를 사용합니다. 대체 인코딩으로 디코딩하는 데도 실패하면 상위 범위 바이트가 이스케이프됩니다.
	python2에서는 이전 버전과의 호환성을 위해 기본 전략이 'passthrough'이고 python3에서는 'fallback'입니다.
	'strict'가 선택되고 디코딩이 실패하면 오류 메시지에 이 구성 매개변수를 워크어라운드로 변경하라는 메시지가 표시될 수 있습니다. 이 옵션이 p4 clone 요청에 전달되면 결과 새 git 저장소에 유지됩니다.

git-p4.metadataFallbackEncoding::
	'fallback' 전략(git-p4.metadataDecodingStrategy 참조)을 사용하여 Perforce 작성자 이름 및 변경 목록 설명을 디코딩할 때 사용할 대체 인코딩을 지정합니다. 대체 인코딩은 utf-8으로 디코딩이 실패할 때만 사용됩니다. 이 옵션의 기본값은 일반적인 Windows 인코딩인 cp1252입니다. 이 옵션이 p4 clone 요청에 전달되면 결과 새 git 저장소에 유지됩니다.

git-p4.largeFileSystem::
	대용량(이진) 파일에 사용되는 시스템을 지정합니다. 대용량 파일 시스템은 'git p4 submit' 명령을 지원하지 않습니다.
	현재 Git LFS만 구현되어 있습니다(자세한 내용은 https://git-lfs.github.com/ 참조). 이 옵션을 사용하려면 Git LFS 명령줄 확장을 다운로드하고 설치하고 다음과 같이 구성하십시오:
+
-------------
git config       git-p4.largeFileSystem GitLFS
-------------

git-p4.largeFileExtensions::
	파일 확장자와 일치하는 모든 파일