git-patch-id(1)
===============

NAME
----
git-patch-id - 패치에 대한 고유 ID 계산

SYNOPSIS
--------
[synopsis]
git patch-id [--stable | --unstable | --verbatim]

DESCRIPTION
-----------
표준 입력에서 패치를 읽고 패치 ID를 계산합니다.

"패치 ID"는 단순히 패치와 관련된 파일 diff의 SHA-1 합계이며 줄 번호는 무시됩니다. 따라서 "합리적으로 안정적"이지만 동시에 합리적으로 고유합니다. 즉, 동일한 "패치 ID"를 가진 두 패치는 거의 동일한 것이라고 보장할 수 있습니다.

이 명령의 주요 사용 사례는 중복될 가능성이 있는 커밋을 찾는 것입니다.

`git diff-tree --patch` 출력과 함께 사용할 때, 패치가 커밋의 객체 이름으로 시작한다는 사실을 활용하여 두 개의 40바이트 16진수 문자열을 출력합니다. 첫 번째 문자열은 패치 ID이고 두 번째 문자열은 커밋 ID입니다. 이를 사용하여 커밋 세트 또는 범위에 대한 패치 ID 대 커밋 ID 매핑을 만들 수 있습니다.

OPTIONS
-------

`--verbatim`::
	입력이 제공된 그대로의 패치 ID를 계산하며, 공백을 제거하지 않습니다. `--stable`을 암시하고 `--unstable`을 금지합니다.
+
`patchid.verbatim`이 `true`인 경우 이것이 기본값입니다.

`--stable`::
	패치 ID로 "안정적인" 해시 합계를 사용합니다. 이 옵션을 사용하면:
+
--
- 패치를 구성하는 파일 diff의 순서를 재정렬해도 ID에 영향을 주지 않습니다.
  특히, 같은 두 트리를 비교하여 생성된 두 패치에 대해 `-O<orderfile>`의 두 가지 다른 설정을 사용하더라도 동일한 패치 ID 서명이 생성되므로, 두 트리 간의 변경에 대한 메타 정보 인덱싱을 위한 키로 계산된 결과를 사용할 수 있습니다.

- Git 1.9 및 이전 버전에서 생성된 값이나 "불안정한" 해시(아래 `--unstable` 참조)가 설정된 경우에 생성되는 값과 다릅니다. `-O<orderfile>`을 사용하지 않고 가져온 diff 출력에 사용하더라도 마찬가지입니다. 따라서 이러한 "불안정한" 또는 이전 패치 ID를 저장하는 기존 데이터베이스가 사용할 수 없게 됩니다.

- 패치 내의 모든 공백은 무시되며 ID에 영향을 미치지 않습니다.
--
+
`patchid.stable`이 `true`로 설정된 경우 이것이 기본값입니다.

`--unstable`::
	"불안정한" 해시를 패치 ID로 사용합니다. 이 옵션을 사용하면 Git 1.9 및 이전 버전에서 생성된 이전 패치 ID 값과 호환되는 결과가 생성되며 공백은 무시됩니다. Git 1.9 및 이전 버전에서 생성된 패치 ID를 저장하는 사전 기존 데이터베이스(재정렬된 패치를 다루지 않는 경우)를 가진 사용자는 이 옵션을 사용하고 싶을 수 있습니다.
+
이것이 기본값입니다.

EXAMPLES
--------

linkgit:git-cherry[1]는 브랜치의 어떤 커밋이 업스트림 브랜치의 패치 ID와 동등한 커밋을 가지고 있는지 보여줍니다. 하지만 그러한 커밋이 존재하는지 여부만 알려줍니다. 업스트림에서 관련 커밋을 알고 싶다면 어떻게 해야 할까요? 이 명령을 사용하여 자신의 브랜치와 업스트림 브랜치 간의 매핑을 만들 수 있습니다.

----
#!/bin/sh

upstream="$1"
branch="$2"
test -z "$branch" && branch=HEAD
limit="$3"
if test -n "$limit"
then
    tail_opts="$limit".."$upstream"
else
    since=$(git log --format=%aI "$upstream".."$branch" | tail -1)
    tail_opts=--since="$since"' '"$upstream"
fi
for_branch=$(mktemp)
for_upstream=$(mktemp)

git rev-list --no-merges "$upstream".."$branch" |
    git diff-tree --patch --stdin |
    git patch-id  --stable | sort >"$for_branch"
git rev-list --no-merges $tail_opts |
    git diff-tree --patch --stdin |
    git patch-id  --stable | sort >"$for_upstream"
join -a1 "$for_branch" "$for_upstream" | cut -d' ' -f2,3
rm "$for_branch"
rm "$for_upstream"
----

이제 첫 번째 열은 자신의 브랜치의 커밋을 보여주고 두 번째 열은 패치 ID와 동등한 커밋(존재하는 경우)을 보여줍니다.

SEE ALSO
--------
linkgit:git-cherry[1]

GIT
---
linkgit:git[1] 제품군의 일부