git-rebase(1)
=============

NAME
----
git-rebase - 다른 베이스 팁 위에 커밋 다시 적용

SYNOPSIS
--------
[verse]
'git rebase' [-i | --interactive] [<options>] [--exec <cmd>]
	[--onto <newbase> | --keep-base] [<upstream> [<branch>]]
'git rebase' [-i | --interactive] [<options>] [--exec <cmd>] [--onto <newbase>]
	--root [<branch>]
'git rebase' (--continue|--skip|--abort|--quit|--edit-todo|--show-current-patch)

DESCRIPTION
-----------
커밋 시리즈를 다른 시작점으로 이식합니다.
`git rebase`를 사용하여 커밋 순서를 변경하거나 결합할 수도 있습니다: 이를 수행하는 방법은 아래의 INTERACTIVE MODE를 참조하십시오.

예를 들어, 이 기록에서 `topic` 브랜치에서 작업 중이었고 `master` 브랜치에서 완료된 작업을 "따라잡고" 싶다고 가정해 보겠습니다.

------------
          A---B---C topic
         /
    D---E---F---G master
------------

`master`에서 분기된 이후 `topic`에서 만든 커밋(즉, A, B, C)을 현재 `master` 위에 이식하려고 합니다. `topic` 브랜치가 체크아웃된 상태에서 `git rebase master`를 실행하여 이를 수행할 수 있습니다. 다른 브랜치에서 `topic`을 리베이스하려면 `git rebase master topic`은 `git checkout topic && git rebase master`의 바로 가기입니다.

------------
                  A'--B'--C' topic
                 /
    D---E---F---G master
------------


이 과정에서 병합 충돌이 발생하면, `git rebase`는 첫 번째 문제 커밋에서 중지하고 충돌 마커를 남깁니다. 이 경우 다음 중 하나를 수행할 수 있습니다.

1. 충돌을 해결합니다. `git diff`를 사용하여 마커(<<<<<<)를 찾고 충돌을 해결하기 위해 편집할 수 있습니다. 편집한 각 파일에 대해 Git에 충돌이 해결되었음을 알려야 합니다. `git add <filename>`으로 충돌을 해결됨으로 표시할 수 있습니다. 모든 충돌을 해결한 후 다음 명령으로 리베이스 프로세스를 계속할 수 있습니다.

   git rebase --continue

2. `git rebase`를 중지하고 다음 명령으로 브랜치를 원래 상태로 되돌립니다.

   git rebase --abort

3. 다음 명령으로 병합 충돌을 일으킨 커밋을 건너<binary data, 1>니다.

   git rebase --skip

리베이스할 `<upstream>`을 지정하지 않으면 `branch.<name>.remote` 및 `branch.<name>.merge` 옵션에 구성된 업스트림이 사용됩니다 (자세한 내용은 linkgit:git-config[1] 참조). `--fork-point` 옵션이 가정됩니다. 현재 어떤 브랜치에도 없거나 현재 브랜치에 구성된 업스트림이 없으면 리베이스가 중단됩니다.

다음은 `git rebase <upstream>`이 수행하는 작업에 대한 단순화된 설명입니다.

1. 현재 브랜치에서 `<upstream>`에서 분기된 이후 `<upstream>`에서 해당 커밋이 없는 모든 커밋 목록을 만듭니다.
2. `git checkout --detach <upstream>`과 동일하게 `<upstream>`을 체크아웃합니다.
3. 커밋을 순서대로 하나씩 다시 적용합니다. 이는 각 커밋에 대해 `git cherry-pick <commit>`을 실행하는 것과 유사합니다. 병합이 처리되는 방식은 REBASING MERGES를 참조하십시오.
4. `git checkout -B <branch>`와 동일하게 브랜치가 최종 커밋을 가리키도록 업데이트합니다.

[NOTE]
리베이스를 시작할 때 `ORIG_HEAD`는 리베이스될 브랜치의 팁에 있는 커밋을 가리키도록 설정됩니다. 그러나 리베이스 중에 `git reset`과 같이 `ORIG_HEAD`를 변경하는 다른 명령이 사용되면 리베이스가 끝날 때 `ORIG_HEAD`가 해당 커밋을 계속 가리킨다고 보장할 수 없습니다. 그러나 이전 브랜치 팁은 현재 브랜치의 reflog (즉, `@{1}`, linkgit:gitrevisions[7] 참조)를 사용하여 액세스할 수 있습니다.

--ONTO를 사용한 토픽 브랜치 이식
----------------------------------------

다음은 토픽 브랜치를 한 브랜치를 기반으로 다른 브랜치로 이식하는 방법으로, `rebase --onto`를 사용하여 후자는 브랜치에서 토픽 브랜치를 포크한 것처럼 보이게 하는 방법입니다.

먼저 'topic'이 'next' 브랜치를 기반으로 한다고 가정해 봅시다.
예를 들어, 'topic'에서 개발된 기능은 'next'에 있는 일부 기능에 의존합니다.

------------
    o---o---o---o---o  master
         \
          o---o---o---o---o  next
                           \
                            o---o---o  topic
------------

'topic'이 'master' 브랜치를 기반으로 하도록 만들고 싶습니다. 예를 들어, 'topic'이 의존하는 기능이 더 안정적인 'master' 브랜치로 병합되었기 때문입니다. 다음과 같이 보이도록 하려고 합니다.

------------
    o---o---o---o---o  master
        |            \
        |             o'--o'--o'  topic
         \
          o---o---o---o---o  next
------------

다음 명령을 사용하여 이를 얻을 수 있습니다.

    git rebase --onto master next topic


--onto 옵션의 또 다른 예는 브랜치의 일부를 리베이스하는 것입니다.
다음과 같은 상황이 있다면:

------------
                            H---I---J topicB
                           /
                  E---F---G  topicA
                 /
    A---B---C---D  master
------------

다음 명령은

    git rebase --onto master topicA topicB

결과는 다음과 같습니다.

------------
                 H'--I'--J'  topicB
                /
                | E---F---G  topicA
                |/
    A---B---C---D  master
------------

이는 topicB가 topicA에 의존하지 않을 때 유용합니다.

커밋 범위도 리베이스로 제거할 수 있습니다.
다음과 같은 상황이 있다면:

------------
    E---F---G---H---I---J  topicA
------------

다음 명령은

    git rebase --onto topicA~5 topicA~3 topicA

F와 G 커밋을 제거하는 결과를 낳습니다.

------------
    E---H'---I'---J'  topicA
------------

이는 F와 G에 결함이 있었거나 topicA의 일부가 아니어야 하는 경우 유용합니다. `--onto`의 인수와 `<upstream>` 매개변수는 유효한 커밋-ish가 될 수 있음을 참고하십시오.

MODE OPTIONS
------------

이 섹션의 옵션은 다른 옵션과 함께 사용할 수 없으며, 서로 함께 사용할 수도 없습니다.

--continue::
	병합 충돌을 해결한 후 리베이스 프로세스를 다시 시작합니다.

--skip::
	현재 패치를 건너<binary data, 1>면서 리베이스 프로세스를 다시 시작합니다.

--abort::
	리베이스 작업을 중단하고 HEAD를 원래 브랜치로 재설정합니다. 리베이스 작업이 시작될 때 `<branch>`가 제공되었다면 `HEAD`는 `<branch>`로 재설정됩니다. 그렇지 않으면 `HEAD`는 리베이스 작업이 시작된 위치로 재설정됩니다.

--quit::
	리베이스 작업을 중단하지만 `HEAD`는 원래 브랜치로 재설정되지 않습니다. 인덱스와 워킹 트리도 결과적으로 변경되지 않은 상태로 유지됩니다. `--autostash`를 사용하여 임시 스태시 항목이 생성된 경우 스태시 목록에 저장됩니다.

--edit-todo::
	대화형 리베이스 중에 todo 목록을 편집합니다.

--show-current-patch::
	대화형 리베이스 중이거나 충돌로 인해 리베이스가 중지되었을 때 현재 패치를 표시합니다. 이는 `git show REBASE_HEAD`와 동일합니다.

OPTIONS
-------
--onto <newbase>::
	새 커밋을 생성할 시작점입니다. `--onto` 옵션이 지정되지 않은 경우 시작점은 `<upstream>`입니다. 기존 브랜치 이름뿐만 아니라 유효한 커밋이 될 수 있습니다.
+
특수한 경우로, A와 B의 머지 베이스에 대한 바로 가기로 "A\...B"를 사용할 수 있습니다. A 또는 B 중 하나를 생략할 수 있으며, 이 경우 기본값은 HEAD입니다.

TRANSPLANTING A TOPIC BRANCH WITH --ONTO 위의 예제를 참조하십시오.

--keep-base::
	새 커밋을 생성할 시작점을 `<upstream>`과 `<branch>`의 머지 베이스로 설정합니다.
	`git rebase --keep-base <upstream> <branch>`를 실행하는 것은
	`git rebase --reapply-cherry-picks --no-fork-point --onto <upstream>...<branch> <upstream> <branch>`를 실행하는 것과 동일합니다.
+
이 옵션은 업스트림 브랜치 위에 기능을 개발하는 경우에 유용합니다. 기능 개발 중에 업스트림 브랜치가 진행될 수 있으며 업스트림 위에 계속 리베이스하는 것이 최선의 방법이 아닐 수 있지만 베이스 커밋은 그대로 유지하는 것이 좋습니다. 베이스 커밋이 변경되지 않았으므로 이 옵션은 커밋을 잃지 않도록 `--reapply-cherry-picks`를 의미합니다.
+
이 옵션과 `--fork-point` 모두 `<upstream>`과 `<branch>` 간의 머지 베이스를 찾지만, 이 옵션은 새 커밋이 생성될 _시작점_으로 머지 베이스를 사용하고, `--fork-point`는 리베이스될 _커밋 집합_을 결정하는 데 머지 베이스를 사용합니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

<upstream>::
	비교 대상 업스트림 브랜치입니다. 기존 브랜치 이름뿐만 아니라 유효한 커밋이 될 수 있습니다. 현재 브랜치의 구성된 업스트림으로 기본값입니다.

<branch>::
	작업 브랜치; 기본값은 `HEAD`입니다.

--apply::
	리베이스에 적용 전략 사용 (`git-am` 내부 호출). 이 옵션은 나중에 머지 백엔드가 적용 백엔드가 수행하는 모든 작업을 처리하면 더 이상 사용되지 않을 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--empty=(drop|keep|stop)::
	시작 시 비어 있지 않고 업스트림 커밋의 깨끗한 체리픽이 아닌 커밋이 리베이스 후 (이미 업스트림 변경 사항의 하위 집합을 포함하기 때문에) 비게 되는 경우 처리 방법:
+
--
`drop`;;
	커밋이 삭제됩니다. 이것이 기본 동작입니다.
`keep`;;
	커밋이 유지됩니다. `--exec`가 지정된 경우 (IMHO `-i`/`--interactive`가 함께 지정되지 않은 경우) 이 옵션이 암시됩니다.
`stop`;;
`ask`;;
	커밋이 적용될 때 리베이스가 중단되어 삭제, 파일 추가 편집, 또는 빈 변경 사항 커밋을 선택할 수 있습니다. 이 옵션은 `-i`/`--interactive`가 지정되면 암시됩니다. `ask`는 `stop`의 사용되지 않는 별칭입니다.
--
+
비어 있는 상태로 시작하는 커밋은 유지되고( `--no-keep-empty`가 지정되지 않은 경우), 깨끗한 체리픽인 커밋( `git log --cherry-mark ...`로 결정됨)은 감지되어 미리 삭제됩니다( `--reapply-cherry-picks` 또는 `--keep-base`가 전달되지 않는 한).
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--no-keep-empty::
--keep-empty::
	리베이스 전에 비어 있는 커밋(즉, 부모에서 아무것도 변경하지 않은 커밋)을 결과에 유지하지 않습니다. 비어 있는 커밋은 유지하는 것이 기본값이며, 사용자가 의도적으로 그러한 커밋을 생성하고 싶어한다는 것을 나타내는 `--allow-empty` 재정의 플래그를 `git commit`에 전달해야 하기 때문에 그러한 커밋을 생성하려면 `git commit`에 `--allow-empty` 재정의 플래그를 전달해야 합니다.
+
이 플래그의 사용은 드물 것입니다. 대화형 리베이스를 시작하여 원하지 않는 커밋에 해당하는 줄을 제거하여 비어 있는 커밋을 제거할 수 있기 때문입니다. 이 플래그는 외부 도구가 많은 빈 커밋을 생성하고 이를 모두 제거하려는 경우 편리한 바로 가기로 존재합니다.
+
비어 있지 않지만 리베이스 후 비게 되는 커밋에 대해서는 `--empty` 플래그를 참조하십시오.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--reapply-cherry-picks::
--no-reapply-cherry-picks::
	업스트림 커밋의 모든 깨끗한 체리픽을 미리 삭제하는 대신 다시 적용합니다. (만약 이 커밋들이 리베이스 후 업스트림 변경 사항의 하위 집합을 포함하기 때문에 비게 되면, 해당 커밋에 대한 동작은 `--empty` 플래그에 의해 제어됩니다.)
+
`--keep-base` (이거나 `--no-reapply-cherry-picks`가 제공되지 않는 한)가 없을 경우, 이러한 커밋은 자동으로 삭제됩니다. 이는 모든 업스트림 커밋을 읽어야 하므로, 읽어야 할 업스트림 커밋이 많은 저장소에서는 성능이 저하될 수 있습니다. 'merge' 백엔드를 사용할 때 삭제된 각 커밋에 대해 경고가 표시됩니다( `--quiet`가 제공되지 않는 한). `advice.skippedCherryPicks`가 false로 설정되지 않은 경우( linkgit:git-config[1] 참조) 조언도 발행됩니다.
+
`--reapply-cherry-picks`는 리베이스가 모든 업스트림 커밋을 읽는 것을 생략하여 성능을 향상시킬 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--allow-empty-message::
	No-op. 빈 메시지를 가진 커밋을 리베이스하는 것은 실패했으며 이 옵션은 해당 동작을 재정의하여 빈 메시지를 가진 커밋을 리베이스할 수 있게 했습니다. 이제 빈 메시지를 가진 커밋은 리베이스를 중단시키지 않습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

-m::
--merge::
	머지 전략 사용 (기본값).
+
리베이스 머지는 워킹 브랜치의 각 커밋을 `<upstream>` 브랜치 위에 다시 적용함으로써 수행됩니다. 이 때문에 병합 충돌이 발생하면 'ours'로 보고되는 측은 `<upstream>`으로 시작하는 지금까지 리베이스된 시리즈이고, 'theirs'는 워킹 브랜치입니다.
	즉, 측면이 뒤바뀌었습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

-s <strategy>::
--strategy=<strategy>::
	주어진 머지 전략을 사용합니다 (기본값 `ort` 대신).
	이는 `--merge`를 의미합니다.
+
`git rebase`는 주어진 전략을 사용하여 워킹 브랜치의 각 커밋을 `<upstream>` 브랜치 위에 다시 적용하기 때문에, `ours` 전략을 사용하면 `<branch>`의 모든 패치가 비워지므로 거의 의미가 없습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

-X <strategy-option>::
--strategy-option=<strategy-option>::
	`<strategy-option>`을 머지 전략에 전달합니다.
	이는 `--merge`를 의미하며, 전략이 지정되지 않은 경우 `-s ort`를 의미합니다. `-m` 옵션에 대해 설명된 'ours'와 'theirs'의 반전을 참고하십시오.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

include::rerere-options.adoc[]

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	GPG 사인 커밋. `keyid` 인수는 선택 사항이며 커미터 신원으로 기본값 설정됩니다. 지정된 경우 공백 없이 옵션에 붙여야 합니다. `--no-gpg-sign`은 `commit.gpgSign` 구성 변수와 이전 `--gpg-sign`을 모두 무효화하는 데 유용합니다.

-q::
--quiet::
	조용하게. `--no-stat`를 의미합니다.

-v::
--verbose::
	자세하게. `--stat`를 의미합니다.

--stat::
	이전 리베이스 이후 변경된 내용을 보여주는 diffstat를 표시합니다. diffstat는 rebase.stat 구성 옵션에 의해서도 제어됩니다.

-n::
--no-stat::
	리베이스 프로세스의 일부로 diffstat를 표시하지 않습니다.

--no-verify::
	이 옵션은 사전 리베이스 훅을 우회합니다. linkgit:githooks[5]도 참조하십시오.

--verify::
	사전 리베이스 훅이 실행되도록 허용하며, 이것이 기본값입니다. 이 옵션은 `--no-verify`를 재정의하는 데 사용될 수 있습니다. linkgit:githooks[5]도 참조하십시오.

-C<n>::
	각 변경 전후에 최소 `<n>`줄의 주변 컨텍스트가 일치하는지 확인합니다. 주변 컨텍스트가 더 적은 경우 모두 일치해야 합니다. 기본적으로 어떤 컨텍스트도 무시되지 않습니다. `--apply`를 의미합니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--no-ff::
--force-rebase::
-f::
	변경되지 않은 커밋을 패스트포워드하는 대신 모든 리베이스된 커밋을 개별적으로 다시 적용합니다. 이렇게 하면 리베이스된 브랜치의 전체 기록이 새 커밋으로 구성됩니다.
+
토픽 브랜치 병합을 되돌린 후에 이 옵션을 사용하면 토픽 브랜치가 새 커밋으로 재생성되므로 "되돌리기 취소" 없이 성공적으로 다시 병합할 수 있습니다 (자세한 내용은 link:howto/revert-a-faulty-merge.html[revert-a-faulty-merge How-To] 참조).

--fork-point::
--no-fork-point::
	리베이스될 커밋을 계산할 때 `<upstream>`과 `<branch>` 간의 더 나은 공통 조상을 찾기 위해 reflog를 사용합니다.
+
`--fork-point`가 활성화되면, 리베이스될 커밋 집합을 계산하는 데 `<upstream>` 대신 'fork_point'가 사용됩니다. 여기서 'fork_point'는 `git merge-base --fork-point <upstream> <branch>` 명령의 결과입니다 ( linkgit:git-merge-base[1] 참조). 'fork_point'가 비어 있게 되면, `<upstream>`이 대체로 사용됩니다.
+
명령줄에 `<upstream>` 또는 `--keep-base`가 제공되면 기본값은 `--no-fork-point`이고, 그렇지 않으면 기본값은 `--fork-point`입니다. `rebase.forkpoint` in linkgit:git-config[1]도 참조하십시오.
+
브랜치가 `<upstream>`을 기반으로 했지만 `<upstream>`이 되감기고 브랜치에 삭제된 커밋이 포함된 경우, 이 옵션은 `--keep-base`와 함께 사용하여 이러한 커밋을 브랜치에서 삭제할 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--ignore-whitespace::
	차이 조정을 시도할 때 공백 차이를 무시합니다. 현재 각 백엔드는 근사치를 구현합니다.
+
apply backend;;
	패치를 적용할 때 컨텍스트 줄의 공백 변경을 무시합니다. 불행히도, 패치로 대체되는 "이전" 줄이 기존 파일과 공백만 다른 경우, 성공적인 패치 적용 대신 병합 충돌이 발생합니다.
+
merge backend;;
	병합 시 공백 변경만 있는 줄은 변경되지 않은 것으로 처리합니다. 불행히도, 공백을 수정하기 위해 의도된 패치 덩어리는 다른 쪽에서 충돌하는 변경 사항이 없더라도 삭제됩니다.

--whitespace=<option>::
	이 플래그는 패치를 적용하는 `git apply` 프로그램 ( linkgit:git-apply[1] 참조)에 전달됩니다.
	`--apply`를 의미합니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--committer-date-is-author-date::
	커미터 날짜로 현재 시간을 사용하는 대신, 리베이스 중인 커밋의 작성자 날짜를 커미터 날짜로 사용합니다. 이 옵션은 `--force-rebase`를 의미합니다.
+
경고: 기록 탐색 메커니즘은 커밋이 비감소하는 커밋 타임스탬프를 가지고 있다고 가정합니다. 이 옵션을 실제로 사용해야 하는지 고려해야 합니다. 그런 다음 이 옵션을 사용하여 커미터 날짜를 재정의해야 하는 경우, 리베이스하는 커밋이 적용 중인 가장 오래된 커밋(작성자 날짜 기준)보다 이전(커밋 날짜 기준) 베이스 위에 있어야 합니다.

--ignore-date::
--reset-author-date::
	원본 커밋의 작성자 날짜 대신 현재 시간을 리베이스된 커밋의 작성자 날짜로 사용합니다. 이 옵션은 `--force-rebase`를 의미합니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--signoff::
	리베이스된 모든 커밋 메시지에 `Signed-off-by` 트레일러를 추가합니다. `--interactive`가 제공된 경우 선택, 편집 또는 재작성 표시된 커밋에만 트레일러가 추가됨을 참고하십시오.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--trailer=<trailer>::
	링크git:git-interpret-trailers[1]를 통해 처리되는 모든 리베이스된 커밋 메시지에 주어진 트레일러를 추가합니다. 이 옵션은 `--force-rebase`를 의미합니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

-i::
--interactive::
	리베이스할 커밋 목록을 만듭니다. 리베이스 전에 사용자가 목록을 편집하도록 합니다. 이 모드는 커밋을 분할하는 데에도 사용할 수 있습니다 ( SPLITTING COMMITS 아래 참조).
+
커밋 목록 형식은 rebase.instructionFormat 구성 옵션을 설정하여 변경할 수 있습니다. 사용자 정의 지침 형식은 자동으로 커밋 해시가 형식 앞에 추가됩니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

-r::
--rebase-merges[=(rebase-cousins|no-rebase-cousins)]::
--no-rebase-merges::
	기본적으로 리베이스는 todo 목록에서 병합 커밋을 삭제하고 리베이스된 커밋을 단일 선형 브랜치에 넣습니다. `--rebase-merges`를 사용하면 리베이스할 커밋 내의 브랜칭 구조를 다시 생성하여 보존하려고 시도합니다. 해결된 병합 충돌이나 수동 수정은 수동으로 해결/재적용해야 합니다. `--no-rebase-merges`는 `rebase.rebaseMerges` 구성 옵션과 이전 `--rebase-merges`를 모두 무효화하는 데 사용될 수 있습니다.
+
병합을 리베이스할 때 두 가지 모드가 있습니다: `rebase-cousins`와 `no-rebase-cousins`. 모드가 지정되지 않으면 기본값은 `no-rebase-cousins`입니다. `no-rebase-cousins` 모드에서는 `<upstream>`을 직접적인 조상이 아닌 커밋은 원래 브랜치 지점을 유지합니다 (즉, linkgit:git-log[1]의 `--ancestry-path` 옵션에 의해 제외되는 커밋은 기본적으로 원래 조상을 유지합니다). `rebase-cousins` 모드에서는 이러한 커밋이 대신 `<upstream>` (또는 지정된 경우 `<onto>`)으로 리베이스됩니다.
+
현재 병합 커밋을 다시 생성하는 것은 `ort` 머지 전략을 통해서만 가능합니다. 다른 머지 전략은 명시적인 `exec git merge -s <strategy> [...]` 명령을 통해서만 사용할 수 있습니다.
+
REBASING MERGES 및 INCOMPATIBLE OPTIONS 아래도 참조하십시오.

-x <cmd>::
--exec <cmd>::
	최종 기록에서 커밋을 생성하는 각 줄 뒤에 "exec <cmd>"를 추가합니다. `<cmd>`는 하나 이상의 쉘 명령으로 해석됩니다. 실패하는 명령은 리베이스를 중단하고 종료 코드 1을 반환합니다.
+
명령 하나에 여러 명령을 사용하여 여러 명령을 실행할 수 있습니다.
+
	git rebase -i --exec "cmd1 && cmd2 && ..."
+
또는 여러 `--exec`를 제공하여 실행할 수 있습니다.
+
	git rebase -i --exec "cmd1" --exec "cmd2" --exec ...
+
`--autosquash`가 사용되면 `exec` 줄은 중간 커밋에 대해 추가되지 않으며, 각 스쿼시/픽스업 시리즈의 끝에만 나타납니다.
+
이는 내부적으로 `--interactive` 메커니즘을 사용하지만 명시적인 `--interactive` 없이 실행할 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--root::
	`<upstream>`으로 제한하는 대신 `<branch>`에서 도달 가능한 모든 커밋을 리베이스합니다. 이를 통해 브랜치의 루트 커밋을 리베이스할 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--autosquash::
--no-autosquash::
	특별히 포맷된 메시지로 커밋을 리베이스 중인 이전 커밋으로 자동 스쿼시합니다. 커밋 메시지가 "squash! ", "fixup! " 또는 "amend! "로 시작하면 제목의 나머지 부분이 커밋 지정자로 취급되며, 이는 커밋의 제목 또는 해시와 일치하는 경우 이전 커밋과 일치합니다. 커밋이 완전히 일치하지 않으면, 지정자와 커밋 제목의 시작 부분과의 일치가 고려됩니다.
+
리베이스 todo 목록에서 스쿼시, 픽스업 및 amend 커밋의 동작은 `pick`에서 `squash`, `fixup` 또는 `fixup -C`로 변경되며, 수정 중인 커밋 바로 뒤로 이동합니다. `--interactive` 옵션을 사용하여 진행하기 전에 todo 목록을 검토하고 편집할 수 있습니다.
+
스쿼시 마커가 있는 커밋을 생성하는 권장 방법은 대상 커밋을 인수로 사용하고 새 커밋의 제목을 자동으로 채우는 linkgit:git-commit[1]의 `--squash`, `--fixup`, `--fixup=amend:` 또는 `--fixup=reword:` 옵션을 사용하는 것입니다.
+
`rebase.autoSquash` 구성 변수를 true로 설정하면 대화형 리베이스에 대해 자동 스쿼싱이 기본적으로 활성화됩니다. `--no-autosquash` 옵션은 해당 설정을 무효화하는 데 사용될 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

--autostash::
--no-autostash::
	작업이 시작되기 전에 임시 스태시 항목을 자동으로 생성하고 작업이 종료된 후 적용합니다. 이는 더티 워크트리에서 리베이스를 실행할 수 있음을 의미합니다. 그러나 주의해서 사용하십시오. 성공적인 리베이스 후 최종 스태시 적용으로 인해 복잡한 충돌이 발생할 수 있습니다.

--reschedule-failed-exec::
--no-reschedule-failed-exec::
	실패한 `exec` 명령을 자동으로 다시 예약합니다. 이는 대화형 모드(또는 `--exec` 옵션이 제공된 경우)에서만 의미가 있습니다.
+
이 옵션은 리베이스가 시작될 때 적용됩니다. 이는 최초 `git rebase`에 제공된 명령줄 옵션, `rebase.rescheduleFailedExec` 구성 ( linkgit:git-config[1] 또는 "CONFIGURATION" 아래 참조), 또는 기본값 false에 기반하여 전체 리베이스에 대해 보존됩니다.
+
이 옵션을 전체 리베이스에 대해 기록하는 것은 편의 기능입니다. 그렇지 않으면 `git rebase --continue`가 호출될 때 `rebase.rescheduleFailedExec=true` 구성이 존재하여 명시적인 `--no-reschedule-failed-exec`는 무효화됩니다. 현재 `--[no-]reschedule-failed-exec`를 `git rebase --continue`에 전달할 수 없습니다.

--update-refs::
--no-update-refs::
	리베이스 중인 커밋을 가리키는 모든 브랜치를 자동으로 강제 업데이트합니다. 워크트리에서 체크아웃된 모든 브랜치는 이 방식으로 업데이트되지 않습니다.
+
`rebase.updateRefs` 구성 변수가 설정된 경우, 이 옵션을 사용하여 해당 설정을 재정의하고 비활성화할 수 있습니다.
+
INCOMPATIBLE OPTIONS 아래도 참조하십시오.

INCOMPATIBLE OPTIONS
--------------------

다음 옵션:

 * --apply
 * --whitespace
 * -C

은 다음 옵션과 호환되지 않습니다:

 * --merge
 * --strategy
 * --strategy-option
 * --autosquash
 * --rebase-merges
 * --interactive
 * --exec
 * --no-keep-empty
 * --empty=
 * --[no-]reapply-cherry-picks ( --keep-base 없이 사용 시)
 * --update-refs
 * --root ( --onto 없이 사용 시)
 * --trailer

추가로, 다음 옵션 쌍은 호환되지 않습니다:

 * --keep-base 와 --onto
 * --keep-base 와 --root
 * --fork-point 와 --root

BEHAVIORAL DIFFE