git-read-tree(1)
================

NAME
----
git-read-tree - 인덱스로 트리 정보 읽기


SYNOPSIS
--------
[verse]
'git read-tree' [(-m [--trivial] [--aggressive] | --reset | --prefix=<prefix>)
		[-u | -i]] [--index-output=<file>] [--no-sparse-checkout]
		(--empty | <tree-ish1> [<tree-ish2> [<tree-ish3>]])


DESCRIPTION
-----------
<tree-ish>로 주어진 트리 정보를 인덱스로 읽어오지만, 실제 "캐싱"하는 파일들은 *업데이트하지 않습니다*. (참고: linkgit:git-checkout-index[1])

옵션으로, `-m` 플래그를 사용하여 트리를 인덱스로 병합하거나, 빠른-포워드(즉, 2-way) 병합 또는 3-way 병합을 수행할 수 있습니다. `-m`과 함께 사용될 때, `-u` 플래그는 병합 결과로 작업 트리 파일도 업데이트하도록 합니다.

'git read-tree' 자체는 단순한(trivial) 병합만 수행합니다. 충돌하는 경로만 병합되지 않은 상태로 'git read-tree'가 반환됩니다.

OPTIONS
-------
-m::
	읽기만 하는 것이 아니라 병합을 수행합니다. 이전 병합을 완료하지 않아 인덱스 파일에 병합되지 않은 항목이 있는 경우 명령이 실행을 거부합니다.

--reset::
	-m과 같지만, 병합되지 않은 항목이 실패하는 대신 폐기됩니다. `-u`와 함께 사용될 때, 작업 트리 변경 사항 또는 추적되지 않은 파일이나 디렉토리를 잃게 되는 업데이트는 작업을 중단하지 않습니다.

-u::
	병합이 성공한 후, 병합 결과로 작업 트리 파일을 업데이트합니다.

-i::
	일반적으로 병합은 현재 헤드 커밋과 최신 상태인 인덱 파일 및 작업 트리를 요구하여 로컬 변경 사항을 잃지 않도록 합니다. 이 플래그는 작업 트리와의 검사를 비활성화하며, 직접적으로 관련 없는 트리 병합을 임시 인덱스 파일로 생성할 때 사용하기 위한 것입니다.

-n::
--dry-run::
	인덱스나 작업 트리 파일을 실제로 업데이트하지 않고, 명령이 오류를 발생시키는지 확인합니다.

-v::
	파일을 체크아웃하는 진행 상황을 표시합니다.

--trivial::
	'git read-tree'에 의한 3-way 병합을, 인덱스에서 충돌하는 파일을 해결되지 않은 상태로 남기고 단순한(trivial) 경우에 대한 병합을 수행하는 대신, 파일 수준 병합이 필요 없을 때만 발생하도록 제한합니다.

--aggressive::
	일반적으로 'git read-tree'에 의한 3-way 병합은 매우 단순한(trivial) 경우에 대한 병합을 수행하고 다른 경우에는 인덱에서 해결되지 않은 상태로 둡니다. 따라서 상위 수준(porcelain)에서 다른 병합 정책을 구현할 수 있습니다. 이 플래그는 명령이 내부적으로 몇 가지 추가 경우를 해결하도록 합니다:
+
* 한쪽에서 경로를 제거하고 다른 쪽에서 경로를 수정하지 않은 경우. 해결은 해당 경로를 제거하는 것입니다.
* 양쪽 모두에서 경로를 제거하는 경우. 해결은 해당 경로를 제거하는 것입니다.
* 양쪽 모두 동일한 경로를 추가하는 경우. 해결은 해당 경로를 추가하는 것입니다.

--prefix=<prefix>::
	현재 인덱 내용을 유지하고, `<prefix>` 디렉토리 아래의 지정된 트리-쉬(tree-ish) 내용을 읽습니다. 명령은 원래 인덱 파일에 이미 존재했던 항목을 덮어쓰는 것을 거부합니다.

--index-output=<file>::
	결과를 `$GIT_INDEX_FILE`에 쓰는 대신, 결과 인덱을 지정된 파일에 씁니다. 명령이 실행되는 동안, 원래 인덱 파일은 평소와 같은 메커니즘으로 잠깁니다. 파일은 일반적인 인덱 파일 옆에 생성되는 임시 파일에서 rename(2)될 수 있어야 합니다. 일반적으로 이는 인덱 파일과 동일한 파일 시스템에 있어야 하며, 인덱 파일 및 인덱 출력 파일이 위치한 디렉토리에 대한 쓰기 권한이 필요함을 의미합니다.

--recurse-submodules::
--no-recurse-submodules::
	--recurse-submodules를 사용하면 슈퍼프로젝트에 기록된 커밋에 따라 모든 활성 하위 모듈의 내용이 재귀적으로 read-tree를 호출하여 업데이트되며, 하위 모듈의 HEAD는 해당 커밋에서 분리(detached)됩니다.

--no-sparse-checkout::
	`core.sparseCheckout`이 true이더라도 희소 체크아웃 지원을 비활성화합니다.

--empty::
	트리 객체를 인덱스로 읽어오는 대신, 인덱을 비웁니다.

-q::
--quiet::
	화면 출력 메시지를 억제합니다.

<tree-ish#>::
	읽기/병합할 트리 객체의 ID입니다.


MERGING
-------
`-m`이 지정된 경우, 'git read-tree'는 3가지 종류의 병합을 수행할 수 있습니다. 트리 1개를 지정하면 단일 트리 병합, 트리 2개를 지정하면 빠른-포워드 병합, 트리 3개 이상을 지정하면 3-way 병합입니다.


Single Tree Merge
~~~~~~~~~~~~~~~~~
트리가 1개만 지정된 경우, 'git read-tree'는 사용자가 `-m`을 지정하지 않은 것처럼 작동합니다. 단, 원래 인덱에 지정된 경로 이름에 대한 항목이 있고, 해당 경로의 내용이 읽어오는 트리의 내용과 일치하면, 인덱의 stat 정보가 사용됩니다. (다시 말해, 인덱의 stat()이 병합되는 트리의 stat()보다 우선합니다.)

이는 `git read-tree -m <newtree>`를 실행한 후 `git checkout-index -f -u -a`를 수행할 때, 'git checkout-index'가 실제로 변경된 항목만 체크아웃하도록 합니다.

이는 'git diff-files'가 'git read-tree' 실행 후 실행될 때 불필요한 오탐지를 피하는 데 사용됩니다.


Two Tree Merge
~~~~~~~~~~~~~~

일반적으로 이는 `git read-tree -m $H $M`과 같이 호출됩니다. 여기서 $H는 현재 저장소의 헤드 커밋이고, $M은 외부 트리의 헤드입니다. 이는 $H보다 앞서 나아가는 상황입니다 (즉, 빠른-포워드 상황).

두 개의 트리가 지정될 때, 사용자가 'git read-tree'에 다음과 같이 지시하는 것입니다:

     1. 현재 인덱 및 작업 트리는 $H에서 파생되었지만, $H 이후 로컬 변경 사항이 있을 수 있습니다.

     2. 사용자는 $M으로 빠른-포워드 하기를 원합니다.

이 경우 `git read-tree -m $H $M` 명령은 이 "병합" 결과로 인해 로컬 변경 사항이 손실되지 않도록 합니다. 다음은 "이어받기" 규칙입니다. 여기서 "I"는 인덱을 나타내고, "clean"은 인덱과 작업 트리가 일치함을 의미하며, "exists"/"nothing"은 지정된 커밋에서 경로의 존재 여부를 나타냅니다:

....
	I                   H        M        Result
       -------------------------------------------------------
     0  nothing             nothing  nothing  (발생하지 않음)
     1  nothing             nothing  exists   M 사용
     2  nothing             exists   nothing  인덱에서 경로 제거
     3  nothing             exists   exists,  "초기 체크아웃"인 경우 M 사용,
				     H == M   그렇지 않으면 인덱 유지
				     exists,  실패
				     H != M

        clean I==H  I==M
       ------------------
     4  yes   N/A   N/A     nothing  nothing  인덱 유지
     5  no    N/A   N/A     nothing  nothing  인덱 유지

     6  yes   N/A   yes     nothing  exists   인덱 유지
     7  no    N/A   yes     nothing  exists   인덱 유지
     8  yes   N/A   no      nothing  exists   실패
     9  no    N/A   no      nothing  exists   실패

     10 yes   yes   N/A     exists   nothing  인덱에서 경로 제거
     11 no    yes   N/A     exists   nothing  실패
     12 yes   no    N/A     exists   nothing  실패
     13 no    no    N/A     exists   nothing  실패

	clean (H==M)
       ------
     14 yes                 exists   exists   인덱 유지
     15 no                  exists   exists   인덱 유지

        clean I==H  I==M (H!=M)
       ------------------
     16 yes   no    no      exists   exists   실패
     17 no    no    no      exists   exists   실패
     18 yes   no    yes     exists   exists   인덱 유지
     19 no    no    yes     exists   exists   인덱 유지
     20 yes   yes   no      exists   exists   M 사용
     21 no    yes   no      exists   exists   실패
....

모든 "인덱 유지" 경우에서, 인덱 항목은 원래 인덱 파일 그대로 유지됩니다. 항목이 최신 상태가 아닌 경우, 'git read-tree'는 -u 플래그 하에서 작동 시 작업 트리의 복사본을 그대로 유지합니다.

이 형태의 'git read-tree'가 성공적으로 반환되면, `git diff-index --cached $M`을 실행하여 어떤 "로컬 변경 사항"이 이어받아졌는지 확인할 수 있습니다. 이는 `git diff-index --cached $H`가 2개 트리 병합 전에 생성했을 결과와 반드시 일치하지는 않습니다. 이는 18번 및 19번 경우 때문입니다. 즉, 이미 $M에 변경 사항이 있었다면 (예: 이메일 패치를 통해 얻었다면), `git diff-index --cached $H`는 이 병합 전에 변경 사항을 알려주었겠지만, 2개 트리 병합 후 `git diff-index --cached $M` 출력에는 나타나지 않습니다.

3번 경우는 약간 까다로우며 설명이 필요합니다. 이 규칙의 결과는 논리적으로 사용자가 경로 제거를 스테이징한 후 새 브랜치로 전환할 때 경로를 제거해야 합니다. 그러나 이는 초기 체크아웃을 방지하므로, 인덱 내용이 비어 있는 경우에만 M(새 트리)을 사용하도록 규칙이 수정됩니다. 그렇지 않으면 $H와 $M이 같을 동안 경로 제거가 유지됩니다.

3-Way Merge
~~~~~~~~~~~
각 "인덱" 항목에는 2비트의 "스테이지" 상태가 있습니다. 스테이지 0은 일반적인 것이고, 정상적인 사용에서는 볼 수 있는 유일한 것입니다.

하지만, 세 개의 트리를 사용하여 'git read-tree'를 수행하면 "스테이지"가 1부터 시작됩니다.

이는 다음과 같이 수행할 수 있음을 의미합니다:

----------------
$ git read-tree -m <tree1> <tree2> <tree3>
----------------

그러면 <tree1> 항목은 "stage1"에, <tree2> 항목은 "stage2"에, <tree3> 항목은 "stage3"에 있는 인덱이 생성됩니다. 현재 브랜치로 다른 브랜치를 병합할 때, 공통 조상 트리를 <tree1>으로, 현재 브랜치 헤드를 <tree2>로, 다른 브랜치 헤드를 <tree3>으로 사용합니다.

더 나아가, 'git read-tree'에는 특별한 규칙이 있습니다. 특정 상태에서 모든 측면에서 일치하는 파일을 보면, "stage0"으로 "축소"됩니다:

   - stage 2와 3이 같습니다. 하나를 취합니다 (어느 쪽이든 상관 없습니다. 우리 브랜치의 stage 2와 그들의 브랜치의 stage 3에서 동일한 작업이 이루어졌기 때문입니다).

   - stage 1과 stage 2가 같고 stage 3이 다른 경우. stage 3을 가져옵니다 (우리 브랜치인 stage 2는 stage 1의 조상 이후 아무런 작업을 하지 않았지만, 그들의 브랜치인 stage 3은 작업을 수행했습니다).

   - stage 1과 stage 3이 같고 stage 2가 다른 경우. stage 2를 가져옵니다 (우리는 작업을 했고 그들은 하지 않았습니다).

'git write-tree' 명령은 잘못된(nonsensical) 트리를 쓰는 것을 거부하며, stage 0이 아닌 단일 항목을 보면 병합되지 않은 항목에 대해 불평합니다.

이 모든 것이 완전히 말이 안 되는 규칙처럼 들릴 수 있지만, 빠른 병합을 수행하는 데 실제로 필요한 것입니다. 다양한 스테이지는 "결과 트리" (stage 0, 즉 "병합됨"), 원본 트리 (stage 1, 즉 "orig"), 그리고 병합하려는 두 트리 (각각 stage 2 및 3)를 나타냅니다.

3-way 병합을 이미 채워진 인덱 파일로 시작할 때 스테이지 1, 2, 3의 순서 (따라서 세 개의 <tree-ish> 커맨드라인 인자 순서)는 중요합니다. 다음은 알고리즘이 어떻게 작동하는지에 대한 개요입니다:

- 모든 세 트리에서 동일한 형식으로 파일이 존재하는 경우, 'git read-tree'에 의해 자동으로 "병합됨" 상태로 축소됩니다.

- 세 트리에서 *어떠한* 차이라도 있는 파일은 인덱에 별도의 항목으로 남습니다. 비-0 스테이지를 제거하고 병합된 버전을 삽입하는 방법을 결정하는 것은 "포세린 정책(porcelain policy)"에 달려 있습니다.

- 인덱 파일은 이 모든 정보를 저장하고 복원하므로, 점진적으로 병합할 수 있습니다. 하지만 스테이지 1/2/3 (즉, "병합되지 않은 항목")에 항목이 있는 한 결과를 쓸 수 없습니다. 따라서 병합 알고리즘은 매우 간단해집니다:

  * 인덱을 순서대로 순회하고 stage 0 항목은 모두 무시합니다. 이미 완료되었기 때문입니다.

  * "stage1"을 찾았지만 일치하는 "stage2" 또는 "stage3"이 없는 경우, 두 트리 모두에서 제거되었음을 알 수 있습니다 (원본 트리에서만 존재했음). 해당 항목을 제거합니다.

  * 일치하는 "stage2" 및 "stage3" 트리를 찾으면, 그 중 하나를 제거하고 다른 하나를 "stage0" 항목으로 전환합니다. 일치하는 "stage1" 항목이 있으면 함께 제거합니다. ... 모든 일반적인 단순 규칙 ...

이 마지막 단계를 수행하기 위해 일반적으로 'git merge-index'와 'git merge-one-file'을 함께 사용합니다. 스크립트는 각 경로를 병합하는 동안 작업 트리 파일을 업데이트하고, 성공적인 병합 후 완료합니다.

이미 채워진 인덱 파일로 3-way 병합을 시작할 때, 이는 작업 트리 파일의 상태를 나타내는 것으로 간주되며, 인덱 파일에 기록되지 않은 변경 사항이 있는 파일도 있을 수 있습니다. 더 나아가, 이 상태는 stage 2 트리에서 "파생된" 것으로 간주됩니다. 3-way 병합은 원본 인덱 파일에 stage 2와 일치하지 않는 항목이 발견되면 실행을 거부합니다.

이는 작업 중인 변경 사항을 잃는 것을 방지하고 관련 없는 병합 커밋에 무작위 변경 사항을 혼합하는 것을 방지하기 위해 이루어집니다. 예를 들어, 저장소에 마지막으로 커밋된 상태에서 시작한다고 가정해 봅시다:

----------------
$ JC=`git rev-parse --verify "HEAD^0"`
$ git checkout-index -f -u -a $JC
----------------

'git update-index'를 실행하지 않고 무작위 편집을 수행합니다. 그런 다음 "업스트림" 트리의 팁이 풀(pull)한 이후로 진행된 것을 발견합니다:

----------------
$ git fetch git://.... linus
$ LT=`git rev-parse FETCH_HEAD`
----------------

작업 트리는 여전히 HEAD ($JC)를 기반으로 하지만, 이후 일부 편집이 있습니다. 3-way 병합은 $JC 이후로 인덱 항목을 추가하거나 수정하지 않았는지 확인하고, 그렇지 않으면 올바르게 작동합니다. 따라서 다음 순서로:

----------------
$ git read-tree -m -u `git merge-base $JC $LT` $JC $LT
$ git merge-index git-merge-one-file -a
$ echo "Merge with Linus" | \
  git commit-tree `git write-tree` -p $JC -p $LT
----------------

커밋할 내용은 $JC와 $LT 간의 순수한 병합이며, 작업 중인 변경 사항은 포함되지 않고, 작업 트리는 병합 결과로 업데이트됩니다.

그러나 이 병합으로 덮어쓰여질 작업 트리 내의 로컬 변경 사항이 있다면, 'git read-tree'는 변경 사항이 손실되는 것을 방지하기 위해 실행을 거부합니다.

즉, 작업 트리에만 존재하는 것에 대해 걱정할 필요가 없습니다. 프로젝트의 병합에 관여하지 않는 부분에 로컬 변경 사항이 있을 경우, 변경 사항은 병합을 방해하지 않으며 그대로 유지됩니다. *방해하는* 경우, 병합은 시작조차 되지 않습니다 ('git read-tree'가 큰 소리로 불평하고 아무것도 수정하지 않고 실패합니다). 이 경우, 계속 하던 작업을 재개하고, 작업 트리가 준비되면 (즉, 작업 중인 작업을 완료했으면) 병합을 다시 시도할 수 있습니다.


SPARSE CHECKOUT
---------------

참고: linkgit:git-update-index[1] 및 `read-tree`의 skip-worktree 기능은
linkgit:git-sparse-checkout[1] 소개 이전에 만들어졌습니다.
skip-worktree 관련 요구 사항의 경우
`sparse-checkout` 명령을 사용하는 것이 좋습니다. 그러나 아래 정보는
`sparse-checkout` 명령의 cone 모드가 아닌 패턴 스타일을 이해하려는 사용자에게 유용할 수 있습니다.

"희소 체크아웃"을 사용하면 작업 디렉토리를 희소하게 채울 수 있습니다.
이는 skip-worktree 비트 (linkgit:git-update-index[1] 참조)를 사용하여
Git에게 작업 디렉토리의 파일이 살펴볼 가치가 있는지 여부를 알려줍니다.

'git read-tree' 및 기타 병합 기반 명령('git merge', 'git
checkout'...)은 skip-worktree 비트맵 및 작업 디렉토리 업데이트를 유지하는 데 도움이 될 수 있습니다. `$GIT_DIR/info/sparse-checkout`은
skip-worktree 참조 비트맵을 정의하는 데 사용됩니다. 'git read-tree'가
작업 디렉토리를 업데이트해야 하는 경우, .gitignore 파일과 동일한 구문을 사용하는
이 파일에 따라 인덱에서 skip-worktree 비트를 재설정합니다. 항목이 이 파일의 패턴과 일치하거나,
항목이 작업 트리에 있는 파일에 해당하는 경우, 해당 항목에 skip-worktree가 설정되지 않습니다. 그렇지 않으면 skip-worktree가 설정됩니다.

그런 다음 새로운 skip-worktree 값과 이전 값을 비교합니다.
skip-worktree가 설정됨에서 설정되지 않음으로 변경되면 해당 파일을 다시 추가합니다.
설정되지 않음에서 설정됨으로 변경되면 해당 파일이 제거됩니다.

`$GIT_DIR/info/sparse-checkout`은 일반적으로 파일을 지정하는 데 사용되지만,
반전 패턴을 사용하여 파일을 *제외*하도록 지정할 수도 있습니다. 예를 들어, `unwanted` 파일을 제거하려면:

----------------
/*
!unwanted
----------------

또 다른 까다로운 점은 더 이상 희소 체크아웃을 원하지 않을 때 작업 디렉토리를 완전히 다시 채우는 것입니다. "희소 체크아웃"을 비활성화할 수 없습니다. 왜냐하면 skip-worktree 비트가 여전히 인덱에 있고 작업 디렉토리는 여전히 희소하게 채워져 있기 때문입니다. `$GIT_DIR/info/sparse-checkout` 파일 내용을 사용하여 작업 디렉토리를 다시 채워야 합니다:

----------------
/*
----------------

그 후 희소 체크아웃을 비활성화할 수 있습니다. 'git
read-tree' 및 유사한 명령의 희소 체크아웃 지원은 기본적으로 비활성화되어 있습니다.
희소 체크아웃 지원을 받으려면 `core.sparseCheckout`을 활성화해야 합니다.


SEE ALSO
--------
linkgit:git-write-tree[1], linkgit:git-ls-files[1],
linkgit:gitignore[5], linkgit:git-sparse-checkout[1]

GIT
---
linkgit:git[1] 제품군의 일부