git-cherry-pick(1)
==================

NAME
----
git-cherry-pick - 변경 내용을 포함하는 기존 커밋 적용

SYNOPSIS
--------
[verse]
'git cherry-pick' [--edit] [-n] [-m <parent-number>] [-s] [-x] [--ff]
		  [-S[<keyid>]] <commit>...
'git cherry-pick' (--continue | --skip | --abort | --quit)

DESCRIPTION
-----------

기존 커밋 하나 이상을 지정하면, 각 커밋이 도입한 변경 내용을 적용하여 각각 새로운 커밋으로 기록합니다. 이를 위해서는 워킹 트리가 깨끗한 상태여야 합니다 (HEAD 커밋으로부터의 수정 사항이 없어야 함).

변경 내용을 적용하는 방법이 명확하지 않으면 다음과 같은 상황이 발생합니다:

1. 현재 브랜치와 `HEAD` 포인터는 마지막으로 성공적으로 생성된 커밋에 머무릅니다.
2. `CHERRY_PICK_HEAD` ref는 적용하기 어려운 변경 내용을 도입한 커밋을 가리키도록 설정됩니다.
3. 변경 내용이 깔끔하게 적용된 경로는 인덱스 파일과 워킹 트리 모두에서 업데이트됩니다.
4. 충돌이 발생하는 경로는 인덱스 파일이 "TRUE MERGE" 섹션에 설명된 대로 최대 세 가지 버전을 기록합니다.
   linkgit:git-merge[1]. 워킹 트리 파일에는 일반적인 충돌 마커 `<<<<<<<`와 `>>>>>>>`로 둘러싸인 충돌에 대한 설명이 포함됩니다.
5. 다른 수정 사항은 없습니다.

이러한 충돌을 해결하는 방법에 대한 팁은 linkgit:git-merge[1]을 참조하십시오.

OPTIONS
-------
<commit>...::
	cherry-pick할 커밋.
	커밋을 지정하는 더 완전한 목록은 linkgit:gitrevisions[7]을 참조하십시오.
	커밋 집합을 전달할 수 있지만 기본적으로 탐색은 수행되지 않으며 `--no-walk` 옵션이 지정된 것처럼 동작합니다. linkgit:git-rev-list[1]을 참조하십시오. 범위 지정은 모든 <commit>... 인수에 단일 revision walk를 전달한다는 점에 유의하십시오 (나중에 'maint master..next'를 사용하는 예시 참조).

-e::
--edit::
	이 옵션을 사용하면 'git cherry-pick'은 커밋하기 전에 커밋 메시지를 편집할 수 있게 해줍니다.

--cleanup=<mode>::
	이 옵션은 커밋 메시지가 커밋 메커니즘에 전달되기 전에 어떻게 정리될지 결정합니다. 자세한 내용은 linkgit:git-commit[1]을 참조하십시오. 특히 '<mode>'에 `scissors` 값이 지정되면, 충돌이 발생할 경우 `MERGE_MSG`에 `scissors`가 추가된 후 전달됩니다.

-x::
	커밋을 기록할 때, 원래 커밋 메시지에 "(cherry picked from commit ...)"이라는 줄을 추가하여 이 변경이 어떤 커밋에서 cherry-pick되었는지 표시합니다. 이는 충돌이 없는 cherry pick에 대해서만 수행됩니다. 개인 브랜치에서 cherry-pick하는 경우에는 이 옵션을 사용하지 마십시오. 해당 정보는 수신자에게 쓸모없기 때문입니다. 반면에 공개적으로 보이는 두 브랜치 (예: 오래된 릴리스의 유지 관리 브랜치로의 수정 사항 백포트) 사이에서 cherry-pick하는 경우, 이 정보를 추가하면 유용할 수 있습니다.

-r::
	이전에는 이 명령이 기본적으로 `-x`를 수행했으며 `-r`은 이를 비활성화했습니다. 이제 기본값은 `-x`를 수행하지 않으므로 이 옵션은 아무런 기능도 하지 않습니다.

-m <parent-number>::
--mainline <parent-number>::
	일반적으로 머지 커밋은 어느 쪽이 주 계열인지 알 수 없기 때문에 cherry-pick할 수 없습니다. 이 옵션은 주 계열의 부모 번호 (1부터 시작)를 지정하고 cherry-pick이 지정된 부모에 대해 변경 내용을 다시 적용할 수 있도록 합니다.

-n::
--no-commit::
	일반적으로 이 명령은 자동으로 일련의 커밋을 생성합니다.
	이 플래그는 명명된 각 커밋을 cherry-pick하는 데 필요한 변경 내용을 커밋 없이 워킹 트리와 인덱스에 적용합니다. 또한 이 옵션을 사용하면 인덱스가 HEAD 커밋과 일치할 필요가 없습니다. cherry-pick은 인덱스의 시작 상태를 기준으로 수행됩니다.
+
이는 한 번에 여러 커밋의 효과를 인덱스에 cherry-pick할 때 유용합니다.

-s::
--signoff::
	커밋 메시지 끝에 `Signed-off-by` 트레일러를 추가합니다.
	자세한 내용은 linkgit:git-commit[1]의 signoff 옵션을 참조하십시오.

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	GPG로 커밋에 서명합니다. `keyid` 인수는 선택 사항이며 기본값은 커미터 ID입니다. 지정된 경우 공백 없이 옵션에 붙여야 합니다. `--no-gpg-sign`은 `commit.gpgSign` 구성 변수와 이전 `--gpg-sign` 모두를 무효화하는 데 유용합니다.

--ff::
	현재 HEAD가 cherry-pick된 커밋의 부모와 같은 경우, 이 커밋으로 fast forward를 수행합니다.

--allow-empty::
	기본적으로 빈 커밋을 cherry-pick하면 오류가 발생하며 `git commit --allow-empty`의 명시적인 호출이 필요함을 나타냅니다. 이 옵션은 해당 동작을 재정의하여 빈 커밋이 cherry-pick에서 자동으로 보존되도록 합니다. "--ff"가 적용되는 경우, "fast-forward" 요구 사항을 충족하는 빈 커밋은 이 옵션 없이도 유지된다는 점에 유의하십시오. 또한 이 옵션의 사용은 원래 빈 상태였던 커밋만 유지합니다 (즉, 커밋이 부모와 동일한 트리를 기록한 경우). 이전 커밋으로 인해 빈 상태가 된 커밋은 cherry-pick을 실패하게 만듭니다. 해당 커밋의 포함을 강제하려면 `--empty=keep`을 사용하십시오.

--allow-empty-message::
	기본적으로 빈 메시지가 있는 커밋을 cherry-pick하면 실패합니다.
	이 옵션은 해당 동작을 재정의하여 빈 메시지가 있는 커밋을 cherry-pick할 수 있게 합니다.

--empty=(drop|keep|stop)::
	현재 히스토리에 이미 있는 변경과 중복되는 커밋을 cherry-pick할 때 처리하는 방법.
+
--
`drop`;;
	해당 커밋은 삭제됩니다.
`keep`;;
	해당 커밋은 유지됩니다. `--allow-empty`를 의미합니다.
`stop`;;
	커밋이 적용될 때 cherry-pick이 중지되어 커밋을 검사할 수 있습니다. 이것이 기본 동작입니다.
--
+
`--empty=drop` 및 `--empty=stop`은 원래 빈 상태가 아니라 이전 커밋으로 인해 빈 상태가 된 커밋만 처리하는 방법을 지정한다는 점에 유의하십시오. 원래 빈 상태였던 커밋은 `--empty=keep` 또는 `--allow-empty`가 지정되지 않으면 cherry-pick을 계속 실패하게 합니다.
+

--keep-redundant-commits::
	`--empty=keep`에 대한 지원 중단된 동의어.

--strategy=<strategy>::
	지정된 머지 전략을 사용합니다. 한 번만 사용해야 합니다.
	자세한 내용은 linkgit:git-merge[1]의 MERGE STRATEGIES 섹션을 참조하십시오.

-X<option>::
--strategy-option=<option>::
	머지 전략별 옵션을 머지 전략에 전달합니다. 자세한 내용은 linkgit:git-merge[1]을 참조하십시오.

include::rerere-options.adoc[]

SEQUENCER SUBCOMMANDS
---------------------
include::sequencer.adoc[]

EXAMPLES
--------
`git cherry-pick master`::

	master 브랜치의 최상단 커밋이 도입한 변경 내용을 적용하고 이 변경 사항으로 새로운 커밋을 생성합니다.

`git cherry-pick ..master`::
`git cherry-pick ^HEAD master`::

	master의 조상이지만 HEAD의 조상은 아닌 모든 커밋이 도입한 변경 내용을 적용하여 새로운 커밋을 생성합니다.

`git cherry-pick maint next ^master`::
`git cherry-pick maint master..next`::

	maint 또는 next의 조상이지만 master 또는 그 조상은 아닌 모든 커밋이 도입한 변경 내용을 적용합니다. 마지막 부분은 `maint`와 `master`와 `next` 사이의 모든 것을 의미하는 것이 아닙니다. 특히 `maint`가 `master`에 포함된 경우 사용되지 않습니다.

`git cherry-pick master~4 master~2`::

	master가 가리키는 다섯 번째와 세 번째 마지막 커밋이 도입한 변경 내용을 적용하고 이 변경 사항으로 2개의 새 커밋을 생성합니다.

`git cherry-pick -n master~1 next`::

	master가 가리키는 두 번째 마지막 커밋과 next가 가리키는 마지막 커밋이 도입한 변경 내용을 워킹 트리와 인덱스에 적용하지만, 이러한 변경 사항으로 어떠한 커밋도 생성하지 않습니다.

`git cherry-pick --ff ..next`::

	히스토리가 선형이고 HEAD가 next의 조상인 경우, 워킹 트리를 업데이트하고 HEAD 포인터를 next와 일치하도록 진행합니다.
	그렇지 않은 경우, next에 있지만 HEAD에는 없는 커밋들이 도입한 변경 내용을 현재 브랜치에 적용하고 각 새로운 변경에 대한 새 커밋을 생성합니다.

`git rev-list --reverse master -- README | git cherry-pick -n --stdin`::

	master 브랜치에서 README를 수정한 모든 커밋이 도입한 변경 내용을 워킹 트리와 인덱스에 적용하여 결과를 검사하고 적합한 경우 단일 새 커밋으로 만들 수 있습니다.

다음 시퀀스는 패치의 백포트를 시도하지만, 패치가 적용되는 코드가 너무 많이 변경되었기 때문에 중단되으며, 다시 시도하지만 이번에는 컨텍스트 라인을 더 주의 깊게 일치시키는 방법을 사용합니다.

------------
$ git cherry-pick topic^             <1>
$ git diff                           <2>
$ git cherry-pick --abort            <3>
$ git cherry-pick -Xpatience topic^  <4>
------------
<1> `git show topic^`에 의해 표시될 변경 내용을 적용합니다.
    이 예시에서는 패치가 깔끔하게 적용되지 않아, 충돌에 대한 정보가 인덱스와
    워킹 트리에 기록되며 새로운 커밋은 생성되지 않습니다.
<2> 조정할 변경 사항 요약
<3> cherry-pick을 취소합니다. 즉, cherry-pick 이전 상태로 돌아가며 워킹 트리 내의 로컬 수정을 유지합니다.
<4> `topic^`이 도입한 변경 내용을 다시 적용하려고 시도합니다.
    잘못 일치하는 컨텍스트 라인에 기반한 실수를 피하기 위해 추가 시간을 할애합니다.

SEE ALSO
--------
linkgit:git-revert[1]

GIT
---
linkgit:git[1] 제품군의 일부