git-format-patch(1)
===================

NAME
----
git-format-patch - 이메일 제출을 위한 패치 준비


SYNOPSIS
--------
[verse]
'git format-patch' [-k] [(-o|--output-directory) <dir> | --stdout]
		   [--no-thread | --thread[=<style>]]
		   [(--attach|--inline)[=<boundary>] | --no-attach]
		   [-s | --signoff]
		   [--signature=<signature> | --no-signature]
		   [--signature-file=<file>]
		   [-n | --numbered | -N | --no-numbered]
		   [--start-number <n>] [--numbered-files]
		   [--in-reply-to=<message-id>] [--suffix=.<sfx>]
		   [--ignore-if-in-upstream] [--always]
		   [--cover-from-description=<mode>]
		   [--rfc[=<rfc>]] [--subject-prefix=<subject-prefix>]
		   [(--reroll-count|-v) <n>]
		   [--to=<email>] [--cc=<email>]
		   [--[no-]cover-letter] [--quiet]
		   [--commit-list-format=<format-spec>]
		   [--[no-]encode-email-headers]
		   [--no-notes | --notes[=<ref>]]
		   [--interdiff=<previous>]
		   [--range-diff=<previous> [--creation-factor=<percent>]]
		   [--filename-max-length=<n>]
		   [--progress]
		   [<common-diff-options>]
		   [ <since> | <revision-range> ]

DESCRIPTION
-----------

각 비-머지 커밋을 "패치" 형태로, 각 커밋 당 하나의 "메시지"로 준비하며, 유닉스 메일박스 형태를 닮도록 포맷팅됩니다.
이 명령어의 출력은 이메일 제출이나 'git am' 사용에 편리합니다.

이 명령어에서 생성된 "메시지"는 세 가지 부분으로 구성됩니다:

* `From <commit>`으로 시작하는 짧은 메타데이터 헤더와
  "file(1)"과 같은 프로그램들이 파일이 이 명령어의 출력임을 인식하도록 돕는 고정된 `Mon Sep 17 00:00:00 2001` 타임스탬프, 작성자 식별 정보, 작성 날짜, 그리고 변경 사항의 제목(커밋 로그 메시지의 첫 번째 문단에서 가져옴)을 기록하는 필드.

* 커밋 로그 메시지의 두 번째 및 이후 문단.

* "패치", 즉 커밋과 그 부모 간의 "diff -p --stat" 출력 (linkgit:git-diff[1] 참조).

로그 메시지와 패치는 세 개의 대시(-)로 이루어진 줄로 분리됩니다.

어떤 커밋을 다룰지 지정하는 두 가지 방법이 있습니다.

1. 단일 커밋 `<since>`는 현재 브랜치의 팁으로 이어지는 커밋 중 `<since>`로 이어지는 히스토리에 없는 커밋들을 출력하라고 지정합니다.

2. 일반적인 `<revision-range>` 표현식 (linkgit:gitrevisions[7]의 "SPECIFYING REVISIONS" 섹션 참조)은 지정된 범위 내의 커밋들을 의미합니다.

첫 번째 규칙이 단일 `<commit>`의 경우 우선 순위를 가집니다. 두 번째 규칙, 즉 히스토리 시작부터 `<commit>`까지 모든 것을 포맷하려면 `--root` 옵션을 사용하십시오: `git format-patch --root <commit>`. `<commit>` 자체만 포맷하려면 `git format-patch -1 <commit>`으로 할 수 있습니다.

기본적으로 각 출력 파일에는 1부터 순차적으로 번호가 매겨지며, 커밋 메시지의 첫 번째 줄(경로명 안전성을 위해 조정됨)이 파일 이름으로 사용됩니다. `--numbered-files` 옵션을 사용하면 출력 파일 이름은 단순한 숫자 시퀀스만 포함하고 커밋의 첫 번째 줄은 appended되지 않습니다.
출력 파일의 이름은 `--stdout` 옵션이 지정되지 않는 한 표준 출력으로 인쇄됩니다.

`-o`가 지정되면, 출력 파일들은 `<dir>`에 생성됩니다. 그렇지 않으면 현재 작업 디렉토리에 생성됩니다. 기본 경로는 `format.outputDirectory` 설정 옵션으로 설정할 수 있습니다. `-o` 옵션은 `format.outputDirectory`보다 우선 순위를 가집니다. `format.outputDirectory`가 다른 곳을 가리키고 있을 때에도 패치를 현재 작업 디렉토리에 저장하려면 `-o .`을 사용하십시오. 모든 디렉토리 구성 요소가 생성됩니다.

기본적으로 단일 패치의 제목은 "[PATCH] " 뒤에 커밋 메시지의 첫 번째 빈 줄까지의 텍스트가 합쳐진 것입니다 (linkgit:git-commit[1]의 DISCUSSION 섹션 참조).

여러 패치가 출력될 때, 제목 접두사는 대신 "[PATCH n/m] "이 됩니다. 단일 패치에 1/1을 추가하도록 강제하려면 `-n`을 사용하십시오. 패치 번호를 제목에서 생략하려면 `-N`을 사용하십시오.

`--thread`가 주어지면, `git-format-patch`는 `In-Reply-To` 및 `References` 헤더를 생성하여 두 번째 및 이후 패치 메일이 첫 번째 메일에 대한 답장처럼 보이게 합니다. 또한 참조를 위한 `Message-ID` 헤더도 생성합니다.

OPTIONS
-------
:git-format-patch: 1
include::diff-options.adoc[]

-<n>::
	가장 위에 있는 <n>개의 커밋으로 패치를 준비합니다.

-o <dir>::
--output-directory <dir>::
	결과 파일을 현재 작업 디렉토리 대신 <dir>에 저장합니다.

-n::
--numbered::
	패치가 하나뿐일 때도 '[PATCH n/m]' 형식으로 출력을 명명합니다.

-N::
--no-numbered::
	'[PATCH]' 형식으로 출력을 명명합니다.

--start-number <n>::
	패치 번호를 1 대신 <n>부터 시작합니다.

--numbered-files::
	출력 파일 이름은 커밋의 첫 번째 줄이 appended되지 않은 단순한 숫자 시퀀스가 됩니다.

-k::
--keep-subject::
	커밋 로그 메시지의 첫 번째 줄에서 '[PATCH]'를 제거하거나 추가하지 않습니다.

-s::
--signoff::
	자신의 커밋터 신원을 사용하여 커밋 메시지에 `Signed-off-by` 트레일러를 추가합니다.
	더 자세한 정보는 linkgit:git-commit[1]의 signoff 옵션을 참조하십시오.

--stdout::
	각 파일을 생성하는 대신, 모든 커밋을 mbox 형식으로 표준 출력에 인쇄합니다.

--attach[=<boundary>]::
	multipart/mixed 첨부 파일을 생성하며, 첫 번째 파트는 커밋 메시지이고 두 번째 파트는 패치 자체이며, `Content-Disposition: attachment` 헤더를 갖습니다.

--no-attach::
	설정 구성을 재구현하여 첨부 파일 생성을 비활성화합니다.

--inline[=<boundary>]::
	multipart/mixed 첨부 파일을 생성하며, 첫 번째 파트는 커밋 메시지이고 두 번째 파트는 패치 자체이며, `Content-Disposition: inline` 헤더를 갖습니다.

--thread[=<style>]::
--no-thread::
	두 번째 및 이후 메일이 첫 번째 메일에 대한 답장처럼 보이게 하기 위해 `In-Reply-To` 및 `References` 헤더 추가를 제어합니다.
	또한 참조를 위한 `Message-ID` 헤더 생성을 제어합니다.
+
선택적인 <style> 인수는 `shallow` 또는 `deep` 중 하나가 될 수 있습니다.
'shallow' 스레딩은 모든 메일을 시리즈의 헤드에 대한 답장으로 만듭니다. 여기서 헤드는 커버 레터, `--in-reply-to`, 첫 번째 패치 메일에서 순서대로 선택됩니다. 'deep' 스레딩은 모든 메일을 이전 메일에 대한 답장으로 만듭니다.
+
기본값은 `format.thread` 설정이 되어 있지 않은 경우 `--no-thread`입니다.
인수 없이 `--thread`를 사용하는 것은 `--thread=shallow`와 동일합니다.
+
'git send-email'의 기본값은 이메일을 자체적으로 스레딩한다는 점에 유의하십시오. `git format-patch`가 스레딩을 처리하도록 하려면 `git send-email`에 대해 스레딩이 비활성화되어 있는지 확인해야 합니다.

--in-reply-to=<message-id>::
	첫 번째 메일(또는 `--no-thread`와 함께 모든 메일)이 주어진 <message-id>에 대한 답장으로 보이게 하여, 새로운 패치 시리즈를 제공하기 위해 스레드를 끊는 것을 방지합니다.

--ignore-if-in-upstream::
	<until>..<since>에 있는 커밋과 일치하는 패치는 포함하지 않습니다. 이는 <since>에서 도달 가능하지만 <until>에서는 도달 가능하지 않은 모든 패치를 검사하고 생성 중인 패치와 비교하며, 일치하는 모든 패치는 무시됩니다.

--always::
	기본적으로 생략되는 변경이 없는 커밋에 대한 패치도 포함합니다.

--cover-from-description=<mode>::
	커버 레터의 어떤 부분이 브랜치 설명을 사용하여 자동으로 채워질지 제어합니다.
+
`<mode>`가 `message` 또는 `default`이면, 커버 레터 제목은 플레이스홀더 텍스트로 채워집니다. 커버 레터 본문은 브랜치 설명으로 채워집니다. 설정 구성이나 명령줄 옵션이 지정되지 않은 경우 기본 모드입니다.
+
`<mode>`가 `subject`이면, 브랜치 설명의 첫 번째 문단이 커버 레터 제목을 채웁니다. 설명의 나머지 부분이 커버 레터 본문을 채웁니다.
+
`<mode>`가 `auto`이면, 브랜치 설명의 첫 번째 문단이 100바이트보다 길면 모드는 `message`가 되고, 그렇지 않으면 `subject`가 사용됩니다.
+
`<mode>`가 `none`이면, 커버 레터 제목과 본문 모두 플레이스홀더 텍스트로 채워집니다.

--description-file=<file>::
	커버 레터를 생성하기 위해 브랜치 설명 대신 <file>의 내용을 사용합니다.

--subject-prefix=<subject-prefix>::
	제목 줄의 표준 '[PATCH]' 대신 '[<subject-prefix>]'를 사용합니다. 이는 패치 시리즈를 명명하는 데 사용될 수 있으며 `--numbered` 옵션과 결합될 수 있습니다.
+
`format.subjectPrefix` 설정 변수는 또한 주어진 저장소에 대해 모든 패치에 적용될 제목 접두사를 설정하는 데 사용될 수 있습니다. 이는 종종 여러 저장소에 대한 패치를 받는 메일링 리스트에서 패치를 구별하는 데 유용합니다 (예: "PATCH my-project" 값).

--filename-max-length=<n>::
	기본 64바이트 대신, 생성된 출력 파일 이름을 약 '<n>' 바이트로 잘라냅니다 (너무 짧은 값은 합리적인 길이로 자동 증가됩니다). `format.filenameMaxLength` 설정 변수의 값 또는 설정되지 않은 경우 64의 기본값을 사용합니다.

--rfc[=<rfc>]::
	제목 접두사에 _<rfc>_ 문자열(기본값 "RFC")을 붙입니다. 제목 접두사의 기본값이 "PATCH"이므로 기본적으로 "RFC PATCH"가 됩니다.
+
RFC는 "Request For Comments"를 의미합니다. 이를 적용하기보다는 논의를 위해 실험적인 패치를 보낼 때 사용합니다. "--rfc=WIP"는 패치가 아직 완료되지 않았음을 나타내는 데 유용할 수 있습니다 ("WIP"는 "Work In Progress"의 약자).
+
수신 커뮤니티의 특정 추가 문자열에 대한 관례가 제목 접두사 뒤에 오는 경우, _<rfc>_ 문자열은 대시("-")로 접두사를 붙여 _<rfc>_ 문자열의 나머지가 제목 접두사 뒤에 추가되도록 신호할 수 있습니다. 예를 들어, `--rfc='-(WIP)'`는 "PATCH (WIP)"를 생성합니다.

-v <n>::
--reroll-count=<n>::
	시리즈를 주제의 <n>번째 반복으로 표시합니다. 출력 파일 이름에는 `v<n>`이 앞에 붙고, 제목 접두사("PATCH" 기본값, ` --subject-prefix` 옵션으로 설정 가능)에는 ` v<n>`이 뒤에 붙습니다. 예를 들어, `--reroll-count=4`는 `Subject: [PATCH v4 1/20] Add makefile`을 포함하는 `v4-0001-add-makefile.patch` 파일을 생성할 수 있습니다.
	`<n>`은 정수일 필요는 없습니다 (예: "--reroll-count=4.4" 또는 "--reroll-count=4rev2" 사용 가능). 하지만 이러한 reroll-count를 사용하는 단점은 이전 버전과의 range-diff/interdiff가 새 반복이 어느 버전과 비교되는지 정확히 명시하지 않는다는 것입니다.

--to=<email>::
	이메일 헤더에 `To:` 헤더를 추가합니다. 이는 설정된 헤더에 추가되며 여러 번 사용될 수 있습니다.
	부정 형태인 `--no-to`는 지금까지 추가된 모든 `To:` 헤더(설정 또는 명령줄에서)를 삭제합니다.

--cc=<email>::
	이메일 헤더에 `Cc:` 헤더를 추가합니다. 이는 설정된 헤더에 추가되며 여러 번 사용될 수 있습니다.
	부정 형태인 `--no-cc`는 지금까지 추가된 모든 `Cc:` 헤더(설정 또는 명령줄에서)를 삭제합니다.

--from::
--from=<ident>::
	각 이메일의 `From:` 헤더에 `ident`를 사용합니다. 커밋 이메일의 경우, 커밋의 작성자 ident가 제공된 `ident`와 텍스트로 동일하지 않으면, 원본 작성자를 원본으로 하는 `From:` 헤더를 메시지 본문에 배치합니다. `ident`가 주어지지 않거나 옵션이 전혀 전달되지 않으면, 현재 커밋터의 ident를 사용합니다.
+
이 옵션은 실제로 이메일을 보내고 자신을 발신자로 식별하면서 원본 작성자를 유지하려는 경우에만 유용합니다 (그리고 `git am`은 본문 헤더를 올바르게 인식할 것입니다). 또한 `git send-email`은 이미 이 변환을 처리하므로, 결과를 `git send-email`에 공급하는 경우 이 옵션을 사용해서는 안 됩니다.

--force-in-body-from::
--no-force-in-body-from::
	`--from` 옵션을 통해 지정된 이메일 발신자의 경우, 기본적으로 발신자와 작성자가 다른 경우 커밋 로그 메시지 맨 위에 실제 커밋 작성자를 식별하기 위한 본문 내 "From:"이 추가됩니다. 이 옵션을 사용하면, 발신자와 작성자가 동일한 이름과 주소를 가지고 있더라도 본문 내 "From:"이 추가됩니다. 이는 메일링 리스트 소프트웨어가 발신자 신원을 오염시키는 경우 도움이 될 수 있습니다.
	`format.forceInBodyFrom` 설정 변수의 값으로 기본 설정됩니다.

--add-header=<header>::
	임의의 헤더를 이메일 헤더에 추가합니다. 이는 설정된 헤더에 추가되며 여러 번 사용될 수 있습니다.
	예: `--add-header="Organization: git-foo"`.
	부정 형태인 `--no-add-header`는 지금까지 설정 또는 명령줄에서 추가된 *모든* (`To:`, `Cc:`, 및 사용자 정의) 헤더를 삭제합니다.

--cover-letter::
--no-cover-letter::
	패치 외에, 브랜치 설명, 커밋 목록 및 전체 diffstat을 포함하는 커버 레터 파일을 생성합니다.
	이를 보내기 전에 파일에서 설명을 채울 수 있습니다.

--commit-list-format=<format-spec>::
	패치 시리즈의 커밋 목록을 생성하는 형식을 지정합니다. format-spec에 허용되는 값은 `shortlog`, `modern` 또는 `log:`로 접두사가 붙은 형식 문자열입니다. 예: `log: %s (%an)`.
	`modern`은 `log:%w(72)[%(count)/%(total)] %s`와 같습니다.
	형식 문자열에 `%`가 포함되어 있으면 (`%<placeholder>`의 일부로 예상됨) `log:` 접두사를 생략할 수 있습니다.
	`format.commitListFormat` 설정 변수가 설정되어 있는 경우의 기본값이며, 그렇지 않으면 `shortlog`입니다.
	명령줄에서 이 옵션이 주어지면 `--no-cover-letter`가 주어지지 않는 한 `--cover-letter`가 사용됨을 의미합니다.

--encode-email-headers::
--no-encode-email-headers::
	ASCII가 아닌 문자가 있는 이메일 헤더를 "Q-encoding" (RFC 2047에 설명됨)으로 인코딩합니다. 헤더를 그대로 출력하는 대신.
	`format.encodeEmailHeaders` 설정 변수의 값으로 기본 설정됩니다.

--interdiff=<previous>::
	리뷰어 지원으로, 커버 레터 또는 1-패치 시리즈의 유일한 패치 주석에 이전 버전의 패치 시리즈와 현재 포맷팅 중인 시리즈 간의 차이를 보여주는 interdiff를 삽입합니다. `previous`는 현재 포맷팅 중인 시리즈와 공통 기반을 공유하는 이전 시리즈의 팁을 명명하는 단일 리비전입니다 (예: `git format-patch --cover-letter --interdiff=feature/v1 -3 feature/v2`).

--range-diff=<previous>::
	리뷰어 지원으로, 커버 레터 또는 1-패치 시리즈의 유일한 패치 주석에 이전 버전의 패치 시리즈와 현재 포맷팅 중인 시리즈 간의 차이를 보여주는 range-diff (linkgit:git-range-diff[1] 참조)를 삽입합니다.
	`previous`는 현재 포맷팅 중인 시리즈와 공통 기반을 공유하는 이전 시리즈의 팁을 명명하는 단일 리비전이 될 수 있습니다 (예: `git format-patch --cover-letter --range-diff=feature/v1 -3 feature/v2`), 또는 두 버전의 시리즈가 분리된 경우 리비전 범위가 될 수 있습니다 (예: `git format-patch --cover-letter --range-diff=feature/v1~3..feature/v1 -3 feature/v2`).
+
명령에 전달된 diff 옵션은 `format-patch`의 기본 제품이 생성되는 방식을 제어하며, 커버 레터 자료 생성에 사용되는 내부 `range-diff` 도구에는 전달되지 않습니다 (향후 변경될 수 있습니다).

--creation-factor=<percent>::
	`--range-diff`와 함께 사용되며, 이전 시리즈와 현재 시리즈의 커밋들을 매칭하는 휴리스틱을 생성/삭제 비용 덤프 팩터를 조정하여 조정합니다. 자세한 내용은 linkgit:git-range-diff[1]를 참조하십시오.
+
기본값은 999입니다 (linkgit:git-range-diff[1]는 60을 사용). 사용 사례는 동일한 주제의 이전 반복과의 비교를 보여주는 것이며, 도구는 두 패치 세트 간에 더 많은 상호 연결성을 찾아야 합니다.

--notes[=<ref>]::
--no-notes::
	커밋에 대한 notes (linkgit:git-notes[1] 참조)를 세 개의 대시 다음 줄에 추가합니다.
+
이것의 예상 사용 사례는 커밋 로그 메시지 자체에 속하지 않는 커밋에 대한 지원 설명을 작성하고 이를 패치 제출과 함께 포함하는 것입니다. `format-patch`가 실행된 후 보내기 전에 이러한 설명을 작성할 수 있지만, Git notes로 유지하면 패치 시리즈의 버전 간에 유지할 수 있습니다 (하지만 linkgit:git-notes[1]의 `notes.rewrite` 설정 옵션에 대한 토론을 참조하여 이 워크플로를 사용하십시오).
+
기본값은 `format.notes` 설정이 되어 있지 않은 경우 `--no-notes`입니다.

--signature=<signature>::
--no-signature::
	생성된 각 메시지에 서명을 추가합니다. RFC 3676에 따라 서명은 '-- '이 있는 줄로 본문에서 분리됩니다. 서명 옵션이 생략되면 서명은 기본적으로 Git 버전 번호가 됩니다.

--signature-file=<file>::
	--signature와 동일하게 작동하지만 서명은 파일에서 읽어옵니다.

--suffix=.<sfx>::
	생성된 파일 이름의 접미사로 `.patch` 대신 지정된 접미사를 사용합니다. 일반적인 대안은 `--suffix=.txt`입니다. 이걸 비워두면 `.patch` 접미사가 제거됩니다.
+
선행 문자가 꼭 점일 필요는 없습니다. 예를 들어, `--suffix=-patch`를 사용하여 `0001-description-of-my-change-patch`를 얻을 수 있습니다.

-q::
--quiet::
	생성된 파일 이름을 표준 출력으로 출력하지 않습니다.

--no-binary::
	이진 파일의 변경 내용을 출력하지 않고, 파일이 변경되었다는 알림만 표시합니다. 이 옵션을 사용하여 생성된 패치는 제대로 적용할 수 없지만, 코드 검토에는 여전히 유용합니다.

--zero-commit::
  각 패치의 From 헤더에 커밋의 해시 대신 모든 0으로 된 해시를 출력합니다.

--no-base::
--base[=<commit>]::
	패치 시리즈가 적용되는 상태를 식별하기 위해 기본 트리 정보(base tree information)를 기록합니다. 자세한 내용은 아래 BASE TREE INFORMATION 섹션을 참조하십시오. <commit>이 "auto"인 경우, 기본 커밋이 자동으로 선택됩니다. `--no-base` 옵션은 `format.useAutoBase` 설정을 재구현합니다.

--root::
	단일 커밋이라도 리비전 인수를 <revision-range>로 처리합니다 (일반적으로 <since>로 처리됨). 지정된 범위에 포함된 root 커밋은 이 플래그와 관계없이 항상 생성 패치로 포맷됩니다.

--progress::
	패치가 생성될 때 진행 상황 보고를 stderr에 표시합니다.

CONFIGURATION
-------------
각 메시지에 추가될 추가 메일 헤더 라인, 제목 접두사 및 파일 접미사의 기본값, 여러 개 이상의 패치를 출력할 때 번호 매기기, "To:" 또는 "Cc:" 헤더 추가, 첨부 파일 구성, 패치 서명 정보를 설정 변수로 지정할 수 있습니다.

------------
[format]
	headers = "Organization: git-foo\n"
	subjectPrefix = CHANGE
	suffix = .txt
	numbered = auto
	to = <email>
	cc = <email>
	attach [ = mime-boundary-string ]
	signOff = true
	outputDirectory = <directory>
	coverLetter = auto
	commitListFormat = shortlog
	coverFromDescription = auto
------------


DISCUSSION
----------

'git format-patch'에서 생성된 패치는 UNIX 메일박스 형식이며, 다음과 같이 실제 메일박스가 아닌 format-patch의 출력을 나타내는 고정된 "매직" 타임스탬프를 갖습니다:

------------
From 8f72bad1baf19a53459661343e21d6491c3908d3 Mon Sep 17 00:00:00 2001
From: Tony Luck <tony.luck@intel.com>
Date: Tue, 13 Jul 2010 11:42:54 -0700
Subject: [PATCH] =?UTF-8?q?[IA64]=20Put=20ia64=20config=20files=20on=20the=20?=
 =?UTF-8?q?Uwe=20Kleine-K=C3=B6nig=20diet?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

arch/arm config files were slimmed down using a python script
(See commit c2330e286f68f1c408b4aa6515ba49d57f05beae comment)

Do the same for ia64 so we can have sleek & trim looking
...
------------

일반적으로 MUA의 초안 폴더에 저장되어, 세 개의 대시 뒤에 기록될 수 있는 시기적절한 설명을 추가하도록 편집된 후 메시지로 전송됩니다. 저희 예시에서는 본문이 "arch/arm config files were..."으로 시작합니다. 수신 측에서는 독자가 흥미로운 패치를 UNIX 메일박스에 저장하고 linkgit:git-am[1]으로 적용할 수 있습니다.

패치가 진행 중인 토론의 일부일 때, 'git format-patch'에서 생성된 패치는 'git am --scissors' 기능을 활용하도록 조정될 수 있습니다. 토론에 대한 여러분의 응답 다음에 "-- >8 --" (가위와 천공)으로만 이루어진 줄이 오고, 그 뒤에는 불필요한 헤더 필드가 제거된 패치가 옵니다:

------------
...
> So we should do such-and-such.

Makes sense to me.  How about this patch?

-- >8 --
Subject: [IA64] Put ia64 config files on the Uwe Kleine-König diet

arch/arm config files were slimmed down using a python script
...
------------

이런 식으로 패치를 보낼 때, 대부분 자신의 패치를 보내는 것이므로 "`From $SHA1 $magic_timestamp`" 마커 외에도 패치 파일에서 `From:` 및 `Date:` 줄을 생략해야 합니다. 패치 제목은 패치가 응답 중인 토론의 제목과 다를 가능성이 높으므로, 예시처럼 Subject: 줄을 유지하는 것이 좋습니다.

패치 손상 확인
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
많은 메일러가 제대로 설정되지 않으면 공백 문자를 손상시킵니다. 다음은 두 가지 일반적인 손상 유형입니다:

* _어떠한_ 공백도 없는 빈 컨텍스트 줄.

* 앞에 공백 하나가 추가된 비어 있지 않은 컨텍스트 줄.

MUA가 제대로 설정되었는지 테스트하는 한 가지 방법은 다음과 같습니다:

* 패치를 자신에게 보내되, To: 및 Cc: 줄에 리스트와 관리자 주소가 포함되지 않도록 하는 점을 제외하고는 평소와 같이 보냅니다.

* 그 패치를 UNIX 메일박스 형식으로 파일에 저장합니다. 이를 a.patch라고 부릅니다.

* 적용합니다:

    $ git fetch <project> master:test-apply
    $ git switch test-apply
    $ git restore --source=HEAD --staged --worktree :/
    $ git am a.patch

제대로 적용되지 않으면 여러 가지 이유가 있을 수 있습니다.

* 패치 자체가 깔끔하게 적용되지 않습니다. 이것은 _나쁩니다_ 하지만 MUA와는 관련이 적습니다. 이 경우 패치를 재생성하기 전에 linkgit:git-rebase[1]로 리베이스하는 것이 좋습니다.

* MUA가 패치를 손상시켰습니다; "am"은 패치가 적용되지 않는다고 불평할 것입니다. `.git/rebase-apply/` 하위 디렉토리를 살펴보고 'patch' 파일이 무엇을 포함하는지 확인하고 위에서 언급한 일반적인 손상 패턴을 검사하십시오.

* 김에 'info' 및 'final-commit' 파일도 확인하십시오. 'final-commit'에 포함된 내용이 커밋 로그 메시지에 보고 싶은 내용과 정확히 일치하지 않으면, 수신자가 패치를 적용할 때 로그 메시지를 수동으로 편집하게 될 것입니다. 패치 이메일의 "Hi, this is my first patch.\n"과 같은 내용은 커밋 메시지의 끝을 나타내는 세 개의 대시 줄 뒤에 와야 합니다.

MUA-SPECIFIC HINTS
------------------
다양한 메일러를 사용하여 인라인으로 패치를 성공적으로 제출하는 방법에 대한 팁이 있습니다.

GMail
~~~~~
GMail은 웹 인터페이스에서 줄 바꾸기를 비활성화할 방법이 없으므로 보낸 모든 이메일을 손상시킵니다. 그러나 "git send-email"을 사용하고 GMail SMTP 서버를 통해 패치를 보내거나, IMAP 이메일 클라이언트를 사용하여 Google IMAP 서버에 연결하고 이를 통해 이메일을 전달할 수 있습니다.

GMail SMTP 서버를 통해 패치를 보내는 "git send-email" 사용 팁은 linkgit:git-send-email[1]의 EXAMPLE 섹션을 참조하십시오.

IMAP 인터페이스를 사용한 제출 팁은 linkgit:git-imap-send[1]의 EXAMPLE 섹션을 참조하십시오.

Thunderbird
~~~~~~~~~~~
기본적으로 Thunderbird는 이메일을 래핑하고 'format=flowed'로 플래그를 지정하여 결과 이메일을 Git에서 사용할 수 없게 만듭니다.

세 가지 다른 접근 방식이 있습니다: 줄 래핑을 끄는 애드온 사용, Thunderbird가 패치를 손상시키지 않도록 구성, 또는 Thunderbird가 패치를 손상시키는 것을 방지하기 위해 외부 편집기 사용.

접근 방식 #1 (애드온)
^^^^^^^^^^^^^^^^^^^^

https://addons.thunderbird.net/thunderbird/addon/toggle-line-wrap 에서 사용 가능한 Toggle Line Wrap 애드온을 설치하십시오.
이 애드온은 작성자 도구 모음에 "Line Wrap" 버튼을 추가하여 선택적으로 끌 수 있습니다. 이제 다른 방식으로 메시지를 작성할 수 있습니다 (복사+붙여넣기, 'git format-patch' | 'git imap-send' 등). 그러나 입력하는 텍스트에는 수동으로 줄 바꿈을 삽입해야 합니다.

보너스 기능으로, 애드온은 com의 패치 텍스트를 감지할 수 있습니다