git-ls-tree(1)
==============

NAME
----
git-ls-tree - 트리에 있는 객체의 내용을 나열합니다.


SYNOPSIS
--------
[verse]
'git ls-tree' [-d] [-r] [-t] [-l] [-z]
	    [--name-only] [--name-status] [--object-only] [--full-name] [--full-tree] [--abbrev[=<n>]] [--format=<format>]
	    <tree-ish> [<path>...]

DESCRIPTION
-----------
현재 워킹 디렉토리에서 "/bin/ls -a"가 하는 것처럼, 주어진 트리 객체의 내용을 나열합니다. 다음 사항에 유의하십시오:

 - '<path>'는 단순히 일치시킬 패턴의 리스트를 나타내기 때문에 "/bin/ls"의 동작과는 약간 다릅니다. 예를 들어, ( `-r` 없이) 디렉토리 이름을 지정하면 동작이 달라지며, 인수 순서는 중요하지 않습니다.

 - '<path>'가 현재 워킹 디렉토리와 관련하여 처리되기 때문에 "/bin/ls"의 동작과 유사합니다. 예를 들어, 'dir' 이라는 디렉토리를 가진 'sub' 디렉토리 내에 있다면, 'git ls-tree -r HEAD dir'을 실행하여 트리('HEAD'의 `sub/dir`)의 내용을 나열할 수 있습니다. 이 경우 루트 레벨에 있지 않은 트리(예: `git ls-tree -r HEAD:sub dir`)를 제공하고 싶지 않을 수 있습니다. 왜냐하면 이는 `HEAD` 커밋에서 `sub/sub/dir`을 요청하는 결과로 이어지기 때문입니다. 그러나 --full-tree 옵션을 전달하여 현재 워킹 디렉토리를 무시할 수 있습니다.

OPTIONS
-------
<tree-ish>::
	트리-ish의 ID.

-d::
	자식 대신 지목된 트리 항목 자체만 표시합니다.

-r::
	하위 트리로 재귀합니다.

-t::
	재귀할 때 트리 항목도 표시합니다. `-r`이 전달되지 않았다면 아무런 효과가 없습니다. `-d`는 `-t`를 의미합니다.

-l::
--long::
	blob (파일) 항목의 객체 크기를 표시합니다.

-z::
	출력에 \0 줄 종결자를 사용하고 파일 이름을 인용하지 않습니다.
	더 많은 정보는 OUTPUT FORMAT을 참조하십시오.

--name-only::
--name-status::
	파일 이름만 나열합니다 ("long" 대신), 한 줄에 하나씩.
	`--object-only`와 조합할 수 없습니다.

--object-only::
	객체의 이름만 나열합니다, 한 줄에 하나씩.
	`--name-only` 또는 `--name-status`와 조합할 수 없습니다.
	이것은 `--format='%(objectname)'`을 지정하는 것과 동일하지만, 이 옵션과 정확히 이 형식을 위해 명령은 일반적인 형식화 메커니즘을 통하지 않고 손으로 최적화된 코드를 사용합니다.

--abbrev[=<n>]::
	전체 40바이트 16진수 객체 줄 대신, 객체를 고유하게 참조하는 '<n>'개의 16진수 숫자를 최소한으로 하는 가장 짧은 접두사를 표시합니다.
	기본이 아닌 숫자 개수는 --abbrev=<n>으로 지정할 수 있습니다.

--full-name::
	현재 워킹 디렉토리와 상대적인 경로 이름 대신, 전체 경로 이름을 표시합니다.

--full-tree::
	현재 워킹 디렉토리로 목록을 제한하지 않습니다.
	`--full-name`을 의미합니다.

--format=<format>::
	보여지는 결과에서 `%(fieldname)`을 삽입하는 문자열입니다.
	또한 `%%`를 `%`로, `NN`이 16진수 숫자인 `%xNN`을 16진수 코드 `NN`을 가진 문자로 삽입합니다. 예를 들어 `%x00`은 `\0` (NUL), `%x09`는 `\t` (TAB), `%x0a`는 `\n` (LF)로 삽입됩니다.
	지정되면, `--format`은 `--long`, `--name-only`, `--object-only`를 포함한 다른 형식 변경 옵션과 조합할 수 없습니다.

[<path>...]::
	경로가 주어지면, 그것들을 표시합니다 (이것은 실제 경로명이 아니라 일치시킬 패턴의 리스트라는 점에 유의하십시오). 그렇지 않으면 암시적으로 트리의 루트 레벨을 유일한 경로 인수로 사용합니다.


Output Format
-------------

`ls-tree`의 출력 형식은 `--format` 옵션 또는 `--format` (위 참조)과 같은 다른 형식 변경 옵션에 의해 결정됩니다.

특정 `--format` 지시자의 사용은 해당 옵션을 사용하는 것과 동등하지만, 전체 형식화 메커니즘을 호출하는 것이 적절한 형식 옵션을 사용하는 것보다 느릴 수 있습니다.

`--format`이 기존 옵션과 정확히 일치하는 경우 `ls-tree`는 적절한 더 빠른 경로를 사용합니다. 따라서 기본 형식은 다음과 동등합니다:

	%(objectmode) %(objecttype) %(objectname)%x09%(path)

이 출력 형식은 'git update-index'의 `--index-info --stdin`이 기대하는 형식과 호환됩니다.

`-l` 옵션이 사용될 경우, 형식은 다음과 같이 변경됩니다:

	%(objectmode) %(objecttype) %(objectname) %(objectsize:padded)%x09%(path)

<objectname>으로 식별된 객체 크기는 바이트 단위이며, 최소 너비 7자로 오른쪽 정렬됩니다. 객체 크기는 blob (파일) 항목에 대해서만 제공됩니다; 다른 항목의 경우 크기 대신 `-` 문자가 사용됩니다.

`-z` 옵션을 사용하지 않으면, "특이한" 문자를 가진 경로명은 `core.quotePath` 설정 변수에 설명된 대로 인용됩니다 (linkgit:git-config[1] 참조). `-z`를 사용하면 파일 이름이 그대로 출력되고 줄은 NUL 바이트로 종료됩니다.

사용자 정의 형식:

`%(fieldname)` 표기법을 사용하여 다른 필드를 삽입할 수 있는 `--format` 옵션을 사용하여 사용자 정의 형식으로 인쇄할 수 있습니다.
예를 들어, "objectname"과 "path" 필드만 관심 있다면, 다음과 같은 특정 "--format"으로 실행할 수 있습니다:

	git ls-tree --format='%(objectname) %(path)' <tree-ish>

FIELD NAMES
-----------

구조화된 필드의 다양한 값을 결과 출력에 삽입하는 데 사용할 수 있습니다. 각 출력 줄에 대해 다음 이름을 사용할 수 있습니다:

objectmode::
	객체의 모드.
objecttype::
	객체의 타입 (`commit`, `blob` 또는 `tree`).
objectname::
	객체의 이름.
objectsize[:padded]::
	`blob` 객체의 크기 (`commit` 또는 `tree`인 경우 "-" ).
	"%(objectsize:padded)"와 같은 패딩된 형식의 크기도 지원합니다.
path::
	객체의 경로명.

GIT
---
linkgit:git[1] 제품군의 일부