git-fast-export(1)
==================

NAME
----
git-fast-export - Git 데이터 내보내기 도구


SYNOPSIS
--------
[verse]
'git fast-export' [<options>] | 'git fast-import'

DESCRIPTION
-----------
이 프로그램은 지정된 리비전을 'git fast-import'로 파이핑하기에 적합한 형식으로 덤프합니다.

인간이 읽을 수 있는 번들 대체(linkgit:git-bundle[1] 참조)로 사용하거나, 'git fast-import'로 전달되기 전에 편집할 수 있는 형식으로 사용하여 히스토리 재작성에 사용할 수 있습니다(예: 'git filter-repo'와 같은 도구가 의존하는 기능).

OPTIONS
-------
--progress=<n>::
	'git fast-import'가 가져오는 동안 표시할 'progress' 문을 <n>개의 객체마다 삽입합니다.

--signed-tags=(verbatim|warn-verbatim|warn-strip|strip|abort)::
	서명된 태그를 처리하는 방법을 지정합니다. 내보내기 후(또는 리비전 제외와 같은 내보내기 중) 어떤 변환이든 해시를 변경할 수 있으므로 서명이 무효화될 수 있습니다.
+
'abort'(기본값)를 요청할 때, 이 프로그램은 서명된 태그를 만날 때 종료됩니다. 'strip'을 사용하면 태그는 조용히 서명되지 않으며, 'warn-strip'을 사용하면 태그는 서명되지 않지만 경고 메시지가 표시됩니다. 'verbatim'을 사용하면 조용히 내보내지고, 'warn-verbatim'(또는 사용되지 않는 동의어 'warn')을 사용하면 내보내지지만 경고 메시지가 표시됩니다. 'verbatim' 및 'warn-verbatim'은 태그나 그 히스토리에 있는 어떤 커밋에도 영향을 미치는 변환이 사용자가 수행하거나 fast-export 또는 fast-import에 의해 수행되지 않거나, 결과 태그가 무효한 서명을 갖게 되는 것을 신경 쓰지 않는 경우에만 사용해야 합니다.

--signed-commits=(verbatim|warn-verbatim|warn-strip|strip|abort)::
	서명된 커밋을 처리하는 방법을 지정합니다. '--signed-tags'와 정확히 동일하게 작동하지만 커밋에 적용됩니다. 기본값은 'strip'이며, 이는 이 옵션이 없는 이전 버전의 이 명령어가 작동한 방식과 동일합니다.
+
내보낼 때 서명은 다음으로 시작합니다:
+
gpgsig <git-hash-algo> <signature-format>
+
여기서 <git-hash-algo>는 Git 객체 해시이므로 "sha1" 또는 "sha256"이고, <signature-format>은 서명 유형이므로 "openpgp", "x509", "ssh" 또는 "unknown"입니다.
+
예를 들어, SHA-1 커밋에 대한 OpenPGP 서명은 `gpgsig sha1 openpgp`로 시작하고, SHA-256 커밋에 대한 SSH 서명은 `gpgsig sha256 ssh`로 시작합니다.
+
커밋의 모든 서명이 내보내지는 동안, 가져오기 도구는 일부만 수락하도록 선택할 수 있습니다. 예를 들어 linkgit:git-fast-import[1]는 현재 각 Git 해시 알고리즘마다 각 커밋에 대해 최대 하나의 서명만 저장합니다.
+
참고: 이는 매우 실험적이며 데이터 스트림 형식은 향후 호환성 보증 없이 변경될 수 있습니다.

--tag-of-filtered-object=(abort|drop|rewrite)::
	태그된 객체가 필터링된 태그를 처리하는 방법을 지정합니다. 내보낼 리비전과 파일을 경로별로 제한할 수 있으므로 태그된 객체는 완전히 필터링될 수 있습니다.
+
'abort'(기본값)를 요청할 때, 이 프로그램은 그러한 태그를 만날 때 종료됩니다. 'drop'을 사용하면 해당 태그가 출력에서 생략됩니다. 'rewrite'을 사용하면 태그된 객체가 커밋인 경우 태그를 재작성하여 조상 커밋을 태그합니다(링크:git-rev-list[1]의 부모 재작성을 통해).

-M::
-C::
	linkgit:git-diff[1] 매뉴얼 페이지에 설명된 대로 이동 및/또는 복사 감지를 수행하고 이를 출력 덤프에서 이름 변경 및 복사 명령을 생성하는 데 사용합니다.
+
이전 버전의 이 명령은 이러한 옵션을 제공할 경우 오류를 보고하지 않고 잘못된 결과를 생성했음에 유의하십시오.

--export-marks=<file>::
	완료 시 내부 마크 테이블을 <file>에 덤프합니다. 마크는 `:markid SHA-1` 형식으로 한 줄에 하나씩 작성됩니다. 리비전에 대한 마크만 덤프됩니다; 블롭에 대한 마크는 무시됩니다. 백엔드는 가져오기가 완료된 후 가져오기를 검증하거나 증분 실행 간에 마크 테이블을 저장하기 위해 이 파일을 사용할 수 있습니다. <file>은 완료 시에만 열리고 비워지므로, 동일한 경로를 --import-marks에도 안전하게 제공할 수 있습니다. 새 객체가 표시/내보내지지 않으면 파일이 작성되지 않습니다.

--import-marks=<file>::
	입력을 처리하기 전에 <file>에 지정된 마크를 로드합니다. 입력 파일은 존재해야 하고, 읽을 수 있어야 하며, --export-marks에서 생성된 것과 동일한 형식을 사용해야 합니다.

--mark-tags::
	블롭과 커밋에 마크 ID를 레이블링하는 것 외에 태그도 레이블링합니다. 이는 `--export-marks` 및 `--import-marks`와 함께 사용하면 유용하며, 중첩된 태그의 내보내기에도 유용합니다(및 필수). 다른 경우에는 해를 끼치지 않으며 기본값이 될 수 있지만, 많은 fast-import 프론트엔드는 마크 식별자가 있는 태그를 수락할 준비가 되어 있지 않습니다.
+
이미 마크된 커밋(또는 태그)은 다시 내보내지지 않습니다. 백엔드가 유사한 --import-marks 파일을 사용하는 경우, 실행 간에 마크를 동일하게 유지함으로써 저장소의 증분 양방향 내보내기가 가능합니다.

--fake-missing-tagger::
	일부 오래된 저장소에는 태거가 없는 태그가 있습니다. fast-import 프로토콜은 이것에 대해 매우 엄격했으며 허용하지 않았습니다. 따라서 출력의 fast-import를 위해 태거를 가짜로 만듭니다.

--use-done-feature::
	스트림을 'feature done' 스탠자로 시작하고 'done' 명령으로 종료합니다.

--no-data::
	블롭 객체의 출력을 건너뛰고 대신 원래 SHA-1 해시를 통해 블롭을 참조합니다. 이는 저장소의 디렉토리 구조나 히스토리를 개별 파일의 내용을 건드리지 않고 다시 작성할 때 유용합니다. 결과 스트림은 이미 필요한 객체를 포함하고 있는 저장소에서만 사용할 수 있습니다.

--full-tree::
	이 옵션을 사용하면 fast-export는 각 커밋에 대해 "deleteall" 지시문을 발행한 다음 커밋의 모든 파일 목록(부모보다 다른 파일만 나열하는 것과 대조적으로)을 제공합니다.

--anonymize::
	원래 트리 및 히스토리 패턴을 유지하면서 저장소의 내용을 익명화합니다. 목표는 개인 저장소에서 발견된 git 버그가 익명화된 저장소에서도 지속되어 버그를 해결하는 데 도움이 되도록 하는 것입니다.
+
이 옵션을 사용하면 ref 이름, 경로, 블롭 내용, 커밋 및 태그 메시지, 이름 및 이메일 주소가 익명화된 데이터로 대체됩니다. 동일한 문자열의 두 인스턴스는 동등하게 대체됩니다(예: 동일한 작성자가 있는 두 커밋은 출력에서 동일한 익명화된 작성자를 갖지만 원래 작성자 문자열과는 무관합니다). 커밋, 브랜치 및 태그 간의 관계는 유지되며 커밋 타임스탬프도 유지됩니다(단, 커밋 메시지와 ref 이름은 원본과 무관함). 트리의 상대적인 구성도 유지됩니다(예: 10개의 파일과 3개의 트리가 있는 루트 트리라면 출력에도 동일하게 유지됨), 하지만 이름과 파일 내용은 대체됩니다.
+
git 버그를 발견했다고 생각하면 전체 저장소의 익명화된 스트림을 내보내는 것으로 시작할 수 있습니다:

---------------------------------------------------
$ git fast-export --anonymize --all >anon-stream
---------------------------------------------------

그런 다음 스트림에서 생성된 저장소에서 버그가 지속되는지 확인합니다(많은 버그는 실제 저장소 내용에 따라 달라지므로 지속되지 않음):

---------------------------------------------------
$ git init anon-repo
$ cd anon-repo
$ git fast-import <../anon-stream
$ ... test your bug ...
---------------------------------------------------

익명화된 저장소에서 버그가 보이면 일반 버그 보고서와 함께 `anon-stream`을 공유하는 것이 좋습니다. 익명화된 스트림은 매우 잘 압축되므로 gzip으로 압축하는 것이 좋습니다. 스트림을 검사하여 개인 데이터가 포함되어 있지 않음을 확인하고 싶다면 직접 확인할 수 있습니다. 다음을 시도해 볼 수도 있습니다.

---------------------------------------------------
$ perl -pe 's/\d+/X/g' <anon-stream | sort -u | less
---------------------------------------------------

이것은 고유한 줄(숫자는 "X"로 변환되어 "User 0", "User 1" 등을 "User X"로 축소함)을 모두 보여줍니다. 결과 출력이 훨씬 작아지고 개인 데이터가 스트림에 포함되어 있지 않음을 빠르게 확인할 수 있습니다.

일부 버그를 재현하려면 ref 이름과 경로가 익명화된 후 특정 커밋이나 경로를 참조해야 하는데, 이는 어려워집니다. 특정 토큰을 그대로 두거나 새 값으로 매핑하도록 요청할 수 있습니다. 예를 들어 `git rev-list sensitive -- secret.c`로 재현되는 버그가 있다면 다음과 같이 실행할 수 있습니다.

---------------------------------------------------
$ git fast-export --anonymize --all \
      --anonymize-map=sensitive:foo \
      --anonymize-map=secret.c:bar.c \
      >stream
---------------------------------------------------

스트림을 가져온 후에는 익명화된 저장소에서 `git rev-list foo -- bar.c`를 실행할 수 있습니다.

경로와 ref 이름은 슬래시 구분 기호로 토큰화됩니다. 위의 명령은 `subdir/secret.c`를 `path123/bar.c`와 같이 익명화합니다. 그런 다음 익명화된 저장소에서 `bar.c`를 검색하여 최종 경로 이름을 결정할 수 있습니다.

최종 경로 이름을 더 쉽게 참조하려면 각 경로 구성 요소를 매핑할 수 있습니다. 예를 들어 `subdir`를 `publicdir`로 익명화하면 최종 경로 이름은 `publicdir/bar.c`가 됩니다.

--anonymize-map=<from>[:<to>]::
	익명화된 출력에서 토큰 `<from>`을 `<to>`로 변환합니다. `<to>`가 생략되면 `<from>`을 자신에게 매핑합니다(즉, 익명화하지 않습니다). `ANONYMIZING` 섹션을 참조하십시오.

--reference-excluded-parents::
	기본적으로 `git fast-export master~5..master`와 같은 명령을 실행하면 master~5 커밋이 포함되지 않고 master~4가 master~5를 더 이상 부모로 갖지 않게 됩니다(단, 이전 master~4와 새 master~4 모두 동일한 파일을 가짐). 대신 `--reference-excluded-parents`를 사용하여 히스토리의 제외된 범위에 있는 커밋을 sha1sum으로 참조하도록 스트림을 만듭니다. 결과 스트림은 이미 필요한 부모 커밋을 포함하고 있는 저장소에서만 사용할 수 있습니다.

--show-original-ids::
	커밋과 블롭에 대한 출력에 `original-oid <SHA1SUM>`이라는 추가 지시문을 추가합니다. 이러한 지시문은 git-fast-import와 같은 가져오기 도구에서 무시될 가능성이 높지만, 중간 필터(예: 이전 커밋을 참조하는 커밋 메시지를 다시 작성하거나 ID별로 블롭을 정리하는 경우)에 유용할 수 있습니다.

--reencode=(yes|no|abort)::
	커밋 객체의 `encoding` 헤더를 처리하는 방법을 지정합니다. 'abort'(기본값)를 요청할 때, 이 프로그램은 그러한 커밋 객체를 만날 때 종료됩니다. 'yes'를 사용하면 커밋 메시지가 UTF-8로 다시 인코딩됩니다. 'no'를 사용하면 원래 인코딩이 유지됩니다.

--refspec::
	지정된 refspec을 각 내보내진 ref에 적용합니다. 여러 개를 지정할 수 있습니다.

[<git-rev-list-args>...]::
	'git rev-parse' 및 'git rev-list'에서 허용되는 인수의 목록으로, 내보낼 특정 객체와 참조를 지정합니다. 예를 들어, `master~10..master`는 현재 master 참조와 10번째 조상 커밋 이후에 추가된 모든 객체(및 --reference-excluded-parents 옵션이 지정되지 않은 경우 master~9와 master~10 공통 파일)를 내보냅니다.

EXAMPLES
--------

-------------------------------------------------------------------
$ git fast-export --all | (cd /empty/repository && git fast-import)
-------------------------------------------------------------------

그러면 전체 저장소가 내보내지고 기존의 빈 저장소로 가져와집니다. UTF-8이 아닌 커밋의 다시 인코딩을 제외하고는 일대일 미러가 될 것입니다.

-----------------------------------------------------
$ git fast-export master~5..master |
	sed "s|refs/heads/master|refs/heads/other|" |
	git fast-import
-----------------------------------------------------

그러면 'master~5..master'에서 'other'라는 새 브랜치가 만들어집니다(예: 'master'에 선형 히스토리가 있는 경우 마지막 5개의 커밋을 사용합니다).

이것은 해당 리비전 범위에서 참조하는 블롭과 커밋 메시지 중 'refs/heads/master' 문자열을 포함하지 않는다고 가정합니다.

ANONYMIZING
-----------

`--anonymize` 옵션을 제공하면 git은 원래 트리 및 히스토리 패턴의 많은 부분을 유지하면서 저장소의 모든 식별 정보를 제거하려고 시도하여 일부 버그를 재현합니다. 목표는 개인 저장소에 있는 git 버그가 익명화된 저장소에서도 지속되어 버그를 해결하는 데 도움이 되도록 하는 것입니다.

이 옵션을 사용하면 ref 이름, 경로, 블롭 내용, 커밋 및 태그 메시지, 이름 및 이메일 주소가 익명화된 데이터로 대체됩니다. 동일한 문자열의 두 인스턴스는 동등하게 대체됩니다(예: 동일한 작성자가 있는 두 커밋은 출력에서 동일한 익명화된 작성자를 갖지만 원래 작성자 문자열과는 무관합니다). 커밋, 브랜치 및 태그 간의 관계는 유지되며 커밋 타임스탬프도 유지됩니다(단, 커밋 메시지와 ref 이름은 원본과 무관함). 트리의 상대적인 구성도 유지됩니다(예: 10개의 파일과 3개의 트리가 있는 루트 트리라면 출력에도 동일하게 유지됨), 하지만 이름과 파일 내용은 대체됩니다.

git 버그를 발견했다고 생각하면 전체 저장소의 익명화된 스트림을 내보내는 것으로 시작할 수 있습니다:

---------------------------------------------------
$ git fast-export --anonymize --all >anon-stream
---------------------------------------------------

그런 다음 스트림에서 생성된 저장소에서 버그가 지속되는지 확인합니다(많은 버그는 실제 저장소 내용에 따라 달라지므로 지속되지 않음):

---------------------------------------------------
$ git init anon-repo
$ cd anon-repo
$ git fast-import <../anon-stream
$ ... test your bug ...
---------------------------------------------------

익명화된 저장소에서 버그가 보이면 일반 버그 보고서와 함께 `anon-stream`을 공유하는 것이 좋습니다. 익명화된 스트림은 매우 잘 압축되므로 gzip으로 압축하는 것이 좋습니다. 스트림을 검사하여 개인 데이터가 포함되어 있지 않음을 확인하고 싶다면 직접 확인할 수 있습니다. 다음을 시도해 볼 수도 있습니다.

---------------------------------------------------
$ perl -pe 's/\d+/X/g' <anon-stream | sort -u | less
---------------------------------------------------

이것은 고유한 줄(숫자는 "X"로 변환되어 "User 0", "User 1" 등을 "User X"로 축소함)을 모두 보여줍니다. 결과 출력이 훨씬 작아지고 개인 데이터가 스트림에 포함되어 있지 않음을 빠르게 확인할 수 있습니다.

일부 버그를 재현하려면 ref 이름과 경로가 익명화된 후 특정 커밋이나 경로를 참조해야 하는데, 이는 어려워집니다. 특정 토큰을 그대로 두거나 새 값으로 매핑하도록 요청할 수 있습니다. 예를 들어 `git rev-list sensitive -- secret.c`로 재현되는 버그가 있다면 다음과 같이 실행할 수 있습니다.

---------------------------------------------------
$ git fast-export --anonymize --all \
      --anonymize-map=sensitive:foo \
      --anonymize-map=secret.c:bar.c \
      >stream
---------------------------------------------------

스트림을 가져온 후에는 익명화된 저장소에서 `git rev-list foo -- bar.c`를 실행할 수 있습니다.

경로와 ref 이름은 슬래시 구분 기호로 토큰화됩니다. 위의 명령은 `subdir/secret.c`를 `path123/bar.c`와 같이 익명화합니다. 그런 다음 익명화된 저장소에서 `bar.c`를 검색하여 최종 경로 이름을 결정할 수 있습니다.

최종 경로 이름을 더 쉽게 참조하려면 각 경로 구성 요소를 매핑할 수 있습니다. 예를 들어 `subdir`를 `publicdir`로 익명화하면 최종 경로 이름은 `publicdir/bar.c`가 됩니다.

LIMITATIONS
-----------

'git fast-import'는 트리를 태그할 수 없으므로 linux.git 저장소를 완전히 내보낼 수 없습니다. 왜냐하면 커밋이 아닌 트리를 참조하는 태그가 포함되어 있기 때문입니다.

SEE ALSO
--------
linkgit:git-fast-import[1]

GIT
---
linkgit:git[1] 제품군의 일부