git-cvsimport(1)
================

NAME
----
git-cvsimport - 다른 SCM에서 데이터를 살려내기; 사람들이 싫어하는 SCM

SYNOPSIS
--------
[verse]
'git cvsimport' [-o <branch-for-HEAD>] [-h] [-v] [-d <CVSROOT>]
	      [-A <author-conv-file>] [-p <options-for-cvsps>] [-P <file>]
	      [-C <git-repository>] [-z <fuzz>] [-i] [-k] [-u] [-s <subst>]
	      [-a] [-m] [-M <regex>] [-S <regex>] [-L <commit-limit>]
	      [-r <remote>] [-R] [<CVS-module>]


DESCRIPTION
-----------
*경고:* `git cvsimport`는 cvsps 버전 2를 사용하며, 이는
지원 중단된 것으로 간주됩니다; cvsps 버전 3 이상에서는 작동하지 않습니다. 만약
CVS 저장소를 한 번만 가져오기(import) 하는 경우
http://cvs2svn.tigris.org/cvs2git.html[cvs2git] 또는
https://gitlab.com/esr/cvs-fast-export[cvs-fast-export]를 사용하는 것을 고려하십시오.

CVS 저장소를 Git으로 가져옵니다. 새 저장소를 생성하거나
기존 저장소로 점진적으로 가져올 수 있습니다.

CVS 로그를 패치 세트로 분할하는 작업은 'cvsps'에 의해 수행됩니다.
최소한 버전 2.1이 필요합니다.

*경고:* 특정 상황에서는 가져오기 결과가 올바르지 않을 수 있습니다.
자세한 내용은 <<issues,ISSUES>> 섹션을 참조하십시오.

'git cvsimport'가 생성한 브랜치에서는 *절대로* 직접 작업을 해서는 안 됩니다.
기본적으로 초기 가져오기는 CVS 저장소의 메인 브랜치로부터
"master" 브랜치를 생성하고 채울 것이며, 이는 자유롭게 작업할 수 있습니다; 그 후에는,
점진적 가져오기 또는 CVS 브랜치를 직접 `git merge`해야 합니다.
들어오는 브랜치를 분리하고 보호하기 위해 -r로 명명된 원격(remote)을
지정하는 것이 좋습니다.

공유 공개 저장소를 설정하여 모든 개발자가 읽기/쓰기할 수 있게 하거나,
linkgit:git-cvsserver[1]를 사용하려면,
가져온 저장소의 bare clone을 만들고,
해당 clone을 공유 저장소로 사용하는 것이 좋습니다.
linkgit:gitcvs-migration[7]을 참조하십시오.


OPTIONS
-------
-v::
	상세 출력: 'cvsimport'가 수행하는 작업을 보고합니다.

-d <CVSROOT>::
	CVS 아카이브의 루트입니다. 로컬(단순 경로) 또는 원격일 수 있습니다;
	현재 :local:, :ext:, :pserver: 액세스 메서드만
	지원됩니다. 지정하지 않으면 'git cvsimport'는 `CVS/Root`에서
	읽으려고 시도합니다. 이러한 파일이 없으면 `CVSROOT` 환경 변수를
	확인합니다.

<CVS-module>::
	가져오려는 CVS 모듈입니다. <CVSROOT>에 상대적입니다.
	지정하지 않으면 'git cvsimport'는 `CVS/Repository`에서
	읽으려고 시도합니다.

-C <target-dir>::
	가져올 Git 저장소 디렉토리입니다. 해당 디렉토리가
        존재하지 않으면 생성됩니다. 기본값은 현재 디렉토리입니다.

-r <remote>::
	이 CVS 저장소를 가져올 Git 원격(remote)입니다.
	모든 CVS 브랜치를 remotes/<remote>/<branch>로 이동시킵니다.
	'git clone'이 기본적으로 'origin'을 사용하는 방식과 유사합니다.

-o <branch-for-HEAD>::
	원격이 지정되지 않은 경우 ( -r 사용 시), CVS의 `HEAD` 브랜치는
	Git 저장소 내의 'origin' 브랜치로 가져와집니다. `HEAD`는 Git에서
	이미 특별한 의미를 가지기 때문입니다.
	원격이 지정된 경우 `HEAD` 브랜치는 'git clone' 동작을 미러링하여
	remotes/<remote>/master로 명명됩니다.
	다른 브랜치로 가져오려면 이 옵션을 사용하십시오.
+
이전 cvs2git 도구로 초기 가져오기를 계속하려면 '-o master'를 사용하십시오.

-i::
	가져오기 전용: 가져온 후 checkout을 수행하지 않습니다. 이 옵션은
	워킹 트리와 인덱스가 변경되지 않도록 보장하며, 존재하지 않으면
	생성하지 않습니다.

-k::
	키워드 제거: 노이즈가 많은 변경 세트를 피하기 위해 CVS 아카이브에서
	'-kk' 옵션으로 파일을 추출합니다. 강력히 권장되지만, 초기 가져온
	트리와의 호환성을 유지하기 위해 기본적으로 비활성화되어 있습니다.

-u::
	태그 및 브랜치 이름의 밑줄 문자를 점으로 변환합니다.

-s <subst>::
	브랜치 이름의 "/" 문자를 <subst>로 대체합니다.

-p <options-for-cvsps>::
	cvsps에 대한 추가 옵션입니다.
	`-u` 및 '-A' 옵션은 암묵적이므로 여기에 사용하면 안 됩니다.
+
여러 옵션을 전달해야 하는 경우 쉼표로 구분하십시오.

-z <fuzz>::
	타임스탬프 퍼지(fuzz) 계수를 초 단위로 cvsps에 전달합니다. 설정되지 않으면,
	cvsps는 기본값으로 300초를 사용합니다.

-P <cvsps-output-file>::
	cvsps를 호출하는 대신, 제공된 cvsps 출력 파일을 읽습니다.
	디버깅에 유용하거나 cvsps가 cvsimport 외부에서 처리될 때 사용합니다.

-m::
	커밋 메시지를 기반으로 머지(merge)를 감지하려고 시도합니다. 이 옵션은
	커밋 메시지에서 소스 브랜치 이름을 캡처하려는 기본 정규식을 활성화합니다.

-M <regex>::
	사용자 지정 정규식으로 커밋 메시지를 기반으로 머지를 감지하려고 시도합니다.
	`-m`과 함께 사용하여 기본 정규식을 활성화할 수도 있습니다. 슬래시(/)를
	이스케이프해야 합니다.
+
정규식은 $1에서 소스 브랜치 이름을 캡처해야 합니다.
+
이 옵션은 여러 감지 정규식을 제공하기 위해 여러 번 사용할 수 있습니다.

-S <regex>::
	정규식과 일치하는 경로를 건너뜁니다.

-a::
	최근 커밋을 포함하여 모든 커밋을 가져옵니다. cvsimport는 기본적으로
	10분 이내의 타임스탬프를 가진 커밋을 건너뜁니다.

-L <limit>::
	가져올 커밋 수를 제한합니다. cvsimport 메모리 누수 문제가 발생할 경우
	우회 방법입니다.

-A <author-conv-file>::
	CVS는 기본적으로 커밋 로그를 작성할 때 Unix 사용자 이름을 사용합니다.
	이 옵션과 author-conv-file을 사용하면 CVS에 기록된 이름을
	저자 이름, 이메일 및 선택적 시간대로 매핑합니다:
+
---------
	exon=Andreas Ericsson <ae@op5.se>
	spawn=Simon Pawn <spawn@frog-pond.org> America/Chicago

---------
+
'git cvsimport'는 마치 해당 저자들이 처음부터
GIT_AUTHOR_NAME 및 GIT_AUTHOR_EMAIL을 올바르게 설정했던 것처럼 보이게 할 것입니다.
시간대가 지정되면 GIT_AUTHOR_DATE에 해당 오프셋이 적용됩니다.
+
편의를 위해 이 데이터는 '-A' 옵션이 제공될 때마다 `$GIT_DIR/cvs-authors`에
저장되며, 'git cvsimport'가 실행될 때마다 해당 파일에서 읽힙니다.
+
나중에 'git cvsexportcommit'으로 CVS에 변경 사항을 다시 내보내려면
이 기능을 사용하지 않는 것이 좋습니다.

-R::
	CVS 개정 번호와 새로 생성된 Git 커밋 ID 간의 매핑을 포함하는
	`$GIT_DIR/cvs-revisions` 파일을 생성합니다. 생성된 파일은
	가져온 (필드명, 개정) 쌍마다 한 줄을 포함하며, 각 줄은 다음과 같은 형식입니다:
+
---------
src/widget.c 1.1 1d862f173cdc7325b6fa6d2ae1cfd61fd1b512b7
---------
+
개정 데이터는 파일이 이미 존재하는 경우 파일 끝에 추가되어,
점진적 가져오기를 수행할 때 사용됩니다.
+
이 옵션은 커밋 메시지, 버그 추적 시스템, 이메일 아카이브 등에
CVS 개정 번호가 저장되어 있는 경우 유용할 수 있습니다.

-h::
	짧은 사용법 메시지를 출력하고 종료합니다.

OUTPUT
------
`-v`가 지정되면, 스크립트는 수행하는 작업을 보고합니다.

그렇지 않으면, 성공은 Unix 방식으로 표시됩니다. 즉, 0의 종료 상태로
종료됩니다.

[[issues]]
ISSUES
------
타임스탬프 관련 문제:

 * CVS 저장소의 커밋 타임스탬프가 커밋 순서를 결정하기에 충분히 안정적이지 않으면
   변경 사항이 잘못된 순서로 나타날 수 있습니다.
 * 파일이 여러 번 "cvs import"된 경우 (예: 여러 벤더 릴리스 가져오기)
   HEAD에 잘못된 내용이 포함됩니다.
 * 서로 다른 파일의 타임스탬프 순서가 커밋 매칭 시간 창 내의
   개정 순서와 교차하면 커밋 순서가 잘못될 수 있습니다.

브랜치 관련 문제:

 * 커밋이 없는 브랜치는 가져오지 않습니다.
 * 분기 시점의 모든 파일이, CVS에 추가되지 않았더라도, 브랜치에 추가됩니다.
 * 이는 소스 브랜치에 분기 브랜치가 생성된 *후*에 추가된 파일에 적용됩니다:
   이전에 분기 브랜치에 커밋이 없었다면 Git에서도 해당 분기 브랜치에
   잘못 추가될 것입니다.

태그 관련 문제:

* 동일한 개정 번호에 대한 여러 태그는 가져오지 않습니다.

만약 이러한 문제 중 일부가 가져오려는 저장소에 적용될 수 있다고 의심되면,
cvs2git을 사용하는 것을 고려하십시오:

* cvs2git (cvs2svn의 일부), `https://subversion.apache.org/`

GIT
---
linkgit:git[1] 제품군의 일부입니다.