git-ls-remote(1)
================

NAME
----
git-ls-remote - 원격 저장소의 참조 목록 표기


SYNOPSIS
--------
[verse]
'git ls-remote' [--branches] [--tags] [--refs] [--upload-pack=<exec>]
	      [-q | --quiet] [--exit-code] [--get-url] [--sort=<key>]
	      [--symref] [<repository> [<patterns>...]]

DESCRIPTION
-----------
원격 저장소에 사용 가능한 참조 목록과 해당 커밋 ID를 표시합니다.


OPTIONS
-------
-b::
--branches::
-t::
--tags::
	각각 로컬 브랜치와 로컬 태그로만 제한합니다.
	이 옵션들은 상호 배타적이지 않습니다; 둘 다 주어졌을 때,
	`refs/heads`와 `refs/tags`에 저장된 참조가 표시됩니다.
	`--heads`와 `-h`는 `--branches`와 `-b`의 폐기된 동의어이며
	미래에 제거될 수 있다는 점에 유의하십시오.
	또한 `git ls-remote -h`가 명령줄에서 다른 것 없이 사용될 때
	도움을 제공하며, 이는 다른 git 서브커맨드와 일관됩니다.

--refs::
	출력에서 벗겨진 태그나 `HEAD`와 같은 의사 참조를 표시하지 않습니다.

-q::
--quiet::
	서로 다른 URL을 stderr에 출력하지 않습니다.

--upload-pack=<exec>::
	원격 호스트 상의 'git-upload-pack'의 전체 경로를 지정합니다.
	이를 통해 SSH를 통해 접근하는 저장소의 참조를 나열할 수 있으며,
	SSH 데몬이 사용자가 구성한 PATH를 사용하지 않는 경우에도 가능합니다.

--exit-code::
	원격 저장소에서 일치하는 참조를 찾지 못했을 때 상태 "2"로 종료합니다.
	일반적으로 명령은 원격 저장소와 성공적으로 통신했을 때,
	일치하는 참조를 찾았는지 여부에 관계없이 상태 "0"으로 종료합니다.

--get-url::
	주어진 원격 저장소의 URL을 확장하며, "url.<base>.insteadOf" 설정(linkgit:git-config[1] 참조)을 감안합니다.
	원격 저장소와 통신하지 않고 종료합니다.

--symref::
	대상이 가리키는 객체 외에도, 심볼릭 참조를 표시할 때
	그것이 가리키는 기본 참조를 표시합니다. 현재,
	upload-pack은 HEAD 심볼릭 참조만 표시하므로,
	ls-remote에 의해 표시되는 유일한 심볼릭 참조가 될 것입니다.

--sort=<key>::
	주어진 키에 따라 정렬합니다. 값을 기준으로 내림차순 정렬하려면
	`-`를 접두사로 붙입니다. "version:refname" 또는 "v:refname"을
	지원합니다 (태그 이름은 버전으로 취급됨). "version:refname" 정렬
	순서는 "versionsort.suffix" 설정 변수에 의해 영향을 받을 수도 있습니다.
	더 많은 정렬 옵션은 linkgit:git-for-each-ref[1]를 참조하십시오.
	`committerdate`와 같이 객체에 대한 접근을 요구하는 키는
	아직 원격으로부터 가져오지 않은 객체를 가진 참조에 대해서는 작동하지 않으며,
	`missing object` 오류를 발생시킬 수 있다는 점에 유의하십시오.

-o <option>::
--server-option=<option>::
	프로토콜 버전 2를 사용하여 통신할 때 서버에 주어진 문자열을 전송합니다.
	주어진 문자열은 NUL 또는 LF 문자를 포함해서는 안 됩니다.
	여러 개의 `--server-option=<option>`이 주어지면,
	명령줄에 나열된 순서대로 모두 상대방에게 전송됩니다.
	명령줄에서 `--server-option=<option>`이 주어지지 않으면,
	"remote.<name>.serverOption" 설정 변수의 값이 대신 사용됩니다.

<repository>::
	쿼리할 "원격" 저장소입니다. 이 매개변수는
	URL 또는 원격의 이름이 될 수 있습니다 (linkgit:git-fetch[1]의 GIT URLS 및 REMOTES 섹션 참조).

<patterns>...::
	생략될 경우, --heads와 --tags를 통한 필터링 후 모든 참조가 표시됩니다.
	<patterns>...가 지정될 경우, 주어진 패턴 중 하나 이상과 일치하는
	참조만 표시됩니다. 각 패턴은 ref의 "꼬리"에 대해 매칭되는 glob이며
	(linkgit:gitglossary[7]의 `glob` 참조),
	ref의 시작(따라서 `refs/heads/foo`와 같은 전체 이름이 일치함) 또는
	슬래시 구분 기호(따라서 `bar`는 `refs/heads/bar`는 일치하지만
	`refs/heads/foobar`는 일치하지 않음)부터 시작합니다.

OUTPUT
------

출력은 다음 형식입니다:

------------
<oid> TAB <ref> LF
------------

주석이 달린 태그를 표시할 때, `--refs`가 주어지지 않는 한, 두 줄이 표시됩니다:
하나는 `<ref>` 자체의 ref 이름이고, 다른 하나는 `<ref>` 뒤에 `^{}`가 붙습니다.
후자 줄의 `<oid>`는 태그가 가리키는 객체의 이름을 보여줍니다.

EXAMPLES
--------

* 모든 참조(심볼릭 및 의사 참조 포함)를 나열하고 태그를 벗겨냅니다:
+
----
$ git ls-remote
27d43aaaf50ef0ae014b88bba294f93658016a2e	HEAD
950264636c68591989456e3ba0a5442f93152c1a	refs/heads/main
d9ab777d41f92a8c1684c91cfb02053d7dd1046b	refs/heads/next
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

* 주어진 패턴과 일치하는 모든 참조를 나열합니다:
+
----
$ git ls-remote http://www.kernel.org/pub/scm/git/git.git master seen rc
5fe978a5381f1fbad26a80e682ddd2a401966740	refs/heads/master
c781a84b5204fb294c9ccc79f8b3baceeb32c061	refs/heads/seen
----

* 주어진 와일드카드 패턴과 일치하는 태그만 나열합니다:
+
----
$ git ls-remote --tags http://www.kernel.org/pub/scm/git/git.git v\*
485a869c64a68cc5795dd99689797c5900f4716d	refs/tags/v2.39.2
cbf04937d5b9fcf0a76c28f69e6294e9e3ecd7e6	refs/tags/v2.39.2^{}
d4ca2e3147b409459955613c152220f4db848ee1	refs/tags/v2.40.0
73876f4861cd3d187a4682290ab75c9dccadbc56	refs/tags/v2.40.0^{}
----

SEE ALSO
--------
linkgit:git-check-ref-format[1].

GIT
---
linkgit:git[1] 제품군의 일부