git-clean(1)
============

NAME
----
git-clean - 워킹 트리에서 추적되지 않은 파일을 제거합니다.

SYNOPSIS
--------
[verse]
'git clean' [-d] [-f] [-i] [-n] [-q] [-e <pattern>] [-x | -X] [--] [<pathspec>...]

DESCRIPTION
-----------

현재 디렉토리에서 시작하여 버전 관리 하에 있지 않은 파일을 재귀적으로 제거하여 워킹 트리를 정리합니다.

일반적으로 Git에 알려지지 않은 파일만 제거되지만, `-x` 옵션을 지정하면 무시된 파일도 제거됩니다. 예를 들어, 모든 빌드 결과물을 제거하는 데 유용할 수 있습니다.

선택적으로 `<pathspec>...` 인수를 제공하면 pathspec과 일치하는 경로만 영향을 받습니다.

OPTIONS
-------
-d::
	일반적으로 `<pathspec>`이 지정되지 않으면 git clean은 너무 많은 것을 제거하는 것을 피하기 위해 추적되지 않은 디렉토리로 재귀하지 않습니다.
	이러한 디렉토리로도 재귀하도록 `-d`를 지정하십시오.
	`<pathspec>`이 지정되면 `-d`는 무관합니다. 지정된 경로와 일치하는 모든 추적되지 않은 파일(`--force` 아래에 언급된 중첩된 git 저장소에 대한 예외 포함)이 제거됩니다.

-f::
--force::
	Git 구성 변수 clean.requireForce가 false로 설정되어 있지 않으면, `-f`가 제공되지 않는 한 'git clean'은 파일이나 디렉토리를 삭제하는 것을 거부합니다. Git은 두 번째 `-f`가 제공되지 않는 한 추적되지 않은 중첩된 git 저장소(하위 디렉토리 .git가 있는 디렉토리)를 수정하는 것을 거부합니다.

-i::
--interactive::
	무엇이 수행될지 보여주고 파일을 임시로 정리합니다. 자세한 내용은
	``Interactive mode''를 참조하십시오.
	구성 변수 `clean.requireForce`는 무시됩니다. 이 모드는 임시로 진행하므로 자체 안전 보호 기능을 제공합니다.

-n::
--dry-run::
	실제로 아무것도 제거하지 않고, 무엇이 수행될지만 보여줍니다.
	구성 변수 `clean.requireForce`는 무시됩니다. 어차피 아무것도 삭제되지 않습니다.

-q::
--quiet::
	조용하게, 오류만 보고하고 성공적으로 제거된 파일은 보고하지 않습니다.

-e <pattern>::
--exclude=<pattern>::
	표준 무시 규칙(linkgit:gitignore[5] 참조)에 추가하여 주어진 제외 패턴을 사용합니다.

-x::
	표준 무시 규칙(linkgit:gitignore[5] 참조)을 사용하지 않지만,
	명령행에서 `-e` 옵션으로 주어진 무시 규칙은 여전히 사용합니다.
	이를 통해 빌드 결과물을 포함한 모든 추적되지 않은 파일을 제거할 수 있습니다.
	이것은 (아마도 'git restore' 또는 'git reset'과 함께) 깨끗한 빌드를 테스트하기 위해 깨끗한 워킹 디렉토리를 생성하는 데 사용할 수 있습니다.

-X::
	Git에 의해 무시된 파일만 제거합니다.
	모든 것을 처음부터 다시 빌드하는 데 유용할 수 있지만, 수동으로 생성된 파일은 유지합니다.

Interactive mode
----------------
이 명령이 임시 모드로 진입할 때, 정리될 파일 및 디렉토리를 보여주고 임시 명령 루프로 들어갑니다.

명령 루프는 사용 가능한 하위 명령 목록을 표시하고 "What now> " 프롬프트를 제공합니다. 일반적으로 프롬프트가 단일 '>'로 끝나면, 제공된 선택 사항 중 하나만 선택하고 Enter를 누를 수 있습니다.

------------
    *** Commands ***
	1: clean                2: filter by pattern    3: select by numbers
	4: ask each             5: quit                 6: help
    What now> 1
------------

위의 선택 사항이 고유한 경우 `c` 또는 `clean`이라고 말할 수도 있습니다.

주요 명령 루프에는 6개의 하위 명령이 있습니다.

clean::

   파일과 디렉토리를 정리하기 시작하고 종료합니다.

filter by pattern::

   삭제될 파일과 디렉토리를 보여주고 "Input ignore patterns>>" 프롬프트를 표시합니다.
   파일 및 디렉토리를 삭제에서 제외하기 위해 공백으로 구분된 패턴을 입력할 수 있습니다.
   예: "*.c *.h"는 ".c" 및 ".h"로 끝나는 파일을 삭제에서 제외합니다.
   필터링된 결과에 만족하면 ENTER(빈 줄)를 눌러 메인 메뉴로 돌아갑니다.

select by numbers::

   삭제될 파일과 디렉토리를 보여주고 "Select items to delete>>" 프롬프트를 표시합니다.
   프롬프트가 다음과 같이 이중 '>>'로 끝나면, 공백이나 쉼표로 연결된 여러 항목을 선택할 수 있습니다.
   또한 범위를 지정할 수도 있습니다. 예: "2-5 7,9"는 목록에서 2,3,4,5,7,9를 선택합니다.
   범위의 두 번째 숫자가 생략되면, 나머지 모든 항목이 선택됩니다. 예: "7-"은 목록에서 7,8,9를 선택합니다.
   '*'를 사용하여 모든 항목을 선택할 수 있습니다.
   또한 필터링된 결과에 만족하면 ENTER(빈 줄)를 눌러 메인 메뉴로 돌아갑니다.

ask each::

  정리를 시작하며, 항목을 삭제하려면 하나씩 확인해야 합니다.
  이 작업은 위의 두 작업만큼 효율적이지 않다는 점에 유의하십시오.

quit::

  정리를 수행하지 않고 종료합니다.

help::

  임시 git-clean 사용법을 간략하게 보여줍니다.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/clean.adoc[]

SEE ALSO
--------
linkgit:gitignore[5]

GIT
---
linkgit:git[1] suite의 일부입니다.