git-describe(1)
===============

NAME
----
git-describe - 객체에 접근 가능한 ref를 기반으로 사람이 읽을 수 있는 이름 부여

SYNOPSIS
--------
[synopsis]
git describe [--all] [--tags] [--contains] [--abbrev=<n>] [<commit-ish>...]
git describe [--all] [--tags] [--contains] [--abbrev=<n>] --dirty[=<mark>]
git describe <blob>

DESCRIPTION
-----------
이 명령은 커밋에서 도달 가능한 가장 최근의 태그를 찾습니다. 태그가 커밋을 가리키면 태그만 표시됩니다. 그렇지 않으면 태그 이름 뒤에 태그된 객체 위의 추가 커밋 수를 붙이고 가장 최근 커밋의 축약된 객체 이름을 붙입니다. 결과는 "사람이 읽을 수 있는" 객체 이름이며, 이는 다른 git 명령에서 커밋을 식별하는 데에도 사용할 수 있습니다.

기본적으로 (`--all` 또는 `--tags` 없이) `git describe`는 주석 태그만 표시합니다. 주석 태그 생성에 대한 자세한 내용은 linkgit:git-tag[1]의 `-a` 및 `-s` 옵션을 참조하십시오.

주어진 객체가 blob을 참조하는 경우, `<commit-ish>:<path>`로 설명됩니다. 여기서, blob은 _<path>_ 에서 _<commit-ish>_ 로 찾을 수 있습니다. _<commit-ish>_ 자체는 `HEAD`로부터의 역 방향 리비전 워크에서 이 blob이 발생하는 첫 번째 커밋을 설명합니다.

OPTIONS
-------
`<commit-ish>...`::
	설명할 커밋-이시 객체 이름. 생략되면 `HEAD`를 기본값으로 합니다.

`--dirty[=<mark>]`::
`--broken[=<mark>]`::
	워킹 트리의 상태를 설명합니다. 워킹 트리가 `HEAD`와 일치하면 출력은 `git describe HEAD`와 동일합니다. 워킹 트리에 로컬 수정 사항이 있으면 `-dirty`가 거기에 appended됩니다. 저장소가 손상되어 Git이 로컬 수정이 있는지 확인할 수 없는 경우, `--broken`이 제공되지 않으면 Git은 오류를 발생시키고, `--broken`이 제공되면 대신 `-broken` 접미사를 appended합니다.

`--all`::
	주석 태그만 사용하는 대신, `refs/` 네임스페이스의 모든 ref를 사용합니다. 이 옵션은 알려진 모든 브랜치, 원격 추적 브랜치 또는 경량 태그와 일치하도록 합니다.

`--tags`::
	주석 태그만 사용하는 대신, `refs/tags` 네임스페이스의 모든 태그를 사용합니다. 이 옵션은 경량(주석 없음) 태그와 일치하도록 합니다.

`--contains`::
	커밋 이전에 오는 태그를 찾는 대신, 커밋 이후에 오고 따라서 그것을 포함하는 태그를 찾습니다. 자동으로 `--tags`를 암시합니다.

`--abbrev=<n>`::
	축약된 객체 이름의 기본 16진수 숫자(저장소의 객체 수에 따라 달라지며 기본값은 7) 대신, _<n>_ 개의 숫자를 사용하거나 고유한 객체 이름을 형성하는 데 필요한 만큼의 숫자를 사용합니다. _<n>_ 이 0이면 긴 형식 suppressed, 가장 가까운 태그만 표시합니다.

`--candidates=<n>`::
	입력 커밋-이시를 설명하기 위해 가장 최근의 10개 태그만 후보로 고려하는 대신, 최대 _<n>_ 개의 후보를 고려합니다. _<n>_ 을 10 이상으로 늘리면 약간 더 오래 걸리지만 더 정확한 결과를 얻을 수 있습니다. _<n>_ 이 0이면 정확한 일치만 출력합니다.

`--exact-match`::
	정확한 일치만 출력합니다 (태그가 제공된 커밋을 직접 참조). 이것은 `--candidates=0`의 동의어입니다.

`--debug`::
	표준 오류로 전송되는 검색 전략에 대한 정보를 자세히 표시합니다. 태그 이름은 여전히 표준 출력으로 출력됩니다.

`--long`::
	태그와 일치하는 경우에도 항상 긴 형식(태그, 커밋 수 및 축약된 커밋 이름)을 출력합니다. 이는 커밋 개체가 태그된 버전인 경우에도 "describe" 출력의 커밋 객체 이름 부분을 보고 싶을 때 유용합니다. 태그 이름만 방출하는 대신, v1.2-0-gdeadbee (tag v1.2부터 0번째 커밋, deadbee 객체를 가리킴...)와 같이 해당 커밋을 설명합니다.

`--match <pattern>`::
	"refs/tags/" 접두사를 제외하고 주어진 `glob`(7) 패턴과 일치하는 태그만 고려합니다. `--all`과 함께 사용하면 패턴과 일치하는 로컬 브랜치 및 원격 추적 참조도 고려하며, 각각 "refs/heads/" 및 "refs/remotes/" 접두사를 제외합니다. 다른 유형의 참조는 고려되지 않습니다. 여러 번 주어진 경우 패턴 목록이 누적되고, 패턴 중 하나와 일치하는 태그가 고려됩니다. 패턴 목록을 지우고 재설정하려면 `--no-match`를 사용하십시오.

`--exclude <pattern>`::
	"refs/tags/" 접두사를 제외하고 주어진 `glob`(7) 패턴과 일치하는 태그를 고려하지 않습니다. `--all`과 함께 사용하면 패턴과 일치하는 로컬 브랜치 및 원격 추적 참조도 고려하지 않으며, 각각 "`refs/heads/`" 및 "`refs/remotes/`" 접두사를 제외합니다. 다른 유형의 참조는 고려되지 않습니다. 여러 번 주어진 경우 패턴 목록이 누적되고, 패턴 중 하나와 일치하는 태그가 제외됩니다. `--match`와 함께 사용하면 태그는 적어도 하나의 `--match` 패턴과 일치하고 `--exclude` 패턴과 일치하지 않을 때 고려됩니다. 패턴 목록을 지우고 재설정하려면 `--no-exclude`를 사용하십시오.

`--always`::
	대체로 고유하게 축약된 커밋 객체를 표시합니다.

`--first-parent`::
	병합 커밋을 만날 때 첫 번째 부모 커밋만 따릅니다. 대상 커밋의 기록에 병합된 브랜치의 태그와 일치하지 않기를 원할 때 유용합니다.

EXAMPLES
--------

git.git 현재 트리와 같은 경우:

	[torvalds@g5 git]$ git describe parent
	v1.0.4-14-g2414721

즉, "parent" 브랜치의 현재 헤드는 v1.0.4를 기반으로 하지만, 그 위에 몇 개의 커밋이 있으므로 describe는 추가 커밋 수("14")와 커밋 자체의 축약된 객체 이름("2414721")을 끝에 추가했습니다.

추가 커밋 수는 `git log v1.0.4..parent`로 표시되는 커밋 수입니다. 해시 접미사는 "`-g`" + parent의 팁 커밋(이것은 `2414721b194453f058079d897d13c4e377f92dc6`였음)의 모호하지 않은 약어입니다. 약어의 길이는 저장소가 커짐에 따라 확장되며, 저장소의 대략적인 객체 수와 생일 역설 주변의 약간의 수학을 사용하고 기본적으로 최소 7을 사용합니다. "g" 접두사는 "git"을 의미하며, 소프트웨어가 관리되는 SCM에 따라 소프트웨어 버전을 설명할 수 있도록 합니다. 이는 사람들이 다른 SCM을 사용할 수 있는 환경에서 유용합니다.

태그 이름에 `git describe`를 수행하면 태그 이름만 표시됩니다:

	[torvalds@g5 git]$ git describe v1.0.4
	v1.0.4

`--all`을 사용하면 명령은 브랜치 헤드를 참조로 사용할 수 있으므로 출력은 참조 경로도 표시합니다:

	[torvalds@g5 git]$ git describe --all --abbrev=4 v1.0.5^2
	tags/v1.0.0-21-g975b

	[torvalds@g5 git]$ git describe --all --abbrev=4 HEAD^
	heads/lt/describe-7-g975b

`--abbrev`를 0으로 설정하면 명령을 사용하여 접미사 없이 가장 가까운 태그 이름을 찾을 수 있습니다:

	[torvalds@g5 git]$ git describe --abbrev=0 v1.0.5^2
	tags/v1.0.0

참고로 지금 이 명령을 실행했을 때 Linus가 본 것보다 지금 이 명령을 실행했을 때 얻는 접미사가 더 길 수 있습니다. 귀하의 Git 저장소에는 975b로 시작하는 새 커밋이 있을 수 있으며, 이는 그 당시에 존재하지 않았고, "-g975b" 접미사만으로는 이러한 커밋을 구별하기에 충분하지 않을 수 있습니다.


SEARCH STRATEGY
---------------

각 커밋-이시에 대해, `git describe`는 먼저 해당 커밋을 정확히 태그하는 태그를 찾습니다. 주석 태그는 항상 경량 태그보다 선호되며, 더 최신 날짜의 태그는 항상 이전 날짜의 태그보다 선호됩니다. 정확한 일치가 발견되면 해당 이름이 출력되고 검색이 중지됩니다.

정확한 일치가 발견되지 않으면, `git describe`는 커밋 기록을 거슬러 올라가 태그된 조상 커밋을 찾습니다. 조상의 태그가 입력 커밋-이시의 SHA-1 약어와 함께 출력됩니다. `--first-parent`가 지정되면 워크는 각 커밋의 첫 번째 부모만 고려합니다.

워크 중에 여러 태그가 발견되면, 입력 커밋-이시와 가장 적은 커밋이 다른 태그가 선택되고 출력됩니다. 여기서 가장 적은 커밋이 다른 것은 `git log tag..input`으로 표시될 커밋 수가 가능한 가장 작은 수로 정의됩니다.

BUGS
----

트리 객체와 커밋을 가리키지 않는 태그 객체는 설명할 수 없습니다. blob을 설명할 때, blob을 가리키는 경량 태그는 무시되지만, 경량 태그가 선호됨에도 불구하고 blob은 `<commit-ish>:<path>`로 설명됩니다.

GIT
---
linkgit:git[1] 스위트의 일부