git-refs(1)
===========

NAME
----
git-refs - 낮음 수준의 ref 접근


SYNOPSIS
--------
[synopsis]
git refs migrate --ref-format=<format> [--no-reflog] [--dry-run]
git refs verify [--strict] [--verbose]
git refs list [--count=<count>] [--shell|--perl|--python|--tcl]
		   [(--sort=<key>)...] [--format=<format>]
		   [--include-root-refs] [--points-at=<object>]
		   [--merged[=<object>]] [--no-merged[=<object>]]
		   [--contains[=<object>]] [--no-contains[=<object>]]
		   [(--exclude=<pattern>)...] [--start-after=<marker>]
		   [ --stdin | (<pattern>...)]
git refs exists <ref>
git refs optimize [--all] [--no-prune] [--auto] [--include <pattern>] [--exclude <pattern>]

DESCRIPTION
-----------

이 명령은 ref에 대한 낮은 수준의 접근을 제공합니다.

COMMANDS
--------

`migrate`::
	Ref 저장소를 다른 형식으로 마이그레이션합니다.

`verify`::
	참조 데이터베이스의 일관성을 검증합니다.

list::
	필터링, 형식 지정 및 정렬을 지원하여 저장소의 참조를 나열합니다. 이 하위 명령은
	linkgit:git-for-each-ref[1]의 별칭이며 동일한 기능을 제공합니다.

exists::
	주어진 참조가 존재하는지 확인합니다. 존재하면 종료 코드가 0이고,
	누락된 경우 2이고, 참조 누락 이외의 오류로 인해 참조 조회에 실패한 경우 1입니다.
	이것은 참조가 실제 객체로 해결되는지 여부를 확인하지는 않습니다.

optimize::
	저장소 성능을 개선하고 디스크 사용량을 줄이기 위해 참조를 최적화합니다.
	이 하위 명령은 linkgit:git-pack-refs[1]의 별칭이며
	동일한 기능을 제공합니다.

OPTIONS
-------

다음 옵션은 `git refs migrate`에 특화되어 있습니다:

`--ref-format=<format>`::
	Ref 저장소를 마이그레이션할 Ref 형식입니다. 다음 중 하나가 될 수 있습니다:
+
include::ref-storage-format.adoc[]

`--dry-run`::
	마이그레이션을 수행하지만 저장소를 수정하지는 않습니다. 마이그레이션된
	ref는 별도로 검사할 수 있는 별도의 디렉토리에 기록됩니다. 디렉토리 이름은 stdout으로 보고됩니다.
	실제 마이그레이션을 수행하기 전에 마이그레이션이 예상대로 작동하는지
	다시 확인하는 데 사용할 수 있습니다.

`--reflog`::
`--no-reflog`::
	Reflog 데이터를 새 백엔드로 마이그레이션할지 또는
	폐기할지를 선택합니다. 기본값은 마이그레이션하는 "--reflog"입니다.

다음 옵션은 `git refs verify`에 특화되어 있습니다:

`--strict`::
	더 엄격한 오류 검사를 활성화합니다. 이렇게 하면 경고가 오류로 보고됩니다.
	linkgit:git-fsck[1]을 참조하십시오.

`--verbose`::
	참조 데이터베이스의 일관성을 검증할 때 상세하게 출력합니다.

다음 옵션은 'git refs list'에 특화되어 있습니다:

include::for-each-ref-options.adoc[]

다음 옵션은 'git refs optimize'에 특화되어 있습니다:

include::pack-refs-options.adoc[]

알려진 제한 사항
-----------------

Ref 형식 마이그레이션은 현재 다음과 같은 몇 가지 알려진 제한 사항이 있습니다:

* 작업 트리(worktree)가 있는 저장소를 마이그레이션하는 것은 불가능합니다.

* 진행 중인 마이그레이션 중에 저장소에 대한 동시 쓰기를 차단할 방법이 없습니다.
	동시 쓰기는 불일치한 마이그레이션 상태로 이어질 수 있습니다. 사용자는
	더 높은 수준에서 쓰기를 차단해야 합니다. 저장소가 예약된 유지 관리를 위해 등록된 경우,
	먼저 git-maintenance(1)으로 등록 해제하는 것이 좋습니다.

이러한 제한 사항은 결국 해제될 수 있습니다.

GIT
---
linkgit:git[1] 스위트의 일부