git-gc(1)
=========

NAME
----
git-gc - 불필요한 파일을 정리하고 로컬 저장소를 최적화합니다.


SYNOPSIS
--------
[verse]
'git gc' [--aggressive] [--auto] [--[no-]detach] [--quiet] [--prune=<date> | --no-prune] [--force] [--keep-largest-pack]

DESCRIPTION
-----------
현재 저장소 내에서 여러 가지 정리 작업을 실행합니다. 예를 들어 파일 리비전을 압축하여(디스크 공간을 줄이고 성능을 향상시키기 위해) 도달할 수 없는 객체를 제거합니다. 도달할 수 없는 객체는 'git add'의 이전 호출에서 생성되었을 수 있습니다. ref를 패킹하고, reflog, rerere 메타데이터 또는 오래된 워킹 트리를 정리합니다. 또한 commit-graph와 같은 보조 인덱스를 업데이트할 수도 있습니다.

객체를 생성하는 일반적인 porcelain 작업이 실행될 때, 저장소가 마지막 유지보수 이후 상당히 커졌는지 확인하고, 그렇다면 `git gc`를 자동으로 실행합니다. 이 동작을 비활성화하는 방법에 대해서는 아래 `gc.auto`를 참조하십시오.

`git gc`를 수동으로 실행하는 것은 저장소에 객체를 추가할 때 정기적으로 이러한 porcelain 명령을 실행하지 않거나, 일회성 저장소 최적화를 수행하거나, 예를 들어 최적이 아닌 대량 가져오기(mass-import)를 정리해야 할 때만 필요합니다. 가져오기 사례에 대한 자세한 내용은 linkgit:git-fast-import[1]의 "PACKFILE OPTIMIZATION" 섹션을 참조하십시오.

OPTIONS
-------

--aggressive::
	일반적으로 'git gc'는 매우 빠르게 실행되면서도 디스크 공간 활용과 성능을 좋게 유지합니다. 이 옵션은 'git gc'가 저장소를 훨씬 더 많이 최적화하도록 만들며, 이는 훨씬 더 많은 시간을 소모하게 됩니다. 이 최적화의 효과는 대부분 영구적입니다. 자세한 내용은 아래 "AGGRESSIVE" 섹션을 참조하십시오.

--auto::
	이 옵션을 사용하면 'git gc'는 어떤 유지보수가 필요한지 확인합니다. 필요하지 않으면 아무 작업도 수행하지 않고 종료합니다.
+
이 휴리스틱이 작동하는 방식에 대해서는 아래 "CONFIGURATION" 섹션의 `gc.auto` 옵션을 참조하십시오.
+
`gc.auto` 및 `gc.autoPackLimit`과 같은 구성 옵션의 한계를 초과하여 유지보수가 트리거되면, 다른 모든 유지보수 작업(예: rerere, 워킹 트리, reflog 등)도 수행됩니다.

--detach::
--no-detach::
	시스템이 지원하는 경우 백그라운드에서 실행합니다. 이 옵션은 `gc.autoDetach` 설정을 재정의합니다.

--cruft::
--no-cruft::
	도달할 수 없는 객체를 만료시킬 때, 별도의 cruft 팩으로 패킹하여(loose object로 저장하는 대신) 저장합니다. `--cruft`는 기본적으로 활성화되어 있습니다.

--max-cruft-size=<n>::
	도달할 수 없는 객체를 cruft 팩으로 패킹할 때, 새 cruft 팩의 크기를 최대 `<n>` 바이트로 제한합니다. `gc.maxCruftSize` 구성을 통해 지정된 모든 값을 재정의합니다. linkgit:git-repack[1]의 `--max-cruft-size` 옵션을 참조하십시오.

--expire-to=<dir>::
	도달할 수 없는 객체를 cruft 팩으로 패킹할 때, 정리된 객체(있는 경우)를 포함하는 cruft 팩을 `<dir>` 디렉토리에 씁니다. 이 옵션은 `--cruft`와 함께 사용될 때만 효과가 있습니다. linkgit:git-repack[1]의 `--expire-to` 옵션에 대한 자세한 내용은 참조하십시오.

--prune=<date>::
	날짜(기본값은 2주 전, `gc.pruneExpire` 설정 변수로 재정의 가능)보다 오래된 loose object를 정리합니다.
	--prune=now는 객체의 나이와 관계없이 loose object를 정리하며, 다른 프로세스가 저장소에 동시에 쓰고 있는 경우 손상 위험을 증가시킵니다. "NOTES" 섹션을 참조하십시오. --prune은 기본적으로 활성화되어 있습니다.

--no-prune::
	loose object를 정리하지 않습니다.

--quiet::
	모든 진행 상황 보고를 억제합니다.

--force::
	이 저장소에서 다른 `git gc` 인스턴스가 실행 중일 수 있더라도 `git gc`를 강제로 실행합니다.

--keep-largest-pack::
	가장 큰 non-cruft 팩, `.keep` 파일이 표시된 팩, cruft 팩을 제외한 모든 팩이 단일 팩으로 통합됩니다. 이 옵션을 사용하면 `gc.bigPackThreshold`는 무시됩니다.

AGGRESSIVE
----------

`--aggressive` 옵션이 제공되면, linkgit:git-repack[1]은 `-f` 플래그와 함께 호출되며, 이는 다시 linkgit:git-pack-objects[1]에 `--no-reuse-delta`를 전달합니다. 이렇게 하면 기존의 모든 델타가 폐기되고 다시 계산되며, 이는 패킹 시간 훨씬 더 오래 소요되는 대가로 이루어집니다.

이것의 효과는 대부분 영구적입니다. 예를 들어 팩과 loose object가 다른 팩으로 통합될 때 해당 팩의 기존 델타는 재사용될 수 있지만, 더 최적화되지 않은 델타를 더 새 팩에서 선택하는 등 다양한 경우가 있습니다.

또한, `--aggressive`를 제공하면 linkgit:git-repack[1]에 전달되는 `--depth` 및 `--window` 옵션이 조정됩니다. 아래 `gc.aggressiveDepth` 및 `gc.aggressiveWindow` 설정을 참조하십시오. 더 큰 윈도우 크기를 사용하면 더 최적화된 델타를 찾을 가능성이 높아집니다.

해당 저장소에서 맞춤형 성능 벤치마크를 실행하지 않고 이 옵션을 사용하는 것은 가치가 없을 것입니다. 훨씬 더 많은 시간이 소요되며, 결과적인 공간/델타 최적화가 그만한 가치가 있을 수도 있고 그렇지 않을 수도 있습니다. 이 옵션을 전혀 사용하지 않는 것이 대부분의 사용자와 그들의 저장소에 올바른 절충안입니다.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/gc.adoc[]

NOTES
-----

'git gc'는 저장소의 어느 곳에서도 참조되지 않는 객체를 삭제하지 않도록 매우 노력합니다. 특히, 현재 브랜치 및 태그 세트에서 참조하는 객체뿐만 아니라 인덱스, 원격 추적 브랜치, reflog(나중에 수정되거나 되돌려진 브랜치의 커밋을 참조할 수 있음) 및 refs/* 네임스페이스의 다른 모든 항목에서 참조하는 객체도 유지합니다. 'git notes'와 같은 노트가 객체에 첨부되어도 해당 객체를 살아있게 유지하는 데 기여하지 않습니다. 일부 객체가 삭제될 것으로 예상했는데 삭제되지 않았다면, 해당 모든 위치를 확인하고 해당 참조를 제거하는 것이 자신의 경우에 타당한지 결정하십시오.

반면에 'git gc'가 다른 프로세스와 동시에 실행될 때, 다른 프로세스가 사용하지만 아직 참조를 생성하지 않은 객체를 삭제할 위험이 있습니다. 이로 인해 다른 프로세스가 실패하거나, 다른 프로세스가 나중에 삭제된 객체에 대한 참조를 추가하는 경우 저장소가 손상될 수 있습니다. Git에는 이 문제를 크게 완화하는 두 가지 기능이 있습니다.

. `--prune` 날짜보다 최신 수정 시간이 있는 모든 객체는 해당 객체에서 도달 가능한 모든 것과 함께 유지됩니다.

. 데이터베이스에 객체를 추가하는 대부분의 작업은 객체가 이미 존재하는 경우 객체의 수정 시간을 업데이트하여 #1이 적용되도록 합니다.

그러나 이러한 기능은 완전한 해결책에는 미치지 못하므로, 명령을 동시에 실행하는 사용자는 일부 손상 위험을 감수해야 합니다(실제로는 낮아 보입니다).

HOOKS
-----

'git gc --auto' 명령은 'pre-auto-gc' 훅을 실행합니다. 자세한 내용은 linkgit:githooks[5]를 참조하십시오.


SEE ALSO
--------
linkgit:git-prune[1]
linkgit:git-reflog[1]
linkgit:git-repack[1]
linkgit:git-rerere[1]

GIT
---
linkgit:git[1] 제품군의 일부