git-fsmonitor{litdd}daemon(1)
=============================

NAME
----
git-fsmonitor--daemon - 내장 파일시스템 모니터

SYNOPSIS
--------
[verse]
'git fsmonitor{litdd}daemon' start
'git fsmonitor{litdd}daemon' run
'git fsmonitor{litdd}daemon' stop
'git fsmonitor{litdd}daemon' status

DESCRIPTION
-----------

플랫폼별 파일시스템 알림 기능을 사용하여 워킹 디렉터리의 파일 및 디렉터리
변경 사항을 감시하는 데몬입니다.

이 데몬은 `git status`와 같은 명령과 직접 통신하며, 느린 linkgit:githooks[5] 인터페이스 대신
link:technical/api-simple-ipc.html[simple IPC] 인터페이스를 사용합니다.

이 데몬은 Git에 내장되어 있어 서드파티 도구가 필요하지 않습니다.

OPTIONS
-------

start::
	백그라운드에서 데몬을 시작합니다.

run::
	포그라운드에서 데몬을 실행합니다.

stop::
	현재 워킹 디렉터리에서 실행 중인 데몬이 있는 경우 중지합니다.

status::
	데몬이 현재 워킹 디렉터리를 감시하고 있다면 0으로 종료됩니다.

REMARKS
-------

이 데몬은 단일 워킹 디렉터리를 감시하고 최근 변경된 파일 및 디렉터리 목록을 유지 관리하는 데 사용되는 장기 실행 프로세스입니다. `git status`와 같은 명령은
먼저 워킹 디렉터리의 변경 사항 요약을 요청하고 디스크를 스캔하는 것을 피할 수 있다면 성능이 향상될 수 있습니다.

`core.fsmonitor`가 `true`로 설정되면 (linkgit:git-config[1] 참조), `git status`와 같은 명령은
데몬에게 변경 사항을 요청하고 (필요한 경우) 자동으로 시작합니다.

자세한 내용은 linkgit:git-update-index[1]의 "File System Monitor" 섹션을 참조하세요.

CAVEATS
-------

fsmonitor 데몬은 현재 하위 모듈을 인식하지 못하며 하위 모듈 내에서 발생하는 파일시스템 이벤트를 필터링하는 방법을 알지 못합니다.
fsmonitor 데몬이 슈퍼 레포를 감시하고 있고 파일이 하위 모듈의 워킹 디렉터리 내에서 수정되면, 해당 변경 사항을 (슈퍼 레포에 대한 변경으로) 보고합니다.
하지만 클라이언트는 이러한 추가 이벤트를 올바르게 무시하므로 성능에 영향을 줄 수는 있지만, 잘못된 결과는 발생하지 않습니다.

기본적으로 fsmonitor 데몬은 네트워크에 마운트된 저장소를 사용하는 것을 거부합니다. 이는 `fsmonitor.allowRemote`를
`true`로 설정하여 무시할 수 있습니다. 하지만 fsmonitor 데몬은 모든 네트워크에 마운트된 저장소에서 올바르게 작동한다고 보장되지 않으므로, 이러한 사용은 실험적인 것으로 간주됩니다.

Mac OS에서는 Git 명령과 fsmonitor 데몬 간의 프로세스 간 통신(IPC)이 Unix 도메인 소켓(UDS)을 통해 이루어집니다. UDS는 특수 유형의 파일로,
네이티브 Mac OS 파일 시스템에서 지원되지만 네트워크에 마운트된 파일 시스템, NTFS 또는 FAT32에서는 지원되지 않습니다.
다른 파일 시스템은 필요한 지원을 할 수도 있고 안 할 수도 있습니다. fsmonitor 데몬은 이러한 파일 시스템에서 작동한다고 보장되지 않으며, 이러한 사용은 실험적인 것으로 간주됩니다.

기본적으로 소켓은 `.git` 디렉터리에 생성됩니다. 하지만 `.git` 디렉터리가 네트워크에 마운트된 파일 시스템에 있는 경우,
`$HOME/.git-fsmonitor-*`에 대신 생성됩니다. `$HOME` 자체가 네트워크에 마운트된 파일 시스템에 있는 경우,
소켓 파일을 생성할 Mac OS 네이티브 파일 시스템의 디렉터리 경로를 `fsmonitor.socketDir` 구성 변수로 설정해야 합니다.

위의 디렉터리 ('.git', '$HOME', 또는 `fsmonitor.socketDir`) 중 어느 것도 네이티브 Mac OS 파일 시스템에 있지 않으면,
fsmonitor 데몬은 오류를 보고하여 데몬과 현재 실행 중인 명령이 종료됩니다.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/fsmonitor--daemon.adoc[]

GIT
---
linkgit:git[1] 제품군의 일부입니다.