git-hash-object(1)
==================

NAME
----
git-hash-object - Compute object ID and optionally create an object from a file


SYNOPSIS
--------
[verse]
'git hash-object' [-t <type>] [-w] [--path=<file> | --no-filters]
		[--stdin [--literally]] [--] <file>...
'git hash-object' [-t <type>] [-w] --stdin-paths [--no-filters]

DESCRIPTION
-----------
지정된 타입의 객체에 대한 객체 ID 값을, 명시된 파일(워킹 트리 외부일 수 있음)의 내용으로 계산하고, 결과 객체를 선택적으로 객체 데이터베이스에 씁니다. 계산된 객체 ID를 표준 출력으로 보고합니다. <type>이 지정되지 않으면 기본값은 "blob"입니다.

OPTIONS
-------

-t <type>::
	생성할 객체의 타입을 지정합니다 (기본값: "blob"). 가능한 값은 `commit`, `tree`, `blob`, `tag`입니다.

-w::
	실제로 객체를 객체 데이터베이스에 씁니다.

--stdin::
	파일 대신 표준 입력에서 객체를 읽습니다.

--stdin-paths::
	명령줄 대신 표준 입력에서 파일 이름을 한 줄에 하나씩 읽습니다.

--path::
	주어진 경로에 있는 것처럼 객체를 해싱합니다. 파일의 위치는 해시 값에 직접적인 영향을 주지 않지만, 경로는 객체 데이터베이스에 배치되기 전에 적용될 Git 필터를 결정하는 데 사용됩니다. 필터 적용 결과, 객체 데이터베이스에 저장되는 실제 blob은 주어진 파일과 다를 수 있습니다. 이 옵션은 주로 워킹 디렉토리 외부의 임시 파일이나 표준 입력에서 읽은 파일을 해싱하는 데 유용합니다.

--no-filters::
	속성 메커니즘에 의해 선택될 입력 필터, 줄 끝 변환을 포함하여 무시하고 내용을 그대로 해싱합니다. 파일이 표준 입력에서 읽히는 경우, `--path` 옵션이 지정되지 않는 한 항상 암시됩니다.

--literally::
	`--stdin`이 표준 객체 파싱 또는 git-fsck 검사를 통과하지 못할 수 있는 쓰레기를 느슨한 객체로 해싱할 수 있도록 허용합니다. Git 자체를 스트레스 테스트하거나 실제 환경에서 발견되는 손상되거나 잘못된 객체의 특성을 재현하는 데 유용합니다.

GIT
---
linkgit:git[1] 제품군의 일부