git-merge-file(1)
=================

NAME
----
git-merge-file - 삼방향 파일 병합 실행


SYNOPSIS
--------
[verse]
'git merge-file' [-L <current-name> [-L <base-name> [-L <other-name>]]]
	[--ours|--theirs|--union] [-p|--stdout] [-q|--quiet] [--marker-size=<n>]
	[--[no-]diff3] [--object-id] <current> <base> <other>


DESCRIPTION
-----------
세 개의 파일 `<current>`, `<base>`, `<other>`가 주어졌을 때,
'git merge-file'은 `<base>`에서 `<other>`까지의 모든 변경 사항을 `<current>`에 통합합니다. 결과는 일반적으로
`<current>`로 저장됩니다. 'git merge-file'은 별도의 변경 사항을
결합하는 데 유용합니다. `<base>`가 원본이고 `<current>`와
`<other>` 둘 다 `<base>`의 수정본이라고 가정하면,
'git merge-file'은 두 변경 사항을 모두 결합합니다.

`<current>`와 `<other>` 모두가 공통 줄 세그먼트에 변경 사항이 있는 경우 충돌이 발생합니다. 충돌이 발견되면, 'git merge-file'은
일반적으로 경고를 출력하고 충돌 부분을
<<<<<<< 와 >>>>>>> 표식으로 둘러쌉니다. 일반적인 충돌은 다음과 같습니다.

	<<<<<<< A
	lines in file A
	=======
	lines in file B
	>>>>>>> B

충돌이 있는 경우, 사용자는 결과를 편집하고
대안 하나를 삭제해야 합니다. 그러나 `--ours`, `--theirs`, 또는 `--union` 옵션이 적용되는 경우,
이러한 충돌은 `<current>`의 줄, `<other>`의 줄, 또는 둘 다의 줄을 각각 선호하여 해결됩니다.
충돌 표식의 길이는 `--marker-size` 옵션으로 지정할 수 있습니다.

`--object-id`가 지정된 경우, 동일한 동작이 발생하지만,
병합 대상을 파일로 지정하는 대신
객체 ID 목록으로 지정합니다.

이 프로그램의 종료 값은 오류 시 음수이고, 그렇지 않은 경우 충돌 횟수입니다 (127개보다 많으면 127로 잘립니다).
병합이 깨끗하면 종료 값은 0입니다.

'git merge-file'은 RCS 'merge'의 최소한의 복제본으로 설계되었습니다. 즉,
linkgit:git[1]에 필요한 RCS 'merge'의 모든 기능을 구현합니다.


OPTIONS
-------

--object-id::
	병합할 내용을 현재 저장소의 블롭으로 지정하고 파일이 아닙니다.
	이 경우, 작업은 유효한 저장소 내에서 이루어져야 합니다.
+
`-p` 옵션이 지정되면, 병합된 파일(충돌 포함)은
평소와 같이 표준 출력으로 전송됩니다. 그렇지 않으면, 병합된 파일은
객체 저장소에 기록되고 해당 블롭의 객체 ID가 표준 출력에 기록됩니다.

-L <label>::
	이 옵션은 최대 세 번까지 지정할 수 있으며,
	충돌 보고서에서 해당 파일 이름 대신 사용될 레이블을
	지정합니다. 즉,
	`git merge-file -L x -L y -L z a b c`는
	a, b, c 파일 대신
	x, y, z 파일에서 나온 것처럼 보이는 출력을 생성합니다.

-p::
	결과를 `<current>`를 덮어쓰는 대신 표준 출력으로 보냅니다.

-q::
	조용함; 충돌에 대해 경고하지 않습니다.

--diff3::
	"diff3" 스타일로 충돌을 표시합니다.

--zdiff3::
	"zdiff3" 스타일로 충돌을 표시합니다.
+
`--diff3` 및 `--zdiff3` 옵션은 `merge.conflictStyle`
구성 변수의 값으로 기본 설정됩니다 (linkgit:git-config[1] 참조).

--ours::
--theirs::
--union::
	파일에 충돌을 남겨두는 대신, 우리 (또는 그들 또는 둘 다) 쪽의 줄을 선호하여 충돌을 해결합니다.

--diff-algorithm={patience|minimal|histogram|myers}::
	병합 중에 다른 diff 알고리즘을 사용합니다. 현재 기본값은 "myers"이지만,
	"histogram"과 같이 더 최신 알고리즘을 선택하면
	중요하지 않은 일치하는 줄(예: 다른 함수의 중괄호)로 인해 발생하는 잘못된 병합을
	피하는 데 도움이 될 수 있습니다. linkgit:git-diff[1] `--diff-algorithm`도 참조하십시오.

EXAMPLES
--------

`git merge-file README.my README README.upstream`::

	README을 기준으로 README.my와 README.upstream의 변경 사항을 결합하고,
	병합을 시도한 후 결과를 README.my에 씁니다.

`git merge-file -L a -L b -L c tmp/a123 tmp/b234 tmp/c345`::

	tmp/b234를 기준으로 tmp/a123과 tmp/c345를 병합하지만,
	레이블 `a`와 `c`를 tmp/a123과 tmp/c345 대신 사용합니다.

`git merge-file -p --object-id abc1234 def567 890abcd`::

	def567을 기준으로 블롭 abc1234와 890abcd의 변경 사항을 결합하고,
	병합을 시도한 후 결과를 표준 출력에 씁니다.

GIT
---
linkgit:git[1] 도구 모음의 일부