git-http-push(1)
================

NAME
----
git-http-push - HTTP/DAV를 통해 다른 저장소로 객체를 푸시

SYNOPSIS
--------
[verse]
'git http-push' [--all] [--dry-run] [--force] [--verbose] <URL> <ref> [<ref>...]

DESCRIPTION
-----------
로컬 저장소에 없는 객체를 원격 저장소로 보내고, 원격 브랜치를 업데이트합니다.

*주의*: libcurl 버전이 7.16보다 이전인 경우 이 명령어는 일시적으로 비활성화됩니다. 해당 조합은 작동하지 않고 저장소가 손상될 수 있다는 보고가 있습니다.

OPTIONS
-------
--all::
	원격 저장소가 현재 상태로 완전하다고 가정하지 않고, 지역 ref의 전체 기록에 있는 모든 객체의 존재 여부를 원격 저장소에서 확인합니다.

--force::
	일반적으로 이 명령어는 덮어쓰는 데 사용된 지역 ref의 조상이 아닌 원격 ref를 업데이트하는 것을 거부합니다.
	이 플래그는 해당 검사를 비활성화합니다. 이는 원격 저장소에서 커밋이 손실될 수 있음을 의미하므로 주의해서 사용하십시오.

--dry-run::
	업데이트를 실제로 보내는 것을 제외한 모든 작업을 수행합니다.

--verbose::
	로컬에서 탐색 중인 객체 목록과 원격 저장소로 성공적으로 전송된 객체 목록을 보고합니다.

-d::
-D::
	원격 저장소에서 <ref>를 제거합니다. 지정된 브랜치는 원격 HEAD가 될 수 없습니다. -d가 지정된 경우 다음의 다른 조건도 충족되어야 합니다.

	- 원격 HEAD는 로컬에 있는 객체로 해석되어야 합니다.
	- 지정된 브랜치는 로컬에 있는 객체로 해석되어야 합니다.
	- 지정된 브랜치는 원격 HEAD의 조상이어야 합니다.

<ref>...::
	업데이트할 원격 ref입니다.

SPECIFYING THE REFS
-------------------

'<ref>' 명세는 단일 패턴이거나 콜론 ':'으로 구분된 두 패턴의 쌍일 수 있습니다 (이는 ref 이름에 콜론이 포함될 수 없음을 의미합니다). 단일 패턴 '<name>'은 '<name>:<name>'의 약어입니다.

각 패턴 쌍 '<src>:<dst>'는 콜론 앞의 소스 측과 콜론 뒤의 대상 측으로 구성됩니다. 푸시될 ref는 소스 측과 일치하는 것을 찾아 결정되며, 대상 측을 사용하여 푸시될 위치가 결정됩니다.

 - '<src>'가 지역 ref 중 정확히 하나와 일치하지 않으면 오류입니다.

 - '<dst>'가 어떤 원격 ref와도 일치하지 않으면, 다음 중 하나여야 합니다.

   * "refs/"로 시작해야 합니다. 이 경우 '<dst>'는 대상으로 문자 그대로 사용됩니다.

   * <src> == <dst>이고 <src>와 일치하는 ref가 원격 ref 집합에 존재하지 않아야 합니다. <src>와 일치하는 ref가 대상 이름으로 사용됩니다.

--force 없이, <dst>가 존재하지 않거나 <dst>가 <src>의 올바른 부분 집합(즉, 조상)인 경우에만 <src> ref가 원격지에 저장됩니다. "fast-forward check"라고 알려진 이 검사는 원격 ref를 실수로 덮어쓰고 다른 사람의 커밋을 거기서 잃어버리는 것을 방지하기 위해 수행됩니다.

--force와 함께 사용하면 모든 ref에 대한 fast-forward check가 비활성화됩니다.

선택적으로, <ref> 매개변수에 '+' 기호를 접두사로 붙여 해당 ref에 대해서만 fast-forward check를 비활성화할 수 있습니다.

GIT
---
linkgit:git[1] 제품군의 일부