git-switch(1)
=============

NAME
----
git-switch - 브랜치 전환

SYNOPSIS
--------
[synopsis]
git switch [<options>] [--no-guess] <branch>
git switch [<options>] --detach [<start-point>]
git switch [<options>] (-c|-C) <new-branch> [<start-point>]
git switch [<options>] --orphan <new-branch>

DESCRIPTION
-----------
지정된 브랜치로 전환합니다. 워킹 트리와 인덱스가 브랜치에 맞게 업데이트됩니다. 모든 새 커밋은 이 브랜치의 최상단에 추가됩니다.

옵션으로, `-c`, `-C`를 사용하거나, 동일한 이름을 가진 원격 브랜치에서 자동으로( `--guess` 참조), 또는 `--detach`를 사용하여 새 브랜치를 생성하고 전환할 수 있습니다.

브랜치로의 전환은 깨끗한 인덱스와 워킹 트리가 필요하지 않습니다 (즉, `HEAD`와 비교하여 차이가 없는 경우). 그러나 작업이 로컬 변경 사항의 손실을 초래하는 경우, `--discard-changes` 또는 `--merge` 옵션으로 명시하지 않는 한 작업이 중단됩니다.

OPTIONS
-------
_<branch>_::
	전환할 브랜치.

_<new-branch>_::
	새 브랜치의 이름.

_<start-point>_::
	새 브랜치의 시작점. _<start-point>_를 지정하면 `HEAD`가 현재 가리키는 지점 외의 다른 기록 지점을 기반으로 브랜치를 만들 수 있습니다. (또는 `--detach`의 경우, 다른 지점에서 분리하여 검사할 수 있습니다.)
+
`git switch` 또는 `git checkout` 작업으로 전환했던 _<N>_번째 이전 브랜치/커밋을 참조하기 위해 `@{-<N>}` 구문을 사용할 수 있습니다. `-`는 `@{-1}`과 동의어입니다. 이는 종종 두 브랜치 간의 빠른 전환이나 실수로 브랜치 전환을 취소하는 데 사용됩니다.
+
특별한 경우로, _<rev-a>_와 _<rev-b>_의 머지 베이스에 대한 바로 가기로 `<rev-a>...<rev-b>`를 사용할 수 있습니다. 단, 이때 머지 베이스가 정확히 하나 존재해야 합니다. _<rev-a>_와 _<rev-b>_ 중 최대 하나를 생략할 수 있으며, 이 경우 기본값은 `HEAD`입니다.

`-c <new-branch>`::
`--create <new-branch>`::
	_<start-point>_에서 시작하는 _<new-branch>_라는 새 브랜치를 생성한 후 해당 브랜치로 전환합니다. 이는 다음의 트랜잭션적 등가물입니다.
+
------------
$ git branch <new-branch>
$ git switch <new-branch>
------------
+
즉, 브랜치가 다른 작업 트리에서 사용 중인 경우와 같이 `git switch`가 성공하지 않으면 브랜치가 재설정/생성되지 않습니다 (현재 브랜치가 동일하게 유지되는 것뿐만 아니라, 브랜치가 start-point로 재설정되지도 않습니다).

`-C <new-branch>`::
`--force-create <new-branch>`::
	`--create`와 유사하지만, _<new-branch>_가 이미 존재하는 경우 _<start-point>_로 재설정됩니다. 다음의 편리한 바로 가기입니다.
+
------------
$ git branch -f _<new-branch>_
$ git switch _<new-branch>_
------------

`-d`::
`--detach`::
	검사 및 폐기 가능한 실험을 위해 커밋으로 전환합니다. 자세한 내용은 linkgit:git-checkout[1]의 "DETACHED HEAD" 섹션을 참조하십시오.

`--guess`::
`--no-guess`::
	_<branch>_를 찾을 수 없지만, 정확히 하나의 리모트( _<remote>_이라고 부름)에 이름이 일치하는 추적 브랜치가 존재하는 경우, 다음의 등가물로 처리됩니다.
+
------------
$ git switch -c <branch> --track <remote>/<branch>
------------
+
브랜치가 여러 리모트에서 존재하고 그 중 하나가 `checkout.defaultRemote` 구성 변수로 이름이 지정된 경우, _<branch>_가 모든 리모트에서 고유하지 않더라도 모호성 해소를 위해 해당 리모트를 사용합니다. `checkout.defaultRemote=origin` 등으로 설정하여 _<branch>_가 모호하지만 'origin' 리모트에 존재하는 경우 항상 거기서 원격 브랜치를 가져오도록 합니다. 자세한 내용은 linkgit:git-config[1]의 `checkout.defaultRemote`도 참조하십시오.
+
`--guess`가 기본 동작입니다. 이를 비활성화하려면 `--no-guess`를 사용하십시오.
+
기본 동작은 `checkout.guess` 구성 변수를 통해 설정할 수 있습니다.

`-f`::
`--force`::
	`--discard-changes`의 별칭입니다.

`--discard-changes`::
	인덱스나 워킹 트리가 `HEAD`와 다른 경우에도 진행합니다. 인덱스와 워킹 트리는 모두 전환 대상에 맞게 복원됩니다. `--recurse-submodules`가 지정된 경우, 서브모듈 내용도 전환 대상에 맞게 복원됩니다. 이는 로컬 변경 사항을 버리는 데 사용됩니다.

`-m`::
`--merge`::
	현재 브랜치와 전환하려는 브랜치 간에 변경된 하나 이상의 파일에 대한 로컬 수정 사항이 있는 경우, 일반적으로 명령은 수정을 보존하기 위해 브랜치 전환을 거부합니다. 그러나 이 옵션을 사용하면 충돌하는 로컬 수정 사항이 전환 전에 자동으로 스태시(stash)되고 이후에 다시 적용됩니다. 로컬 수정 사항이 브랜치 간의 차이점과 겹치지 않으면 스태시 없이 전환이 진행됩니다. 스태시 재적용 시 충돌이 발생하면 해당 항목은 스태시 목록에 저장됩니다. 충돌을 해결하고 완료되면 `git stash drop`을 실행하거나, 나중에 변경 사항을 다시 적용하기 위해 (예: `git reset --hard`로) 워킹 트리를 정리한 다음 `git stash pop`을 실행합니다.

`--conflict=<style>`::
	위의 `--merge` 옵션과 동일하지만, 충돌하는 덩어리(hunks)가 표시되는 방식을 변경하고 `merge.conflictStyle` 구성 변수를 재정의합니다. 가능한 값은 `merge` (기본값), `diff3`, `zdiff3`입니다.

`-q`::
`--quiet`::
	조용하게, 피드백 메시지를 억제합니다.

`--progress`::
`--no-progress`::
	진행 상태는 기본적으로 터미널에 연결되어 있는 경우 표준 오류 스트림에 보고됩니다. `--quiet`가 지정된 경우는 제외합니다. 이 플래그는 터미널에 연결되어 있지 않더라도, `--quiet` 여부에 관계없이 진행 상태 보고를 활성화합니다.

`-t`::
`--track[ (direct|inherit)]`::
	새 브랜치를 생성할 때 "업스트림" 구성을 설정합니다. `-c`가 암시됩니다. 자세한 내용은 linkgit:git-branch[1]의 `--track`을 참조하십시오.
+
`-c` 옵션이 주어지지 않으면, 새 브랜치의 이름은 해당 리모트의 refspec의 로컬 부분에서 파생된 원격 추적 브랜치에서 파생됩니다. 그런 다음 "*"까지의 초기 부분을 제거합니다. 이는 `origin/hack` (또는 `remotes/origin/hack`, 또는 `refs/remotes/origin/hack`)에서 분기할 때 `hack`을 로컬 브랜치로 사용하도록 합니다. 주어진 이름에 슬래시가 없거나 위의 추측 결과 이름이 비어 있으면 추측이 중단됩니다. 이 경우 `-c`를 사용하여 명시적으로 이름을 지정할 수 있습니다.

`--no-track`::
	`branch.autoSetupMerge` 구성 변수가 true인 경우에도 "업스트림" 구성을 설정하지 않습니다.

`--orphan <new-branch>`::
	_<new-branch>_라는 이름의 새 언본(unborn) 브랜치를 생성합니다. 추적된 모든 파일이 제거됩니다.

`--ignore-other-worktrees`::
	`git switch`는 원하는 ref가 다른 작업 트리에서 이미 체크아웃된 경우 거부합니다. 이 옵션을 사용하면 ref를 anyway로 체크아웃합니다. 즉, ref는 둘 이상의 작업 트리에서 보유될 수 있습니다.

`--recurse-submodules`::
`--no-recurse-submodules`::
	`--recurse-submodules`를 사용하면 최상위 프로젝트에 기록된 커밋에 따라 모든 활성 서브모듈의 내용이 업데이트됩니다. 아무것도 사용되지 않거나 (`--no-recurse-submodules`) 사용되지 않는 경우 서브모듈 워킹 트리가 업데이트되지 않습니다. linkgit:git-submodule[1]과 마찬가지로, 이것은 서브모듈의 `HEAD`를 분리합니다.

EXAMPLES
--------

다음 명령은 "master" 브랜치로 전환합니다:

------------
$ git switch master
------------

잘못된 브랜치에서 작업한 후, 올바른 브랜치로 전환하려면 다음을 사용합니다:

------------
$ git switch mytopic
------------

그러나, "잘못된" 브랜치와 올바른 "mytopic" 브랜치는 로컬에서 수정된 파일에서 다를 수 있으며, 이 경우 위의 전환은 실패할 것입니다:

------------
$ git switch mytopic
error: You have local changes to 'frotz'; not switching branches.
------------

명령에 `-m` 플래그를 제공하면 로컬 변경 사항이 새 브랜치로 전달됩니다:

------------
$ git switch -m mytopic
Applied autostash.
Switched to branch 'mytopic'
The following paths have local changes:
M	frotz
------------

전환 후 로컬 수정 사항은 다시 적용되며 인덱스 파일에 등록되지 않으므로 `git diff`는 새 브랜치의 최상단에서 어떤 변경 사항을 만들었는지 보여줍니다.

mytopic으로 전환하기 전의 이전 브랜치 ("master" 브랜치)로 다시 전환하려면:

------------
$ git switch -
------------

모든 커밋에서 새 브랜치를 성장시킬 수 있습니다. 예를 들어, "`HEAD~3`"으로 전환하고 "`fixup`" 브랜치를 만듭니다:

------------
$ git switch -c fixup HEAD~3
Switched to a new branch 'fixup'
------------

이름이 같은 원격 브랜치에서 새 브랜치를 시작하려면:

------------
$ git switch new-topic
Branch `new-topic` set up to track remote branch `new-topic` from `origin`
Switched to a new branch `new-topic`
------------

새 브랜치를 생성하지 않고 임시 검사 또는 실험을 위해 커밋 `HEAD~3`을 체크아웃하려면:

------------
$ git switch --detach HEAD~3
HEAD is now at 9fc9555312 Merge branch 'cc/shared-index-permbits'
------------

수행한 작업이 보존할 가치가 있다고 판단되면, 언제든지 새 이름을 지정할 수 있습니다 (전환하지 않고):

------------
$ git switch -c good-surprises
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/checkout.adoc[]

SEE ALSO
--------
linkgit:git-checkout[1],
linkgit:git-branch[1]

GIT
---
linkgit:git[1] suite의 일부