git-update-ref(1)
=================

NAME
----
git-update-ref - ref에 저장된 객체 이름을 안전하게 업데이트

SYNOPSIS
--------
[synopsis]
git update-ref [-m <reason>] [--no-deref] -d <ref> [<old-oid>]
git update-ref [-m <reason>] [--no-deref] [--create-reflog] <ref> <new-oid> [<old-oid>]
git update-ref [-m <reason>] [--no-deref] --stdin [-z] [--batch-updates]

DESCRIPTION
-----------
두 개의 인수가 주어지면, 심볼릭 ref를 해석할 수도 있는 <ref>에 <new-oid>를 저장합니다. 예를 들어, `git update-ref HEAD <new-oid>`는 현재 브랜치 헤드를 새 객체로 업데이트합니다.

세 개의 인수가 주어지면, <ref>의 현재 값이 <old-oid>와 일치하는지 확인한 후에, 심볼릭 ref를 해석할 수도 있는 <ref>에 <new-oid>를 저장합니다. 예를 들어, `git update-ref refs/heads/master <new-oid> <old-oid>`는 master 브랜치 헤드의 현재 값이 <old-oid>인 경우에만 <new-oid>로 업데이트합니다. 생성하려는 ref가 존재하지 않도록 하기 위해 40개의 "0" 또는 빈 문자열을 <old-oid>로 지정할 수 있습니다.

마지막 인수는 객체 이름입니다. 이 명령은 옵션 없이 심볼릭 ref를 다른 ref를 가리키도록 업데이트하는 것을 지원하지 않습니다 (linkgit:git-symbolic-ref[1] 참조). 하지만 `git update-ref --stdin`에는 일반 ref와 심볼릭 ref를 동일한 트랜잭션으로 커밋할 수 있는 `symref-*` 명령이 있습니다.

--no-deref가 주어지면, 심볼릭 포인터를 따르는 대신 <ref> 자체가 덮어쓰여집니다.

-d와 함께 사용하면, <old-oid>를 포함하고 있는지 확인한 후에 지정된 <ref>를 삭제합니다.

--stdin과 함께 사용하면, update-ref는 표준 입력에서 지침을 읽고 모든 수정을 함께 수행합니다. 다음과 같은 형식의 명령을 지정합니다:

	update SP <ref> SP <new-oid> [SP <old-oid>] LF
	create SP <ref> SP <new-oid> LF
	delete SP <ref> [SP <old-oid>] LF
	verify SP <ref> [SP <old-oid>] LF
	symref-update SP <ref> SP <new-target> [SP (ref SP <old-target> | oid SP <old-oid>)] LF
	symref-create SP <ref> SP <new-target> LF
	symref-delete SP <ref> [SP <old-target>] LF
	symref-verify SP <ref> [SP <old-target>] LF
	option SP <opt> LF
	start LF
	prepare LF
	commit LF
	abort LF

--create-reflog와 함께 사용하면, update-ref는 일반적으로 생성되지 않더라도 각 ref에 대해 reflog를 생성합니다.

--batch-updates와 함께 사용하면, update-ref는 업데이트를 배치로 실행하지만 개별 업데이트는 유효하지 않거나 잘못된 사용자 입력으로 인해 실패할 수 있으며 성공한 업데이트만 적용합니다. 그러나 I/O 오류 또는 메모리 문제와 같은 시스템 관련 오류는 배치 업데이트 전체 실패로 이어질 것입니다. 실패한 업데이트는 다음 형식으로 보고됩니다:

	rejected SP (<old-oid> | <old-target>) SP (<new-oid> | <new-target>) SP <rejection-reason> LF

공백을 포함하는 필드는 C 소스 코드의 문자열처럼 따옴표로 묶습니다. 즉, 큰따옴표로 둘러싸고 백슬래시 이스케이프를 사용합니다. 40개의 "0" 문자를 0 값으로 지정합니다. 누락된 값을 지정하려면 값과 이전 SP를 완전히 생략하십시오.

대안으로, -z를 사용하여 NUL로 종료되는 형식으로, 따옴표 없이 지정할 수 있습니다:

	update SP <ref> NUL <new-oid> NUL [<old-oid>] NUL
	create SP <ref> NUL <new-oid> NUL
	delete SP <ref> NUL [<old-oid>] NUL
	verify SP <ref> NUL [<old-oid>] NUL
	symref-update SP <ref> NUL <new-target> [NUL (ref NUL <old-target> | oid NUL <old-oid>)] NUL
	symref-create SP <ref> NUL <new-target> NUL
	symref-delete SP <ref> NUL [<old-target>] NUL
	symref-verify SP <ref> NUL [<old-target>] NUL
	option SP <opt> NUL
	start NUL
	prepare NUL
	commit NUL
	abort NUL

이 형식에서는 40개의 "0"을 0 값으로 지정하고 빈 문자열을 누락된 값으로 지정합니다.

두 형식 모두에서, 값은 Git이 객체 이름으로 인식하는 어떤 형태로든 지정될 수 있습니다. 다른 형식의 명령이나 반복되는 <ref>는 오류를 발생시킵니다. 명령의 의미는 다음과 같습니다:

update::
	(주어진 경우) <old-oid>를 확인한 후 <ref>를 <new-oid>로 설정합니다.
	업데이트 후 ref가 존재하지 않도록 0인 <new-oid>를 지정하거나, 업데이트 전에 ref가 존재하지 않도록 0인 <old-oid>를 지정합니다.

create::
	존재하지 않음을 확인한 후 <ref>를 <new-oid>로 생성합니다.
	주어진 <new-oid>는 0이 될 수 없습니다.

delete::
	(주어진 경우) <old-oid>를 포함하고 있음을 확인한 후 <ref>를 삭제합니다.
	주어진 경우 <old-oid>는 0이 될 수 없습니다.

symref-update::
	(주어진 경우) <old-target> 또는 <old-oid>를 확인한 후 <ref>를 <new-target>로 설정합니다.
	업데이트 전에 ref가 존재하지 않음을 보장하기 위해 0인 <old-oid>를 지정합니다.

verify::
	<ref>를 <old-oid>와 비교하여 확인하지만 변경하지는 않습니다.
	<old-oid>가 0이거나 생략된 경우 ref는 존재하지 않아야 합니다.

symref-create::
	존재하지 않음을 확인한 후 심볼릭 ref <ref>를 <new-target>로 생성합니다.

symref-delete::
	(주어진 경우) <old-target>을 포함하고 있음을 확인한 후 <ref>를 삭제합니다.

symref-verify::
	심볼릭 <ref>를 <old-target>과 비교하여 확인하지만 변경하지는 않습니다.
	<old-target>이 생략된 경우 ref는 존재하지 않아야 합니다. `no-deref` 모드에서만 사용할 수 있습니다.

option::
	<ref>를 지정하는 다음 명령의 동작을 수정합니다.
	유효한 유일한 옵션은 심볼릭 ref 해석을 피하기 위한 `no-deref`입니다.

start::
	트랜잭션을 시작합니다. 비트랜잭션 세션과 달리, 트랜잭션은 명시적인 커밋 없이 세션이 종료되면 자동으로 중단됩니다. 이 명령은 현재 트랜잭션이 이미 커밋 또는 중단된 경우 새 빈 트랜잭션을 생성할 수 있습니다.

prepare::
	트랜잭션을 커밋할 준비를 합니다. 이 명령은 큐에 있는 모든 참조 업데이트에 대한 잠금 파일을 생성합니다. 하나의 참조를 잠글 수 없는 경우 트랜잭션이 중단됩니다.

commit::
	트랜잭션에 대해 큐에 있는 모든 참조 업데이트를 커밋하고 트랜잭션을 종료합니다.

abort::
	트랜잭션을 중단하고, 트랜잭션이 준비 상태인 경우 모든 잠금을 해제합니다.

모든 <ref>를 동시에 일치하는 <old-oid>와 함께 잠글 수 있으면 모든 수정 사항이 적용됩니다. 그렇지 않으면 수정 사항은 적용되지 않습니다. 각 개별 <ref>는 원자적으로 업데이트 또는 삭제되지만, 동시 읽기는 여전히 수정 사항의 일부를 볼 수 있다는 점에 유의하십시오.

LOGGING UPDATES
---------------
"core.logAllRefUpdates" 설정 매개변수가 true이고 ref가 "refs/heads/", "refs/remotes/", "refs/notes/" 또는 HEAD 또는 ORIG_HEAD와 같은 의사 ref인 경우; 또는 "$GIT_DIR/logs/<ref>" 파일이 존재하면 `git update-ref`는 ref 값의 변경 사항을 설명하는 줄을 "$GIT_DIR/logs/<ref>" 로그 파일에 추가합니다 (로그 이름을 생성하기 전에 모든 심볼릭 ref를 해석합니다). 로그 줄 형식은 다음과 같습니다:

    oldsha1 SP newsha1 SP committer LF

여기서 "oldsha1"은 이전에 <ref>에 저장된 40자 16진수 값이고, "newsha1"은 <new-oid>의 40자 16진수 값이며, "committer"는 표준 Git 커미터 식별자 형식의 커미터 이름, 이메일 주소 및 날짜입니다.

-m 옵션과 함께 사용하면:

    oldsha1 SP newsha1 SP committer TAB message LF

여기서 모든 필드는 위에서 설명한 대로이며 "message"는 -m 옵션에 제공된 값입니다.

업데이트는 현재 사용자가 새 로그 파일을 생성할 수 없거나 기존 로그 파일에 추가할 수 없거나 커미터 정보를 사용할 수 없는 경우 (ref를 변경하지 않고) 실패합니다.

NOTES
-----

심볼릭 ref는 처음에는 심볼릭 링크를 사용하여 구현되었습니다. 이것은 모든 파일 시스템이 심볼릭 링크를 지원하는 것은 아니기 때문에 이제는 사용이 중단되었습니다.

이 명령은 "refs/"로 시작하는 경우에만 *실제* 심볼릭 링크를 따릅니다. 그렇지 않으면, 단순히 읽으려고 시도하고 일반 파일처럼 업데이트합니다 (즉, 파일 시스템이 그것들을 따르도록 허용하지만, 다른 곳의 심볼릭 링크를 일반 파일 이름으로 덮어쓸 것입니다.)

SEE ALSO
--------
linkgit:git-symbolic-ref[1]

GIT
---
linkgit:git[1] 제품군의 일부