git-archive(1)
==============

NAME
----
git-archive - Create an archive of files from a named tree


SYNOPSIS
--------
[verse]
'git archive' [--format=<fmt>] [--list] [--prefix=<prefix>/] [<extra>]
	      [-o <file> | --output=<file>] [--worktree-attributes]
	      [--remote=<repo> [--exec=<git-upload-archive>]] <tree-ish>
	      [<path>...]

DESCRIPTION
-----------
지정된 포맷으로 명명된 트리(tree)의 트리 구조를 포함하는 아카이브를 생성하여 표준 출력으로 작성합니다. <prefix>가 지정되면 아카이브 내 파일 이름 앞에 붙습니다.

'git archive'는 커밋 ID 또는 태그 ID와 달리 트리 ID가 주어졌을 때 다르게 동작합니다. 트리 ID가 제공되면 현재 시간이 아카이브 내 각 파일의 수정 시간으로 사용됩니다. 반면, 커밋 ID 또는 태그 ID가 제공되면 참조된 커밋 객체에 기록된 커밋 시간이 대신 사용됩니다. 또한 tar 포맷이 사용될 경우 커밋 ID는 전역 확장 pax 헤더에 저장되며, 'git get-tar-commit-id'를 사용하여 추출할 수 있습니다. ZIP 파일에서는 파일 주석으로 저장됩니다.

OPTIONS
-------

--format=<fmt>::
	결과 아카이브의 포맷. 가능한 값은 `tar`, `zip`, `tar.gz`, `tgz`이며
	`tar.<format>.command` 설정을 통해 정의된 모든 포맷입니다. `--format`이
	지정되지 않고 출력 파일이 지정된 경우 (예: `foo.zip`으로 작성 시 `zip` 포맷)
	파일 이름으로부터 포맷을 추론할 수 있습니다. 그렇지 않으면 출력 포맷은 `tar`입니다.

-l::
--list::
	사용 가능한 모든 포맷을 표시합니다.

-v::
--verbose::
	진행 상황을 stderr로 보고합니다.

--prefix=<prefix>/::
	아카이브 내 경로 앞에 <prefix>/를 붙입니다. 반복될 수 있으며; 가장 오른쪽에 있는 값이 모든 추적된 파일에 사용됩니다. `--add-file`에 사용되는 값은 아래를 참조하십시오.
+
<prefix>는 주어진 대로 사용되며 정규화되지 않습니다. 선행 슬래시 또는 상위 디렉토리 구성 요소(예: `../`)를 포함할 수 있습니다. 일부 아카이브 소비자는 이러한 경로를 잠재적으로 안전하지 않다고 처리하고 추출 중에 조정하거나 경고할 수 있습니다.

-o <file>::
--output=<file>::
	표준 출력 대신 <file>에 아카이브를 작성합니다.

--add-file=<file>::
	추적되지 않은 파일을 아카이브에 추가합니다. 여러 파일을 추가하기 위해 반복될 수 있습니다. 아카이브에서 파일의 경로는 이 `--add-file` 이전에 마지막으로 지정된 `--prefix` 옵션의 값(있는 경우)과 <file>의 기본 파일 이름을 연결하여 구성됩니다.

--add-virtual-file=<path>:<content>::
	지정된 내용을 아카이브에 추가합니다. 여러 파일을 추가하기 위해 반복될 수 있습니다.
+
`<path>` 인자는 리터럴 큰따옴표 문자로 시작하거나 끝날 수 있습니다. 포함된 파일 이름은 C 스타일 문자열로 해석됩니다. 즉, 백슬래시가 이스케이프 문자처럼 해석됩니다. 경로에 콜론이 포함되어 콜론이 경로와 내용 사이의 구분 기호로 잘못 해석되는 것을 방지하거나 경로가 큰따옴표로 시작하거나 끝나는 경우 경로를 따옴표로 묶어야 합니다.
+
파일 모드는 일반 파일로 제한되며, 옵션은 플랫폼 종속 명령줄 제한의 영향을 받을 수 있습니다. 복잡하지 않은 경우 추적되지 않은 파일을 작성하고 대신 `--add-file`을 사용하십시오.
+
`--add-file`과 달리 아카이브에서 생성되는 경로는 `--prefix` 옵션의 영향을 받지 않으며, 전체 `<path>`가 옵션의 값으로 제공될 수 있습니다.

--worktree-attributes::
	워킹 트리에서도 .gitattributes 파일의 속성을 찾습니다 (<<ATTRIBUTES>> 참조).

--mtime=<time>::
	아카이브 항목의 수정 시간을 설정합니다. 이 옵션이 없으면 `<tree-ish>`가 커밋 또는 태그인 경우 커밋 시간이 사용되고, 트리인 경우 현재 시간이 사용됩니다.

<extra>::
	아카이버 백엔드에서 이해하는 모든 옵션일 수 있습니다.
	다음 섹션을 참조하십시오.

--remote=<repo>::
	로컬 저장소에서 tar 아카이브를 만드는 대신, 원격 저장소에서 tar 아카이브를 가져옵니다. 원격 저장소는 `<tree-ish>`에서 허용될 수 있는 sha1 표현식에 제약을 둘 수 있습니다. 자세한 내용은 linkgit:git-upload-archive[1]를 참조하십시오.

--exec=<git-upload-archive>::
	--remote와 함께 사용하여 원격 측의 'git-upload-archive' 경로를 지정합니다.

<tree-ish>::
	아카이브를 생성할 트리 또는 커밋입니다.

<path>::
	선택적 경로 매개변수 없이는 현재 작업 디렉토리의 모든 파일과 하위 디렉토리가 아카이브에 포함됩니다.
	하나 이상의 경로가 지정되면 이러한 경로만 포함됩니다.

BACKEND EXTRA OPTIONS
---------------------

zip
~~~
-<digit>::
	압축 레벨을 지정합니다. 값이 클수록 명령이 더 많은 시간을 들여 더 작은 크기로 압축할 수 있습니다. 지원되는 값은 `-0` (저장 전용)부터 `-9` (최대 비율)까지입니다.
	주어지지 않으면 기본값은 `-6`입니다.

tar
~~~
-<number>::
	압축 레벨을 지정합니다. 이 값은 `tar.<format>.command`에 구성된 압축 명령에 전달됩니다. 지원되는 레벨 목록과 이 옵션이 지정되지 않은 경우의 기본 레벨은 구성된 명령의 매뉴얼 페이지를 참조하십시오.

CONFIGURATION
-------------

tar.umask::
	이 변수는 tar 아카이브 항목의 권한 비트를 제한하는 데 사용될 수 있습니다. 기본값은 0002로, 월드 쓰기 비트를 끕니다. 특별한 값 "user"는 아카이브를 실행하는 사용자의 umask가 대신 사용됨을 나타냅니다. 자세한 내용은 umask(2)를 참조하십시오. `--remote`가 사용되면 원격 저장소의 설정만 적용됩니다.

tar.<format>.command::
	이 변수는 `git archive`에 의해 생성된 tar 출력이 파이프될 쉘 명령을 지정합니다. 명령은 표준 입력에 생성된 tar 파일과 함께 쉘을 사용하여 실행되며, 표준 출력으로 최종 출력을 생성해야 합니다. 모든 압축 레벨 옵션은 명령에 전달됩니다 (예: `-9`).
+
`tar.gz` 및 `tgz` 포맷은 자동으로 정의되며 기본적으로 internal gzip 구현을 호출하는 `git archive gzip` 명령을 사용합니다.

tar.<format>.remote::
	true이면 linkgit:git-upload-archive[1]를 통해 원격 클라이언트에서 사용할 수 있도록 해당 포맷을 활성화합니다. 사용자 정의 포맷의 경우 기본값은 false이지만, `tar.gz` 및 `tgz` 포맷의 경우 true입니다.

[[ATTRIBUTES]]
ATTRIBUTES
----------

export-ignore::
	export-ignore 속성이 있는 파일과 디렉토리는 아카이브 파일에 추가되지 않습니다. 자세한 내용은 linkgit:gitattributes[5]를 참조하십시오.

export-subst::
	파일에 export-subst 속성이 설정되어 있으면 Git은 해당 파일을 아카이브에 추가할 때 여러 플레이스홀더를 확장합니다. 자세한 내용은 linkgit:gitattributes[5]를 참조하십시오.

참고로 속성은 기본적으로 아카이빙 중인 트리의 `.gitattributes` 파일에서 가져옵니다. 만약 아카이브 생성 방식(예: `.gitattributes`에 적절한 export-ignore를 추가하지 않고 커밋한 경우)을 나중에 조정하고 싶다면, 체크아웃된 `.gitattributes` 파일을 필요한 대로 조정하고 `--worktree-attributes` 옵션을 사용하십시오. 또는 어떤 트리든 아카이브할 때 적용해야 하는 필요한 속성을 `$GIT_DIR/info/attributes` 파일에 유지할 수 있습니다.

EXAMPLES
--------
`git archive --format=tar --prefix=junk/ HEAD | (cd /var/tmp/ && tar xf -)`::

	현재 브랜치의 최신 커밋 내용을 포함하는 tar 아카이브를 생성하고, `/var/tmp/junk` 디렉토리에 압축을 풉니다.

`git archive --format=tar --prefix=git-1.4.0/ v1.4.0 | gzip >git-1.4.0.tar.gz`::

	v1.4.0 릴리스에 대한 압축된 tarball을 생성합니다.

`git archive --format=tar.gz --prefix=git-1.4.0/ v1.4.0 >git-1.4.0.tar.gz`::

	내장 tar.gz 처리를 사용하여 위와 동일하게 작동합니다.

`git archive --prefix=git-1.4.0/ -o git-1.4.0.tar.gz v1.4.0`::

	위와 동일하지만, 출력 파일에서 포맷이 추론됩니다.

`git archive --format=tar --prefix=git-1.4.0/ v1.4.0^{tree} | gzip >git-1.4.0.tar.gz`::

	전역 확장 pax 헤더 없이 v1.4.0 릴리스에 대한 압축된 tarball을 생성합니다.

`git archive --format=zip --prefix=git-docs/ HEAD:Documentation/ > git-1.4.0-docs.zip`::

	현재 HEAD의 Documentation/ 디렉토리 내용을 'git-1.4.0-docs.zip'에 'git-docs/' 접두사를 붙여 넣습니다.

`git archive -o latest.zip HEAD`::

	현재 브랜치의 최신 커밋 내용을 포함하는 Zip 아카이브를 생성합니다. 출력 파일의 확장자로부터 포맷이 추론된다는 점에 유의하십시오.

`git archive -o latest.tar --prefix=build/ --add-file=configure --prefix= HEAD`::

	현재 브랜치의 최신 커밋 내용을 접두사 없이 포함하고, 추적되지 않은 파일 'configure'을 'build/' 접두사와 함께 포함하는 tar 아카이브를 생성합니다.

`git config tar.tar.xz.command "xz -c"`::

	LZMA 압축 tar 파일 생성을 위해 "tar.xz" 포맷을 구성합니다. `--format=tar.xz`를 지정하여 사용하거나, `-o foo.tar.xz`와 같은 출력 파일을 생성하여 사용할 수 있습니다.


SEE ALSO
--------
linkgit:gitattributes[5]

GIT
---
linkgit:git[1] 제품군의 일부