git-credential(1)
=================

NAME
----
git-credential - 사용자 자격 증명을 검색 및 저장

SYNOPSIS
--------
------------------
'git credential' (fill|approve|reject|capability)
------------------

DESCRIPTION
-----------

Git은 시스템별 도우미로부터 자격 증명을 저장하고 검색하며, 사용자에게 사용자 이름과 암호를 묻는 내부 인터페이스가 있습니다. `git-credential` 명령은 이 인터페이스를 스크립트에게 공개하여 Git과 동일한 방식으로 자격 증명을 검색, 저장 또는 묻는 기능을 수행할 수 있습니다. 이 스크립트 가능한 인터페이스의 디자인은 내부 C API를 모델링합니다. 개념에 대한 자세한 내용은 credential.h를 참조하십시오.

`git-credential`은 명령줄에서 "action" 옵션( `fill`, `approve` 또는 `reject` 중 하나)을 받고 표준 입력에서 자격 증명 설명을 읽습니다( <<IOFMT,INPUT/OUTPUT FORMAT>> 참조).

action이 `fill`인 경우 `git-credential`은 구성 파일, 구성된 자격 증명 도우미 연락 또는 사용자에게 묻는 작업을 통해 설명에 "username" 및 "password" 속성을 추가하려고 시도합니다. 그런 다음 자격 증명 설명의 사용자 이름 및 암호 속성은 이미 제공된 속성과 함께 표준 출력으로 인쇄됩니다.

action이 `approve`인 경우 `git-credential`은 나중에 사용할 수 있도록 자격 증명을 저장할 수 있는 구성된 자격 증명 도우미에게 설명을 보냅니다.

action이 `reject`인 경우 `git-credential`은 설명과 일치하는 저장된 자격 증명을 삭제할 수 있는 구성된 자격 증명 도우미에게 설명을 보냅니다.

action이 `capability`인 경우 `git-credential`은 지원하는 기능을 표준 출력으로 알립니다.

action이 `approve` 또는 `reject`인 경우 출력은 생성되지 않아야 합니다.

GIT CREDENTIAL의 일반적인 사용
-----------------------------

`git-credential`을 사용하는 애플리케이션은 일반적으로 다음과 같은 단계를 따라 `git credential`을 사용합니다.

  1. 컨텍스트를 기반으로 자격 증명 설명을 생성합니다.
+
예를 들어, `https://example.com/foo.git`에 대한 암호가 필요한 경우 다음 자격 증명 설명을 생성할 수 있습니다 (마지막 빈 줄을 잊지 마십시오. 이는 `git credential`에게 애플리케이션이 자신이 가진 모든 정보를 피드하는 것을 완료했음을 알립니다):

	 protocol=https
	 host=example.com
	 path=foo.git

  2. 이 설명에 대한 사용자 이름과 암호를 얻기 위해 `git-credential`에 요청합니다. 이는 `git credential fill`을 실행하고 (1) 단계의 설명을 표준 입력으로 제공하여 수행됩니다. 완료된 자격 증명 설명(인증 자체, 즉 로그인 및 암호를 포함)은 다음과 같이 표준 출력으로 생성됩니다:

	protocol=https
	host=example.com
	username=bob
	password=secr3t
+
대부분의 경우 이는 입력에서 제공된 속성이 출력에서 반복된다는 것을 의미하지만, Git은 프로토콜이 HTTP(s)이고 `credential.useHttpPath`가 false인 경우 `path` 속성을 제거하는 등 자격 증명 설명을 수정할 수도 있습니다.
+
`git credential`이 암호를 알고 있었다면, 이 단계에서 사용자가 실제로 암호를 입력하는 것이 포함되지 않았을 수 있습니다 (사용자가 키체인을 잠금 해제하기 위해 암호를 입력했거나 키체인이 이미 잠금 해제되어 사용자 상호 작용이 없었을 수 있습니다).

  3. 자격 증명(예: (2) 단계에서 사용자 이름과 암호를 사용하여 URL 액세스)을 사용하고 수락되는지 확인합니다.

  4. 암호의 성공 또는 실패를 보고합니다. 자격 증명이 작업을 성공적으로 완료할 수 있도록 허용한 경우, 다음에 호출될 때 `git credential`이 재사용하도록 `approve` 액션으로 표시할 수 있습니다. 작업 중에 자격 증명이 거부된 경우, 다음에 호출될 때 `git credential`이 새 암호를 묻도록 `reject` 액션을 사용합니다. 어느 경우든, `git credential`은 (1) 단계에서 제공된 필드(자격 증명 자체 포함)를 포함하는 (2) 단계에서 얻은 자격 증명 설명으로 피드되어야 합니다.

[[IOFMT]]
INPUT/OUTPUT FORMAT
-------------------

`git credential`은 표준 입력/출력에서 자격 증명 정보를 읽거나 씁니다(사용되는 action에 따라 다름). 이 정보는 `git credential`이 로그인 정보를 얻을 키(예: host, protocol, path) 또는 얻을 실제 자격 증명 데이터(username/password)에 해당할 수 있습니다.

자격 증명은 이름이 지정된 속성 세트로 분할되며, 각 속성은 줄당 하나씩입니다. 각 속성은 키-값 쌍으로 지정되며 `=` (등호)로 구분되고 뒤에 줄 바꿈 문자가 옵니다.

키에는 `=`, 줄 바꿈 또는 NUL을 제외한 모든 바이트가 포함될 수 있습니다. 값에는 줄 바꿈 또는 NUL을 제외한 모든 바이트가 포함될 수 있습니다. 효율적인 파싱을 위해 줄(뒤따르는 줄 바꿈 포함)은 65535바이트를 초과할 수 없습니다.

C 스타일 배열 브래킷 `[]`으로 끝나는 키가 있는 속성은 여러 값을 가질 수 있습니다. 다중 값 속성의 각 인스턴스는 값의 순서 목록을 형성합니다. 반복되는 속성의 순서로 값의 순서가 정의됩니다. 비어 있는 다중 값 속성 (`key[]=\n`)은 이전 항목을 지우고 목록을 재설정하는 역할을 합니다.

모든 경우에 모든 바이트는 그대로 처리됩니다(즉, 따옴표가 없으며 줄 바꿈 또는 NUL이 포함된 값을 전송할 수 없습니다). 속성 목록은 빈 줄 또는 파일 끝으로 종료됩니다.

Git은 다음과 같은 속성을 이해합니다:

`protocol`::

	자격 증명이 사용될 프로토콜 (예: `https`).

`host`::

	네트워크 자격 증명의 원격 호스트 이름. 지정된 경우 포트 번호가 포함될 수 있습니다 (예: "example.com:8088").

`path`::

	자격 증명이 사용될 경로. 예를 들어, 원격 HTTPS 저장소에 액세스하기 위한 서버의 저장소 경로가 됩니다.

`username`::

	자격 증명의 사용자 이름. (예: URL, 구성, 사용자 또는 이전에 실행된 도우미에서).

`password`::

	저장하도록 요청하는 자격 증명의 암호.

`password_expiry_utc`::

	OAuth 액세스 토큰과 같은 생성된 암호에는 만료 날짜가 있을 수 있습니다.
	도우미로부터 자격 증명을 읽을 때 `git credential fill`은 만료된 암호를 무시합니다. Unix 시간 UTC, 1970년 이후 초로 표현됩니다.

`oauth_refresh_token`::

	OAuth 액세스 토큰이 암호인 경우 OAuth 새로 고침 토큰이 함께 제공될 수 있습니다.
	도우미는 암호 속성과 마찬가지로 이 속성을 기밀로 취급해야 합니다. Git 자체는 이 속성에 대한 특별한 동작이 없습니다.

`url`::

	`git credential`이 이 특별한 속성을 읽을 때, 값은 URL로 파싱되어 해당 구성 요소가 읽힌 것처럼 처리됩니다 (예: `url=https://example.com`은 `protocol=https` 및 `host=example.com`이 제공된 것처럼 동작합니다). 이는 호출자가 URL을 직접 파싱하는 것을 피하는 데 도움이 될 수 있습니다.
+
프로토콜 지정은 필수이며 URL에 호스트 이름이 지정되지 않은 경우 (예: "cert:///path/to/file") 자격 증명에는 값이 빈 문자열인 호스트 이름 속성이 포함됩니다.
+
URL에 누락된 구성 요소 (예: 위의 예에서 사용자 이름이 없는 경우)는 설정되지 않은 상태로 유지됩니다.

`authtype`::
	사용해야 하는 인증 스키임을 나타냅니다.
	HTTP 및 HTTPS의 일반적인 값에는 `basic`, `bearer`, `digest`가 포함되지만, 후자는 안전하지 않으므로 사용해서는 안 됩니다. `credential`이 사용되는 경우 해당 프로토콜 (일반적으로 HTTP)에 적합한 임의의 문자열로 설정될 수 있습니다.
+
이 값은 입력에 제공된 해당 기능(아래 참조)이 없으면 전송되지 않아야 합니다.

`credential`::
	해당 프로토콜 (일반적으로 HTTP)에 적합한 사전 인코딩된 자격 증명입니다.
	이 키가 전송되는 경우 `authtype`은 필수이며 `username` 및 `password`는 사용되지 않습니다. HTTP의 경우 Git은 `authtype` 값과 이 값을 단일 공백으로 연결하여 `Authorization` 헤더를 결정합니다.
+
이 값은 적절한 기능(아래 참조)이 제공되지 않으면 전송되지 않아야 합니다.

`ephemeral`::
	이 부울 값은 true인 경우 `credential` 필드의 값이 시간적 유용성이 제한되어 자격 증명 도우미에 의해 저장되지 않아야 함을 나타냅니다. 예를 들어, HTTP Digest `credential` 값은 nonce를 사용하여 계산되며 재사용하면 인증이 성공하지 않습니다.
	이는 또한 짧은 기간 (예: 24시간) 자격 증명과 같은 상황에 사용될 수 있습니다. 기본값은 false입니다.
+
자격 증명 도우미는 작업이 성공했는지 여부를 결정하기 위해 `store` 또는 `erase`로 호출됩니다.
+
이 값은 적절한 기능(아래 참조)이 제공되지 않으면 전송되지 않아야 합니다.

`state[]`::
	이 값은 도우미가 다시 호출될 때 전달될 불투명한 상태를 제공합니다. 각 다른 자격 증명 도우미는 이를 한 번 지정할 수 있습니다. 값은 자격 증명 도우미에 고유한 접두사를 포함해야 하며 일치하지 않는 값은 무시해야 합니다.
+
이 값은 적절한 기능(아래 참조)이 제공되지 않으면 전송되지 않아야 합니다.

`continue`::
	이것은 활성화된 경우 이 인증이 다단계 인증 단계의 비최종 부분임을 나타내는 부울 값입니다. 이는 NTLM 및 Kerberos와 같은 프로토콜에서 일반적이며, 두 번의 클라이언트 인증 라운드가 필요하며 이 플래그를 설정하면 자격 증명 도우미가 다단계 인증 단계를 구현할 수 있습니다. 이 플래그는 추가 단계가 필요한 경우, 즉 또 다른 인증 라운드가 예상되는 경우에만 보내야 합니다.
+
이 값은 적절한 기능(아래 참조)이 제공되지 않으면 전송되지 않아야 합니다. 이 속성은 자격 증명 도우미에서 Git (또는 `git credential`을 호출하는 다른 프로그램)으로 정보를 전달하는 '단방향'입니다.

`wwwauth[]`::

	Git이 `WWW-Authenticate` 인증 헤더를 포함하는 HTTP 응답을 수신하면, 이는 Git에서 자격 증명 도우미로 전달됩니다.
+
각 'WWW-Authenticate' 헤더 값은 다중 값 속성 'wwwauth[]'로 전달되며, 여기서 속성의 순서는 HTTP 응답에 나타나는 순서와 같습니다. 이 속성은 Git에서 자격 증명 도우미로 추가 정보를 전달하는 '단방향'입니다.

`capability[]`::
	Git 또는 도우미가 해당 기능을 지원함을 신호합니다. 이는 프로토콜의 더 나은, 더 구체적인 데이터를 제공하는 데 사용될 수 있습니다. `capability[]` 지시문은 이를 의존하는 값 앞에 와야 하며, 이러한 지시문은 프로토콜에서 처음으로 알려져야 합니다.
+
현재 두 가지 기능이 지원됩니다. 첫 번째는 `authtype`으로, `authtype`, `credential`, `ephemeral` 값이 이해됨을 나타냅니다. 두 번째는 `state`로, `state[]` 및 `continue` 값이 이해됨을 나타냅니다.
+
기능이 지원된다고 해서 추가 기능이 의무적으로 사용되는 것은 아니지만, 기능 없이 제공되어서는 안 됩니다.

알려지지 않은 속성 및 기능은 조용히 폐기됩니다.

[[CAPA-IOFMT]]
CAPABILITY INPUT/OUTPUT FORMAT
------------------------------

`git credential capability`의 경우 형식이 약간 다릅니다. 먼저 `version 0` 발표가 현재 프로토콜 버전을 나타내고, 각 기능이 `capability authtype`과 같은 줄로 알려집니다. 자격 증명 도우미도 이 형식을 구현할 수 있으며, 다시 `capability` 인수를 사용합니다. 향후 빈 줄이 추가될 수 있습니다. 호출자는 이해하지 못하는 줄은 무시해야 합니다.

이것은 자격 증명 도우미 프로토콜의 새로운 부분이므로, 이전 버전의 Git 및 일부 자격 증명 도우미는 이를 지원하지 않을 수 있습니다. 0이 아닌 종료 상태를 받거나 첫 번째 줄이 `version`이라는 단어와 공백으로 시작하지 않으면, 호출자는 기능이 지원되지 않는다고 가정해야 합니다.

이 형식의 의도는 자격 증명 출력과 구별하여 모호하지 않게 하는 것입니다. 매우 간단한 자격 증명 도우미 (예: 인라인 쉘 스크립트)를 사용할 수 있으며, 항상 동일한 출력을 생성합니다. 별도의 형식을 사용하면 사용자는 기능 광고를 올바르게 구현하거나 기능 쿼링 시 혼동하는 것에 대해 걱정하지 않고 이 구문을 계속 사용할 수 있습니다.

GIT
---
linkgit:git[1] 제품군의 일부