git-rm(1)
=========

NAME
----
git-rm - 워킹 트리와 인덱스에서 파일 제거

SYNOPSIS
--------
[synopsis]
git rm [-f | --force] [-n] [-r] [--cached] [--ignore-unmatch]
       [--quiet] [--pathspec-from-file=<file> [--pathspec-file-nul]]
       [--] [<pathspec>...]

DESCRIPTION
-----------
인덱스에서, 또는 워킹 트리와 인덱스에서 pathspec과 일치하는 파일을 제거합니다. `git rm`은 작업 디렉토리에서만 파일을 제거하지 않습니다. (작업 트리에서만 파일을 제거하고 인덱스에 유지하는 옵션은 없습니다. 해당 작업을 하려면 `/bin/rm`을 사용하세요.) 제거되는 파일은 브랜치의 최신 커밋과 동일해야 하며, 해당 내용에 대한 어떠한 업데이트도 인덱스에 스테이징되지 않아야 합니다. 하지만 `-f` 옵션으로 이 기본 동작을 재정의할 수 있습니다. `--cached`가 사용될 경우, 스테이징된 내용은 브랜치의 최신 커밋이나 디스크의 파일과 일치해야 하며, 이를 통해 인덱스에서만 파일을 제거할 수 있습니다. sparse-checkouts가 사용 중일 때 (linkgit:git-sparse-checkout[1] 참조), `git rm`은 sparse-checkout 패턴 내의 경로만 제거합니다.


OPTIONS
-------
`<pathspec>...`::
	제거할 파일. 선행 디렉토리 이름 (예: `dir`은 `dir/file1` 및 `dir/file2`를 제거)을 지정하여 디렉토리의 모든 파일을 제거하고, 재귀적으로 모든 하위 디렉토리를 제거할 수 있습니다. 하지만 이 경우 `-r` 옵션을 명시적으로 지정해야 합니다.
+
이 명령어는 Git에 알려진 경로만 제거합니다.
+
파일 globbing은 디렉토리 경계를 넘어서 일치합니다. 따라서 `d`와 `d2` 두 디렉토리가 있을 때, `git rm 'd*'`와 `git rm 'd/*'` 사이에는 차이가 있습니다. 전자는 `d2` 디렉토리도 제거합니다.
+
더 자세한 내용은 linkgit:gitglossary[7]의 _<pathspec>_ 항목을 참조하십시오.

`-f`::
`--force`::
	최신 업데이트 확인을 재정의합니다.

`-n`::
`--dry-run`::
	실제로 파일을 제거하지 않습니다. 대신, 인덱스에 파일이 존재하고 명령어로 인해 제거될 예정이었는지 보여줍니다.

`-r`::
        선행 디렉토리 이름이 주어졌을 때 재귀적 제거를 허용합니다.

`--`::
	이 옵션은 명령줄 옵션과 파일 목록을 분리하는 데 사용될 수 있습니다 (파일명이 명령줄 옵션으로 오인될 수 있을 때 유용합니다).

`--cached`::
	이 옵션을 사용하여 스테이징에서 제거하고 인덱스에서만 경로를 제거하십시오.
	워킹 트리 파일은 수정 여부에 관계없이 그대로 유지됩니다.

`--ignore-unmatch`::
	일치하는 파일이 없어도 0 상태 코드로 종료합니다.

`--sparse`::
	sparse-checkout cone 외부의 인덱스 항목 업데이트를 허용합니다.
	일반적으로 `git rm`은 sparse-checkout cone에 맞지 않는 경로의 인덱스 항목을 업데이트하는 것을 거부합니다. linkgit:git-sparse-checkout[1]을 참조하십시오.

`-q`::
`--quiet`::
	`git rm`은 일반적으로 제거된 각 파일에 대해 한 줄 ( `rm` 명령 형식)을 출력합니다. 이 옵션은 해당 출력을 억제합니다.

`--pathspec-from-file=<file>`::
	Pathspec이 인수로 전달되는 대신 _<file>_에서 전달됩니다. _<file>_이 정확히 `-`이면 표준 입력이 사용됩니다. Pathspec 요소는 _LF_ 또는 _CR_/_LF_로 구분됩니다. Pathspec 요소는 `core.quotePath` 구성 변수 ( linkgit:git-config[1] 참조)에 설명된 대로 따옴표로 묶을 수 있습니다. `--pathspec-file-nul` 및 전역 `--literal-pathspecs`도 참조하십시오.

`--pathspec-file-nul`::
	`--pathspec-from-file`에서만 의미가 있습니다. Pathspec 요소는 _NUL_ 문자로 구분되며 다른 모든 문자는 리터럴로 간주됩니다 (줄 바꿈 및 따옴표 포함).


REMOVING FILES THAT HAVE DISAPPEARED FROM THE FILESYSTEM
--------------------------------------------------------
파일 시스템에서 사라진 경로만 인덱스에서 제거하는 `git rm` 옵션은 없습니다. 하지만 사용 사례에 따라 여러 가지 방법으로 수행할 수 있습니다.

``git commit -a'' 사용
~~~~~~~~~~~~~~~~~~~~~~~
다음 커밋에서 워킹 트리의 추적되는 모든 파일의 수정을 기록하고 `rm` ( `git rm`과 반대)을 사용하여 워킹 트리에서 제거된 파일의 모든 제거를 기록하려면 `git commit -a`를 사용하십시오. 이 명령어는 모든 제거를 자동으로 감지하고 기록합니다. 커밋 없이 유사한 효과를 얻으려면 `git add -u`를 사용해도 됩니다.

``git add -A'' 사용
~~~~~~~~~~~~~~~~~~~~
공급업체 브랜치에 대한 새로운 코드 드롭을 수락할 때, 경로 제거뿐만 아니라 새 경로 추가 및 기존 경로 수정도 기록하고 싶을 가능성이 높습니다.

일반적으로 이 명령어로 워킹 트리에서 모든 추적되는 파일을 먼저 제거합니다.

----------------
git ls-files -z | xargs -0 rm -f
----------------

그런 다음 워킹 트리에 새 코드를 untar합니다. 또는 변경 사항을 워킹 트리로 'rsync'할 수도 있습니다.

그 후, 워킹 트리에서 모든 제거, 추가 및 수정 사항을 기록하는 가장 쉬운 방법은 다음과 같습니다.

----------------
git add -A
----------------

linkgit:git-add[1]을 참조하십시오.

Other ways
~~~~~~~~~~
정말로 워킹 트리에 더 이상 존재하지 않는 파일을 인덱스에서 제거하기만 하려면 (예: 워킹 트리가 더러워서 `git commit -a`를 사용할 수 없을 때) 다음 명령어를 사용하십시오.

----------------
git diff --name-only --diff-filter=D -z | xargs -0 git rm --cached
----------------

SUBMODULES
----------
gitfile을 사용하는 서브모듈 (Git 버전 1.7.8 이상으로 클론되었음을 의미)만 작업 트리에서 제거됩니다. 해당 리포지토리가 슈퍼프로젝트의 `.git` 디렉토리 내에 있기 때문입니다. 서브모듈 (또는 그 안에 중첩된 것)이 여전히 `.git` 디렉토리를 사용하는 경우, `git rm`은 서브모듈의 히스토리를 보호하기 위해 슈퍼프로젝트의 git 디렉토리로 서브모듈 git 디렉토리를 이동시킵니다. 존재하는 경우 linkgit:gitmodules[5] 파일의 `submodule.<name>` 섹션도 제거되고 해당 파일은 스테이징됩니다 ( `--cached` 또는 `-n`을 사용하지 않는 한).

서브모듈은 `HEAD`가 인덱스에 기록된 것과 동일하고, 추적되는 파일이 수정되지 않았으며, 무시되지 않은 추적되지 않은 파일이 서브모듈의 작업 트리에 없을 때 최신 상태로 간주됩니다. 무시된 파일은 소모품으로 간주되며 서브모듈의 작업 트리가 제거되는 것을 막지 못합니다.

지역 서브모듈 체크아웃만 작업 트리에서 제거하고 제거를 커밋하지 않으려면 대신 linkgit:git-submodule[1] `deinit`을 사용하십시오. 서브모듈 제거에 대한 자세한 내용은 linkgit:gitsubmodules[7]을 참조하십시오.

EXAMPLES
--------
`git rm Documentation/\*.txt`::
	`Documentation` 디렉토리 및 그 하위 디렉토리의 모든 `*.txt` 파일을 인덱스에서 제거합니다.
+
예제에서 별표 `*`는 쉘에서 따옴표 처리됩니다. 이를 통해 쉘이 아닌 Git이 `Documentation/` 디렉토리 아래의 파일 및 하위 디렉토리의 경로명을 확장할 수 있습니다.

`git rm -f git-*.sh`::
	이 예제에서는 쉘이 별표를 확장하도록 허용합니다 (즉, 파일들을 명시적으로 나열합니다). 따라서 `subdir/git-foo.sh`는 제거되지 않습니다.

BUGS
----
슈퍼프로젝트 업데이트가 채워진 서브모듈을 제거할 때마다 (예: 제거 전후의 커밋 간 전환 때) 이전 위치에 오래된 서브모듈 체크아웃이 남아 있을 수 있습니다. 이전 디렉토리를 제거하는 것은 gitfile을 사용하는 경우에만 안전합니다. 그렇지 않으면 서브모듈의 히스토리가 삭제될 수 있습니다. 재귀적 서브모듈 업데이트가 구현되면 이 단계는 불필요해질 것입니다.

SEE ALSO
--------
linkgit:git-add[1]

GIT
---
linkgit:git[1] suite의 일부