git-bundle(1)
=============

NAME
----
git-bundle - 아카이브로 객체 및 ref 전송


SYNOPSIS
--------
[verse]
'git bundle' create [-q | --quiet | --progress]
		    [--version=<version>] <file> <git-rev-list-args>
'git bundle' verify [-q | --quiet] <file>
'git bundle' list-heads <file> [<refname>...]
'git bundle' unbundle [--progress] <file> [<refname>...]

DESCRIPTION
-----------

"번들" 파일을 생성, 압축 해제 및 조작합니다. 번들은 네트워크 연결의 다른 쪽에 활성 "서버"가 없는 "오프라인" Git 객체 전송에 사용됩니다.

저장소의 증분 및 전체 백업을 모두 생성( "EXAMPLES"의 "full backup" 예제 참조)하고, 한 저장소의 ref 상태를 다른 저장소로 전달하는 데 사용할 수 있습니다(두 번째 예제 참조).

`ssh://` 및 `https://`와 같은 프로토콜을 통해 페치하거나 기타 "읽기" 작업을 수행하는 Git 명령도 번들 파일에 대해 작동할 수 있습니다. 번들에서 새 저장소를 linkgit:git-clone[1] 하거나, 번들에서 페치하기 위해 linkgit:git-fetch[1] 을 사용하거나, 내부에 포함된 ref를 linkgit:git-ls-remote[1] 으로 나열하는 것이 가능합니다. 이에 상응하는 "쓰기" 지원은 없습니다. 즉, 번들로의 'git push'는 지원되지 않습니다.

BUNDLE FORMAT
-------------

번들은 헤더가 포함된 `.pack` 파일( linkgit:git-pack-objects[1] 참조)이며, 번들에 포함된 ref가 표시됩니다.

패킹된 아카이브 형식 자체와 마찬가지로 번들은 자체 포함되거나 제외 사항을 사용하여 생성될 수 있습니다. 아래 "OBJECT PREREQUISITES" 섹션을 참조하십시오.

리비전 제외를 사용하여 생성된 번들은 linkgit:git-pack-objects[1] 의 `--thin` 옵션을 사용하여 생성된 "thin pack"이며, linkgit:git-index-pack[1] 의 `--fix-thin` 옵션을 사용하여 언번들됩니다.

리비전 제외를 사용할 때 "thick pack"을 생성하는 옵션은 없으며 사용자는 차이에 대해 걱정할 필요가 없습니다. "thin pack"을 사용함으로써, 제외를 사용하여 생성된 번들은 크기가 더 작습니다. 내부적으로 "thin"이라는 사실은 단지 호기심으로, 그리고 다른 문서에 대한 참조로만 언급됩니다.

자세한 내용은 linkgit:gitformat-bundle[5] 을, "thin pack"에 대한 논의는 linkgit:gitformat-pack[5] 을 참조하십시오.

OPTIONS
-------

create [options] <file> <git-rev-list-args>::
	'file'이라는 이름의 번들을 생성하는 데 사용됩니다. 이를 위해서는 '<git-rev-list-args>' 인수를 사용하여 번들 내용을 정의해야 합니다. 'options'에는 'git bundle create' 하위 명령에 대한 특정 옵션이 포함됩니다. 'file'이 `-` 이면 번들은 stdout으로 기록됩니다.

verify <file>::
	번들 파일이 유효하고 현재 저장소에 깨끗하게 적용될 수 있는지 확인하는 데 사용됩니다. 여기에는 번들 형식 자체에 대한 확인과 사전 요구 커밋이 존재하고 현재 저장소에 완전히 연결되어 있는지 확인하는 것이 포함됩니다. 그런 다음 'git bundle'은 누락된 커밋 목록을 출력합니다(있는 경우). 마지막으로 "object filter"와 같은 추가 기능에 대한 정보가 출력됩니다. 더 많은 정보를 보려면 linkgit:gitformat-bundle[5] 의 "Capabilities"를 참조하십시오. 성공 시 종료 코드는 0이 되지만, 번들 파일이 유효하지 않으면 0이 아닌 값을 갖습니다. 'file'이 `-` 이면 번들은 stdin에서 읽힙니다.

list-heads <file>::
	번들에 정의된 ref를 나열합니다. ref 목록으로 뒤따르는 경우, 주어진 ref와 일치하는 ref만 출력됩니다. 'file'이 `-` 이면 번들은 stdin에서 읽힙니다.

unbundle <file>::
	번들의 객체를 'git index-pack'으로 전달하여 저장소에 저장한 다음, 정의된 모든 ref의 이름을 출력합니다. ref 목록이 제공되면, 목록의 ref와 일치하는 ref만 출력됩니다. 이 명령은 실제로 플러밍이며 'git fetch'에 의해서만 호출되도록 의도되었습니다. 'file'이 `-` 이면 번들은 stdin에서 읽힙니다.

<git-rev-list-args>::
	'git rev-parse' 및 'git rev-list'(그리고 명명된 ref 포함, 아래 SPECIFYING REFERENCES 참조)에서 허용되는 인수의 목록으로, 전송할 특정 객체 및 ref를 지정합니다. 예를 들어, `master~10..master`는 현재 master ref를 10번째 조상 커밋 이후 추가된 모든 객체와 함께 패키징합니다. 패키징할 ref 및 객체의 수에는 명시적인 제한이 없습니다.


[<refname>...]::
	보고된 ref를 제한하는 데 사용되는 ref 목록입니다. 이는 주로 'git fetch'에서 사용되며, 팩의 모든 것을 반드시 받지는 않고 요청한 ref만 받도록 예상합니다 (이 경우 'git bundle'은 'git fetch-pack'처럼 작동합니다).

--progress::
	-q가 지정되지 않은 경우, 기본적으로 표준 오류 스트림에 진행 상황 상태가 보고됩니다. 이 플래그는 표준 오류 스트림이 터미널에 연결되어 있지 않은 경우에도 진행 상황 상태를 강제합니다.

--version=<version>::
	번들 버전을 지정합니다. 버전 2는 이전 형식이며 SHA-1 저장소에만 사용할 수 있습니다. 더 새로운 버전 3에는 확장을 허용하는 기능이 포함되어 있습니다. 기본값은 사용 중인 해시 알고리즘을 기반으로 하는 가장 오래된 지원 형식입니다.

-q::
--quiet::
	이 플래그를 사용하면 명령이 표준 오류 스트림에 진행 상황을 보고하지 않습니다.

SPECIFYING REFERENCES
---------------------

리비전에는 번들에 패키징될 ref 이름이 동반되어야 합니다. 또는 `--all`을 사용하여 모든 ref를 패키징할 수 있습니다.

둘 이상의 ref를 패키징할 수 있으며, 둘 이상의 사전 요구 객체 세트를 지정할 수 있습니다. 패키징된 객체는 사전 요구 사항의 합집합에 포함되지 않은 객체입니다.

'git bundle create' 명령은 'git rev-parse --abbrev-ref=loose'와 동일한 규칙을 사용하여 ref 이름을 확인합니다. 각 사전 요구 사항은 명시적으로 (예: `^master~10`) 또는 암묵적으로 (예: `master~10..master`, `--since=10.days.ago master`) 지정될 수 있습니다.

이러한 간단한 경우는 모두 OK입니다("master" 및 "next" 브랜치가 있다고 가정):

----------------
$ git bundle create master.bundle master
$ echo master | git bundle create master.bundle --stdin
$ git bundle create master-and-next.bundle master next
$ (echo master; echo next) | git bundle create master-and-next.bundle --stdin
----------------

그리고 이것들도 마찬가지입니다 (그리고 동일하지만 생략된 `--stdin` 예제):

----------------
$ git bundle create recent-master.bundle master~10..master
$ git bundle create recent-updates.bundle master~10..master next~5..next
----------------

참조 이름 또는 참조로 확인할 수 없는 범위를 가진 범위는 허용되지 않습니다.

----------------
$ git bundle create HEAD.bundle $(git rev-parse HEAD)
fatal: Refusing to create empty bundle.
$ git bundle create master-yesterday.bundle master~10..master~5
fatal: Refusing to create empty bundle.
----------------

OBJECT PREREQUISITES
--------------------

번들을 생성할 때 공통 기록이 없는 저장소에서 언번들할 수 있는 자체 포함 번들을 생성할 뿐만 아니라 기록의 초기 부분에 필요한 객체를 제외하기 위해 음수 리비전을 제공할 수 있습니다.

`git bundle create`에 `new`와 같은 리비전을 전달하면 `new` 리비전에서 도달 가능한 모든 객체를 포함하는 번들 파일이 생성됩니다. 이 번들은 어떤 저장소에서도 언번들되어 `new` 리비전에 이르는 전체 기록을 얻을 수 있습니다.

----------------
$ git bundle create full.bundle new
----------------

`old..new`와 같은 리비전 범위는 번들이 "언번들"-가능하려면 `old` 리비전 (및 거기서 도달 가능한 객체)이 존재해야 하는 번들 파일을 생성합니다.

----------------
$ git bundle create full.bundle old..new
----------------

사전 요구 사항이 없는 자체 포함 번들은 빈 저장소를 포함하여 어디든 추출하거나 (즉, `new`, `old..new` 아님) 복제할 수 있습니다.

대상에 이미 있는 객체를 포함하는 번들 파일을 만들기 위해 안전하게 하는 것이 좋습니다. 이러한 객체는 대상에서의 언패킹 중에 무시됩니다.

원본 저장소에서 직접 복제할 때와 동일한 ref 집합을 제공하려면 `<git-rev-list-args>`에 대해 `--branches --tags`를 사용하십시오.

'git bundle verify' 명령은 수신자 저장소가 사전 요구 사항이 있는 번들에 대해 필요한 사전 요구 커밋을 가지고 있는지 확인할 수 있습니다.

EXAMPLES
--------

두 가지 경우를 논의하겠습니다.

1. 저장소의 전체 백업 취하기
2. 두 기계가 직접 연결되지 않은 상태에서 한 저장소의 기록을 다른 기계로 전송하기

먼저 저장소의 전체 백업을 고려합니다. 다음 명령은 모든 ref가 번들에 포함된다는 의미에서 저장소의 전체 백업을 수행합니다.

----------------
$ git bundle create backup.bundle --all
----------------

하지만 다시 말하지만, 이것은 ref에 대한 것일 뿐입니다. 즉, ref 및 해당 ref에서 도달 가능한 커밋만 포함됩니다. 인덱스, 워킹 트리, 스태시, 저장소별 구성, 훅 등의 내용은 포함되지 않습니다.

나중에 예를 들어 linkgit:git-clone[1] 을 사용하여 해당 저장소를 복구할 수 있습니다.

----------------
$ git clone backup.bundle <new directory>
----------------

다음 예에서는 기계 A의 저장소 R1의 기록을 기계 B의 다른 저장소 R2로 전송한다고 가정합니다.
어떤 이유로든 A와 B 간의 직접 연결이 허용되지 않지만, 어떤 메커니즘(CD, 이메일 등)을 통해 A에서 B로 데이터를 이동할 수 있습니다. R1의 master 브랜치에서 R2를 업데이트하려고 합니다.

프로세스를 부트스트랩하기 위해 사전 요구 사항이 없는 번들을 먼저 생성할 수 있습니다. 마지막으로 처리한 커밋까지 기록하기 위해 태그를 사용하여 나중에 다른 저장소를 증분 번들로 업데이트하기 쉽게 만들 수 있습니다.

----------------
machineA$ cd R1
machineA$ git bundle create file.bundle master
machineA$ git tag -f lastR2bundle master
----------------

그런 다음 file.bundle을 대상 기계 B로 전송합니다. 이 번들은 추출을 위해 기존 객체가 필요하지 않으므로, 이를 사용하여 기계 B에서 새 저장소를 복제할 수 있습니다.

----------------
machineB$ git clone -b master /home/me/tmp/file.bundle R2
----------------

이렇게 하면 결과 저장소에 "origin"이라는 원격이 정의되어 번들에서 페치 및 풀링할 수 있습니다. R2의 $GIT_DIR/config 파일에는 다음과 같은 항목이 있습니다.

------------------------
[remote "origin"]
    url = /home/me/tmp/file.bundle
    fetch = refs/heads/*:refs/remotes/origin/*
------------------------

mine.git 저장소를 업데이트하려면 /home/me/tmp/file.bundle에 저장된 번들을 증분 업데이트로 교체한 후 페치 또는 풀할 수 있습니다.

원본 저장소에서 더 많은 작업을 수행한 후, 다른 저장소를 업데이트하기 위해 증분 번들을 생성할 수 있습니다.

----------------
machineA$ cd R1
machineA$ git bundle create file.bundle lastR2bundle..master
machineA$ git tag -f lastR2bundle master
----------------

그런 다음 번들을 다른 기계로 전송하여 /home/me/tmp/file.bundle을 교체하고 거기서 풀합니다.

----------------
machineB$ cd R2
machineB$ git pull
----------------

의도된 수신자 저장소가 필요한 객체를 어떤 커밋까지 가지고 있어야 하는지 알고 있다면, 이를 사용하여 사전 요구 사항을 지정하여 결과 번들에 포함될 리비전 및 객체를 제한할 수 있습니다. 이전 예에서는 이 목적으로 lastR2bundle 태그를 사용했지만, linkgit:git-log[1] 명령에 제공할 수 있는 다른 옵션을 사용할 수 있습니다. 몇 가지 추가 예는 다음과 같습니다.

둘 다 존재하는 태그를 사용할 수 있습니다.

----------------
$ git bundle create mybundle v1.0.0..master
----------------

시간 기반 사전 요구 사항을 사용할 수 있습니다.

----------------
$ git bundle create mybundle --since=10.days master
----------------

커밋 수를 사용할 수 있습니다.

----------------
$ git bundle create mybundle -10 master
----------------

`git-bundle verify`를 실행하여 사전 요구 사항으로 생성된 번들에서 추출할 수 있는지 확인할 수 있습니다.

----------------
$ git bundle verify mybundle
----------------

이렇게 하면 번들에서 추출하기 위해 어떤 커밋을 가지고 있어야 하는지 나열되고, 해당 커밋을 가지고 있지 않으면 오류가 발생합니다.

수신자 저장소의 관점에서 번들은 정기적인 저장소와 마찬가지로 페치 또는 풀하는 대상입니다. 예를 들어, 페치할 때 ref를 매핑할 수 있습니다.

----------------
$ git fetch mybundle master:localRef
----------------

거기서 제공하는 ref를 확인할 수도 있습니다.

----------------
$ git ls-remote mybundle
----------------

DISCUSSION
----------

저장소의 전체 백업을 만드는 단순한 방법은 `cp -r <repo> <destination>`와 같은 것을 사용하는 것입니다. 복사 작업 중에 저장소에 쓰여질 수 있기 때문에 이는 권장되지 않습니다. 결과적으로 `<destination>`의 일부 파일이 손상될 수 있습니다.

이것이 저장소 백업을 위해 Git 도구를 사용하는 것이 권장되는 이유이며, 이 명령 또는 linkgit:git-clone[1] 과 같은 도구를 사용할 수 있습니다. 그러나 이러한 도구는 ref 및 커밋 외의 상태를 백업하는 데 도움이 되지 않는다는 점을 염두에 두십시오. 즉, 인덱스, 워킹 트리, 스태시, 저장소별 구성, 훅 등의 내용을 백업하는 데 도움이 되지 않습니다.

시스템 간 파일 동기화와 관련된 문제를 논의하기 위해 linkgit:gitfaq[7]의 "TRANSFERS" 섹션을 참조하십시오.

FILE FORMAT
-----------

linkgit:gitformat-bundle[5] 을 참조하십시오.

GIT
---
linkgit:git[1] 제품군의 일부