git-name-rev(1)
===============

NAME
----
git-name-rev - 주어진 리비전에 대한 심볼릭 이름 찾기


SYNOPSIS
--------
[verse]
'git name-rev' [--tags] [--refs=<pattern>]
	       ( --all | --annotate-stdin | <commit-ish>... )

DESCRIPTION
-----------
'git rev-parse'에서 파싱 가능한 어떤 형식으로든 주어진 리비전에 대해 사람이 이해하기 쉬운 심볼릭 이름을 찾습니다.


OPTIONS
-------

--tags::
	브랜치 이름을 사용하지 않고, 커밋의 이름을 지정하기 위해 태그만 사용합니다.

--refs=<pattern>::
	주어진 쉘 패턴과 일치하는 이름을 가진 ref만 사용합니다. 패턴은 브랜치 이름, 태그 이름 또는 완전히 지정된 ref 이름일 수 있습니다. 여러 번 주어지면, 주어진 쉘 패턴 중 하나와 일치하는 이름을 가진 ref를 사용합니다. `--no-refs`를 사용하여 이전에 주어진 ref 패턴을 모두 지울 수 있습니다.

--exclude=<pattern>::
	주어진 쉘 패턴과 일치하는 이름을 가진 ref는 사용하지 않습니다. 패턴은 브랜치 이름, 태그 이름 또는 완전히 지정된 ref 이름 중 하나일 수 있습니다. 여러 번 주어지면, ref는 주어진 패턴 중 하나 이상과 일치하고 `--exclude` 패턴 중 어떤 것과도 일치하지 않을 때 사용됩니다. `--refs`와 함께 사용될 때, ref는 최소한 하나의 `--refs` 패턴과 일치하고 어떤 `--exclude` 패턴과도 일치하지 않을 때만 사용됩니다. `--no-exclude`를 사용하여 제외 패턴 목록을 지울 수 있습니다.

--all::
	모든 ref에서 도달 가능한 모든 커밋을 나열합니다.

--annotate-stdin::
	표준 입력의 모든 40자리 SHA-1 16진수 (예: $hex)를 "$hex ($rev_name)"으로 치환하여 표준 입력을 변환합니다. `--name-only`와 함께 사용될 때, "$rev_name"으로 치환하고 $hex는 완전히 생략합니다. 이 옵션은 이전 버전의 Git에서는 `--stdin`으로 불렸습니다.
+
예시:
+
-----------
$ cat sample.txt

축약된 리비전 2ae0a9cb82는 치환되지 않습니다.
치환 후 전체 이름은 2ae0a9cb8298185a94e5998086f380a355dd8907이며,
그 트리 객체는 70d105cc79e63b81cfdcb08a15297c23e60b07ad입니다.

$ git name-rev --annotate-stdin <sample.txt

축약된 리비전 2ae0a9cb82는 치환되지 않습니다.
치환 후 전체 이름은 2ae0a9cb8298185a94e5998086f380a355dd8907 (master)이며,
그 트리 객체는 70d105cc79e63b81cfdcb08a15297c23e60b07ad입니다.

$ git name-rev --name-only --annotate-stdin <sample.txt

축약된 리비전 2ae0a9cb82는 치환되지 않습니다.
치환 후 전체 이름은 master이며,
그 트리 객체는 70d105cc79e63b81cfdcb08a15297c23e60b07ad입니다.
-----------

--name-only::
	SHA-1과 이름을 모두 출력하는 대신 이름만 출력합니다. `--tags`와 함께 주어지면, 일반적인 태그 접두사 "tags/"도 이름에서 생략되어 `git-describe`의 출력에 더 가깝게 일치합니다.

--no-undefined::
	참조가 정의되지 않았을 때 "undefined"를 출력하는 대신 오류 코드 != 0으로 종료됩니다.

--always::
	폴백으로 고유하게 축약된 커밋 객체를 표시합니다.

EXAMPLES
--------

커밋이 주어졌을 때, 해당 커밋이 로컬 ref에 대해 상대적으로 어디에 있는지 찾습니다. 누군가가 여러분에게 환상적인 커밋 33db5f4d9027a10e477ccf054b2c1ab94f74c85a에 대해 썼다고 가정해 봅시다. 물론, 커밋을 살펴보겠지만, 그것은 단지 무슨 일이 일어났는지 알려줄 뿐, 맥락은 알려주지 않습니다.

'git name-rev'를 사용해 봅시다:

------------
% git name-rev 33db5f4d9027a10e477ccf054b2c1ab94f74c85a
33db5f4d9027a10e477ccf054b2c1ab94f74c85a tags/v0.99~940
------------

이제 더 현명해졌습니다. v0.99보다 940개의 리비전 이전이라는 것을 알기 때문입니다.

할 수 있는 또 다른 좋은 점은 다음과 같습니다:

------------
% git log | git name-rev --annotate-stdin
------------

GIT
---
linkgit:git[1] 시리즈의 일부