git-filter-branch(1)
====================

NAME
----
git-filter-branch - 브랜치 재작성

SYNOPSIS
--------
[verse]
'git filter-branch' [--setup <command>] [--subdirectory-filter <directory>]
	[--env-filter <command>] [--tree-filter <command>]
	[--index-filter <command>] [--parent-filter <command>]
	[--msg-filter <command>] [--commit-filter <command>]
	[--tag-name-filter <command>] [--prune-empty]
	[--original <namespace>] [-d <directory>] [-f | --force]
	[--state-branch <branch>] [--] [<rev-list-options>...]

WARNING
-------
'git filter-branch'는 의도된 히스토리 재작성에 대한 예상치 못한
결과를 초래할 수 있는 많은 함정이 있습니다 (그리고 매우 낮은 성능
때문에 이러한 문제를 조사할 시간이 거의 없을 수 있습니다).
이러한 안전 및 성능 문제는 이전 호환 방식으로 수정할 수 없으며
따라서 사용을 권장하지 않습니다. 대신 https://github.com/newren/git-filter-repo/[git
filter-repo]와 같은 대체 히스토리
필터링 도구를 사용하십시오. 그래도 'git filter-branch'를 사용해야 하는 경우,
carefully read <<SAFETY>>(그리고 <<PERFORMANCE>>)를 읽고 filter-branch의
위험에 대해 알아본 다음, 그곳에 나열된 위험 요소를 가능한 한
경계하면서 피하십시오.

DESCRIPTION
-----------
지정된 <rev-list-options>에 포함된 브랜치의 Git 리비전 히스토리를
다시 작성할 수 있게 합니다. 각 리비전에 사용자 정의 필터를 적용합니다.
이러한 필터는 각 트리(예: 파일 제거 또는 모든 파일에 대한 perl
rewrite 실행) 또는 각 커밋에 대한 정보를 수정할 수 있습니다.
그렇지 않으면 모든 정보(원본 커밋 시간 또는 머지 정보 포함)는 보존됩니다.

명령은 명령줄에 지정된 _긍정적인_ ref만 다시 작성합니다 (예: 'a..b'를
전달하면 'b'만 다시 작성됩니다).
필터를 지정하지 않으면 커밋은 아무런 변경 없이 다시 커밋되므로
일반적으로 아무런 효과가 없습니다. 그럼에도 불구하고, Git 버그 또는
이와 유사한 경우를 보상하는 데 유용할 수 있으므로 이러한 사용은
허용됩니다.

*참고*: 이 명령은 `.git/info/grafts` 파일과
`refs/` 네임스페이스의 ref를 존중합니다.
graft 또는 대체 ref가 정의되어 있으면 이 명령을 실행하면
영구적으로 적용됩니다.

*경고*! 다시 작성된 히스토리는 모든
객체에 대해 다른 객체 이름을 가지며 원본 브랜치와 수렴하지 않습니다.
다시 작성된 브랜치를 원본 브랜치 위에 쉽게 푸시하고 배포할 수 없습니다.
전체 영향을 알지 못하면 이 명령을 사용하지 마십시오.
단순한 단일 커밋으로 문제를 해결할 수 있다면 그래도 사용하지 마십시오.
(이전 발행된 히스토리를 다시 작성하는 것에 대한 추가 정보는
linkgit:git-rebase[1]의 "RECOVERING FROM UPSTREAM
REBASE" 섹션을 참조하십시오.)

다시 작성된 버전이 올바른지 항상 확인하십시오: 원본 ref는
다시 작성된 ref와 다른 경우 'refs/original/' 네임스페이스에
저장됩니다.

이 작업은 I/O 비용이 매우 많이 들기 때문에,
`-d` 옵션을 사용하여 임시 디렉토리를 디스크 외부(예: tmpfs)로
리디렉션하는 것이 좋을 수 있습니다. 속도 향상이 매우 두드러지다고
보고되었습니다.

Filters
~~~~~~~

필터는 아래 나열된 순서대로 적용됩니다. <command>
인수는 'eval' 명령을 사용하여 항상 쉘 컨텍스트에서 평가됩니다
(커밋 필터 제외, 기술적 이유로).
그 전에, `$GIT_COMMIT` 환경 변수가 다시 작성되는 커밋의 ID를
포함하도록 설정됩니다. 또한, GIT_AUTHOR_NAME,
GIT_AUTHOR_EMAIL, GIT_AUTHOR_DATE, GITTER_NAME, GIT_COMMITTER_EMAIL,
및 GIT_COMMITTER_DATE는 현재 커밋에서 가져와 환경으로 내보내집니다.
필터가 실행된 후 linkgit:git-commit-tree[1]에 의해 생성되는
대체 커밋의 작성자 및 커미터 식별자에 영향을 미치기 위해서입니다.

<command>의 평가 중 어느 것이든 0이 아닌 종료 상태를 반환하면
전체 작업이 중단됩니다.

'map' 함수를 사용할 수 있습니다. 이 함수는 "원본 sha1 id"를 인수로
받고 커밋이 이미 다시 작성된 경우 "다시 작성된 sha1 id"를
출력하고, 그렇지 않은 경우 "원본 sha1 id"를 출력합니다. 'map' 함수는
커밋 필터가 여러 개의 커밋을 내보낸 경우 여러 ID를 별도 줄로 반환할 수 있습니다.

OPTIONS
-------

--setup <command>::
	이것은 각 커밋에 대해 실행되는 실제 필터가 아니라 루프 직전에
	한 번 실행되는 설정입니다. 따라서 아직 커밋별 변수는 정의되지
	않았습니다. 여기에 정의된 함수 또는 변수는 커밋 필터를
	제외한 후속 필터 단계에서 사용하거나 수정할 수 있습니다 (기술적
	이유).

--subdirectory-filter <directory>::
	주어진 하위 디렉토리만 터치하는 히스토리만 살펴봅니다.
	결과는 해당 디렉토리만 프로젝트 루트로 포함합니다. <<Remap_to_ancestor>>를
	의미합니다.

--env-filter <command>::
	커밋이 수행될 환경만 수정해야 하는 경우 이 필터를 사용할 수 있습니다.
	특히 작성자/커미터 이름/이메일/시간 환경 변수를
	다시 작성하려고 할 수 있습니다 (linkgit:git-commit-tree[1] 참조).

--tree-filter <command>::
	트리와 그 내용을 다시 작성하기 위한 필터입니다.
	인수는 체크아웃된 트리의 루트로 작업 디렉토리가 설정된 쉘에서
	평가됩니다. 새 트리는 그대로 사용됩니다 (새 파일은 자동 추가되고,
	사라진 파일은 자동 제거됩니다 - .gitignore 파일이나 다른 무시
	규칙은 _효과가 없습니다_!).

--index-filter <command>::
	인덱스를 다시 작성하기 위한 필터입니다. 트리 필터와 유사하지만
	트리를 체크아웃하지 않으므로 훨씬 빠릅니다. `git rm --cached
	--ignore-unmatch ...`와 함께 자주 사용됩니다. 복잡한
	경우는 linkgit:git-update-index[1]을 참조하십시오.

--parent-filter <command>::
	커밋의 부모 목록을 다시 작성하기 위한 필터입니다.
	표준 입력으로 부모 문자열을 받고 표준 출력으로 새 부모 문자열을
	출력해야 합니다. 부모 문자열은 linkgit:git-commit-tree[1]에
	설명된 형식입니다: 초기 커밋의 경우 비어 있고, 일반 커밋의 경우
	"-p parent"이며, 머지 커밋의 경우 "-p parent1 -p parent2 -p parent3 ..."
	입니다.

--msg-filter <command>::
	커밋 메시지를 다시 작성하기 위한 필터입니다.
	인수는 원본 커밋 메시지가 표준 입력에 있는 쉘에서 평가됩니다.
	표준 출력은 새 커밋 메시지로 사용됩니다.

--commit-filter <command>::
	커밋을 수행하기 위한 필터입니다.
	이 필터가 지정되면 'git commit-tree' 명령 대신 호출됩니다.
	인수는 "<TREE_ID> [(-p <PARENT_COMMIT_ID>)...]" 형식이며
	로그 메시지는 표준 입력으로 전달됩니다. 커밋 ID는 표준 출력으로
	예상됩니다.
+
특별한 확장으로, 커밋 필터는 여러
커밋 ID를 내보낼 수 있습니다. 이 경우 원본 커밋의 다시 작성된
자식은 모두 부모로 갖게 됩니다.
+
이 필터에서 'map' 편의 함수와 다른 편의 함수를 사용할 수 있습니다.
예를 들어, 'skip_commit "$@"'를 호출하면 현재 커밋을 제외합니다 (하지만
해당 변경 사항은 제외하지 않습니다! 이를 원하면 대신 'git rebase'를
사용하십시오).
+
단일 부모를 가진 커밋과 트리에 변경이 없는 경우를 유지하고 싶지 않으면
`git commit-tree "$@"` 대신 `git_commit_non_empty_tree "$@"`를
사용할 수도 있습니다.

--tag-name-filter <command>::
	태그 이름을 다시 작성하기 위한 필터입니다. 전달될 때,
	다시 작성된 객체(또는 다시 작성된 객체를 가리키는 태그 객체)를
	가리키는 모든 태그 ref에 대해 호출됩니다.
	원본 태그 이름은 표준 입력을 통해 전달되며, 새 태그 이름은
	표준 출력으로 예상됩니다.
+
원본 태그는 삭제되지 않지만 덮어쓰일 수 있습니다.
태그를 단순히 업데이트하려면 "--tag-name-filter cat"을 사용하십시오.
이 경우 매우 주의하고 변환이 잘못되었을 경우를 대비하여 기존 태그를
백업했는지 확인하십시오.
+
태그 객체의 거의 정확한 다시 작성이 지원됩니다. 태그에
메시지가 첨부되어 있으면 동일한 메시지, 작성자 및 타임스탬프로
새 태그 객체가 생성됩니다. 태그에 서명이 첨부되어 있으면
서명이 제거됩니다. 정의상 서명을 보존하는 것은 불가능합니다.
이것이 "거의" 정확한 이유는, 태그가 변경되지 않은 경우(동일한
객체를 가리키고, 동일한 이름을 가지는 등) 서명을 유지해야 하기 때문입니다.
이것은 사실이 아닙니다. 서명은 항상 제거됩니다. 구매자는 주의해야 합니다.
작성자나 타임스탬프(또는 태그 메시지)를 변경하는 것도 지원되지 않습니다.
다른 태그를 가리키는 태그는 밑단의 커밋을 가리키도록 다시 작성됩니다.

--prune-empty::
	일부 필터는 트리를 수정하지 않는 빈 커밋을 생성합니다.
	이 옵션은 git-filter-branch에게 이러한 커밋이 0개 또는 1개의
	비-pruned 부모를 가진 경우 제거하도록 지시합니다. 따라서 머지
	커밋은 그대로 유지됩니다. 이 옵션은 `--commit-filter`와 함께
	사용할 수 없으며, 커밋 필터에서 제공된 `git_commit_non_empty_tree`
	함수를 사용하여 동일한 효과를 얻을 수 있습니다.

--original <namespace>::
	원본 커밋이 저장될 네임스페이스를 설정하려면 이 옵션을 사용하십시오.
	기본값은 'refs/original'입니다.

-d <directory>::
	재작성을 위해 사용될 임시 디렉토리의 경로를 설정하려면 이 옵션을 사용하십시오.
	트리 필터를 적용할 때, 명령은 트리를 임시로 어떤
	디렉토리로 체크아웃해야 하므로, 대규모 프로젝트의 경우 상당한
	공간을 소비할 수 있습니다. 기본적으로 `.git-rewrite/` 디렉토리에서
	수행하지만 이 매개변수로 해당 선택을 재정의할 수 있습니다.

-f::
--force::
	'git filter-branch'는 기존 임시 디렉토리가 있거나 'refs/original/'로
	시작하는 ref가 이미 있는 경우 강제로 시작하지 않으면 거부합니다.

--state-branch <branch>::
	이 옵션은 시작 시 명명된 브랜치에서 이전 객체와 새 객체 간의
	매핑을 로드하고 종료 시 해당 브랜치로 새 커밋으로 저장하도록
	합니다. 이를 통해 대형 트리의 증분 작업이 가능해집니다. '<branch>'가
	존재하지 않으면 생성됩니다.

<rev-list options>...::
	'git rev-list'에 대한 인수입니다. 이러한 옵션에 포함된 모든
	긍정적인 ref는 다시 작성됩니다. `--all`과 같은 옵션을 지정할 수도
	있지만, 'git filter-branch' 옵션과 분리하기 위해 `--`를 사용해야
	합니다. <<Remap_to_ancestor>>를 의미합니다.

[[Remap_to_ancestor]]
조상으로 다시 매핑
~~~~~~~~~~~~~~~~~

linkgit:git-rev-list[1] 인수(예: 경로 제한기)를 사용하여 다시 작성될
리비전 집합을 제한할 수 있습니다. 그러나 명령줄의 긍정적인 ref는
구별됩니다. 이러한 제한기가 이러한 ref를 제외하도록 허용하지 않습니다.
이 목적을 위해 대신 제외되지 않은 가장 가까운 조상을 가리키도록
다시 작성됩니다.

EXIT STATUS
-----------

성공 시 종료 상태는 `0`입니다. 필터가 다시 작성할 커밋을 찾지 못하면
종료 상태는 `2`입니다. 다른 오류 발생 시 종료 상태는 0이 아닌 다른
값일 수 있습니다.

EXAMPLES
--------

비밀 정보나 저작권 침해 내용이 포함된 파일을 모든 커밋에서 제거하고
싶다고 가정해 보겠습니다:

-------------------------------------------------------
git filter-branch --tree-filter 'rm filename' HEAD
-------------------------------------------------------

그러나 파일이 일부 커밋의 트리에서 누락된 경우,
단순 `rm filename`은 해당 트리 및 커밋에 대해 실패합니다.
따라서 해당 스크립트로 `rm -f filename`을 대신 사용하고 싶을 수 있습니다.

'git rm'과 함께 `--index-filter`를 사용하면 훨씬 빠른
버전을 얻을 수 있습니다. `rm filename`을 사용하는 것처럼,
파일이 커밋의 트리에서 누락된 경우 `git rm --cached filename`은
실패합니다. 파일을 "완전히 잊고" 싶다면, 히스토리에 언제
들어갔는지는 중요하지 않으므로 `--ignore-unmatch`도 추가합니다:

--------------------------------------------------------------------------
git filter-branch --index-filter 'git rm --cached --ignore-unmatch filename' HEAD
--------------------------------------------------------------------------

이제, 다시 작성된 히스토리가 HEAD에 저장됩니다.

저장소를 마치 `foodir/`가 프로젝트 루트였던 것처럼 다시 작성하고
다른 모든 히스토리를 삭제하려면:

-------------------------------------------------------
git filter-branch --subdirectory-filter foodir -- --all
-------------------------------------------------------

따라서 라이브러리 하위 디렉토리를 자체 저장소로
만들 수 있습니다. 'filter-branch' 옵션과
리비전 옵션을 구분하는 `--` 및 모든 브랜치와 태그를 다시 작성하기 위한
`--all`에 유의하십시오.

현재 초기 커밋의 부모로 커밋(일반적으로 다른
히스토리의 맨 위에 있는 커밋)을 설정하여 다른 히스토리를 현재
히스토리 뒤에 붙이고 싶을 때:

-------------------------------------------------------------------
git filter-branch --parent-filter 'sed "s/^\$/-p <graft-id>/"' HEAD
-------------------------------------------------------------------

(부모 문자열이 비어 있는 경우 - 초기 커밋을 처리할 때 발생 - graftcommit을
부모로 추가합니다). 이 경우 단일 루트를 가진 히스토리를 가정합니다
(즉, 공통 조상이 없는 머지는 발생하지 않았음). 그렇지 않은 경우:

--------------------------------------------------------------------------
git filter-branch --parent-filter \
	'test $GIT_COMMIT = <commit-id> && echo "-p <graft-id>" || cat' HEAD
--------------------------------------------------------------------------

또는 더 간단하게:

-----------------------------------------------
git replace --graft $commit-id $graft-id
git filter-branch $graft-id..HEAD
-----------------------------------------------

"Darl McBribe"에 의해 작성된 커밋을 히스토리에서 제거하려면:

------------------------------------------------------------------------------
git filter-branch --commit-filter '
	if [ "$GIT_AUTHOR_NAME" = "Darl McBribe" ];
	then
		skip_commit "$@";
	else
		git commit-tree "$@";
	fi' HEAD
------------------------------------------------------------------------------

'skip_commit' 함수는 다음과 같이 정의됩니다:

--------------------------
skip_commit()
{
	shift;
	while [ -n "$1" ];
	do
		shift;
		map "$1";
		shift;
	done;
}
--------------------------

shift 마술은 먼저 트리 ID를 버리고 그 다음 -p 매개변수를 버립니다.
이것은 머지를 올바르게 처리합니다! Darl이 P1과 P2 사이에 머지를
커밋한 경우, 적절하게 전달되며 머지 커밋 대신 머지의 모든 자식은
P1, P2를 부모로 하는 머지 커밋이 됩니다.

*참고* 커밋에 의해 도입된 변경 사항 중 후속 커밋에 의해
되돌려지지 않은 것은 다시 작성된 브랜치에 남아 있습니다.
_변경 사항_과 커밋을 함께 버리고 싶다면 'git rebase'의
대화형 모드를 사용해야 합니다.

`--msg-filter`를 사용하여 커밋 로그 메시지를 다시 작성할 수 있습니다.
예를 들어, 'git svn-id' 문자열은 'git svn'에 의해 생성된 저장소에서
이런 식으로 제거할 수 있습니다:

-------------------------------------------------------
git filter-branch --msg-filter '
	sed -e "/^git-svn-id:/d"
'
-------------------------------------------------------

마지막 10개 커밋(머지가 아닌 커밋)에 'Acked-by' 줄을 추가해야 하는 경우,
이 명령을 사용하십시오:

--------------------------------------------------------
git filter-branch --msg-filter '
	cat &&
	echo "Acked-by: Bugs Bunny <bunny@bugzilla.org>"
' HEAD~10..HEAD
--------------------------------------------------------

`--env-filter` 옵션은 커미터 및/또는 작성자 식별자를 수정하는 데
사용할 수 있습니다. 예를 들어, 잘못 구성된 user.email 때문에
커밋에 잘못된 식별자가 있다는 것을 알게 된 경우,
프로젝트를 게시하기 전에 다음과 같이 수정할 수 있습니다:

--------------------------------------------------------
git filter-branch --env-filter '
	if test "$GIT_AUTHOR_EMAIL" = "root@localhost"
	then
		GIT_AUTHOR_EMAIL=john@example.com
	fi
	if test "$GIT_COMMITTER_EMAIL" = "root@localhost"
	then
		GIT_COMMITTER_EMAIL=john@example.com
	fi
' -- --all
--------------------------------------------------------

다시 작성을 히스토리의 일부로만 제한하려면, 새 브랜치 이름 외에
리비전 범위를 지정하십시오. 새 브랜치 이름은 이 범위의
'git rev-list'가 인쇄하는 최상위 리비전을 가리킵니다.

다음 히스토리를 고려하십시오:

------------------
     D--E--F--G--H
    /     /
A--B-----C
------------------

D, E, F, G, H 커밋만 다시 작성하고, A, B, C는 그대로 두려면:

--------------------------------
git filter-branch ... C..H
--------------------------------

E, F, G, H 커밋을 다시 작성하려면 다음 중 하나를 사용하십시오:

----------------------------------------
git filter-branch ... C..H --not D
git filter-branch ... D..H --not C
----------------------------------------

전체 트리를 하위 디렉토리로 이동하거나 거기서 제거하려면:

---------------------------------------------------------------
git filter-branch --index-filter \
	'git ls-files -s | sed "s-\t\"*-&newsubdir/-" |
		GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
			git update-index --index-info &&
	 mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"' HEAD
---------------------------------------------------------------

CHECKLIST FOR SHRINKING A REPOSITORY
------------------------------------

git-filter-branch는 파일의 일부를 없애는 데 사용될 수 있으며,
보통 `--index-filter`와 `--subdirectory-filter`의 조합과 함께 사용됩니다.
결과 저장소가 원본보다 작을 것으로 기대하지만, Git이 객체를
삭제하라고 명시적으로 지시하기 전까지는 객체를 잃지 않도록
노력하기 때문에 실제로 작게 만들려면 몇 가지 추가 단계가 필요합니다.
먼저 다음 사항을 확인하십시오:

* Blob이 수명 주기 동안 이동한 경우 파일 이름의 모든 변형을
  실제로 제거했는지 확인하십시오. `git log --name-only --follow --all -- filename`
  은 이름 변경을 찾는 데 도움이 될 수 있습니다.

* 모든 ref를 필터링했는지 확인하십시오: git-filter-branch를
  호출할 때 `--tag-name-filter cat -- --all`을 사용하십시오.

그러면 더 작은 저장소를 얻는 두 가지 방법이 있습니다. 더 안전한 방법은
복제하는 것입니다. 그러면 원본은 그대로 유지됩니다.

* `git clone file:///path/to/repo`로 복제하십시오. 복제된
  저장소에는 제거된 객체가 없습니다. linkgit:git-clone[1]을
  참조하십시오. (단순 경로로 복제하면 모든 것이 하드링크됩니다!)

어떤 이유로든 복제를 원하지 않는다면, 대신 다음 사항을 확인하십시오
(이 순서대로). 이것은 매우 파괴적인 접근 방식이므로,
* 백업을 만들거나* 다시 복제하십시오. 경고했습니다.

* git-filter-branch에 의해 백업된 원본 ref를 제거하십시오: `git
  for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git
  update-ref -d`와 같이 하십시오.

* `git reflog expire --expire=now --all`로 모든 reflog를 만료시키십시오.

* 참조되지 않은 모든 객체를 `git gc --prune=now`로 가비지 수집하십시오
  (`--prune`에 인수를 지원하지 않는 git-gc가 오래된 경우
  `git repack -ad; git prune`을 대신 사용하십시오).

[[PERFORMANCE]]
PERFORMANCE
-----------

git-filter-branch의 성능은 매우 느립니다. 그 설계는 이전 호환
구현이 빨라지는 것을 불가능하게 만듭니다:

* 파일을 편집하는 데 있어, git-filter-branch는 원본 repo에
  존재했던 각 커밋을 확인합니다. repo에 `10^5`개의 파일과 `10^5`개의
  커밋이 있지만 각 커밋이 5개의 파일만 수정하는 경우,
  git-filter-branch는 고유한 blob이 (최대) `5*10^5`개만 있음에도 불구하고
  `10^10`번의 수정을 수행하도록 합니다.

* 속임수를 써서 git-filter-branch가 수정된 파일에만 작동하도록
  하려고 하면 두 가지 문제가 발생합니다.

  ** 사용자가 단순히 파일을 이름 변경하려는 경우 삭제 시 문제가
     발생합니다 (존재하지 않는 파일을 삭제하려고 하면 아무 작업도
     하지 않는 것처럼 보이기 때문입니다. 임의 사용자 제공 쉘을 통한
     이름 변경 시 삭제를 다시 매핑하려면 약간의 기교가 필요합니다).

  ** 이름 변경에 대한 삭제 매핑 기교에 성공하더라도, 사용자가
     파일 내용이나 이름에만 기반하여 필터링하는 대신 커밋의 토폴로지에
     의존하여 파일들을 필터링할 수 있기 때문에 이전 호환성을 기술적으로
     위반하는 것입니다 (비록 이것이 실제로는 관찰되지 않았더라도).

* 파일을 편집할 필요가 없고 단순히 일부를 이름 변경하거나
  제거하므로 각 파일을 확인할 필요가 없다면 (즉, --index-filter를
  사용할 수 있음), 필터에 대한 쉘 스니펫을 전달해야 합니다.
  이는 각 커밋에 대해 해당 필터를 실행할 수 있는 준비된 git repo가
  필요함을 의미합니다. 이는 상당한 설정입니다.

* 또한, git-filter-branch는 각 커밋에 대해 여러 개의 추가 파일을
  생성하거나 업데이트합니다. 일부는 git-filter-branch에서 제공하는
  편의 함수(map() 등)를 지원하기 위한 것이고, 다른 일부는 내부 상태를
  추적하기 위한 것입니다 (하지만 사용자 필터에서 접근할 수도 있습니다.
  git-filter-branch의 회귀 테스트 중 하나가 그렇게 합니다).
  이는 본질적으로 git-filter-branch와 사용자 제공 필터 간의 IPC 메커니즘으로
  파일 시스템을 사용하는 것을 의미합니다. 디스크는 느린 IPC 메커니즘이
  되는 경향이 있으며, 이러한 파일에 쓰는 것은 또한 우리가 각 커밋마다
  맞닥뜨리는 별도의 프로세스 간의 강제 동기화 지점을 나타냅니다.

* 사용자 제공 쉘 명령은 종종 명령 파이프라인을 포함하게 되어
  커밋당 많은 프로세스를 생성하게 됩니다. 다른 프로세스를 생성하고
  실행하는 것은 운영 체제마다 매우 다양한 시간이 걸리지만, 어떤
  플랫폼에서도 함수 호출에 비해 매우 느립니다.

* git-filter-branch 자체는 쉘로 작성되었는데, 이는 다소 느립니다.
  이것은 이전 호환 방식으로 수정될 수 있는 유일한 성능 문제이지만,
  git-filter-branch 설계의 본질적인 위 문제들과 비교할 때 도구 언어
  자체는 상대적으로 사소한 문제입니다.

  ** 측면 관련: 안타깝게도 사람들은 쉘로 작성된 측면에
     집착하는 경향이 있으며, 성능 문제를 해결하기 위해 git-filter-branch를
     다른 언어로 다시 작성할 수 있는지 주기적으로 묻습니다.
     이는 더 큰 근본적인 문제를 무시할 뿐만 아니라, 예상보다
     적게 도움이 됩니다. git-filter-branch 자체가 쉘이 아니라면,
     편의 함수(map(), skip_commit() 등)와 `--setup` 인수는
     프로그램 시작 시 한 번 실행되는 대신 각 사용자 필터에
     (따라서 각 커밋마다 다시 실행됨) 앞에 붙여야 합니다.

https://github.com/newren/git-filter-repo/[git filter-repo] 도구는
이러한 성능 문제나 안전 문제(아래 참조)가 없는 git-filter-branch의
대안입니다. git-filter-branch에 의존하는 기존 도구를 가진 사람들을 위해,
'git filter-repo'는
https://github.com/newren/git-filter-repo/blob/master/contrib/filter-repo-demos/filter-lamely[filter-lamely]도
제공합니다. 이것은 (몇 가지 주의 사항과 함께)
git-filter-branch의 대체품입니다. filter-lamely는 git-filter-branch와
동일한 모든 안전 문제를 겪지만, 최소한 성능 문제는 약간 완화합니다.

[[SAFETY]]
SAFETY
------

git-filter-branch는 저장소를 쉽게 손상시키거나 시작 시보다 더 나쁜
상태로 끝낼 수 있는 다양한 함정으로 가득합니다:

* "작업 중이고 테스트된 필터" 세트를 가지고 그것을 문서화하거나
  동료에게 제공하는 사람이 있을 수 있습니다. 그 동료는 해당 필터를
  동일한 명령이 작동하지 않는 다른 OS에서 실행할 수 있습니다 (git-filter-branch
  맨페이지의 일부 예제도 이에 영향을 받습니다).
  BSD와 GNU 사용자랜드의 차이는 정말 나쁠 수 있습니다. 운이 좋다면,
  오류 메시지가 마구 쏟아질 것입니다. 하지만 거의 비슷하게, 명령은
  요청된 필터링을 수행하지 않거나, 원치 않는 변경을 하여 조용히
  손상시킬 수 있습니다. 원치 않는 변경은 몇 개의 커밋에만 영향을 미칠 수
  있으므로, 그렇게 명확하지도 않습니다. (문제가 반드시 명확하지는
  않다는 사실은 다시 작성된 히스토리가 상당히 오랫동안 사용된 후에야
  발견될 가능성이 높으며, 이때 또 다른 플래그 데이를 또 다른
  다시 작성에 대해 정당화하기가 정말 어렵습니다.)

* 공백이 포함된 파일 이름은 쉘 파이프라인에 문제를 일으키기 때문에
  쉘 스니펫에서 종종 잘못 처리됩니다. 모든 사람이 find -print0,
  xargs -0, git-ls-files -z 등을 능숙하게 다루는 것은 아닙니다.
  아는 사람이라도