git-sparse-checkout(1)
======================

NAME
----
git-sparse-checkout - 워킹 트리의 추적된 파일 집합을 부분 집합으로 줄임


SYNOPSIS
--------
[verse]
'git sparse-checkout' (init | list | set | add | reapply | disable | check-rules | clean) [<options>]


DESCRIPTION
-----------

이 명령은 스파스 체크아웃을 생성하는 데 사용됩니다. 스파스 체크아웃은 워킹 트리에 추적된 모든 파일이 존재하는 것에서 해당 파일의 부분 집합만 존재하는 것으로 변경합니다. 또한 어떤 파일 부분 집합이 존재하는지 전환하거나, 모든 추적된 파일을 워킹 복사본에 다시 존재하도록 되돌릴 수 있습니다.

파일의 부분 집합은 기본값인 콘 모드에서 디렉토리 목록을 제공하거나, 콘 모드가 아닌 모드에서 패턴 목록을 제공하여 선택됩니다.

스파스 체크아웃 모드에 있을 때, 다른 Git 명령은 약간 다르게 동작합니다.
예를 들어, 브랜치를 전환하면 스파스 체크아웃 디렉토리/패턴 외부의 경로는 업데이트되지 않으며, `git commit -a`는 스파스 체크아웃 디렉토리/패턴 외부의 경로를 삭제된 것으로 기록하지 않습니다.

이 명령은 실험적입니다. 이 명령의 동작 및 스파스 체크아웃의 존재 하에서 다른 명령의 동작은 향후 변경될 가능성이 높습니다.


COMMANDS
--------
'list'::
	스파스 체크아웃 파일에 있는 디렉토리 또는 패턴을 설명합니다.

'set'::
	'set' 서브커맨드 다음에 오는 인수 목록에서 스파스 체크아웃 파일을 채우고,
	원하는 값으로 이미 설정되지 않은 경우 필요한 스파스 체크아웃 구성 설정
	(`core.sparseCheckout`, `core.sparseCheckoutCone`, `index.sparse`)을 활성화하고,
	작업 디렉토리를 일치하도록 업데이트합니다.
+
워킹 트리 내에서 스파스 체크아웃 설정을 조정하는 것이 다른 워킹 트리에서의
스파스 체크아웃 설정을 변경하지 않도록 하려면, 'set' 서브커맨드는 이미 존재하지
않는 경우 워크트리별 구성을 사용하도록 저장소 구성을 업그레이드합니다.
'set' 서브커맨드에 대한 인수로 정의된 희소성은 워크트리별 스파스 체크아웃 파일에
저장됩니다. 자세한 내용은 linkgit:git-worktree[1] 및
`linkgit:git-config[1]`의 `extensions.worktreeConfig` 문서를 참조하십시오.
+
`--stdin` 옵션이 제공되면, 디렉토리 또는 패턴은
인수가 아닌 표준 입력에서 줄바꿈으로 구분된 목록으로 읽습니다.
+
기본적으로 입력 목록은 `git ls-tree -d --name-only`의 출력과 일치하는 디렉토리 목록으로 간주됩니다.
이것은 이중 따옴표 (")로 시작하는 경로명을 C 스타일 따옴표 문자열로 해석하는 것을 포함합니다.
명시된 디렉토리 아래의 모든 파일(모든 깊이에서)과 주어진 디렉토리 또는 그 조상 중 하나의 형제인 파일이
스파스 체크아웃에 포함됩니다 (자세한 내용은 아래 'CONE PATTERN SET' 참조).
이전에는 이것이 기본값이 아니었고, `--cone`을 지정하거나 `core.sparseCheckoutCone`을 활성화해야 했습니다.
+
`--no-cone`이 전달되면, 입력 목록은 패턴 목록으로 간주됩니다.
이 모드에는 `--sparse-index`와 같은 일부 옵션과 작동하지 않는 것을 포함하여 몇 가지 단점이 있습니다.
아래 "Non-cone Problems" 섹션에 설명된 대로, 이를 사용하는 것을 권장하지 않습니다.
+
`--[no-]sparse-index` 옵션을 사용하여 스파스 인덱스를 사용하십시오 (기본값은 사용하지 않음).
스파스 인덱스는 인덱스의 크기를 스파스 체크아웃 정의에 더 가깝게 일치하도록 줄입니다.
이는 `git status` 또는 `git add`와 같은 명령에 상당한 성능 이점을 줄 수 있습니다.
이 기능은 아직 실험적입니다. 이 기능과 제대로 통합될 때까지 일부 명령은 스파스 인덱스로 인해 더 느릴 수 있습니다.
+
**경고:** 스파스 인덱스를 사용하려면 인덱스를 외부 도구가 완전히 이해하지 못하는 방식으로 수정해야 합니다.
이 호환성으로 문제가 발생하는 경우, `git sparse-checkout init --no-sparse-index`를 실행하여
인덱스를 스파스가 아니도록 다시 작성하십시오. 이전 버전의 Git은 스파스 디렉토리 항목 인덱스 확장 기능을 이해하지 못하며,
비활성화될 때까지 저장소와 상호 작용하지 못할 수 있습니다.

'add'::
	스파스 체크아웃 파일을 업데이트하여 추가 디렉토리
	(콘 모드) 또는 패턴 (콘 모드 아님)을 포함합니다.
	기본적으로, 이 디렉토리 또는 패턴은 명령줄 인수에서 읽어오지만,
	`--stdin` 옵션을 사용하여 stdin에서 읽을 수 있습니다.

'reapply'::
	스파스 패턴 규칙을 워킹 트리의 경로에 다시 적용합니다.
	merge 또는 rebase와 같은 명령은 작업을 수행하기 위해 경로를 구체화할 수 있습니다
	(예: 충돌을 보여주기 위해), 그리고 다른
	스파스 체크아웃 명령은 개별 파일을 스파스화하는 데 실패할 수 있습니다
	(예: 스테이징되지 않은 변경 사항이나 충돌이 있는 경우).
	이러한 경우, 영향을 받은 경로를 정리한 후 (예: 충돌 해결,
	변경 사항 취소 또는 커밋 등) `git sparse-checkout reapply`를 나중에 실행하는 것이 좋습니다.
+
`reapply` 명령은 `set` 명령의 플래그와 동일한 의미로
`--[no-]cone` 및 `--[no-]sparse-index` 플래그를 사용할 수도 있습니다.
이는 모든 스파스 경로를 다시 지정할 필요 없이 어떤 스파스 모드를 사용하고 있는지 변경하기 위한 것입니다.

'clean'::
	스파스 체크아웃 정의 외부의 파일을 기회적으로 제거합니다.
	이 명령은 재귀 디렉토리 일치를 사용하여 제거할 파일을 결정하기 위해
	콘 모드를 필요로 합니다.
	파일은 추적된 디렉토리 내에 있고 스파스 체크아웃 정의 밖에 있는 경우
	제거 대상으로 간주됩니다.
+
병합 충돌이나 스파스 체크아웃 정의 외부의 수정된 파일과 같은 일부 특수한 경우는
그렇지 않으면 제거될 파일들을 유지하게 할 수 있습니다.
충돌을 해결하고, 수정을 스테이징하고, `git sparse-checkout reapply`와
`git sparse-checkout clean`을 함께 사용하여 이러한 경우를 해결하십시오.
+
이 명령은 스파스 인덱스가 효율적으로 작동하도록 하는 데 사용될 수 있습니다.
물론 `index.sparse=true` 구성을 통해 스파스 인덱스 기능을 활성화할 필요는 없습니다.
+
작업 트리 파일의 우발적인 삭제를 방지하기 위해, `clean` 서브커맨드는
`-f` 또는 `--force` 옵션 없이는 파일을 삭제하지 않으며, `clean.requireForce` 설정 옵션이
`false`로 설정되지 않는 한 그렇습니다.
+
`--dry-run` 옵션은 삭제하지 않고 제거될 디렉토리를 나열합니다.
이 모드로 실행하는 것은 clean 명령의 동작을 예측하거나
어떤 종류의 파일이 스파스 디렉토리에 남아 있는지 결정하는 데 도움이 될 수 있습니다.
+
`--verbose` 옵션은 제거 대상으로 간주되는 디렉토리 내의 모든 파일을 나열합니다.
이 옵션은 해당 파일이 실제로 중요한지 또는 현재 스파스 체크아웃에도 불구하고
디렉토리가 여전히 존재하는 이유를 설명하는 데 도움이 됩니다.

'disable'::
	`core.sparseCheckout` 구성 설정을 비활성화하고,
	모든 파일을 포함하도록 작업 디렉토리를 복원합니다.

'init'::
	지정된 경로 없이 `set`과 유사하게 작동하는 폐지된 명령입니다.
	향후 제거될 수 있습니다.
+
역사적으로 `set`은 필요한 모든 구성 설정을 처리하지 않았으므로,
`init`과 `set`을 모두 호출해야 했습니다.
두 가지를 모두 호출하면 `init` 단계에서 거의 모든 추적된 파일을 제거하고 (콘 모드에서는 무시된 파일도 제거),
그러면 `set` 단계에서 추적된 파일 중 많은 것을 (무시된 파일은 제외) 다시 추가했습니다.
사라진 파일 외에도 이 조합의 성능과 UI는 좋지 않았습니다.
+
또한 역사적으로 `init`은 스파스 체크아웃 파일이 이미 존재하는 경우 실제로는 초기화하지 않았습니다.
이는 스파스 체크아웃으로 돌아갈 때 후속 'set' 또는 'add' 명령에 전달할 경로를
기억하지 못할 수 있었음을 의미합니다. 그러나 `--cone` 및 `--sparse-index` 옵션은
disable 명령 간에 기억되지 않았으므로, 단순 `init`을 호출하여 쉽게 복원하는 유틸리티가 감소했습니다.

'check-rules'::
	스파스 규칙이 하나 이상의 경로와 일치하는지 확인합니다.
+
기본적으로 `check-rules`는 stdin에서 경로 목록을 읽고 현재 스파스 규칙과
일치하는 것만 출력합니다. 입력은 한 줄에 하나의 경로를 포함해야 하며,
`git ls-tree --name-only`의 출력과 일치합니다. 이중 따옴표 (")로 시작하는
경로명은 C 스타일 따옴표 문자열로 해석됩니다.
+
`--rules-file <file>` 플래그와 함께 호출될 때, 입력 파일은 현재의
스파스 체크아웃 규칙 대신 `<file>`에 있는 스파스 체크아웃 규칙과 일치합니다.
파일의 규칙은 `git sparse-checkout set --stdin`이 허용하는 형식과 동일하게 예상됩니다
(특히, 줄바꿈으로 구분되어야 합니다).
+
기본적으로 `--rules-file` 옵션에 전달된 규칙은 콘 모드 디렉토리로 해석됩니다.
`--rules-file`로 콘 모드 아님 패턴을 전달하려면, 이 옵션을 `--no-cone` 옵션과 함께 사용하십시오.
+
`-z` 플래그와 함께 호출될 때, stdin에 있는 경로의 형식과 출력 경로는
널 문자로 종료되고 따옴표로 묶이지 않습니다. 참고로 이것은 `--rules-file` 옵션으로 전달된
규칙 형식에는 적용되지 않습니다.


EXAMPLES
--------
`git sparse-checkout set MY/DIR1 SUB/DIR2`::

	MY/DIR1/ 및 SUB/DIR2/ 아래의 모든 파일 (모든 깊이에서)이 워킹 복사본에
	있는 스파스 체크아웃으로 변경합니다 (MY/, SUB/ 및 최상위 디렉토리의
	바로 아래 파일도 포함). 이미 스파스 체크아웃 상태인 경우,
	워킹 복사본에 있는 파일을 이 새로운 선택으로 변경합니다.
	이 명령은 또한 더 이상 추적된 파일이나 무시되지 않은 추적되지 않은 파일이
	없는 모든 디렉토리의 무시된 파일을 삭제합니다.

`git sparse-checkout disable`::

	모든 파일을 포함하도록 워킹 디렉토리를 다시 채우고 스파스
	체크아웃을 비활성화합니다.

`git sparse-checkout add SOME/DIR/ECTORY`::

	SOME/DIR/ECTORY/ 아래의 모든 파일 (모든 깊이에서)을
	스파스 체크아웃에 추가합니다. IMMEDIATE/DIR/의 바로 아래 파일도
	추가합니다. 이 명령을 사용하기 전에 반드시 스파스 체크아웃 상태여야 합니다.

`git sparse-checkout reapply`::

	명령이 선택된 스파스 디렉토리를 존중하지 않는 방식으로 워킹 트리를
	업데이트할 수 있습니다. 이는 Git 외부의 도구가 파일을 작성하거나,
	병합/리베이스 시 충돌 발생과 같은 특별한 경우 때문에 Git 명령에 영향을 미치거나,
	일부 명령이 스파스 체크아웃을 완전히 지원하지 않았기 때문입니다
	(예: 이전 `recursive` 병합 백엔드는 제한적인 지원만 했습니다).
	이 명령은 기존 스파스 디렉토리 사양을 다시 적용하여
	워킹 디렉토리가 일치하도록 합니다.

INTERNALS -- SPARSE CHECKOUT
----------------------------

"스파스 체크아웃"은 워킹 디렉토리를 스파스하게 채울 수 있게 합니다.
이것은 skip-worktree 비트 (linkgit:git-update-index[1] 참조)를 사용하여
Git에게 파일이 볼 가치가 있는지 여부를 알려줍니다. skip-worktree 비트가 설정되어 있고
파일이 워킹 트리에 존재하지 않으면, 해당 파일의 부재는 무시됩니다. Git은
이러한 파일의 내용을 채우는 것을 피할 것이며, 이는 많은 파일을 가진 저장소에서 작업할 때
많은 파일 중 현재 사용자에게 중요한 파일이 적은 경우 스파스 체크아웃이 유용하게 만듭니다.

$GIT_DIR/info/sparse-checkout 파일은
skip-worktree 참조 비트맵을 정의하는 데 사용됩니다. Git이 워킹 디렉토리를
업데이트할 때, 이 파일을 기반으로 인덱스의 skip-worktree 비트를 업데이트합니다.
파일의 패턴과 일치하는 파일은 워킹 디렉토리에 나타나고, 나머지는 나타나지 않습니다.

INTERNALS -- NON-CONE PROBLEMS
------------------------------

`set` 및 `add` 서브커맨드에 의해 채워지는 $GIT_DIR/info/sparse-checkout 파일은
`.gitignore` 파일과 동일한 구문을 사용하는 패턴 모음으로 정의됩니다.
콘 모드에서는 이러한 패턴이 디렉토리에만 일치하도록 제한됩니다 (사용자는 디렉토리 이름만
제공하거나 볼 필요가 있음). 콘 모드가 아닌에서는 모든 gitignore 스타일 패턴이 허용됩니다.
논-콘 모드에서 전체 gitignore 스타일 패턴을 사용하는 것은 여러 가지 단점이 있습니다:

  * 근본적으로, 이는 다양한 워크트리 업데이트 프로세스 (pull,
    merge, rebase, switch, reset, checkout 등)가 O(N*M) 패턴 일치가 필요하게 만듭니다.
    여기서 N은 패턴 수이고 M은 인덱스의 경로 수입니다. 이는 확장이 잘 되지 않습니다.

  * 확장성 문제를 피하기 위해서는 선행 디렉토리 이름이나 glob을 명시하여
    패턴 수를 제한해야 합니다.

  * glob을 명령줄에 전달하는 것은 사용자가 glob을 따옴표로 묶는 것을 잊어서 쉘이
    모든 일치하는 파일로 확장하여 이를 개별적으로
    sparse-checkout set/add에 전달하는 오류를 범할 수 있기 때문에 오류 발생 가능성이 높습니다.
    이것은 "git grep -- *.c"와 같은 경우에도 문제가 될 수 있지만, grep/log/status의 오류는
    즉각적인 출력에서 나타납니다. sparse-checkout의 경우, 오류는
    스파스 체크아웃 명령이 실행될 때 기록되며 사용자가 나중에 브랜치를 전환하거나 리베이스하거나 병합할 때까지
    문제가 되지 않을 수 있으며, 사용자의 오류와 이를 발견/인지할 기회 사이에 지연이 발생합니다.

  * 이전 항목과 관련하여, sparse-checkout에는 'add' 서브커맨드는 있지만 'remove' 서브커맨드는 없습니다.
    'remove' 서브커맨드가 추가되더라도, 우발적인 따옴표 없는 glob을 되돌리는 것은
    "너무 많이 제거"할 위험이 있습니다. 왜냐하면 우발적인 추가 이전에 포함되었던 항목들을 제거할 수 있기 때문입니다.

  * 논-콘 모드는 무엇을 *포함*할지를 선택하기 위해 gitignore 스타일 패턴을 사용합니다
    (제외 패턴 제외).  .gitignore 파일은 무엇을 *제외*할지를 선택하기 위해 gitignore 스타일 패턴을 사용합니다
    (제외 패턴 제외). gitignore 스타일 패턴에 대한 문서는 일반적으로
    일치 또는 불일치가 아닌, 사용자가 "제외"하려는 것에 대해 이야기합니다.
    이것은 사용자가 원하는 동작을 얻기 위해 스파스 체크아웃 패턴을 지정하는 방법을 배울 때 혼란을 야기할 수 있습니다.

  * "특별한 경로 패턴 일치"를 제공하려는 다른 모든 git 서브커맨드는 pathspec을 사용하지만,
    스파스 체크아웃의 논-콘 모드는 gitignore 패턴을 사용하며, 이는 일관성이 떨어져 보입니다.

  * "올바른" 동작이 불분명한 엣지 케이스가 있습니다. 두 가지 예:
+
첫째, 두 사용자가 하위 디렉토리에 있고, 첫 번째 사용자가 실행합니다
+
----
git sparse-checkout set '/toplevel-dir/*.c'
----
+
두 번째 사용자는 실행합니다
+
----
git sparse-checkout set relative-dir
----
+
해당 인수를
+
----
current/subdirectory/toplevel-dir/*.c
----
+
및
+
----
current/subdirectory/relative-dir
----
+
로 변환하여 스파스 체크아웃 파일에 삽입해야 할까요? 첫 번째 명령을 입력한 사용자는
set/add의 인수가 논-콘 모드에서 패턴이라고 가정하고 있을 가능성이 높으며,
이러한 변환에 만족하지 않을 것입니다. 그러나 많은 gitignore 스타일 패턴은 단순히 경로이며,
두 번째 명령을 입력한 사용자가 생각하고 있던 것일 수 있으며, 해당 인수가 변환되지 않으면 불만을 느낄 것입니다.
+
둘째, 논-콘 모드 사용자를 위한 set/add 명령에 대해 bash-completion은 무엇을 완성해야 할까요?
경로를 제안한다면, 이는 위의 문제를 악화시키는 것일까요? 또한, 경로를 제안한다면,
사용자가 '!' 또는 '#'로 시작하는 파일이나 디렉토리가 있거나, '*' , '\', '?', '[', 또는 ']'를
이름에 가지고 있다면 어떻게 될까요? 그리고 경로를 제안한다면, 현재 디렉토리의 "/progress.txt"가 아닌
(루트 파일 시스템에서) "/pro"를 "/proc"으로 완성할까요? (사용자는 논-콘 모드에서 선행 '/'로 경로를 시작하기를 원할 가능성이 높습니다.
.gitignore 파일이 종종 하나를 가지고 있는 것과 같은 이유입니다.)
파일이나 디렉토리를 완성하면 이러한 모든 경우에 나쁜 놀라움을 줄 수 있습니다.

  * 과도한 유연성으로 인해 다른 확장이 본질적으로 비현실적이었습니다.
    `--sparse-index`는 논-콘 모드에서 불가능할 가능성이 높습니다.
    어떻게든 가능하더라도 구현하는 데 훨씬 더 많은 작업이 필요했을 것이며,
    실제로는 너무 느렸을 수 있습니다. 부분적 복제와 스파스 체크아웃 간의 커플링을
    추가하기 위한 일부 아이디어는 더 제한된 경로 집합으로만 실현 가능합니다.

이러한 모든 이유로 인해 논-콘 모드는 폐지됩니다. 콘 모드로 전환해 주십시오.


INTERNALS -- CONE MODE HANDLING
-------------------------------

기본값인 "콘 모드"는 디렉토리만 지정할 수 있게 합니다.
지정된 모든 디렉토리에 대해, 해당 디렉토리 아래의 모든 경로는 포함되며,
선행 디렉토리 (최상위 디렉토리 포함)의 바로 아래에 있는 모든 파일도 포함됩니다.
따라서 `Documentation/technical/` 디렉토리를 지정하면
스파스 체크아웃에 다음이 포함됩니다:

  * 최상위 디렉토리의 모든 파일
  * `Documentation/` 바로 아래의 모든 파일
  * `Documentation/technical/`의 모든 깊이의 모든 파일

또한, 콘 모드에서는 디렉토리가 지정되지 않은 경우에도 최상위 디렉토리의 파일이 포함됩니다.

스파스 체크아웃 패턴을 콘 모드에서 변경할 때, Git은 스파스 체크아웃 콘에
포함되지 않은 각 추적된 디렉토리를 검사하여 무시된 파일을 포함하고 있는지 확인합니다.
만약 해당 파일들이 모두 `.gitignore` 패턴 때문에 무시되었다면, 해당 디렉토리는 삭제될 것입니다.
만약 해당 디렉토리 내의 무시되지 않은 파일 중 하나라도 있다면, 해당 디렉토리 내에서는
어떤 삭제도 일어나지 않고 경고 메시지가 나타날 것입니다. 만약 이러한 파일들이 중요하다면,
해당 파일들을 포함하도록 스파스 체크아웃 정의를 재설정하고, `git add` 및 `git commit`을 사용하여
저장한 후, 남아 있는 파일들을 수동으로 제거하여 Git이 최적화되도록 하십시오.

디렉토리가 내부적으로 스파스 체크아웃의 전체 패턴 집합으로 어떻게 변환되는지
알아보려면 "Internals -- Cone Pattern Set" 섹션을 참조하십시오.


INTERNALS -- FULL PATTERN SET
-----------------------------

전체 패턴 집합은 임의의 패턴 일치와 복잡한 포함/제외 규칙을 허용합니다.
이는 인덱스를 업데이트할 때 O(N*M) 패턴 일치로 이어질 수 있습니다. 여기서 N은 패턴 수이고 M은 인덱스의 경로 수입니다.
이 성능 문제를 해결하기 위해 `core.sparseCheckoutCone`이 활성화된 경우 더 제한된 패턴 집합이 허용됩니다.

스파스 체크아웃 파일은 `.gitignore` 파일과 동일한 구문을 사용합니다.
자세한 내용은 linkgit:gitignore[5]를 참조하십시오. 여기서 패턴은
보통 어떤 파일을 제외할지보다 어떤 파일을 포함할지를 선택하는 데 사용됩니다.
(그러나 gitignore 스타일 패턴이 '!'로 시작하는 패턴에 의해 정의된 제외를 가지므로,
어떤 파일을 *포함하지 않을지*도 선택할 수 있어 약간 혼란스러울 수 있습니다.)

예를 들어, 모든 것을 선택한 다음 `unwanted` 파일을 제거하려면 (따라서 `unwanted`라는 이름의 파일만 제외하고 모든 파일이 워킹 트리에 나타나도록 하려면):

    git sparse-checkout set --no-cone '/*' '!unwanted'

이러한 패턴은 `$GIT_DIR/info/sparse-checkout`에 그대로 배치됩니다. 따라서 이때의 파일 내용은 다음과 같습니다:

----------------
/*
!unwanted
----------------

스파스 체크아웃에 사용되는 gitignore 스타일 패턴에 대해 더 알아보려면,
linkgit:git-read-tree[1]의 "Sparse Checkout" 섹션도 참조하십시오.


INTERNALS -- CONE PATTERN SET
-----------------------------

콘 모드에서는 디렉토리만 허용되지만, 전체 패턴 집합에서 사용되는
동일한 gitignore 스타일 패턴으로 변환됩니다. 이러한 모드에서 사용되는
특정 패턴을 두 가지 유형 중 하나로 참조합니다:

1. *재귀:* 디렉토리 안의 모든 경로가 포함됩니다.

2. *부모:* 디렉토리의 바로 아래에 있는 모든 파일이 포함됩니다.

콘 모드는 항상 최상위 레벨의 파일을 포함하므로,
`git sparse-checkout set`을 디렉토리를 지정하지 않고 실행하면,
최상위 디렉토리가 부모 패턴으로 추가됩니다. 이때 스파스 체크아웃 파일은 다음 패턴을 포함합니다:

----------------
/*
!/*/
----------------

이것은 "최상위 디렉토리 바로 아래의 모든 것을 포함하지만, 그 아래 어느 레벨의 것도 포함하지 않음"을 의미합니다.

콘 모드에서, `git sparse-checkout set` 서브커맨드는 디렉토리 목록을 가져옵니다.
`git sparse-checkout set A/B/C` 명령은 `A/B/C` 디렉토리를 재귀 패턴으로 설정하고,
`A`와 `A/B` 디렉토리를 부모 패턴으로 추가합니다. 결과적인 스파스 체크아웃 파일은 이제 다음과 같습니다:

----------------
/*
!/*/
/A/
!/A/*/
/A/B/
!/A/B/*/
/A/B/C/
----------------

여기서 순서가 중요하므로, 음수 패턴은 파일의 아래쪽에 나타나는 양수 패턴에 의해 재정의됩니다.

`core.sparseCheckoutCone`이 명시적으로 `false`로 설정되지 않은 한,
Git은 스파스 체크아웃 파일을 이러한 유형의 패턴을 예상하며 구문 분석합니다.
패턴이 일치하지 않으면 Git은 경고합니다. 패턴이 예상된 형식과 일치하면,
Git은 스파스 체크아웃 포함을 계산하기 위해 더 빠른 해시 기반 알고리즘을 사용합니다.
만약 일치하지 않으면, Git은 `core.sparseCheckoutCone` 설정에 관계없이
`core.sparseCheckoutCone`이 false로 설정된 것처럼 동작합니다.

콘 모드 사례에서, 전체 패턴이 $GIT_DIR/info/sparse-checkout 파일에 기록되더라도,
`git sparse-checkout list` 서브커맨드는 재귀 패턴을 정의하는 디렉토리를 나열합니다.
위의 예제 스파스 체크아웃 파일의 경우, 출력은 다음과 같습니다:

--------------------------
$ git sparse-checkout list
A/B/C
--------------------------

`core.ignoreCase=true`인 경우, 패턴 일치 알고리즘은 대소문자를 구분하지 않는 검사를 사용합니다.
이것은 'git sparse-checkout set' 명령에서 파일 이름의 대소문자 불일치를 보정하여
워킹 디렉토리에서 예상되는 콘을 반영합니다.


INTERNALS -- SUBMODULES
-----------------------

저장소에 하나 이상의 서브모듈이 포함되어 있다면, 서브모듈은
`git submodule` 명령과의 상호 작용을 기반으로 채워집니다.
특히, `git submodule init -- <path>`는 `<path>`의 서브모듈이 존재하는지 확인하는 반면,
`git submodule deinit [-f] -- <path>`는 `<path>`의 서브모듈 파일을 제거합니다 (무시된 파일,
커밋되지 않은 변경 사항, 푸시되지 않은 히스토리를 포함).
스파스 체크아웃이 워킹 트리에서 파일을 제거하지만 인덱스에 항목을 남기는 것과 유사하게,
초기화 해제된 서브모듈은 워킹 디렉토리에서 제거되지만 인덱스에는 여전히 항목이 있습니다.

서브모듈에는 푸시되지 않은 변경 사항이나 추적되지 않은 파일이 있을 수 있으므로,
제거하면 데이터 손실이 발생할 수 있습니다. 따라서 스파스 포함/제외 규칙을 변경해도
이미 체크아웃된 서브모듈이 워킹 복사본에서 제거되지는 않습니다.
즉, `checkout`이 서브모듈을 자동으로 제거하거나 초기화하지 않는 것처럼
브랜치 간 전환 시 서브모듈을 제거하거나 추가해도, `sparse-checkout`을 사용하여
"흥미로운" 파일의 범위를 줄이거나 확장해도 서브모듈이 자동으로 초기화 해제되거나
초기화되지는 않습니다.

또한, 위의 사실들은 "추적된" 파일이 작업 복사본에 존재하지 않는 여러 이유가 있음을 의미합니다:
스파스 체크아웃에서 스파스 패턴 적용, 서브모듈 초기화 상태.
따라서 `git grep`과 같이 워킹 복사본의 추적된 파일에서 작동하는 명령은
이러한 제약 중 하나 또는 둘 다에 의해 제한된 결과를 반환할 수 있습니다.


SEE ALSO
--------

linkgit:git-read-tree[1]
linkgit:gitignore[5]

GIT
---
linkgit:git[1] suite의 일부