git-add(1)
==========

NAME
----
git-add - Add file contents to the index

SYNOPSIS
--------
[synopsis]
git add [--verbose | -v] [--dry-run | -n] [--force | -f] [--interactive | -i] [--patch | -p]
	[--edit | -e] [--[no-]all | -A | --[no-]ignore-removal | [--update | -u]] [--sparse]
	[--intent-to-add | -N] [--refresh] [--ignore-errors] [--ignore-missing] [--renormalize]
	[--chmod=(+|-)x] [--pathspec-from-file=<file> [--pathspec-file-nul]]
	[--] [<pathspec>...]

DESCRIPTION
-----------
새 파일 또는 변경된 파일의 내용을 인덱스에 추가합니다. "인덱스"(또는 "스테이징 영역")는 다음 커밋을 준비하는 데 사용됩니다.

`git commit` 명령을 다른 인수 없이 실행하면 스테이징된 변경사항만 커밋됩니다. 예를 들어, `file.c`를 수정하고 해당 파일의 변경사항을 커밋하려면 다음을 실행할 수 있습니다.

   git add file.c
   git commit

`git add -p`를 사용하여 파일의 일부 변경사항만 추가할 수도 있습니다.

이 명령은 커밋 전에 여러 번 수행할 수 있습니다. `add` 명령이 실행될 당시 지정된 파일의 내용만 추가합니다. 나중에 변경된 내용을 다음 커밋에 포함하려면 `git add`를 다시 실행하여 새 내용을 인덱스에 추가해야 합니다.

`git status` 명령을 사용하면 다음 커밋을 위해 스테이징된 파일 변경사항에 대한 요약을 얻을 수 있습니다.

`git add` 명령은 기본적으로 무시된 파일을 추가하지 않습니다. `--force` 옵션을 사용하여 무시된 파일을 추가할 수 있습니다. 무시된 파일의 정확한 파일 이름을 지정하면 `git add`가 무시된 파일 목록과 함께 실패합니다. 그렇지 않으면 파일을 조용히 무시합니다.

커밋에 콘텐츠를 추가하는 대체 방법에 대해서는 linkgit:git-commit[1]을 참조하십시오.


OPTIONS
-------
`<pathspec>...`::
	내용을 추가할 파일입니다. 파일 glob(예: `*.c`)을 사용하여 일치하는 모든 파일을 추가할 수 있습니다. 또한 선행 디렉터리 이름(예: `dir`은 `dir/file1` 및 `dir/file2`를 추가)을 지정하여 디렉터리 전체의 현재 상태와 일치하도록 인덱스를 업데이트할 수 있습니다(예: `dir` 지정은 워킹 트리에서 수정된 파일 `dir/file1`, 워킹 트리에서 추가된 파일 `dir/file2`, 워킹 트리에서 제거된 파일 `dir/file3`뿐만 아니라 모두 기록합니다). 이전 버전의 Git은 제거된 파일을 무시했으므로 수정되거나 새 파일을 추가하지만 제거된 파일은 무시하려면 `--no-all` 옵션을 사용하십시오.
+
_<pathspec>_ 구문에 대한 자세한 내용은 linkgit:gitglossary[7]의 'pathspec' 항목을 참조하십시오.

`-n`::
`--dry-run`::
	실제로 파일을 추가하지 않고, 파일이 존재하거나 무시될지 여부만 표시합니다.

`-v`::
`--verbose`::
        자세하게 표시합니다.

`-f`::
`--force`::
	무시된 파일도 추가할 수 있도록 합니다. 이 옵션은 `submodule.<name>.ignore=all`이 설정되어 있지만 서브모듈 업데이트를 스테이징하려는 경우에도 사용됩니다. 서브모듈의 `path`는 명시적으로 지정해야 합니다.

`--sparse`::
	sparse-checkout cone 외부의 인덱스 항목을 업데이트할 수 있습니다.
	일반적으로 `git add`는 경로가 sparse-checkout cone에 맞지 않는 인덱스 항목을 업데이트하지 않습니다. 해당 파일은 경고 없이 워킹 트리에서 제거될 수 있기 때문입니다. 자세한 내용은 linkgit:git-sparse-checkout[1]을 참조하십시오.

`-i`::
`--interactive`::
	워킹 트리에서 수정된 내용을 대화형으로 인덱스에 추가합니다. 선택적으로 경로 인수를 제공하여 워킹 트리의 하위 집합으로 작업을 제한할 수 있습니다. 자세한 내용은 ``대화형 모드''를 참조하십시오.

`-p`::
`--patch`::
	인덱스와 워킹 트리 간의 패치 덩어리를 대화형으로 선택하여 인덱에 추가합니다. 이를 통해 사용자는 수정된 내용을 스테이징하기 전에 차이점을 검토할 기회를 얻습니다.
+
이는 `add --interactive`를 효과적으로 실행하지만 초기 명령 메뉴를 우회하고 직접 `patch` 서브명령으로 이동합니다. 자세한 내용은 ``대화형 모드''를 참조하십시오.

include::diff-context-options.adoc[]

`-e`::
`--edit`::
	인덱스와의 차이를 편집기에서 열고 사용자가 편집하도록 합니다. 편집기가 닫힌 후 덩어리 헤더를 조정하고 패치를 인덱에 적용합니다.
+
이 옵션의 의도는 적용할 패치의 줄을 선택하거나 스테이징할 줄의 내용을 수정하는 것입니다. 이는 대화형 덩어리 선택기를 사용하는 것보다 빠르고 유연할 수 있습니다. 그러나 자신을 혼동하고 인덱에 적용되지 않는 패치를 만들기는 쉽습니다. 아래의 패치 편집을 참조하십시오.

`-u`::
`--update`::
	_<pathspec>_과 일치하는 항목이 이미 있는 경우에만 인덱을 업데이트합니다.
	워킹 트리에 맞춰 인덱 항목을 제거하거나 수정하지만 새 파일은 추가하지 않습니다.
+
`-u` 옵션을 사용할 때 _<pathspec>_이 지정되지 않으면
	워킹 트리의 모든 추적된 파일이 업데이트됩니다(이전 Git 버전은 현재 디렉터리와 그 하위 디렉터리로 업데이트를 제한했습니다).

`-A`::
`--all`::
`--no-ignore-removal`::
	워킹 트리에 _<pathspec>_과 일치하는 파일이 있는 경우뿐만 아니라 인덱에 이미 항목이 있는 경우에도 인덱을 업데이트합니다.
	워킹 트리와 일치하도록 인덱 항목을 추가, 수정 및 제거합니다.
+
`-A` 옵션을 사용할 때 _<pathspec>_이 지정되지 않으면
	워킹 트리의 모든 파일이 업데이트됩니다(이전 Git 버전은 현재 디렉터리와 그 하위 디렉터리로 업데이트를 제한했습니다).

`--no-all`::
`--ignore-removal`::
	인덱에 알려지지 않은 새 파일을 추가하고 워킹 트리에서 수정된 파일을 추가하여 인덱을 업데이트하지만
	워킹 트리에서 제거된 파일은 무시합니다. 이 옵션은 _<pathspec>_이 사용되지 않을 때 아무 작업도 수행하지 않습니다.
+
이 옵션은 주로 이전
	Git 버전에 익숙한 사용자에게 도움이 됩니다. `git add <pathspec>...`는 `git add --no-all <pathspec>...`의 축약형으로, 제거된 파일을 무시했습니다.

`-N`::
`--intent-to-add`::
	나중에 추가될 경로라는 사실만 기록합니다. 경로에 대한 항목은 내용 없이 인덱에 배치됩니다. 이는 `git diff`로 해당 파일의 스테이징되지 않은 내용을 표시하고 `git commit -a`로 커밋하는 것을 포함하여 여러 가지 용도로 유용합니다.

`--refresh`::
	파일을 추가하지 않고 stats() 정보만 인덱에서 새로 고칩니다.

`--ignore-errors`::
	일부 파일을 인덱화하는 동안 오류로 인해 추가할 수 없었던 경우 작업을 중단하지 않고 나머지 파일을 계속 추가합니다. 명령은 여전히 0이 아닌 상태로 종료됩니다.
	`add.ignoreErrors` 구성 변수를 true로 설정하면 기본 동작이 됩니다.

`--ignore-missing`::
	이 옵션은 `--dry-run`과 함께만 사용할 수 있습니다. 이 옵션을 사용하면 사용자는 지정된 파일 중 어떤 파일이 무시될지 확인할 수 있습니다. 해당 파일이 워킹 트리에 이미 있는지 여부에 관계없습니다.

`--no-warn-embedded-repo`::
	기본적으로 `git add`는 `.gitmodules`에 항목을 생성하지 않고 `git submodule add`를 사용하지 않고 내장된 저장소를 인덱에 추가할 때 경고합니다. 이 옵션은 경고를 억제합니다(예: 서브모듈에 대해 수동으로 작업을 수행하는 경우).

`--renormalize`::
	모든 추적된 파일에 "clean" 프로세스를 다시 적용하여 인덱에 다시 강제로 추가합니다.
	`core.autocrlf` 구성이나 `text` 속성을 변경한 후 잘못된 _CRLF/LF_ 줄 끝으로 추가된 파일을 수정하는 데 유용합니다.
	이 옵션은 `-u`를 암시합니다. 개별 CR 문자는 변경되지 않으므로 _CRLF_가 _LF_로 정리되더라도 _CRCRLF_ 시퀀스는 _CRLF_로 부분적으로만 정리됩니다.

`--chmod=(+|-)x`::
	추가된 파일의 실행 비트를 재정의합니다. 실행 비트는 인덱에서만 변경되며 디스크상의 파일은 변경되지 않습니다.

`--pathspec-from-file=<file>`::
	pathspec은 명령줄 인수 대신 _<file>_에서 전달됩니다. _<file>_이 정확히 `-`이면 표준 입력이 사용됩니다. Pathspec 요소는 _LF_ 또는 _CR/LF_로 구분됩니다. Pathspec 요소는 `core.quotePath` 구성 변수(linkgit:git-config[1] 참조)에 설명된 대로 인용될 수 있습니다. `--pathspec-file-nul` 및 전역 `--literal-pathspecs`도 참조하십시오.

`--pathspec-file-nul`::
	`--pathspec-from-file`과 함께 사용할 때만 의미가 있습니다. Pathspec 요소는 _NUL_ 문자로 구분되며 다른 모든 문자는 그대로 취급됩니다(줄 바꿈 및 따옴표 포함).

`--`::
	이 옵션은 명령줄 옵션과 파일 목록을 구분하는 데 사용할 수 있습니다(파일 이름이 명령줄 옵션으로 오해될 수 있는 경우 유용).


EXAMPLES
--------

* `Documentation` 디렉터리와 해당 하위 디렉터리 아래의 모든 ++*.txt++ 파일의 내용을 추가합니다.
+
------------
$ git add Documentation/\*.txt
------------
+
이 예제에서는 별표 ++*++가 셸에서 인용되므로 `Documentation/` 디렉터리의 하위 디렉터리에서도 파일을 포함할 수 있습니다.

* 모든 ++git-*.sh++ 스크립트의 내용을 추가하는 것을 고려합니다.
+
------------
$ git add git-*.sh
------------
+
이 예제는 셸이 별표를 확장하도록 허용하므로(즉, 파일을 명시적으로 나열합니다) `subdir/git-foo.sh`는 고려하지 않습니다.

INTERACTIVE MODE
----------------
명령이 대화형 모드로 들어가면 'status' 서브명령의 출력을 표시한 다음 대화형 명령 루프로 들어갑니다.

명령 루프는 사용 가능한 서브명령 목록을 표시하고 "What now> " 프롬프트를 제공합니다. 일반적으로 프롬프트가 단일 '>'로 끝나면 다음 예와 같이 제공된 선택 항목 중 하나만 선택하고 Enter를 누를 수 있습니다.

------------
    *** Commands ***
      1: status       2: update       3: revert       4: add untracked
      5: patch        6: diff         7: quit         8: help
    What now> 1
------------

위에서 선택 항목이 고유한 경우 `s` 또는 `sta` 또는 `status`라고 말할 수도 있습니다.

주 명령 루프에는 6개의 서브명령(도움말 및 종료 포함)이 있습니다.

status::

   이것은 `HEAD`와 인덱 사이의 변경 사항(즉, `git commit`이라고 말하면 커밋될 내용)과 인덱과 워킹 트리 파일 사이의 변경 사항(즉, `git add`를 사용하여 `git commit` 전에 더 많이 스테이징할 수 있는 내용)을 각 경로별로 표시합니다. 샘플 출력은 다음과 같습니다.
+
------------
              staged     unstaged path
     1:       binary      nothing foo.png
     2:     +403/-35        +1/-1 add-interactive.c
------------
+
`foo.png`는 `HEAD`와 차이가 있지만(이진 파일이므로 줄 수를 표시할 수 없음) 인덱 복사본과 워킹 트리 버전 사이에 차이가 없음을(워킹 트리 버전도 다른 경우 'binary'가 'nothing' 대신 표시됨) 보여줍니다. 다른 파일인 `add-interactive.c`는 인덱에 커밋할 경우 403 줄이 추가되고 35 줄이 삭제되었지만 워킹 트리 파일에는 추가 수정(추가 1개, 삭제 1개)이 있습니다.

update::

   이것은 상태 정보를 표시하고 "Update>>" 프롬프트를 표시합니다. 프롬프트가 이중 '>>'로 끝나면 공백 또는 쉼표로 연결하여 여러 선택을 할 수 있습니다. 또한 범위를 지정할 수도 있습니다. 예를 들어 "2-5 7,9"는 목록에서 2,3,4,5,7,9를 선택합니다. 범위의 두 번째 숫자가 생략되면 나머지 모든 패치가 선택됩니다. 예를 들어 "7-"은 목록에서 7,8,9를 선택합니다. '*'를 사용하여 모두 선택할 수 있습니다.
+
선택한 내용은 '*'로 강조 표시됩니다.
+
------------
           staged     unstaged path
  1:       binary      nothing foo.png
* 2:     +403/-35        +1/-1 add-interactive.c
------------
+
선택을 제거하려면 입력 앞에 `-`를 붙입니다.
+
------------
Update>> -2
------------
+
선택을 완료한 후 빈 줄로 응답하여 선택한 경로의 워킹 트리 파일 내용을 인덱에 스테이징합니다.

revert::

  이것은 'update'와 매우 유사한 UI를 가지며, 선택한 경로의 스테이징된 정보는 HEAD 버전과 동일하게 되돌립니다. 새 경로는 추적되지 않게 됩니다.

add untracked::

  이것은 'update' 및 'revert'와 매우 유사한 UI를 가지며, 추적되지 않은 경로를 인덱에 추가할 수 있습니다.

patch::

  이것은 'status'와 유사한 선택 항목 중에서 하나의 경로를 선택하게 합니다.
  경로를 선택한 후에는 인덱과 워킹 트리 파일 간의 차이를 보여주고 각 덩어리의 변경 사항을 스테이징할지 묻습니다. 다음 옵션 중 하나를 선택하고 Enter를 누를 수 있습니다.

       y - 이 덩어리를 스테이징합니다
       n - 이 덩어리를 스테이징하지 마십시오
       q - 종료; 이 덩어리 또는 나머지 덩어리를 스테이징하지 마십시오
       a - 이 덩어리와 파일의 이후 모든 덩어리를 스테이징합니다
       d - 이 덩어리 또는 파일의 이후 모든 덩어리를 스테이징하지 마십시오
       g - 이동할 덩어리를 선택합니다
       / - 주어진 정규 표현식과 일치하는 덩어리를 검색합니다
       j - 다음 결정되지 않은 덩어리로 이동하여 아래에서 롤오버합니다
       J - 다음 덩어리로 이동하여 아래에서 롤오버합니다
       k - 이전 결정되지 않은 덩어리로 이동하여 위에서 롤오버합니다
       K - 이전 덩어리로 이동하여 위에서 롤오버합니다
       s - 현재 덩어리를 더 작은 덩어리로 분할합니다
       e - 현재 덩어리를 수동으로 편집합니다
       p - 현재 덩어리를 인쇄합니다
       P - 페이저를 사용하여 현재 덩어리를 인쇄합니다
       ? - 도움말 인쇄
+
모든 덩어리의 운명을 결정한 후, 선택된 덩어리가 있으면 선택된 덩어리로 인덱이 업데이트됩니다.
+
`interactive.singleKey` 구성 변수를 `true`로 설정하면 Enter 키를 누를 필요 없이 이 작업을 생략할 수 있습니다.

diff::

  이것은 커밋할 내용(즉, `HEAD`와 인덱 사이)을 검토하게 합니다.


EDITING PATCHES
---------------

`git add -e`를 호출하거나 대화형 덩어리 선택기에서 `e`를 선택하면 편집기에서 패치가 열립니다. 편집기가 종료된 후 결과가 인덱에 적용됩니다. 패치를 임의로 변경할 수 있지만 일부 변경은 혼란스러운 결과를 초래하거나 패치를 적용할 수 없게 만들 수도 있습니다. 작업을 완전히 중단하려면(즉, 인덱에 새 항목을 스테이징하지 않으려면) 패치의 모든 줄을 삭제하십시오. 다음 목록은 패치에서 볼 수 있는 일반적인 항목과 합리적인 편집 작업을 설명합니다.

--
added content::

추가된 내용은 "{plus}"로 시작하는 줄로 표시됩니다. 이러한 추가 줄을 삭제하여 스테이징되지 않도록 할 수 있습니다.

removed content::

제거된 내용은 "-"로 시작하는 줄로 표시됩니다. "-"를 " "(공백)으로 변환하여 제거의 스테이징을 방지할 수 있습니다.

modified content::

수정된 내용은 "-" 줄(기존 내용 제거) 뒤에 "{plus}" 줄(대체 내용 추가)로 표시됩니다. "-" 줄을 " "(공백)으로 변환하고 "{plus}" 줄을 삭제하여 수정 사항의 스테이징을 방지할 수 있습니다. 쌍의 절반만 수정하면 인덱에 혼란스러운 변경이 발생할 가능성이 있음을 주의하십시오.
--

더 복잡한 작업도 수행할 수 있습니다. 그러나 패치는 인덱에만 적용되고 워킹 트리에는 적용되지 않으므로 워킹 트리는 인덱의 변경을 "되돌리는" 것처럼 보일 수 있습니다. 예를 들어, `HEAD`에도 워킹 트리에도 없는 새 줄을 인덱에 도입하면 새 줄이 커밋을 위해 스테이징되지만 워킹 트리에서는 해당 줄이 되돌려진 것처럼 보입니다.

이러한 구문은 피하거나 극도로 주의해서 사용하십시오.

--
untouched content 제거::

인덱과 워킹 트리 사이에 차이가 없는 내용은 컨텍스트 줄에 " "(공백)으로 표시될 수 있습니다. 컨텍스트 줄을 "-"로 변환하여 스테이징을 위해 제거할 수 있습니다. 결과 워킹 트리 파일은 내용을 다시 추가하는 것처럼 보입니다.

기존 content 수정::

공백을 "-"로 변환하여 컨텍스트 줄을 제거하고(스테이징을 위해) 새 내용으로 "{plus}" 줄을 추가하여 컨텍스트 줄을 수정할 수도 있습니다. 마찬가지로 기존 추가 또는 수정에 대한 "{plus}" 줄을 수정할 수 있습니다. 모든 경우에 새 수정은 워킹 트리에서 되돌려진 것처럼 보입니다.

new content::

패치에 없는 새 콘텐츠를 추가할 수도 있습니다. 각 줄은 "{plus}"로 시작하는 새 줄을 추가하면 됩니다. 추가는 워킹 트리에서 되돌려진 것처럼 보입니다.
--

또한 적용을 불가능하게 만드는 몇 가지 작업은 피해야 합니다.

* 컨텍스트(" ") 또는 제거("-") 줄 추가
* 컨텍스트 또는 제거 줄 삭제
* 컨텍스트 또는 제거 줄의 내용 수정

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

:git-add: 1
include::config/add.adoc[]

SEE ALSO
--------
linkgit:git-status[1]
linkgit:git-rm[1]
linkgit:git-reset[1]
linkgit:git-mv[1]
linkgit:git-commit[1]
linkgit:git-update-index[1]

GIT
---
linkgit:git[1] suite의 일부