git-worktree(1)
===============

NAME
----
git-worktree - 여러 워킹 트리 관리


SYNOPSIS
--------
[synopsis]
git worktree add [-f] [--detach] [--checkout] [--lock [--reason <string>]]
		 [--orphan] [(-b | -B) <new-branch>] <path> [<commit-ish>]
git worktree list [-v | --porcelain [-z]]
git worktree lock [--reason <string>] <worktree>
git worktree move <worktree> <new-path>
git worktree prune [-n] [-v] [--expire <expire>]
git worktree remove [-f] <worktree>
git worktree repair [<path>...]
git worktree unlock <worktree>

DESCRIPTION
-----------

동일한 저장소에 연결된 여러 워킹 트리를 관리합니다.

Git 저장소는 여러 워킹 트리를 지원할 수 있으며, 이를 통해 한 번에 여러 브랜치를 체크아웃할 수 있습니다. `git worktree add` 명령을 사용하면 새 워킹 트리가 저장소에 연결되며, 해당 저장소의 다른 워킹 트리와 구별되는 추가 메타데이터가 함께 제공됩니다. 워킹 트리와 이 메타데이터를 "워크트리(worktree)"라고 합니다.

이 새로운 워크트리는 linkgit:git-init[1] 또는 linkgit:git-clone[1]으로 준비된 "메인 워크트리(main worktree)"와 달리 "연결된 워크트리(linked worktree)"라고 합니다. 저장소에는 메인 워크트리가 하나(베어 저장소가 아닌 경우) 있고, 제로 개 이상의 연결된 워크트리가 있을 수 있습니다. 연결된 워크트리 사용이 끝나면 `git worktree remove`로 제거하십시오.

가장 간단한 형태인 `git worktree add <path>`는 _<path>_의 마지막 구성 요소를 이름으로 하는 새 브랜치를 자동으로 생성하며, 새 주제에 대해 작업할 계획일 경우 편리합니다. 예를 들어, `git worktree add ../hotfix`는 새 브랜치 `hotfix`를 생성하고 `../hotfix` 경로에 체크아웃합니다. 대신 새 워크트리에서 기존 브랜치에서 작업하려면 `git worktree add <path> <branch>`를 사용하십시오. 반면에, 기존 개발을 방해하지 않고 실험적인 변경 사항을 만들거나 테스트하려는 경우, 어떤 브랜치와도 연결되지 않은 "일회용(throwaway)" 워크트리를 만드는 것이 편리할 때가 많습니다. 예를 들어, `git worktree add -d <path>`는 현재 브랜치의 동일한 커밋에서 분리된 `HEAD`를 가진 새 워크트리를 생성합니다.

워킹 트리가 `git worktree remove`를 사용하지 않고 삭제된 경우, 저장소에 있는 해당 관리 파일(아래 "DETAILS" 참조)은 결국 자동으로 제거됩니다(linkgit:git-config[1]의 `gc.worktreePruneExpire` 참조). 또는 메인 또는 연결된 워크트리에서 `git worktree prune`을 실행하여 오래된 관리 파일을 정리할 수 있습니다.

연결된 워크트리의 워킹 트리가 항상 마운트되지 않는 휴대용 장치 또는 네트워크 공유에 저장되어 있는 경우, `git worktree lock` 명령을 실행하여 해당 관리 파일이 정리되지 않도록 할 수 있으며, 선택적으로 `--reason`을 지정하여 잠금 이유를 설명할 수 있습니다.

COMMANDS
--------
`add <path> [<commit-ish>]`::

 _<path>_ 위치에 워크트리를 생성하고 _<commit-ish>_를 해당 워크트리에 체크아웃합니다. 새 워크트리는 현재 저장소에 연결되며, `HEAD`, `index` 등과 같은 워크트리별 파일을 제외한 모든 것을 공유합니다. 편의를 위해 _<commit-ish>_는 `@{-1}`과 동일한 "`-`"입니다.
+
 _<commit-ish>_가 브랜치 이름(`_<branch>_`라 함)이고 찾을 수 없으며 `-b`, `-B`, `--detach`가 사용되지 않았지만 정확히 하나의 원격( `_<remote>_`라 함)에 해당 이름을 가진 추적 브랜치가 존재하는 경우, 다음의 동등한 것으로 취급합니다:
+
------------
$ git worktree add --track -b <branch> <path> <remote>/<branch>
------------
+
브랜치가 여러 원격에 존재하고 그 중 하나가 `checkout.defaultRemote` 구성 변수에 의해 이름이 지정된 경우, _<branch>_가 모든 원격에서 고유하지 않더라도 모호성을 해소하기 위해 해당 원격을 사용합니다. _<branch>_가 모호하지만 `origin` 원격에 존재하는 경우 항상 해당 원격에서 원격 브랜치를 체크아웃하도록 `checkout.defaultRemote=origin`으로 설정하십시오. linkgit:git-config[1]의 `checkout.defaultRemote`도 참조하십시오.
+
 _<commit-ish>_가 생략되고 `-b`, `-B`, `--detach`가 사용되지 않은 경우, 편의를 위해 새 워크트리는 `$(basename <path>)`의 이름을 가진 브랜치(`_<branch>_`라 함)와 연결됩니다. _<branch>_가 존재하지 않으면 `HEAD`를 기반으로 새 브랜치가 `-b <branch>`가 주어진 것처럼 자동으로 생성됩니다. _<branch>_가 이미 존재하는 경우, 다른 곳에서 체크아웃되지 않았다면 새 워크트리에 체크아웃됩니다. 그렇지 않으면 명령은 워크트리 생성을 거부합니다(`--force`가 사용되지 않은 경우).
+
 _<commit-ish>_가 생략되고 `--detach` 또는 `--orphan`이 사용되지 않았으며, 유효한 로컬 브랜치(또는 `--guess-remote`가 지정된 경우 원격 브랜치)가 없는 경우, 편의를 위해 새 워크트리는 `--orphan`이 명령에 전달된 것처럼 _<branch>_ ( `-b` 또는 `-B`가 사용되지 않은 경우 `$(basename <path>)` 이후)라는 새 태어나지 않은 브랜치와 연결됩니다. 저장소에 원격이 있고 `--guess-remote`가 사용되었지만 로컬 또는 원격 브랜치가 없는 경우, 명령은 경고 메시지를 표시하며 사용자에게 먼저 원격에서 페치하도록 상기시킵니다(또는 `-f`/`--force`로 재정의).

`list`::

각 워크트리의 세부 정보를 나열합니다. 메인 워크트리가 먼저 나열되고, 그 다음 각 연결된 워크트리가 나열됩니다. 출력 세부 정보에는 워크트리가 베어인지 여부, 현재 체크아웃된 리비전, 현재 체크아웃된 브랜치(없으면 "detached HEAD"), 워크트리가 잠겨 있으면 "locked", `prune` 명령으로 정리할 수 있으면 "prunable"이 포함됩니다.

`lock`::

작업 트리가 항상 마운트되는 것은 아닌 휴대용 장치 또는 네트워크 공유에 있는 경우, 해당 작업 트리의 관리 파일이 자동으로 정리되지 않도록 잠급니다. 이는 이동하거나 삭제하는 것도 방지합니다. 선택적으로 `--reason`을 사용하여 잠금 이유를 지정하십시오.

`move`::

워크트리를 새 위치로 이동합니다. 메인 워크트리 또는 서브모듈을 포함하는 연결된 워크트리는 이 명령으로 이동할 수 없습니다. (그러나 `git worktree repair` 명령은 메인 워크트리를 수동으로 이동하는 경우 연결된 워크트리와의 연결을 복구할 수 있습니다.)

`prune`::

작업 트리가 누락된 워크트리의 `$GIT_DIR/worktrees`에서 워크트리 정보를 제거합니다. 더 이상 필요하지 않은 워크트리를 수동으로 제거한 후 유용합니다(다음부터 그렇게 하려면 "git worktree remove"를 사용하십시오). 또한, 워크트리를 다른 곳으로 _이동_하여 워크트리 정보가 댕글링된 경우, "git worktree repair"를 사용하여 워크트리를 새 워크트리 위치에 다시 연결하십시오.

`remove`::

워크트리를 제거합니다. 추적되지 않은 파일이 없고 추적된 파일에 수정 사항이 없는 "깨끗한" 워크트리만 제거할 수 있습니다. "unclean" 워크트리 또는 서브모듈이 있는 워크트리는 `--force`를 사용하여 제거할 수 있습니다. 메인 워크트리는 제거할 수 없습니다.

`repair [<path>...]`::

외부 요인으로 인해 손상되거나 오래된 경우 가능한 경우 워크트리 관리 파일을 복구합니다.
+
예를 들어, 메인 워크트리(또는 베어 저장소)가 이동되면 연결된 워크트리가 이를 찾을 수 없습니다. 메인 워크트리에서 `repair`를 실행하면 연결된 워크트리에서 메인 워크트리로의 연결이 복구됩니다.
+
마찬가지로, `git worktree move`를 사용하지 않고 연결된 워크트리의 워킹 트리가 이동된 경우, 메인 워크트리(또는 베어 저장소)가 이를 찾을 수 없습니다. 최근에 이동된 워크트리 내에서 `repair`를 실행하면 연결이 다시 설정됩니다. 여러 연결된 워크트리가 이동된 경우, 각 트리의 새 _<path>_를 인수로 사용하여 아무 워크트리에서나 `repair`를 실행하면 모든 경로에 대한 연결이 다시 설정됩니다.
+
메인 워크트리와 연결된 워크트리가 모두 수동으로 이동되거나 복사된 경우, 메인 워크트리에서 `repair`를 실행하고 각 연결된 워크트리의 새 _<path>_를 지정하면 양방향 모든 연결이 복구됩니다.

`unlock`::

워크트리의 잠금을 해제하여 정리, 이동 또는 삭제할 수 있도록 합니다.

OPTIONS
-------

`-f`::
`--force`::
	기본적으로 `add`는 _<commit-ish>_가 브랜치 이름이고 다른 워크트리에서 이미 체크아웃되었거나, _<path>_가 이미 어떤 워크트리에 할당되었지만 누락된 경우(예: _<path>_가 수동으로 삭제된 경우) 새 워크트리 생성을 거부합니다. 이 옵션은 이러한 안전 장치를 재정의합니다. 누락되었지만 잠긴 워크트리 경로를 추가하려면 `--force`를 두 번 지정하십시오.
+
`move`는 `--force`를 두 번 지정하지 않는 한 잠긴 워크트리를 이동하는 것을 거부합니다. 대상으로 이미 다른 워크트리가 할당되었지만 누락된 경우(예: _<new-path>_가 수동으로 삭제된 경우), `--force`를 사용하면 이동이 진행됩니다. 대상이 잠겨 있으면 `--force`를 두 번 사용하십시오.
+
`remove`는 `--force`가 사용되지 않는 한 "unclean" 워크트리를 제거하는 것을 거부합니다. 잠긴 워크트리를 제거하려면 `--force`를 두 번 지정하십시오.

`-b <new-branch>`::
`-B <new-branch>`::
	`add`와 함께, _<new-branch>_라는 새 브랜치를 _<commit-ish>_를 시작으로 생성하고 _<new-branch>_를 새 워크트리에 체크아웃합니다. _<commit-ish>_가 생략되면 `HEAD`를 기본값으로 사용합니다.
	기본적으로 `-b`는 브랜치가 이미 존재하는 경우 새 브랜치 생성을 거부합니다. `-B`는 이 안전 장치를 재정의하여 _<new-branch>_를 _<commit-ish>_로 재설정합니다.

`-d`::
`--detach`::
	`add`와 함께, 새 워크트리에서 `HEAD`를 분리합니다. linkgit:git-checkout[1]의 "DETACHED HEAD"를 참조하십시오.

`--checkout`::
`--no-checkout`::
	기본적으로 `add`는 _<commit-ish>_를 체크아웃합니다. 그러나 `--no-checkout`을 사용하여 sparse-checkout 구성과 같은 사용자 정의를 위해 체크아웃을 억제할 수 있습니다. linkgit:git-read-tree[1]의 "Sparse checkout"을 참조하십시오.

`--guess-remote`::
`--no-guess-remote`::
	`worktree add <path>`에서 _<commit-ish>_ 없이, `HEAD`에서 새 브랜치를 생성하는 대신, _<path>_의 기본 이름과 일치하는 원격에서 추적 브랜치가 하나만 존재하는 경우, 새 브랜치의 기반을 원격 추적 브랜치로 하고, 새 브랜치의 "업스트림"으로 해당 원격 추적 브랜치를 표시합니다.
+
이것은 `worktree.guessRemote` 구성 옵션을 사용하여 기본 동작으로 설정할 수도 있습니다.

`--relative-paths`::
`--no-relative-paths`::
	상대 경로 또는 절대 경로(기본값)를 사용하여 워크트리를 연결합니다.
	linkgit:git-config[1]에서 `worktree.useRelativePaths` 구성 옵션을 재정의합니다.
+
`repair`와 함께, 링크가 올바르더라도 절대/상대 불일치가 있는 경우 링크 파일이 업데이트됩니다.

`--track`::
`--no-track`::
	새 브랜치를 생성할 때, _<commit-ish>_가 브랜치인 경우, 새 브랜치의 "업스트림"으로 표시합니다. _<commit-ish>_가 원격 추적 브랜치인 경우 이것이 기본값입니다. 자세한 내용은 linkgit:git-branch[1]의 `--track`을 참조하십시오.

`--lock`::
	생성 후 워크트리를 잠긴 상태로 유지합니다. 이것은 `git worktree add` 후 `git worktree lock`을 실행하는 것과 같지만 경합 조건이 없습니다.

`-n`::
`--dry-run`::
	`prune`과 함께, 아무것도 제거하지 않고 제거할 대상을 보고합니다.

`--orphan`::
	`add`와 함께, 새 워크트리와 인덱스를 비우고 워크트리를 _<new-branch>_라는 새 태어나지 않은 브랜치와 연결합니다.

`--porcelain`::
	`list`와 함께, 스크립트에서 쉽게 파싱할 수 있는 형식으로 출력합니다.
	이 형식은 Git 버전과 사용자 구성에 관계없이 안정적으로 유지됩니다. `-z`와 함께 사용하는 것이 좋습니다.
	자세한 내용은 아래를 참조하십시오.

`-z`::
	`--porcelain`이 `list`와 함께 지정될 때 각 줄을 새 줄 대신 _NUL_로 종료합니다. 이렇게 하면 워크트리 경로에 새 줄 문자가 포함된 경우에도 출력을 파싱할 수 있습니다.

`-q`::
`--quiet`::
	`add`와 함께, 피드백 메시지를 억제합니다.

`-v`::
`--verbose`::
	`prune`과 함께, 모든 제거를 보고합니다.
+
`list`와 함께, 워크트리에 대한 추가 정보를 출력합니다(아래 참조).

`--expire <time>`::
	`prune`과 함께, _<time>_보다 오래된 누락된 워크트리만 정리합니다.
+
`list`와 함께, _<time>_보다 오래된 누락된 워크트리를 정리 가능하다고 주석 처리합니다.

`--reason <string>`::
	`lock` 또는 `add --lock`과 함께, 워크트리가 잠긴 이유를 설명합니다.

_<worktree>_::
	워크트리는 상대 또는 절대 경로로 식별할 수 있습니다.
+
워크트리 경로의 마지막 경로 구성 요소가 워크트리 중에서 고유한 경우, 워크트리를 식별하는 데 사용할 수 있습니다. 예를 들어 `/abc/def/ghi`와 `/abc/def/ggg`에 두 개의 워크트리만 있는 경우, `ghi` 또는 `def/ghi`로 전자의 워크트리를 가리키기에 충분합니다.

REFS
----
여러 워크트리를 사용할 때 일부 ref는 모든 워크트리간에 공유되지만, 다른 ref는 개별 워크트리에 특정됩니다. 한 가지 예는 각 워크트리마다 다른 `HEAD`입니다. 이 섹션에서는 공유 규칙과 한 워크트리의 ref를 다른 워크트리에서 액세스하는 방법에 대해 설명합니다.

일반적으로 모든 의사 ref는 워크트리별이며 `refs/`로 시작하는 모든 ref는 공유됩니다. 의사 ref는 `$GIT_DIR` 바로 아래에 있는 `HEAD`와 같이 `$GIT_DIR/refs/` 안에 있지 않은 ref입니다. 그러나 예외가 있습니다: `refs/bisect`, `refs/worktree`, `refs/rewritten`에 있는 ref는 공유되지 않습니다.

워크트리별 ref는 `main-worktree`와 `worktrees`라는 두 개의 특수 경로를 통해 다른 워크트리에서 액세스할 수 있습니다. 전자는 메인 워크트리의 워크트리별 ref에 액세스하고, 후자는 모든 연결된 워크트리에 액세스합니다.

예를 들어, `main-worktree/HEAD` 또는 `main-worktree/refs/bisect/good`는 각각 메인 워크트리의 `HEAD` 및 `refs/bisect/good`와 동일한 값으로 확인됩니다. 마찬가지로, `worktrees/foo/HEAD` 또는 `worktrees/bar/refs/bisect/bad`는 `$GIT_COMMON_DIR/worktrees/foo/HEAD` 및 `$GIT_COMMON_DIR/worktrees/bar/refs/bisect/bad`와 동일합니다.

ref에 액세스하려면 `$GIT_DIR`을 직접 보는 것은 좋지 않습니다. 대신 linkgit:git-rev-parse[1] 또는 linkgit:git-update-ref[1]와 같은 명령을 사용하십시오. 이러한 명령은 ref를 올바르게 처리합니다.

CONFIGURATION FILE
------------------
기본적으로 저장소 `config` 파일은 모든 워크트리간에 공유됩니다.
`core.bare` 또는 `core.worktree` 구성 변수가 공통 config 파일에 존재하고 `extensions.worktreeConfig`가 비활성화된 경우, 해당 변수는 메인 워크트리에만 적용됩니다.

워크트리 별 구성을 가지려면 `worktreeConfig` 확장을 활성화할 수 있습니다. 예:

------------
$ git config extensions.worktreeConfig true
------------

이 모드에서는 특정 구성이 `git rev-parse --git-path config.worktree`에서 가리키는 경로에 유지됩니다. `git config --worktree`를 사용하여 이 파일에 구성을 추가하거나 업데이트할 수 있습니다. 이전 Git 버전에서는 이 확장을 가진 저장소에 액세스하는 것을 거부합니다.

이 파일에서는 `core.bare` 및 `core.worktree`에 대한 예외가 사라졌습니다. `$GIT_DIR/config`에 존재하는 경우 메인 워크트리의 `config.worktree`로 이동해야 합니다. 또한 공유하고 싶지 않은 다른 구성을 검토하고 이동할 기회를 가질 수도 있습니다.

 - `core.worktree`는 절대 공유해서는 안 됩니다.

 - `core.bare`의 값이 `core.bare=true`인 경우 공유해서는 안 됩니다.

 - `core.sparseCheckout`은 모든 워크트리에 대해 항상 sparse checkout을 사용하는 것이 확실하지 않은 한 공유해서는 안 됩니다.

자세한 내용은 linkgit:git-config[1]의 `extensions.worktreeConfig` 설명을 참조하십시오.

DETAILS
-------
각 연결된 워크트리는 저장소의 `$GIT_DIR/worktrees` 디렉토리에 개인 하위 디렉토리를 갖습니다. 개인 하위 디렉토리의 이름은 보통 연결된 워크트리 경로의 기본 이름이며, 고유하게 만들기 위해 숫자가 추가될 수 있습니다. 예를 들어, `$GIT_DIR=/path/main/.git`이고 `git worktree add /path/other/test-next next` 명령을 실행하면 `/path/other/test-next`에 연결된 워크트리가 생성되고 `$GIT_DIR/worktrees/test-next` 디렉토리(또는 `test-next`가 이미 사용 중인 경우 `$GIT_DIR/worktrees/test-next1`)도 생성됩니다.

연결된 워크트리 내에서 `$GIT_DIR`은 이 개인 디렉토리를 가리키도록 설정되고(예: 예제의 `/path/main/.git/worktrees/test-next`) `$GIT_COMMON_DIR`은 메인 워크트리의 `$GIT_DIR`을 가리키도록 설정됩니다(예: `/path/main/.git`). 이러한 설정은 연결된 워크트리의 최상위 디렉토리에 있는 `.git` 파일에 이루어집니다.

`git rev-parse --git-path`를 통한 경로 해석은 경로에 따라 `$GIT_DIR` 또는 `$GIT_COMMON_DIR`을 사용합니다. 예를 들어, 연결된 워크트리 `git rev-parse --git-path HEAD`는 메인 워크트리의 `HEAD`와 동일한 `/path/main/.git/worktrees/test-next/HEAD`를 반환합니다( `/path/other/test-next/.git/HEAD` 또는 `/path/main/.git/HEAD`가 아님). 반면 `git rev-parse --git-path refs/heads/master`는 `$GIT_COMMON_DIR`을 사용하고 `/path/main/.git/refs/heads/master`를 반환합니다. ref는 `refs/bisect`, `refs/worktree`, `refs/rewritten`을 제외하고 모든 워크트리간에 공유되기 때문입니다.

linkgit:gitrepository-layout[5]에서 자세한 내용을 참조하십시오. `$GIT_DIR`의 일부인지에 대해 어떠한 가정도 하지 마십시오. `$GIT_DIR` 내부의 무언가에 직접 액세스해야 하는 경우. 최종 경로를 얻으려면 `git rev-parse --git-path`를 사용하십시오.

연결된 워크트리를 수동으로 이동하는 경우, 해당 항목 디렉토리의 `gitdir` 파일을 업데이트해야 합니다. 예를 들어, 연결된 워크트리를 `/newpath/test-next`로 이동했고 `.git` 파일이 `/path/main/.git/worktrees/test-next`를 가리키는 경우, `/path/main/.git/worktrees/test-next/gitdir`을 `/newpath/test-next`를 참조하도록 업데이트하십시오. 더 나은 방법은 `git worktree repair`를 실행하여 연결을 자동으로 복구하는 것입니다.

`$GIT_DIR/worktrees` 항목이 정리되는 것을 방지하려면(항목의 워크트리가 휴대용 장치에 저장된 경우와 같이 일부 상황에서 유용할 수 있음) `git worktree lock` 명령을 사용하십시오. 이 명령은 해당 항목 디렉토리에 `locked`라는 파일을 추가합니다. 이 파일에는 일반 텍스트로 이유가 포함되어 있습니다. 예를 들어, 연결된 워크트리의 `.git` 파일이 `/path/main/.git/worktrees/test-next`를 가리키는 경우, `/path/main/.git/worktrees/test-next/locked`라는 파일이 `test-next` 항목이 정리되지 않도록 방지합니다. 자세한 내용은 linkgit:gitrepository-layout[5]를 참조하십시오.

`extensions.worktreeConfig`가 활성화된 경우, `.git/worktrees/<id>/config.worktree` 구성 파일은 `.git/config`를 읽은 후에 읽힙니다.

LIST OUTPUT FORMAT
------------------
`worktree list` 명령에는 두 가지 출력 형식이 있습니다. 기본 형식은 열과 함께 한 줄에 세부 정보를 표시합니다. 예:

------------
$ git worktree list
/path/to/bare-source            (bare)
/path/to/linked-worktree        abcd1234 [master]
/path/to/other-linked-worktree  1234abc  (detached HEAD)
------------

이 명령은 각 워크트리의 상태에 따른 주석도 표시합니다. 이러한 주석은 다음과 같습니다.

 * 워크트리가 잠긴 경우: `locked`
 * `git worktree prune`을 통해 정리할 수 있는 경우: `prunable`

------------
$ git worktree list
/path/to/linked-worktree    abcd1234 [master]
/path/to/locked-worktree    acbd5678 (brancha) locked
/path/to/prunable-worktree  5678abc  (detached HEAD) prunable
------------

이러한 주석에 대해 이유가 있을 수도 있으며, 이는 verbose 모드를 사용하여 확인할 수 있습니다. 그러면 주석이 들여쓰기된 다음 줄로 이동하고 추가 정보가 뒤따릅니다.

------------
$ git worktree list --verbose
/path/to/linked-worktree              abcd1234 [master]
/path/to/locked-worktree-no-reason    abcd5678 (detached HEAD) locked
/path/to/locked-worktree-with-reason  1234abcd (brancha)
	locked: worktree path is mounted on a portable device
/path/to/prunable-worktree            5678abc1 (detached HEAD)
	prunable: gitdir file points to non-existent location
------------

추가 정보가 있는 경우 주석이 다음 줄로 이동하고, 그렇지 않으면 워크트리 자체와 동일한 줄에 유지됩니다.

Porcelain Format
~~~~~~~~~~~~~~~~
Porcelain 형식은 속성마다 한 줄입니다. `-z`가 지정된 경우 줄은 새 줄 대신 NUL로 종료됩니다. 속성은 레이블과 단일 공백으로 구분된 값으로 나열됩니다. 부울 속성(`bare`, `detached` 등)은 레이블만 나열되며 값이 true인 경우에만 존재합니다. 일부 속성(`locked` 등)은 이유가 있는지 여부에 따라 레이블만으로 나열되거나 값과 함께 나열될 수 있습니다. 워크트리의 첫 번째 속성은 항상 `worktree`이며, 빈 줄은 레코드의 끝을 나타냅니다. 예:

------------
$ git worktree list --porcelain
worktree /path/to/bare-source
bare

worktree /path/to/linked-worktree
HEAD abcd1234abcd1234abcd1234abcd1234abcd1234
branch refs/heads/master

worktree /path/to/other-linked-worktree
HEAD 1234abc1234abc1234abc1234abc1234abc1234a
detached

worktree /path/to/linked-worktree-locked-no-reason
HEAD 5678abc5678abc5678abc5678abc5678abc5678c
branch refs/heads/locked-no-reason
locked

worktree /path/to/linked-worktree-locked-with-reason
HEAD 3456def3456def3456def3456def3456def3456b
branch refs/heads/locked-with-reason
locked reason why is locked

worktree /path/to/linked-worktree-prunable
HEAD 1233def1234def1234def1234def1234def1234b
detached
prunable gitdir file points to non-existent location

------------

`-z`가 사용되지 않는 한, 잠금 이유에 있는 "특이한" 문자(예: 새 줄)는 이스케이프되고 전체 이유는 구성 변수 `core.quotePath`에서 설명한 대로 따옴표로 묶입니다(linkgit:git-config[1] 참조). 예:

------------
$ git worktree list --porcelain
...
locked "reason\nwhy is locked"
...
------------

EXAMPLES
--------
리팩터링 세션 중에 보스가 갑자기 긴급 수정 사항을 요구할 수 있습니다. 기존에는
linkgit:git-stash[1]를 사용하여 변경 사항을 일시적으로 저장하는 것이 일반적이었지만,
작업 트리가 너무 혼란스러운 상태(새 파일, 이동된 파일, 삭제된 파일 및 기타 조각들이
흩어져 있음)여서 건드리는 것을 위험하게 생각했을 수 있습니다.
대신, 임시 연결된 워크트리를 만들어 긴급 수정 사항을 적용하고, 완료되면 제거한 후
이전 리팩터링 세션으로 돌아갈 수 있습니다.

------------
$ git worktree add -b emergency-fix ../temp master
$ pushd ../temp
# ... hack hack hack ...
$ git commit -a -m 'emergency fix for boss'
$ popd
$ git worktree remove ../temp
------------

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/worktree.adoc[]

BUGS
----
일반적으로 여러 체크아웃은 여전히 실험적인 기능이며, 서브모듈에 대한 지원은 불완전합니다. 슈퍼프로젝트에 대한 여러 체크아웃은 권장되지 않습니다.

GIT
---
linkgit:git[1] 스위트의 일부