git-config(1)
=============

NAME
----
git-config - 저장소 또는 전역 옵션 가져오기 및 설정하기


SYNOPSIS
--------
[verse]
'git config list' [<file-option>] [<display-option>] [--includes]
'git config get' [<file-option>] [<display-option>] [--includes] [--all] [--regexp] [--value=<pattern>] [--fixed-value] [--default=<default>] [--url=<url>] <name>
'git config set' [<file-option>] [--type=<type>] [--all] [--value=<pattern>] [--fixed-value] <name> <value>
'git config unset' [<file-option>] [--all] [--value=<pattern>] [--fixed-value] <name>
'git config rename-section' [<file-option>] <old-name> <new-name>
'git config remove-section' [<file-option>] <name>
'git config edit' [<file-option>]
'git config' [<file-option>] --get-colorbool <name> [<stdout-is-tty>]

DESCRIPTION
-----------
이 명령어를 사용하여 옵션을 조회/설정/교체/해제할 수 있습니다. 이름은 실제로는 점으로 구분된 섹션과 키이며, 값은 이스케이프됩니다.

`--append` 옵션을 사용하여 여러 줄을 옵션에 추가할 수 있습니다.
여러 줄에 걸쳐 발생할 수 있는 옵션을 업데이트하거나 해제하려면 (기본적으로 `--fixed-value` 옵션이 지정되지 않은 경우 확장 정규 표현식인) `--value=<pattern>`이 제공되어야 합니다. 패턴과 일치하는 기존 값만 업데이트되거나 해제됩니다. 패턴과 *일치하지 않는* 줄을 처리하려면 (예제 <<EXAMPLES>>를 참조하세요) 앞에 느낌표 하나를 붙이면 되지만, `--fixed-value` 옵션을 사용하지 않을 때만 작동한다는 점에 유의하세요.

`--type=<type>` 옵션은 'git config'에게 들어오고 나가는 값이 주어진 <type> 아래에서 정규화될 수 있도록 하도록 지시합니다. `--type=<type>`이 지정되지 않으면 정규화가 수행되지 않습니다. 호출자는 `--no-type`을 사용하여 기존의 `--type` 지정자를 해제할 수 있습니다.

읽을 때, 기본적으로 값은 시스템, 전역 및 저장소 로컬 설정 파일에서 읽혀지며, `--system`, `--global`, `--local`, `--worktree` 및 `--file <filename>` 옵션을 사용하여 해당 위치에서만 읽도록 명령에 지시할 수 있습니다 (<<FILES>> 참조).

쓸 때, 새 값은 기본적으로 저장소 로컬 설정 파일에 쓰여지며, `--system`, `--global`, `--worktree`, `--file <filename>` 옵션을 사용하여 해당 위치에 쓰도록 명령에 지시할 수 있습니다 (`--local`이라고 말할 수도 있지만 이는 기본값입니다).

이 명령은 오류 발생 시 0이 아닌 상태 코드로 실패합니다. 일부 종료 코드는 다음과 같습니다:

- 섹션 또는 키가 유효하지 않음 (ret=1),
- 섹션 또는 이름이 제공되지 않음 (ret=2),
- 설정 파일이 유효하지 않음 (ret=3),
- 설정 파일을 쓸 수 없음 (ret=4),
- 존재하지 않는 옵션을 해제하려고 함 (ret=5),
- 여러 줄에 일치하는 옵션을 해제/설정하려고 함 (ret=5), 또는
- 유효하지 않은 정규 표현식을 사용하려고 함 (ret=6).

성공 시, 명령은 종료 코드 0을 반환합니다.

사용 가능한 모든 설정 변수 목록은 `git help --config` 명령을 사용하여 얻을 수 있습니다.

COMMANDS
--------

list::
	설정 파일에 설정된 모든 변수와 해당 값을 나열합니다.

get::
	지정된 키의 값을 출력합니다. 키가 설정에서 여러 번 나타나면 마지막 값을 출력합니다. `--all`이 지정되면 해당 키와 연관된 모든 값을 출력합니다. 키가 존재하지 않으면 오류 코드 1을 반환합니다.

set::
	하나 이상의 설정 옵션에 대한 값을 설정합니다. 기본적으로 이 명령은 여러 값을 갖는 설정 옵션을 쓰는 것을 거부합니다. `--all`을 전달하면 여러 값을 갖는 모든 설정 옵션을 새 값으로 대체하고, `--value=`를 전달하면 주어진 패턴과 일치하는 모든 설정 옵션을 대체합니다.

unset::
	하나 이상의 설정 옵션에 대한 값을 해제합니다. 기본적으로 이 명령은 여러 값을 갖는 키를 해제하는 것을 거부합니다. `--all`을 전달하면 여러 값을 갖는 모든 설정 옵션을 해제하고, `--value`를 전달하면 주어진 패턴과 일치하는 모든 설정 옵션을 해제합니다.

rename-section::
	주어진 섹션을 새 이름으로 변경합니다.

remove-section::
	설정 파일에서 주어진 섹션을 제거합니다.

edit::
	주어진 설정 파일을 수정하기 위해 편집기를 엽니다. `--system`, `--global`, `--local` (기본값), `--worktree` 또는 `--file <config-file>` 중 하나를 사용합니다.

[[OPTIONS]]
OPTIONS
-------

--replace-all::
	기본 동작은 최대 한 줄을 교체하는 것입니다. 이것은 키 (및 선택적으로 `--value=<pattern>`)와 일치하는 모든 줄을 교체합니다.

--append::
	기존 값을 변경하지 않고 옵션에 새 줄을 추가합니다. `set`에서 '--value=^$'를 제공하는 것과 동일합니다.

--comment <message>::
	새롭거나 수정된 줄의 끝에 주석을 추가합니다.
+
_<message>_가 하나 이상의 공백으로 시작하고 "#"으로 이어지면 그대로 사용됩니다. "#"으로 시작하면 그 앞에 공백이 추가됩니다. 그렇지 않으면 " # " (공백, 해시, 공백) 문자열이 앞에 추가됩니다. 그리고 결과 문자열은 변수에 대해 정의된 값 바로 뒤에 배치됩니다. _<message>_는 줄 바꿈 문자를 포함해서는 안 됩니다 (여러 줄 주석은 허용되지 않습니다).

--all::
	`get`과 함께 사용 시, 여러 값을 갖는 키에 대한 모든 값을 반환합니다.

--regexp::
	`get`과 함께 사용 시, 이름을 정규 표현식으로 해석합니다. 정규 표현식 일치는 현재 대소문자를 구분하며, 섹션과 변수 이름은 소문자로, 하위 섹션 이름은 대문자로 유지되지 않는 정규화된 키에 대해 수행됩니다.

--url=<URL>::
	<section>.<key> 형식의 두 부분으로 된 <name>이 주어졌을 때, 주어진 URL에 가장 잘 일치하는 <section>.<URL>.<key>의 값이 반환됩니다 (이러한 키가 없으면 <section>.<key>의 값이 대체로 사용됩니다). <section>만 이름으로 주어졌을 경우, 섹션의 모든 키에 대해 그렇게 하고 목록을 출력합니다. 값이 발견되지 않으면 오류 코드 1을 반환합니다.

--global::
	옵션을 쓸 때: 저장소 `.git/config` 대신 전역 `~/.gitconfig` 파일에 씁니다. 이 파일이 존재하고 `~/.gitconfig` 파일이 존재하지 않으면 `$XDG_CONFIG_HOME/git/config` 파일에 씁니다.
+
옵션을 읽을 때: 모든 사용 가능한 파일 대신 전역 `~/.gitconfig` 및 `$XDG_CONFIG_HOME/git/config`에서만 읽습니다.
+
<<FILES>>도 참조하세요.

--system::
	옵션을 쓸 때: 저장소 `.git/config` 대신 시스템 전체 `$(prefix)/etc/gitconfig`에 씁니다.
+
옵션을 읽을 때: 모든 사용 가능한 파일 대신 시스템 전체 `$(prefix)/etc/gitconfig`에서만 읽습니다.
+
<<FILES>>도 참조하세요.

--local::
	옵션을 쓸 때: 저장소 `.git/config` 파일에 씁니다. 이것이 기본 동작입니다.
+
옵션을 읽을 때: 모든 사용 가능한 파일 대신 저장소 `.git/config`에서만 읽습니다.
+
<<FILES>>도 참조하세요.

--worktree::
	`--local`과 유사하지만, `extensions.worktreeConfig`가 활성화된 경우 `$GIT_DIR/config.worktree`에서 읽거나 씁니다. 그렇지 않으면 `--local`과 동일합니다. `$GIT_DIR`은 기본 워킹 트리의 경우 `$GIT_COMMON_DIR`와 같지만, 다른 워킹 트리의 경우 `$GIT_DIR/worktrees/<id>/` 형식입니다. `extensions.worktreeConfig`를 활성화하는 방법을 알아보려면 linkgit:git-worktree[1]를 참조하세요.

-f <config-file>::
--file <config-file>::
	옵션을 쓸 때: 저장소 `.git/config` 대신 지정된 파일에 씁니다.
+
옵션을 읽을 때: 사용 가능한 모든 파일 대신 지정된 파일에서만 읽습니다.
+
<<FILES>>도 참조하세요.

--blob <blob>::
	`--file`과 유사하지만 지정된 블롭을 파일 대신 사용합니다. 예를 들어, `master:.gitmodules`를 사용하여 마스터 브랜치의 `.gitmodules` 파일에서 값을 읽을 수 있습니다. 블롭 이름 철자에 대한 보다 완전한 목록은 linkgit:gitrevisions[7]의 "SPECIFYING REVISIONS" 섹션을 참조하세요.

`--value=<pattern>`::
`--no-value`::
	`get`, `set`, `unset`과 함께 사용 시, _<pattern>_에 대해서만 일치합니다. 패턴은 `--fixed-value`가 지정되지 않은 한 확장 정규 표현식입니다.
+
_<pattern>_을 해제하려면 `--no-value`를 사용하세요.

--fixed-value::
	`--value=<pattern>`과 함께 사용 시, _<pattern>_을 정규 표현식이 아닌 정확한 문자열로 취급합니다. 이렇게 하면 일치하는 이름/값 쌍이 값이 _<pattern>_과 정확히 일치하는 경우로 제한됩니다.

--type <type>::
  'git config'는 입력 또는 출력이 주어진 타입 제약 조건 하에서 유효한지 확인하고, 출력 값을 `<type>`의 표준 형태로 정규화합니다.
+
유효한 `<type>`는 다음과 같습니다:
+
- 'bool': `true`, `yes`, `on`, 양수를 "true"로, `false`, `no`, `off`, `0`을 "false"로 정규화합니다.
- 'int': 값을 단순 십진수로 정규화합니다. 'k', 'm', 'g' 접미사는 입력 시 각각 1024, 1048576, 1073741824를 곱하는 것을 의미합니다.
- 'bool-or-int': 위에서 설명한 대로 'bool' 또는 'int'에 따라 정규화합니다.
- 'path': 선행 `~`를 `$HOME` 값으로, `~user`를 지정된 사용자의 홈 디렉토리로 확장하여 정규화합니다. 이 지정자는 값을 설정할 때 효과가 없습니다 (하지만 쉘이 확장하도록 하려면 명령줄에서 `git config section.variable ~/`을 사용할 수 있습니다).
- 'expiry-date': 고정 또는 상대 날짜 문자열에서 타임스탬프로 변환하여 정규화합니다. 이 지정자는 값을 설정할 때 효과가 없습니다.
- 'color': 값을 가져올 때 ANSI 색상 이스케이프 시퀀스로 변환하여 정규화합니다. 값을 설정할 때, 주어진 값이 ANSI 색상으로 정규화될 수 있는지 확인하는 유효성 검사가 수행되지만, 값은 그대로 작성됩니다.
+
명령이 `list` 모드인 경우, `--type <type>` 인수는 나열된 각 설정 값에 적용됩니다. 값이 해당 형식으로 성공적으로 파싱되지 않으면 목록에서 제외됩니다.

--bool::
--int::
--bool-or-int::
--path::
--expiry-date::
  타입 지정자를 선택하기 위한 과거의 옵션입니다. 대신 `--type`을 선호하세요 (위 참조).

--no-type::
  이전에 설정된 타입 지정자를 해제합니다 (이전에 설정된 경우). 이 옵션은 'git config'가 검색된 변수를 정규화하지 않도록 요청합니다. `--no-type`은 `--type=<type>` 또는 `--<type>` 없이 효과가 없습니다.

-z::
--null::
	값을 출력하는 모든 옵션의 경우, 항상 값 뒤에 null 문자(개행 문자 대신)를 붙입니다. 키와 값 사이의 구분자로 개행 문자를 사용합니다. 이렇게 하면 값에 줄 바꿈 문자가 포함되어 있어도 출력의 안전한 파싱이 가능합니다.

--name-only::
	`list` 또는 `get`에서 설정 변수 이름만 출력합니다.

`--show-names`::
`--no-show-names`::
	`get`과 함께 사용 시, 값 외에 설정 키를 표시합니다. 기본값은 `--no-show-names`이며, `--url`이 지정되고 _<name>_에 하위 섹션이 없을 때를 제외하고는 그렇습니다.

--show-origin::
	쿼리된 모든 설정 옵션의 출력에 원본 유형 (파일, 표준 입력, 블롭, 명령줄)과 실제 원본 (구성 파일 경로, ref 또는 해당되는 경우 블롭 ID)을 추가합니다.

--show-scope::
	`--show-origin`과 유사하게, 쿼리된 모든 설정 옵션의 출력에 해당 값의 범위 (worktree, local, global, system, command)를 추가합니다.

--get-colorbool <name> [<stdout-is-tty>]::

	`<name>` (예: `color.diff`)의 색상 설정을 찾아서 "true" 또는 "false"를 출력합니다. `<stdout-is-tty>`는 "true" 또는 "false"여야 하며, 구성에서 "auto"라고 말할 때 고려됩니다. `<stdout-is-tty>`가 누락되면 명령 자체의 표준 출력을 확인하고, 색상이 사용될 경우 상태 0으로 종료하거나, 그렇지 않으면 상태 1로 종료합니다.
	`name`에 대한 색상 설정이 정의되지 않은 경우, 명령은 `color.ui`를 대체로 사용합니다.

--includes::
--no-includes::
	설정 파일의 `include.*` 지시문을 값 조회 시 존중합니다. 특정 파일이 주어졌을 때 (예: `--file`, `--global` 등 사용) `off`이고, 모든 설정 파일을 검색할 때 `on`입니다.

--default <value>::
  `get`을 사용할 때 요청한 변수를 찾지 못하면, <value>가 해당 변수에 할당된 값인 것처럼 동작합니다.

DEPRECATED MODES
----------------

다음 모드는 하위 명령을 위해 폐기되었습니다. 새로운 구문으로 마이그레이션하는 것이 좋습니다.

'git config <name>'::
	`git config get <name>`으로 대체되었습니다.

'git config <name> <value> [<value-pattern>]'::
	`git config set [--value=<pattern>] <name> <value>`으로 대체되었습니다.

-l::
--list::
	`git config list`로 대체되었습니다.

--get <name> [<value-pattern>]::
	`git config get [--value=<pattern>] <name>`으로 대체되었습니다.

--get-all <name> [<value-pattern>]::
	`git config get [--value=<pattern>] --all <name>`으로 대체되었습니다.

--get-regexp <name-regexp>::
	`git config get --all --show-names --regexp <name-regexp>`으로 대체되었습니다.

--get-urlmatch <name> <URL>::
	`git config get --url=<URL> <name>`으로 대체되었습니다.

--get-color <name> [<default>]::
	`git config get --type=color [--default=<default>] <name>`으로 대체되었습니다.

--add <name> <value>::
	`git config set --append <name> <value>`으로 대체되었습니다.

--unset <name> [<value-pattern>]::
	`git config unset [--value=<pattern>] <name>`으로 대체되었습니다.

--unset-all <name> [<value-pattern>]::
	`git config unset [--value=<pattern>] --all <name>`으로 대체되었습니다.

--rename-section <old-name> <new-name>::
	`git config rename-section <old-name> <new-name>`으로 대체되었습니다.

--remove-section <name>::
	`git config remove-section <name>`으로 대체되었습니다.

-e::
--edit::
	`git config edit`으로 대체되었습니다.

CONFIGURATION
-------------
`pager.config`는 설정 목록을 가져올 때만 존중됩니다. 즉, `list` 또는 여러 결과를 반환할 수 있는 `get`을 사용할 때입니다. 기본적으로 페이저를 사용합니다.

[[FILES]]
FILES
-----

기본적으로 'git config'는 여러 파일에서 설정 옵션을 읽습니다:

$(prefix)/etc/gitconfig::
	시스템 전체 설정 파일.

$XDG_CONFIG_HOME/git/config::
~/.gitconfig::
	사용자별 설정 파일. XDG_CONFIG_HOME 환경 변수가 설정되지 않았거나 비어 있으면, $HOME/.config/가 $XDG_CONFIG_HOME으로 사용됩니다.
+
이들은 "전역" 설정 파일이라고도 합니다. 두 파일이 모두 존재하면, 위에서 주어진 순서대로 두 파일이 모두 읽혀집니다.

$GIT_DIR/config::
	저장소별 설정 파일.

$GIT_DIR/config.worktree::
	이것은 선택 사항이며 `extensions.worktreeConfig`가 $GIT_DIR/config에 존재할 때만 검색됩니다.

또한 `-c` 옵션을 사용하여 git 명령을 실행할 때 추가 설정 매개변수를 제공할 수 있습니다. 자세한 내용은 linkgit:git[1]을 참조하십시오.

사용 가능한 모든 파일에서 옵션이 읽혀집니다. 전역 또는 시스템 전체 설정 파일이 누락되거나 읽을 수 없으면 무시됩니다. 저장소 설정 파일이 누락되거나 읽을 수 없으면, 'git config'는 0이 아닌 오류 코드로 종료됩니다. 파일이 읽을 수 없는 경우 오류 메시지가 생성되지만, 파일이 누락된 경우에는 메시지가 생성되지 않습니다.

파일은 위에서 주어진 순서대로 읽혀지며, 나중에 발견된 값이 이전에 읽은 값보다 우선합니다. 여러 값이 취해질 경우, 모든 파일에서 해당 키의 모든 값이 사용됩니다.

기본적으로 옵션은 저장소별 설정 파일에만 쓰여집니다. 이것은 `set` 및 `unset`과 같은 옵션에도 영향을 미친다는 점에 유의하세요. *'git config'는 한 번에 하나의 파일만 변경합니다.*

`--file` 옵션으로 파일 경로를 지정하거나 `--system`, `--global`, `--local`, 또는 `--worktree`로 구성 범위를 지정하여 읽거나 쓸 구성 소스를 제한할 수 있습니다. 자세한 내용은 위 <<OPTIONS>>를 참조하십시오.

[[SCOPES]]
SCOPES
------

각 구성 소스는 구성 범위 내에 있습니다. 범위는 다음과 같습니다:

system::
	$(prefix)/etc/gitconfig

global::
	$XDG_CONFIG_HOME/git/config
+
~/.gitconfig

local::
	$GIT_DIR/config

worktree::
	$GIT_DIR/config.worktree

command::
	GIT_CONFIG_{COUNT,KEY,VALUE} 환경 변수 (아래 <<ENVIRONMENT>> 참조)
+
`-c` 옵션

'command'를 제외한 각 범위는 `--system`, `--global`, `--local`, `--worktree`와 같은 명령줄 옵션에 해당합니다.

옵션을 읽을 때, 범위를 지정하면 해당 범위 내의 파일에서만 옵션을 읽게 됩니다. 옵션을 쓸 때, 범위를 지정하면 해당 범위 내의 파일에 쓰여집니다 (저장소별 설정 파일 대신). 전체 설명은 위 <<OPTIONS>>를 참조하십시오.

대부분의 구성 옵션은 정의된 범위에 관계없이 존중되지만, 일부 옵션은 특정 범위에서만 존중됩니다. 전체 내용은 해당 옵션의 문서를 참조하십시오.

보호된 구성
~~~~~~~~~~~~~~~~~~~~~~~

보호된 구성은 'system', 'global', 'command' 범위를 말합니다.
보안상의 이유로 특정 옵션은 보호된 구성에 지정된 경우에만 존중되며, 그렇지 않으면 무시됩니다.

Git은 이러한 범위를 사용자가 제어하거나 신뢰할 수 있는 관리자가 제어하는 것으로 취급합니다. 이는 이러한 범위를 제어하는 공격자가 Git을 사용하지 않고도 상당한 피해를 줄 수 있기 때문입니다. 따라서 사용자의 환경이 이러한 범위를 공격으로부터 보호한다고 가정합니다.

[[ENVIRONMENT]]
ENVIRONMENT
-----------

GIT_CONFIG_GLOBAL::
GIT_CONFIG_SYSTEM::
	전역 또는 시스템 수준 구성 대신 지정된 파일에서 구성을 가져옵니다. 자세한 내용은 linkgit:git[1]을 참조하십시오.

GIT_CONFIG_NOSYSTEM::
	시스템 전체 `$(prefix)/etc/gitconfig` 파일에서 설정을 읽는 것을 건너뛸지 여부입니다. 자세한 내용은 linkgit:git[1]을 참조하십시오.

<<FILES>>도 참조하십시오.

GIT_CONFIG_COUNT::
GIT_CONFIG_KEY_<n>::
GIT_CONFIG_VALUE_<n>::
	GIT_CONFIG_COUNT가 양수로 설정된 경우, 해당 개수까지의 모든 환경 쌍 GIT_CONFIG_KEY_<n> 및 GIT_CONFIG_VALUE_<n>이 프로세스의 런타임 구성에 추가됩니다. 구성 쌍은 0부터 시작합니다. 누락된 키 또는 값은 오류로 처리됩니다. 빈 GIT_CONFIG_COUNT는 GIT_CONFIG_COUNT=0과 동일하게 처리되며, 즉 어떤 쌍도 처리되지 않습니다. 이러한 환경 변수는 구성 파일의 값을 무시하지만, `git -c`를 통해 명시적으로 전달된 옵션에 의해 무시됩니다.
+
이는 구성 파일을 의존할 수 없는 경우, 예를 들어 스크립트를 작성할 때 공통 구성을 가진 여러 git 명령을 실행하려는 경우에 유용합니다.

GIT_CONFIG::
	`git config`에 `--file` 옵션이 제공되지 않은 경우, `GIT_CONFIG`에서 제공된 파일을 `--file`을 통해 제공된 것처럼 사용합니다. 이 변수는 다른 Git 명령에는 영향을 미치지 않으며, 주로 이전 호환성을 위한 것입니다. 일반적으로 `--file` 옵션 대신 사용할 이유는 없습니다.

[[EXAMPLES]]
EXAMPLES
--------

.git/config 파일이 다음과 같다고 가정해 보겠습니다:

------------
#
# 이것은 설정 파일이며,
# '#' 또는 ';' 문자는
# 주석을 나타냅니다.
#

; core variables
[core]
	; 파일 모드를 신뢰하지 않음
	filemode = false

; 우리의 diff 알고리즘
[diff]
	external = /usr/local/bin/diff-wrapper
	renames = true

; 프록시 설정
[core]
	gitproxy= proxy-command for kernel.org
	gitproxy=default-proxy ; for all the rest

; HTTP
[http]
	sslVerify
[http "https://weak.example.com"]
	sslVerify = false
	cookieFile = /tmp/cookie.txt
------------

다음과 같이 `filemode`를 `true`로 설정할 수 있습니다:

------------
% git config set core.filemode true
------------

가상의 프록시 명령 항목에는 어떤 URL에 적용되는지 구별하기 위한 접미사가 실제로 있습니다. kernel.org에 대한 항목을 "ssh"로 변경하는 방법은 다음과 같습니다.

------------
% git config set --value='for kernel.org$' core.gitproxy '"ssh" for kernel.org'
------------

이것은 kernel.org에 대한 키/값 쌍만 교체되도록 합니다.

renames 항목을 삭제하려면 다음을 수행하십시오:

------------
% git config unset diff.renames
------------

multivar (위의 core.gitproxy와 같은)에 대한 항목을 삭제하려면, 정확히 하나의 줄의 값을 일치시키는 정규 표현식을 제공해야 합니다.

주어진 키의 값을 조회하려면 다음을 수행하십시오:

------------
% git config get core.filemode
------------

또는 multivar를 조회하려면:

------------
% git config get --value="for kernel.org$" core.gitproxy
------------

multivar에 대한 모든 값을 알고 싶다면 다음을 수행하십시오:

------------
% git config get --all --show-names core.gitproxy
------------

위험을 감수하고 싶다면, 모든 core.gitproxy를 새 것으로 바꿀 수 있습니다:

------------
% git config set --all core.gitproxy ssh
------------

하지만, 기본 프록시에 대한 줄, 즉 "for ..." 접미사가 없는 줄만 대체하고 싶다면 다음과 같이 하십시오:

------------
% git config set --value='! for ' core.gitproxy ssh
------------

실제로 느낌표가 있는 값만 일치시키려면 다음을 수행해야 합니다:

------------
% git config set --value='[!]' section.key value
------------

기존 프록시를 변경하지 않고 새 프록시를 추가하려면 다음을 사용하십시오:

------------
% git config set --append core.gitproxy '"proxy-command" for example.com'
------------

스크립트에서 구성의 사용자 지정 색상을 사용하는 예제:

------------
#!/bin/sh
WS=$(git config get --type=color --default="blue reverse" color.diff.whitespace)
RESET=$(git config get --type=color --default="reset" "")
echo "${WS}your whitespace color or blue reverse${RESET}"
------------

`https://weak.example.com`의 URL의 경우, `http.sslVerify`는 false로 설정되어 있는 반면, 다른 모든 URL에 대해서는 `true`로 설정되어 있습니다:

------------
% git config get --type=bool --url=https://good.example.com http.sslverify
true
% git config get --type=bool --url=https://weak.example.com http.sslverify
false
% git config get --url=https://weak.example.com http
http.cookieFile /tmp/cookie.txt
http.sslverify false
------------

include::config.adoc[]

BUGS
----
폐기된 `[section.subsection]` 구문을 사용할 때, 값을 변경하면 하위 섹션에 대문자가 하나 이상 포함된 경우 변경이 아닌 다중 줄 키를 추가하게 됩니다. 예를 들어 설정이 다음과 같을 때

--------
  [section.subsection]
    key = value1
--------

`git config section.Subsection.key value2`를 실행하면 다음 결과가 나옵니다:

--------
  [section.subsection]
    key = value1
    key = value2
--------


GIT
---
linkgit:git[1] 제품군의 일부