git-show-branch(1)
==================

NAME
----
git-show-branch - 브랜치와 커밋을 표시

SYNOPSIS
--------
[verse]
'git show-branch' [-a | --all] [-r | --remotes] [--topo-order | --date-order]
		[--current] [--color[=<when>] | --no-color] [--sparse]
		[--more=<n> | --list | --independent | --merge-base]
		[--no-name | --sha1-name] [--topics]
		(<rev> | <glob>)...
'git show-branch' (-g | --reflog)[=<n>[,<base>]] [--list] [<ref>]

DESCRIPTION
-----------

<rev> 또는 <glob>으로 명명된 커밋(또는 refs/heads 및/또는 refs/tags 아래의 모든 ref)에서 시작하는 커밋 계보 그래프를 반 시각적으로 표시합니다.

한 번에 26개 이상의 브랜치와 커밋을 표시할 수 없습니다.

명령줄에서 <rev> 또는 <glob>이 주어지지 않으면 `showbranch.default`의 다중값 구성 항목을 사용합니다.


OPTIONS
-------
<rev>::
	임의의 확장된 SHA-1 표현식(linkgit:gitrevisions[7] 참조)으로,
	일반적으로 브랜치 헤드 또는 태그를 가리킵니다.

<glob>::
	refs/ 아래의 브랜치 또는 태그 이름과 일치하는 glob 패턴입니다.
	예를 들어, refs/heads/topic 아래에 많은 토픽 브랜치가 있다면,
	`topic/*`를 제공하면 해당 브랜치 모두를 표시합니다.

-r::
--remotes::
	원격 추적 브랜치를 표시합니다.

-a::
--all::
	원격 추적 브랜치와 로컬 브랜치를 모두 표시합니다.

--current::
	이 옵션을 사용하면 명령이 현재 브랜치를,
	명령줄에서 주어지지 않았을 때 표시할 rev 목록에 포함합니다.

--topo-order::
        기본적으로 브랜치와 해당 커밋은 역 시간순으로 표시됩니다.
        이 옵션은 브랜치와 해당 커밋을 위상 정렬 순서(즉, 자식 커밋이
        부모 커밋보다 먼저 표시되도록)로 표시합니다.

--date-order::
	이 옵션은 `--topo-order`와 유사하게 부모가 모든 자식보다 먼저 오지 않지만,
	그 외에는 커밋이 커밋 날짜에 따라 정렬됩니다.

--sparse::
	기본적으로 출력은 표시되는 하나의 팁에서만 도달 가능한 머지를 생략합니다.
	이 옵션은 이러한 머지를 보이게 합니다.

--more=<n>::
	보통 명령은 모든 브랜치의 공통 조상인 커밋을 표시한 후 출력합니다.
	이 플래그는 해당 지점을 넘어 <n>개의 공통 커밋을 더 진행하도록
	명령에 알립니다. <n>이 음수이면, 커밋 계보 트리를 표시하지 않고,
	지정된 <ref>만 표시합니다.

--list::
	`--more=-1`의 별칭입니다.

--merge-base::
	커밋 목록을 표시하는 대신, 지정된 커밋에 대한 가능한
	머지 베이스를 결정합니다. 모든 머지 베이스는 지정된 모든 커밋에
	포함됩니다. 이는 linkgit:git-merge-base[1]이 세 개 이상의 커밋을
	처리하는 방식과는 다릅니다.

--independent::
	주어진 <ref> 중에서 다른 <ref>에서 도달할 수 없는 것만 표시합니다.

--no-name::
	각 커밋에 대한 이름 문자열을 표시하지 않습니다.

--sha1-name::
	커밋을 헤드로부터의 경로를 사용하여 이름 짓는 대신(예: "master"의
	조부모를 의미하는 "master~2"), 고유 객체 이름의 접두사로
	이름을 짓습니다.

--topics::
	주어진 첫 번째 브랜치에 있지 않은 커밋만 표시합니다.
	이는 메인 개발 라인에 이미 있는 커밋을 숨김으로써 토픽 브랜치를
	추적하는 데 도움이 됩니다. "git show-branch --topics master topic1 topic2"를
	주면, "git rev-list {caret}master topic1 topic2"로 주어진 리비전을 표시합니다.

-g::
--reflog[=<n>[,<base>]] [<ref>]::
	주어진 ref에 대한 <n>개의 가장 최근 ref-log 항목을 표시합니다.
	<base>가 주어지면, 해당 항목에서 <n>개의 항목까지 거슬러 올라갑니다.
	<base>는 개수 또는 날짜로 지정할 수 있습니다.
	명시적인 <ref> 매개변수가 주어지지 않으면, 기본값은
	현재 브랜치(또는 detached 상태이면 `HEAD`)입니다.

--color[=<when>]::
	각 커밋의 브랜치에 해당하는 상태 기호(`*`, `!`, `+`, `-`)를
	색상으로 지정합니다.
	값은 always(기본값), never, 또는 auto여야 합니다.

--no-color::
	구성 파일에서 기본값이 색상 출력을 지정하더라도 색상 출력을 끕니다.
	`--color=never`와 동일합니다.

--more, --list, --independent, --merge-base 옵션은 서로 배타적입니다.


OUTPUT
------

N개의 <ref>가 주어지면, 처음 N개의 줄은 커밋 메시지에서 가져온
한 줄 설명입니다. $GIT_DIR/HEAD가 가리키는 브랜치 헤드는 별표 `*` 문자로
이름이 붙고 다른 헤드는 `!` 문자로 이름이 붙습니다.

이 N개의 줄 다음에는 각 커밋에 대한 한 줄 로그가 N개의 위치만큼 들여쓰기되어
표시됩니다. 커밋이 I번째 브랜치에 있다면, I번째 들여쓰기 문자는 `+` 기호를
표시하고, 그렇지 않으면 공백을 표시합니다. 머지 커밋은 `-` 기호로 표시됩니다.
각 커밋에는 해당 커밋을 이름 짓는 데 사용할 수 있는 확장된 SHA-1으로
사용할 수 있는 짧은 이름이 표시됩니다.

다음 예는 "master", "fixes", "mhf" 세 개의 브랜드를 보여줍니다.

------------------------------------------------
$ git show-branch master fixes mhf
* [master] Add 'git show-branch'.
 ! [fixes] Introduce "reset type" flag to "git reset"
  ! [mhf] Allow "+remote:local" refspec to cause --force when fetching.
---
  + [mhf] Allow "+remote:local" refspec to cause --force when fetching.
  + [mhf~1] Use git-octopus when pulling more than one head.
 +  [fixes] Introduce "reset type" flag to "git reset"
  + [mhf~2] "git fetch --force".
  + [mhf~3] Use .git/remote/origin, not .git/branches/origin.
  + [mhf~4] Make "git pull" and "git fetch" default to origin
  + [mhf~5] Infamous 'octopus merge'
  + [mhf~6] Retire git-parse-remote.
  + [mhf~7] Multi-head fetch.
  + [mhf~8] Start adding the $GIT_DIR/remotes/ support.
*++ [master] Add 'git show-branch'.
------------------------------------------------

이 세 브랜치는 모두 커밋 메시지가 "Add \'git show-branch\'"인
[master]라는 공통 커밋에서 분기되었습니다.
"fixes" 브랜치는 "Introduce "reset type" flag to "git reset""라는
커밋 하나를 추가합니다. "mhf" 브랜치는 다른 여러 커밋을 추가합니다.
현재 브랜치는 "master"입니다.


EXAMPLES
--------

기본 브랜치를 `refs/heads` 바로 아래에, 토픽 브랜치를
그것의 하위 디렉토리에 유지하는 경우, 구성 파일에 다음 내용을
가지고 있으면 도움이 될 수 있습니다.

------------
[showbranch]
	default = --topo-order
	default = heads/*

------------

이를 사용하면 추가 매개변수 없이 `git show-branch`를 실행하면
기본 브랜치만 표시됩니다. 또한, 우연히 토픽 브랜치에 있다면,
해당 브랜치도 표시됩니다.

------------
$ git show-branch --reflog="10,1 hour ago" --list master
------------

1시간 전 시점의 팁에서부터 10개의 reflog 항목을 표시합니다.
`--list` 없이 실행하면, 이 팁들이 서로 위상학적으로 어떻게
연관되어 있는지 보여주는 출력도 함께 표시됩니다.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/showbranch.adoc[]

GIT
---
linkgit:git[1] 제품군의 일부입니다.