git-archimport(1)
=================

NAME
----
git-archimport - GNU Arch 저장소를 Git으로 가져오기

SYNOPSIS
--------
[verse]
'git archimport' [-h] [-v] [-o] [-a] [-f] [-T] [-D <depth>] [-t <tempdir>]
	       <archive>/<branch>[:<git-branch>]...

DESCRIPTION
-----------
하나 이상의 GNU Arch 저장소에서 프로젝트를 가져옵니다.
제공된 `<archive>/<branch>` 매개변수로 정의된 네임스페이스 내에서 브랜치 및 저장소를 따릅니다.
만약 머지에 사용된 원격 브랜치를 찾지 못하면 일반 커밋으로 가져옵니다.
찾을 수 있다면, 가능한 한 머지로 표시합니다 (아래 토론 참조).

이 스크립트는 '초기 가져오기' 또는 '태그' 유형의 Arch 커밋에서 시작할 수 있는 주요 루트를 제공해야 합니다.
제공된 루트 내에서 새로운 브랜치를 따라 가져올 것입니다.

이것은 오직 하나의 프로젝트만 다룬다고 가정합니다.
다른 루트를 가진 브랜치를 보면 실행을 거부합니다.
이 경우, 가져오기 범위를 명확하게 정의하도록 `<archive>/<branch>` 매개변수를 편집하십시오.

'git archimport'는 백그라운드에서 Arch 저장소에 액세스하기 위해 `tla`를 광범위하게 사용합니다.
경로에 최신 버전의 `tla`가 있는지 확인하십시오. `tla`는 'git archimport'에 전달하는 저장소에 대해 알고 있어야 합니다.

초기 가져오기의 경우, 'git archimport'는 비어 있는 디렉토리에서 자신을 찾을 것으로 예상합니다.
Arch를 사용하는 프로젝트의 개발을 따라가려면, 초기 가져오기와 동일한 매개변수로 'git archimport'를 다시 실행하여 증분 가져오기를 수행하십시오.

'git archimport'는 가져오는 아카이브에 대해 합리적인 브랜치 이름을 생성하려고 시도하지만,
Git 브랜치 이름을 수동으로 지정하는 것도 가능합니다.
이를 위해, 각 `<archive>/<branch>` 매개변수 뒤에 콜론으로 구분하여 Git 브랜치 이름을 쓰십시오.
이런 식으로, Arch 브랜치 이름을 단축하고 Arch 용어를 Git 용어로 변환할 수 있습니다.
예를 들어, "PROJECT{litdd}devo{litdd}VERSION" 브랜치를 "master"로 매핑하는 것입니다.

여러 Arch 브랜치를 하나의 Git 브랜치에 연결하는 것이 가능합니다.
결과는 두 번째 브랜치가 생성된 후 첫 번째 브랜치에 커밋이 이루어지지 않은 경우에만 가장 의미가 있습니다.
그럼에도 불구하고, 주기적으로 회전된 Arch 저장소를 변환하는 데 유용합니다.


MERGES
------
Arch에서 패치 머지 데이터는 Git에서도 머지를 표시하는 데 사용됩니다.
Git은 패치를 추적하는 데 크게 신경 쓰지 않으며, 브랜치가 포크된 시점부터의 모든 커밋을 통합할 때만 머지를 고려합니다.
결과적으로 Git은 브랜치가 얼마나 분기되었는지에 대한 좋은 아이디어를 갖게 됩니다.
따라서 가져오기 과정에서 일부 패치 거래 메타데이터가 손실됩니다.

운 좋게도, Arch에서 가져온 브랜치를 머지하려고 할 때,
Git은 좋은 머지 기준점을 찾을 것이며, 브랜치 간에 순서가 잘못된 패치를 식별할 가능성이 높습니다.

OPTIONS
-------

-h::
	사용법을 표시합니다.

-v::
	상세 출력을 표시합니다.

-T::
	많은 태그. Arch 저장소의 커밋 이름을 반영하는 각 커밋에 대해 태그를 생성합니다.

-f::
	빠른 패치셋 가져오기 전략을 사용합니다.
	이는 대규모 트리에서 상당히 빠를 수 있지만, 디렉토리 이름 변경이나 권한 변경을 처리할 수 없습니다.
	기본 전략은 느리고 안전합니다.

-o::
	이전 버전의 'git archimport'에서 사용된 오래된 스타일의 브랜치 이름과의 호환성을 위해 사용합니다.
	오래된 스타일의 브랜치 이름은 category{litdd}branch였던 반면, 새 스타일의 브랜치 이름은 archive,category{litdd}branch{litdd}version입니다.
	두 경우 모두, 명령줄에서 제공된 이름이 자동으로 생성된 이름을 재정의합니다.

-D <depth>::
	머지 조상을 따라가며 머지된 트리들을 가져오려고 시도합니다.
	패치 로그가 잘렸다면 1보다 큰 깊이를 지정하십시오.

-a::
	`http://mirrors.sourcecontrol.net`에서 아카이브를 자동 등록하려고 시도합니다.
	이것은 특히 -D 옵션과 함께 유용합니다.

-t <tmpdir>::
	기본 tempdir를 재정의합니다.


<archive>/<branch>::
	`tla log`가 이해하는 형식의 <archive>/<branch> 식별자.


GIT
---
linkgit:git[1] 제품군의 일부