git-revert(1)
=============

NAME
----
git-revert - Revert some existing commits

SYNOPSIS
--------
[verse]
'git revert' [--[no-]edit] [-n] [-m <parent-number>] [-s] [-S[<keyid>]] <commit>...
'git revert' (--continue | --skip | --abort | --quit)

DESCRIPTION
-----------

기존 커밋을 하나 이상 받아, 해당 패치가 도입한 변경 사항을 되돌리고, 이를 기록할 새로운 커밋을 생성합니다. 이를 위해서는 워킹 트리가 깨끗해야 합니다 (HEAD 커밋으로부터의 수정 사항이 없어야 합니다).

참고: 'git revert'는 이전 커밋 (종종 결함이 있는 하나)의 영향을 되돌리기 위한 새로운 커밋을 기록하는 데 사용됩니다. 작업 디렉토리에서 커밋되지 않은 모든 변경 사항을 버리려면 linkgit:git-reset[1]을 참조하십시오. 특히 `--hard` 옵션을 참조하십시오. 다른 커밋에 있던 특정 파일을 추출하고 싶다면 linkgit:git-restore[1]을 참조하십시오. 특히 `--source` 옵션을 참조하십시오. 이 대안들은 작업 디렉토리에서 커밋되지 않은 변경 사항을 모두 삭제하므로 주의하여 사용하십시오.

세 가지 명령 간의 차이점은 linkgit:git[1]의 "Reset, restore and revert" 섹션을 참조하십시오.

OPTIONS
-------
<commit>...::
	되돌릴 커밋.
	커밋 이름을 철자하는 방법에 대한 더 완전한 목록은 linkgit:gitrevisions[7]을 참조하십시오.
	커밋 집합도 제공될 수 있지만 기본적으로 탐색은 수행되지 않습니다. linkgit:git-rev-list[1] 및 해당 `--no-walk` 옵션을 참조하십시오.

-e::
--edit::
	이 옵션을 사용하면 'git revert'는 커밋 전에 커밋 메시지를 편집할 수 있게 합니다. 터미널에서 명령을 실행하는 경우 이것이 기본값입니다.

-m parent-number::
--mainline parent-number::
	일반적으로 머지 커밋을 되돌리는 것은 어느 쪽이 메인라인으로 간주되어야 하는지 알 수 없기 때문에 되돌릴 수 없습니다. 이 옵션은 메인라인의 부모 번호 (1부터 시작)를 지정하고, 지정된 부모에 상대적인 변경을 되돌릴 수 있게 합니다.
+
머지 커밋을 되돌리는 것은 머지가 가져온 트리 변경 사항을 원하지 않는다는 것을 선언합니다. 결과적으로, 이후 머지는 이전에 되돌려진 머지의 조상이 아닌 커밋에 의해 도입된 트리 변경 사항만 가져올 것입니다. 이것이 원하는 것일 수도 있고 원하지 않는 것일 수도 있습니다.
+
더 자세한 정보는 link:howto/revert-a-faulty-merge.html[revert-a-faulty-merge How-To]를 참조하십시오.

--no-edit::
	이 옵션을 사용하면 'git revert'는 커밋 메시지 편집기를 시작하지 않습니다.

--cleanup=<mode>::
	이 옵션은 커밋 메시지가 커밋 메커니즘에 전달되기 전에 어떻게 정리될지를 결정합니다. 더 자세한 정보는 linkgit:git-commit[1]을 참조하십시오. 특히 '<mode>'가 `scissors` 값을 가지는 경우, 충돌이 발생했을 때 `MERGE_MSG`에 scissors가 추가된 후 전달됩니다.

-n::
--no-commit::
	일반적으로 이 명령은 어떤 커밋이 되돌려졌는지 명시하는 커밋 로그 메시지와 함께 일부 커밋을 자동으로 생성합니다. 이 플래그는 필요한 변경 사항을 워킹 트리와 인덱스에 적용하지만, 커밋을 생성하지는 않습니다. 또한, 이 옵션을 사용할 경우 인덱스는 HEAD 커밋과 일치할 필요가 없습니다. 되돌리기는 인덱스의 시작 상태에 대해 수행됩니다.
+
이것은 여러 커밋의 효과를 한 번에 인덱스에 되돌리고 싶을 때 유용합니다.

-S[<keyid>]::
--gpg-sign[=<keyid>]::
--no-gpg-sign::
	커밋에 GPG 서명합니다. `keyid` 인자는 선택 사항이며 커미터의 식별자로 기본 설정됩니다. 지정된 경우, 공백 없이 옵션에 붙여야 합니다. `--no-gpg-sign`은 `commit.gpgSign` 구성 변수와 이전 `--gpg-sign` 모두를 무효화하는 데 유용합니다.

-s::
--signoff::
	커밋 메시지 끝에 `Signed-off-by` 트레일러를 추가합니다. 더 자세한 정보는 linkgit:git-commit[1]의 signoff 옵션을 참조하십시오.

--strategy=<strategy>::
	지정된 머지 전략을 사용합니다. 한 번만 사용해야 합니다. 더 자세한 정보는 linkgit:git-merge[1]의 MERGE STRATEGIES 섹션을 참조하십시오.

-X<option>::
--strategy-option=<option>::
	머지 전략별 옵션을 머지 전략에 전달합니다. 더 자세한 정보는 linkgit:git-merge[1]을 참조하십시오.

include::rerere-options.adoc[]

--reference::
	로그 메시지 본문의 시작을 "This reverts <full-object-name-of-the-commit-being-reverted>."로 시작하는 대신, "--pretty=reference" 형식 (linkgit:git-log[1] 참조)을 사용하여 커밋을 참조합니다. `revert.reference` 구성 변수는 이 옵션을 기본값으로 활성화하는 데 사용될 수 있습니다.


SEQUENCER SUBCOMMANDS
---------------------
include::sequencer.adoc[]

EXAMPLES
--------
`git revert HEAD~3`::

	HEAD에서 네 번째 마지막 커밋에 지정된 변경 사항을 되돌리고, 되돌려진 변경 사항을 가진 새로운 커밋을 생성합니다.

`git revert -n master~5..master~2`::

	master에서 다섯 번째 마지막 커밋 (포함)부터 세 번째 마지막 커밋 (포함)까지의 커밋에서 발생한 변경 사항을 되돌리지만, 되돌려진 변경 사항에 대한 커밋을 생성하지는 않습니다. 되돌리기는 워킹 트리와 인덱스만 수정합니다.

DISCUSSION
----------

git은 기본적인 커밋 메시지를 자동으로 생성하지만, 원래 커밋이 왜 되돌려졌는지 설명하는 것이 _강력히_ 권장됩니다.
또한, 반복적으로 되돌리기를 수행하면 "Reapply "Reapply "<original-subject>""와 같이 점점 더 다루기 힘든 제목 줄이 만들어집니다. 더 짧고 고유한 제목으로 수정하는 것을 고려하십시오.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/revert.adoc[]

SEE ALSO
--------
linkgit:git-cherry-pick[1]

GIT
---
linkgit:git[1] 제품군의 일부