git-rerere(1)
=============

NAME
----
git-rerere - 충돌 머지(conflicted merge)의 기록된 해결책 재사용

SYNOPSIS
--------
[verse]
'git rerere' [clear | forget <pathspec>... | diff | status | remaining | gc]

DESCRIPTION
-----------

상대적으로 오래 지속되는 토픽 브랜치(topic branch)를 사용하는 워크플로우에서
개발자는 토픽 브랜치가 완료될 때까지 (주 "릴리즈" 브랜치에 머지되거나,
업스트림으로 보내져 수락될 때까지) 동일한 충돌을 반복해서 해결해야 할 수 있습니다.

이 명령어는 충돌하는 자동 머지(automerge) 결과와 해당 수동 해결(hand resolve) 결과를
초기 수동 머지 시 기록하고, 이전에 기록된 수동 해결책을 해당 자동 머지 결과에 적용하여
개발자를 돕습니다.

[NOTE]
이 명령어를 활성화하려면 `rerere.enabled` 설정 변수를 설정해야 합니다.


COMMANDS
--------

일반적으로 'git rerere'는 인자 없이 사용자 개입 없이 실행됩니다.
하지만, 작동 상태와 상호 작용할 수 있는 여러 명령어가 있습니다.

'clear'::

머지 해결이 중단될 경우 rerere에서 사용하는 메타데이터를 재설정합니다.
'git am [--skip|--abort]' 또는 'git rebase [--skip|--abort]'를 호출하면
이 명령어가 자동으로 호출됩니다.

'forget' <pathspec>::

<pathspec>과 일치하는 경로의 현재 충돌에 대해 rerere가 기록한
충돌 해결을 재설정합니다.

'diff'::

해결의 현재 상태에 대한 diff를 표시합니다.
사용자가 충돌을 해결하는 동안 무엇이 변경되었는지 추적하는 데 유용합니다.
추가 인자는 PATH에 설치된 시스템 'diff' 명령어로 직접 전달됩니다.

'status'::

rerere가 머지 해결을 기록할 충돌이 있는 경로를 출력합니다.

'remaining'::

rerere에 의해 자동 해결되지 않은 충돌이 있는 경로를 출력합니다.
여기에는 충돌하는 서브모듈과 같이 rerere가 추적할 수 없는 경로도 포함됩니다.

'gc'::

오래 전에 발생한 충돌 머지의 기록을 정리합니다.
기본적으로 15일보다 오래된 해결되지 않은 충돌과 60일보다 오래된 해결된 충돌이
정리됩니다. 이러한 기본값은 각각 `gc.rerereUnresolved` 및
`gc.rerereResolved` 구성 변수를 통해 제어됩니다.


DISCUSSION
----------

마스터 브랜치 (또는 업스트림)가 토픽 브랜치에서 포크된 이후 업데이트된
영역을 토픽 브랜치가 수정하는 경우, 토픽 브랜치가 업스트림으로 푸시될 준비가 되기 전에도
최신 마스터로 테스트하고 싶을 수 있습니다:

------------
              o---*---o---o topic
             /
    o---o---o---*---o---o master
------------

이러한 테스트를 위해 마스터와 토픽을 어떤 식으로든 머지해야 합니다.
한 가지 방법은 마스터를 토픽 브랜치로 가져오는 것입니다:

------------
	$ git switch topic
	$ git merge master

              o---*---o---+ topic
             /           /
    o---o---o---*---o---o master
------------

`*`로 표시된 커밋은 동일한 파일의 동일한 영역을 건드립니다.
`+`로 표시된 커밋을 생성할 때 충돌을 해결해야 합니다.
그런 다음 결과를 테스트하여 작업 중인 내용이 최신 마스터의 내용과 함께
여전히 작동하는지 확인할 수 있습니다.

이 테스트 머지 후, 토픽에 대한 작업을 계속하는 두 가지 방법이 있습니다.
가장 쉬운 방법은 테스트 머지 커밋 `+` 위에 구축하는 것이며,
토픽 브랜치의 작업이 최종적으로 준비되면 마스터 브랜치로 토픽 브랜치를 머지하거나,
업스트림에 당신으로부터 푸시하도록 요청할 수 있습니다.
그때까지는, 테스트 머지 `+` 이후 마스터 또는 업스트림이 진행되었을 수 있으며,
이 경우 최종 커밋 그래프는 다음과 같이 보일 것입니다:

------------
	$ git switch topic
	$ git merge master
	$ ... topic 및 master 브랜치 모두에서 작업
	$ git switch master
	$ git merge topic

              o---*---o---+---o---o topic
             /           /         \
    o---o---o---*---o---o---o---o---+ master
------------

그러나 토픽 브랜치가 오래 지속되면, 브랜치에 이러한 "마스터에서 머지" 커밋이
많이 쌓이게 되어 개발 히스토리를 불필요하게 복잡하게 만듭니다.
Linux 커널 메일링 리스트의 독자라면, 서브시스템 유지보수자가 "쓸모없는 머지"로 가득한
브랜치에서 풀링을 요청했을 때 Linus가 그러한 너무 잦은 테스트 머지에 대해 불평했던 것을
기억할 수 있습니다.

대안으로, 테스트 머지로 토픽 브랜치를 깨끗하게 유지하기 위해,
테스트 머지를 무효화하고, 테스트 머지 이전의 팁 위에 계속 구축할 수 있습니다:

------------
	$ git switch topic
	$ git merge master
	$ git reset --hard HEAD^ ;# 테스트 머지 되돌리기
	$ ... topic 및 master 브랜치 모두에서 작업
	$ git switch master
	$ git merge topic

              o---*---o-------o---o topic
             /                     \
    o---o---o---*---o---o---o---o---+ master
------------

이렇게 하면 토픽 브랜치가 최종적으로 준비되어 마스터 브랜치에 머지될 때
하나의 머지 커밋만 남게 됩니다. 이 머지는 `*`로 표시된 커밋에 의해 발생한
충돌을 해결해야 합니다. 그러나 이 충돌은 종종 테스트 머지를 생성할 때
해결했던 것과 동일한 충돌입니다. 'git rerere'는 이전 수동 해결의
정보를 사용하여 최종 충돌 머지를 해결하는 데 도움을 줍니다.

`git rerere` 명령어를 충돌하는 자동 머지 직후에 실행하면
일반적인 충돌 마커 `<<<<<<<`, `=======`, `>>>>>>>`가 포함된
충돌하는 워킹 트리 파일이 기록됩니다. 나중에, 충돌 해결을 완료한 후,
`git rerere`를 다시 실행하면 이러한 파일의 해결된 상태가 기록됩니다.
테스트 머지 시 마스터를 토픽 브랜치로 머지할 때 이 작업을 수행했다고 가정해 봅시다.

다음에, 동일한 충돌하는 자동 머지를 본 후,
`git rerere`를 실행하면 이전 충돌하는 자동 머지, 이전 수동 해결,
그리고 현재 충돌하는 자동 머지 간의 삼방향 머지를 수행합니다.
이 삼방향 머지가 깔끔하게 해결되면, 결과는 워킹 트리 파일에 쓰여지므로
수동으로 해결할 필요가 없습니다. 'git rerere'는 인덱스 파일을 그대로 두므로,
여전히 `git diff` (또는 `git diff -c`)와의 최종 검토 및 만족스러울 때
'git add'를 수행해야 합니다.

편의를 위해, 'git merge'는 자동 머지가 실패하여 종료될 때 자동으로
'git rerere'를 호출하며, 'git rerere'는 새로운 충돌일 경우 수동 해결을 기록하고,
이전 해결이 존재할 경우 재사용합니다. 'git commit' 또한 머지 결과를
커밋할 때 'git rerere'를 호출합니다. 이는 (rerere.enabled 설정 변수를
활성화하는 것 외에) 특별히 할 일이 없음을 의미합니다.

예시에서, 테스트 머지를 수행할 때 수동 해결이 기록되며,
나중에 업데이트된 마스터 및 토픽 브랜치로 실제 머지를 수행할 때
기록된 해결책이 유효하다면 재사용될 것입니다.

'git rerere'가 기록하는 정보는 'git rebase'를 실행할 때도 사용됩니다.
테스트 머지를 무효화하고 토픽 브랜치에서 개발을 계속한 후:

------------
              o---*---o-------o---o topic
             /
    o---o---o---*---o---o---o---o   master

	$ git rebase master topic

				  o---*---o-------o---o topic
				 /
    o---o---o---*---o---o---o---o   master
------------

토픽이 업스트림으로 보내질 준비가 되기 전에 최신 상태로 업데이트하기 위해
`git rebase master topic`을 실행할 수 있습니다.
이렇게 하면 삼방향 머지로 되돌아가며, 이전에 해결했던 테스트 머지와
동일한 방식으로 충돌이 발생합니다.
'git rebase'는 이 충돌을 해결하는 데 도움을 주기 위해 'git rerere'를 실행할 것입니다.

[NOTE] 'git rerere'는 충돌을 감지하기 위해 파일의 충돌 마커에 의존합니다.
파일에 충돌 마커와 비슷해 보이는 줄이 이미 포함되어 있다면,
'git rerere'는 충돌 해결 기록에 실패할 수 있습니다.
이를 해결하기 위해, linkgit:gitattributes[5]의 `conflict-marker-size` 설정을
사용할 수 있습니다.

GIT
---
linkgit:git[1] 제품군의 일부