git-svn(1)
==========

NAME
----
git-svn - Bidirectional operation between a Subversion repository and Git

SYNOPSIS
--------
[verse]
'git svn' <command> [<options>] [<arguments>]

DESCRIPTION
-----------
'git svn'은 Subversion과 Git 간의 변경 세트를 위한 간단한 통로입니다.
Subversion 저장소와 Git 저장소 간의 양방향 변경 흐름을 제공합니다.

'git svn'은 --stdlayout 옵션을 사용하여 일반적인 "trunk/branches/tags" 레이아웃을 따르는
표준 Subversion 저장소를 추적할 수 있습니다.
또한 -T/-t/-b 옵션(아래 'init' 옵션 및 'clone' 명령 참조)을 사용하여
어떤 레이아웃에서든 브랜치와 태그를 따라갈 수 있습니다.

Subversion 저장소 추적(위의 방법 중 하나 사용)이 시작되면, Git
저장소는 'fetch' 명령으로 Subversion에서 업데이트할 수 있고
Subversion은 'dcommit' 명령으로 Git에서 업데이트할 수 있습니다.

COMMANDS
--------

'init'::
	'git svn'을 위한 추가 메타데이터 디렉터리를 포함하여 빈 Git 저장소를 초기화합니다.
	Subversion URL은 명령줄 인수로 지정하거나 -T/-t/-b의 전체 URL
	인수로 지정할 수 있습니다. 선택적으로, 작업할 대상 디렉터리를 두 번째
	인수로 지정할 수 있습니다. 일반적으로 이 명령은 현재 디렉터리를 초기화합니다.

-T<trunk-subdir>;;
--trunk=<trunk-subdir>;;
-t<tags-subdir>;;
--tags=<tags-subdir>;;
-b<branches-subdir>;;
--branches=<branches-subdir>;;
-s;;
--stdlayout;;
	이들은 init을 위한 선택적 명령줄 옵션입니다.
	각 플래그는 상대 저장소 경로(--tags=project/tags) 또는 전체 URL
	(--tags=https://foo.org/project/tags)를 가리킬 수 있습니다.
	Subversion 저장소가 여러 경로에서 태그나 브랜치를 배치하는 경우,
	--tags 및/또는 --branches 옵션을 하나 이상 지정할 수 있습니다.
	--stdlayout 옵션은 trunk,tags,branches를 상대 경로로 설정하는
	단축 방법으로, 이는 Subversion의 기본값입니다. 다른 옵션이 함께 제공되는 경우,
	해당 옵션이 우선합니다.
--no-metadata;;
	[svn-remote] 구성에 'noMetadata' 옵션을 설정합니다.
	이 옵션은 권장되지 않으며, 사용하기 전에 이 매뉴얼의 'svn.noMetadata'
	섹션을 읽어보시기 바랍니다.
--use-svm-props;;
	[svn-remote] 구성에 'useSvmProps' 옵션을 설정합니다.
--use-svnsync-props;;
	[svn-remote] 구성에 'useSvnsyncProps' 옵션을 설정합니다.
--rewrite-root=<URL>;;
	[svn-remote] 구성에 'rewriteRoot' 옵션을 설정합니다.
--rewrite-uuid=<UUID>;;
	[svn-remote] 구성에 'rewriteUUID' 옵션을 설정합니다.
--username=<user>;;
	SVN이 인증을 처리하는 전송(http, https, 및 일반 svn)의 경우, 사용자 이름을 지정합니다.
	다른 전송(예: `svn+ssh://`)의 경우, URL에 사용자 이름을 포함해야 합니다.
	예: `svn+ssh://foo@svn.bar.com/project`
--prefix=<prefix>;;
	이는 trunk/branches/tags가 지정된 경우 원격의 이름에 추가되는 접두사를 지정할 수 있게 합니다.
	접두사는 자동으로 후행 슬래시를 포함하지 않으므로, 원하는 경우 인수에서 후행 슬래시를 포함해야 합니다.
	--branches/-b가 지정된 경우, 접두사는 후행 슬래시를 포함해야 합니다.
	어떤 경우에도 접두사(후행 슬래시 포함) 설정을 강력히 권장합니다. 왜냐하면 SVN 추적 ref들이
	"refs/remotes/$prefix/*"에 위치하여 Git 자체의 원격 추적 ref 레이아웃
	(refs/remotes/$remote/*)와 호환되기 때문입니다. 여러 프로젝트를 추적하여 공통
	저장소를 공유하려는 경우에도 접두사 설정이 유용합니다.
	기본적으로 접두사는 'origin/'으로 설정됩니다.
+
참고: Git v2.0 이전에는 기본 접두사가 ""(접두사 없음)였습니다.
	이는 SVN 추적 ref가 "refs/remotes/*"에 놓였음을 의미하며, 이는 Git 자체의 원격 추적 ref가 구성되는 방식과 호환되지 않습니다.
	이전 기본값을 여전히 원하는 경우, 명령줄에서 `--prefix ""`을 전달하여 얻을 수 있습니다
	(`--prefix=""`은 Perl의 Getopt::Long이 < v2.37인 경우 작동하지 않을 수 있습니다).

--ignore-refs=<regex>;;
	'init' 또는 'clone'에 전달될 때 이 정규 표현식은 설정 키로 보존됩니다.
	`--ignore-refs`에 대한 설명은 'fetch'를 참조하십시오.
--ignore-paths=<regex>;;
	'init' 또는 'clone'에 전달될 때 이 정규 표현식은 설정 키로 보존됩니다.
	`--ignore-paths`에 대한 설명은 'fetch'를 참조하십시오.
--include-paths=<regex>;;
	'init' 또는 'clone'에 전달될 때 이 정규 표현식은 설정 키로 보존됩니다.
	`--include-paths`에 대한 설명은 'fetch'를 참조하십시오.
--no-minimize-url;;
	여러 디렉터리를 추적할 때 ( --stdlayout, --branches, 또는 --tags 옵션 사용),
	git svn은 Subversion 저장소의 루트(또는 허용되는 최고 수준)에 연결을 시도합니다.
	이 기본값은 프로젝트 전체가 저장소 내에서 이동될 때 기록 추적을 개선하지만,
	읽기 액세스 제한이 있는 저장소에서 문제를 일으킬 수 있습니다.
	`--no-minimize-url`을 전달하면 git svn이 URL을 그대로 수락하고 더 높은 수준의 디렉터리로 연결을 시도하지 않도록 합니다.
	이 옵션은 단 하나의 URL/브랜치만 추적할 때 기본적으로 꺼져 있습니다(효과가 미미함).

'fetch'::
	추적 중인 Subversion 원격에서 가져오지 않은 리비전을 가져옵니다.
	$GIT_DIR/config 파일의 [svn-remote "..."] 섹션 이름은 선택적
	명령줄 인수로 지정할 수 있습니다.
+
이는 필요한 경우 rev_map을 자동으로 업데이트합니다 (자세한 내용은 아래 FILES 섹션의
'$GIT_DIR/svn/\**/.rev_map.*' 참조).

--localtime;;
	Git 커밋 시간을 UTC 대신 로컬 시간대로 저장합니다.
	이를 통해 'git log' ( --date=local 없이도)가 로컬 시간대에서 `svn log`가 표시하는 것과 동일한 시간을 표시합니다.
+
이것은 복제한 Subversion 저장소와의 상호 운용성에 영향을 주지 않지만,
로컬 Git 저장소가 다른 사람의 로컬 Git 저장소와 상호 운용될 수 있도록 하려면,
이 옵션을 사용하지 않거나 둘 다 동일한 로컬 시간대에서 사용해야 합니다.

--parent;;
	현재 HEAD의 SVN 부모로부터만 가져옵니다.

--ignore-refs=<regex>;;
	Perl 정규 표현식과 일치하는 브랜치 또는 태그에 대한 ref를 무시합니다.
	`^refs/remotes/origin/(?!tags/wanted-tag|wanted-branch).*$`와 같은 "부정 전방 탐색 단언"을 사용하여
	특정 ref만 허용할 수 있습니다.
+
[verse]
config key: svn-remote.<name>.ignore-refs
+
ignore-refs 구성 키가 설정되어 있고 명령줄 옵션도 제공되는 경우, 두 정규 표현식이 모두 사용됩니다.

--ignore-paths=<regex>;;
	이것은 SVN에서 체크아웃할 때 일치하는 모든 경로를 건너뛰게 하는
	Perl 정규 표현식을 지정할 수 있게 합니다.
	`--ignore-paths` 옵션은 제공된 저장소에 대한 모든 'fetch'(
	'clone', 'dcommit', 'rebase' 등으로 인한 자동 fetch 포함)에 대해 일치해야 합니다.
+
[verse]
config key: svn-remote.<name>.ignore-paths
+
ignore-paths 구성 키가 설정되어 있고 명령줄 옵션도 제공되는 경우, 두 정규 표현식이 모두 사용됩니다.
+
예시:
+
--
모든 fetch에 대해 "doc*" 디렉터리 건너뛰기;;
+
------------------------------------------------------------------------
--ignore-paths="^doc"
------------------------------------------------------------------------

첫 번째 레벨 디렉터리의 "branches"와 "tags" 건너뛰기;;
+
------------------------------------------------------------------------
--ignore-paths="^[^/]+/(?:branches|tags)"
------------------------------------------------------------------------
--

--include-paths=<regex>;;
	이것은 SVN에서 체크아웃할 때 일치하는 경로만 포함하게 하는
	Perl 정규 표현식을 지정할 수 있게 합니다.
	`--include-paths` 옵션은 제공된 저장소에 대한 모든 'fetch'(
	'clone', 'dcommit', 'rebase' 등으로 인한 자동 fetch 포함)에 대해 일치해야 합니다.
	`--ignore-paths`는 `--include-paths`보다 우선합니다.
+
[verse]
config key: svn-remote.<name>.include-paths

--log-window-size=<n>;;
	Subversion 기록을 스캔할 때 요청당 <n>개의 로그 항목을 가져옵니다.
	기본값은 100입니다. 매우 큰 Subversion 저장소의 경우, 'clone'/'fetch'가
	합리적인 시간 내에 완료하려면 더 큰 값이 필요할 수 있습니다.
	그러나 너무 큰 값은 더 높은 메모리 사용량과 요청 시간 초과를 초래할 수 있습니다.

'clone'::
	'init'과 'fetch'를 실행합니다. 제공된 URL의 기본 이름을 기반으로
	디렉터리를 자동으로 생성하거나, 두 번째 인수가 제공되면 디렉터리를 생성하고
	그 안에서 작업합니다. 'init' 및 'fetch' 명령이 수락하는 모든 인수를 수락하지만,
	`--fetch-all`과 `--parent`는 제외됩니다. 저장소가 복제된 후,
	'fetch' 명령은 워킹 트리에 영향을 주지 않고 리비전을 업데이트할 수 있으며,
	'rebase' 명령은 최신 변경 사항으로 워킹 트리를 업데이트할 수 있습니다.

--preserve-empty-dirs;;
	Subversion에서 가져온 각 빈 디렉터리에 대해 로컬 Git 저장소에 플레이스홀더 파일을 생성합니다.
	이는 Subversion 저장소에서 모든 항목을 제거하여 비게 된 디렉터리(그러나 디렉터리 자체는 아님)를 포함합니다.
	플레이스홀더 파일도 추적되며 더 이상 필요하지 않으면 제거됩니다.

--placeholder-filename=<filename>;;
	--preserve-empty-dirs에 의해 생성된 플레이스홀더 파일의 이름을 설정합니다.
	기본값: ".gitignore"

'rebase'::
	SVN 부모의 리비전을 현재 HEAD로부터 가져와서 현재(SVN에 커밋되지 않은) 작업을 재작업합니다.
+
이는 `svn update` 또는 'git pull'과 유사하게 작동하지만, 'git svn'과의 dcommit을 용이하게 하기 위해
'git merge' 대신 'git rebase'를 사용하여 선형 기록을 보존합니다.
+
'git svn fetch'와 'git rebase'가 수락하는 모든 옵션을 수락합니다.
	그러나 `--fetch-all`은 현재 [svn-remote]에서만 가져오며, 모든 [svn-remote] 정의에서 가져오지는 않습니다.
+
'git rebase'와 마찬가지로, 워킹 트리가 깨끗하고 커밋되지 않은 변경 사항이 없어야 합니다.
+
이는 필요한 경우 rev_map을 자동으로 업데이트합니다 (자세한 내용은 아래 FILES 섹션의
'$GIT_DIR/svn/\**/.rev_map.*' 참조).

-l;;
--local;;
	원격으로 가져오지 않고, 업스트림 SVN에서 마지막으로 가져온 커밋에 대해서만 'git rebase'를 실행합니다.

'dcommit'::
	현재 브랜치의 각 diff를 SVN 저장소에 커밋한 다음, 재작업하거나 리셋합니다(SVN과 HEAD 간에 diff가 있는지 여부에 따라 다름).
	이는 Git의 각 커밋에 대해 SVN에 리비전을 생성합니다.
+
옵션 Git 브랜치 이름(또는 Git 커밋 객체 이름)이 인수로 지정된 경우, 서브커맨드는 현재 브랜치가 아닌 지정된 브랜치에서 작동합니다.
+
'set-tree' (아래)보다 'dcommit' 사용을 권장합니다.
+
--no-rebase;;
	커밋 후 재작업하거나 리셋하지 않습니다.
--commit-url <URL>;;
	이 SVN URL(전체 경로)에 커밋합니다. 이는 한 전송 방식(예: 익명 읽기를 위한 `svn://` 또는 `http://`)으로 만들어진 기존 'git svn' 저장소를
	나중에 커밋을 위해 대체 전송 방식(예: `svn+ssh://` 또는 `https://`)에 대한 액세스 권한이 부여된 경우 재사용할 수 있도록 합니다.
+
[verse]
config key: svn-remote.<name>.commiturl
config key: svn.commiturl (모든 svn-remote.<name>.commiturl 옵션 덮어씁니다)
+
commiturl 구성 키의 SVN URL은 SVN 브랜치를 포함합니다.
	전체 SVN 저장소에 대한 커밋 URL을 설정하려면 대신 svn-remote.<name>.pushurl을 사용합니다.
+
다른 목적으로 이 옵션을 사용하는 것(묻지 마십시오)은 매우 강력히 권장하지 않습니다.

--mergeinfo=<mergeinfo>;;
	dcommit 중에 지정된 병합 정보(`--mergeinfo="/branches/foo:1-10"`)를 추가합니다.
	모든 svn 서버 버전은 이 정보를 (속성으로) 저장할 수 있으며, 버전 1.5부터 svn 클라이언트는 이를 활용할 수 있습니다.
	여러 브랜치에서 병합 정보를 지정하려면 브랜치 사이에 단일 공백을 사용합니다(`--mergeinfo="/branches/foo:1-10 /branches/bar:3,5-6,8"`).
+
[verse]
config key: svn.pushmergeinfo
+
이 옵션은 가능한 경우 svn:mergeinfo 속성을 SVN 저장소에 자동으로 채우도록 git-svn을 시도하게 합니다.
	현재, 이는 비-fast-forward 병합을 dcommit할 때만 가능하며, 모든 부모가 SVN에 푸시된 경우 첫 번째 부모를 제외하고 가능합니다.

--interactive;;
	패치 세트가 실제로 SVN로 전송되어야 하는지 사용자에게 확인합니다.
	각 패치에 대해 "yes"(이 패치 수락), "no"(이 패치 폐기), "all"(모든 패치 수락), 또는 "quit"으로 응답할 수 있습니다.
+
'git svn dcommit'은 "no" 또는 "quit" 응답 시 즉시 반환되며, SVN에 아무것도 커밋하지 않습니다.

'branch'::
	SVN 저장소에 브랜치를 생성합니다.

-m;;
--message;;
	커밋 메시지를 지정할 수 있게 합니다.

-t;;
--tag;;
	git svn init 중에 지정된 branches_subdir 대신 tags_subdir를 사용하여 태그를 생성합니다.

-d<path>;;
--destination=<path>;;

	'init' 또는 'clone' 명령에 하나 이상의 --branches (또는 --tags) 옵션이 제공된 경우,
	SVN 저장소에서 생성하려는 브랜치(또는 태그)의 위치를 제공해야 합니다.
	<path>는 브랜치 또는 태그를 생성하는 데 사용할 경로를 지정하며,
	구성된 브랜치 또는 태그 refspec의 왼쪽 핸드사이드 패턴과 일치해야 합니다.
	이러한 refspec은 다음 명령으로 볼 수 있습니다.
+
	git config --get-all svn-remote.<name>.branches
	git config --get-all svn-remote.<name>.tags
+
	여기서 <name>은 'init'의 -R 옵션으로 지정된 SVN 저장소 이름(또는 기본값 "svn")입니다.

--username;;
	커밋을 수행할 SVN 사용자 이름을 지정합니다. 이 옵션은 'username' 구성 속성을 재정의합니다.

--commit-url;;
	지정된 URL을 사용하여 대상 Subversion 저장소에 연결합니다.
	소스 SVN 저장소가 읽기 전용인 경우에 유용합니다.
	이 옵션은 구성 속성 'commiturl'을 재정의합니다.
+
	git config --get-all svn-remote.<name>.commiturl
+

--parents;;
	부모 폴더를 생성합니다. 이 매개변수는 svn cp 명령의 --parents 매개변수와 동일하며,
	비표준 저장소 레이아웃에 유용합니다.

'tag'::
	SVN 저장소에 태그를 생성합니다. 이는 'branch -t'의 단축입니다.

'log'::
	SVN 사용자가 -r/--revision 번호를 참조할 때 SVN 로그 메시지를 쉽게 찾을 수 있도록 합니다.
+
`svn log'의 다음 기능이 지원됩니다.
+
--
-r <n>[:<n>];;
--revision=<n>[:<n>];;
	지원됨, 숫자가 아닌 인수는 지원되지 않음:
	HEAD, NEXT, BASE, PREV 등 ...
-v;;
--verbose;;
	svn log의 --verbose 출력과 완전히 호환되지는 않지만, 상당히 가깝습니다.
--limit=<n>;;
	--max-count와 동일하지 않음, 병합/제외된 커밋을 계산하지 않음
--incremental;;
	지원됨
--
+
새로운 기능:
+
--
--show-commit;;
	Git 커밋 sha1도 표시합니다.
--oneline;;
	--pretty=oneline 버전입니다.
--
+
참고: SVN 자체는 UTC 시간만 저장하고 다른 것은 저장하지 않습니다. 일반 svn 클라이언트는
	UTC 시간을 로컬 시간(또는 TZ= 환경에 기반)으로 변환합니다. 이 명령은 동일한 동작을 합니다.
+
다른 인수는 'git log'로 직접 전달됩니다.

'blame'::
	파일의 각 줄을 마지막으로 수정한 리비전과 작성자를 표시합니다.
	이 모드의 출력은 기본적으로 `svn blame`의 출력과 형식 호환됩니다.
	SVN blame 명령과 마찬가지로, 워킹 트리의 로컬 커밋되지 않은 변경 사항은 무시됩니다.
	HEAD 리비전의 파일 버전이 주석 처리됩니다. 알려지지 않은 인수는 'git blame'으로 직접 전달됩니다.
+
--git-format;;
	Git 커밋 해시 대신 SVN 리비전 번호를 사용하여 'git blame'과 동일한 형식으로 출력을 생성합니다.
	이 모드에서는 SVN에 커밋되지 않은 변경 사항(로컬 워킹 복사 편집 포함)이 리비전 0으로 표시됩니다.

'find-rev'::
	'rN' 형태의 SVN 리비전 번호가 주어지면 해당 Git 커밋 해시를 반환합니다 (선택적으로 트리-이전을 지정하여 검색할 브랜치를 지정할 수 있음).
	트리-이전이 주어지면 해당 SVN 리비전 번호를 반환합니다.
+
-B;;
--before;;
	SVN 리비전이 주어졌을 때 정확한 일치를 요구하지 않고, 대신 지정된 리비전 시점의 (현재 브랜치 상의) SVN 저장소 상태에 해당하는 커밋을 찾습니다.
+
-A;;
--after;;
	SVN 리비전이 주어졌을 때 정확한 일치를 요구하지 않음; 정확한 일치가 없으면 기록을 앞으로 검색하여 가장 가까운 일치를 반환합니다.

'set-tree'::
	이 명령 대신 'dcommit'을 사용하는 것을 고려해야 합니다.
	지정된 커밋 또는 트리 객체를 SVN에 커밋합니다. 이는 가져온 fetch 데이터가 최신이라고 가정합니다.
	SVN에 커밋할 때 패치 처리를 전혀 하지 않으며, 단순히 지정된 트리 또는 커밋의 파일로 덮어씁니다.
	모든 병합은 'git svn' 기능과 독립적으로 수행되었다고 가정합니다.

'create-ignore'::
	디렉터리에 대한 svn:ignore 및 svn:global-ignores 속성을 재귀적으로 찾아 일치하는 .gitignore 파일을 생성합니다.
	결과 파일은 커밋되도록 스테이징되지만 커밋되지는 않습니다.
	특정 리비전을 참조하려면 -r/--revision을 사용합니다.

'show-ignore'::
	디렉터리에 대한 svn:ignore 및 svn:global-ignores 속성을 재귀적으로 찾아 나열합니다.
	출력은 $GIT_DIR/info/exclude 파일에 추가하기에 적합합니다.

'mkdirs'::
	핵심 Git에서 추적할 수 없는 빈 디렉터리를 $GIT_DIR/svn/<refname>/unhandled.log 파일의 정보에 기반하여 다시 생성하려고 시도합니다.
	"git svn clone" 및 "git svn rebase"를 사용할 때 빈 디렉터리는 자동으로 다시 생성되므로, "mkdirs"는 "git checkout" 또는 "git reset"과 같은 명령 이후에 사용하기 위한 것입니다.
	(자세한 내용은 svn-remote.<name>.automkdirs 구성 파일 옵션 참조).

'commit-diff'::
	명령줄에서 두 트리-이전 인수의 diff를 커밋합니다.
	이 명령은 `git svn init`-ed 저장소 **inside**에 있지 않아도 됩니다.
	이 명령은 세 개의 인수를 받습니다. (a) diff의 원본 트리, (b) 새 트리 결과, (c) 대상 Subversion 저장소의 URL.
	(URL)의 마지막 인수는 'git svn'-aware 저장소( 'git svn'으로 `init`-ed)를 사용하는 경우 생략될 수 있습니다.
	-r<revision> 옵션이 이 명령에 필요합니다.
+
커밋 메시지는 `-m` 또는 `-F` 옵션으로 직접 제공되거나, 두 번째 트리-이전이 그러한 객체를 나타낼 때 태그 또는 커밋에서 간접적으로 제공되거나, 편집기 호출을 통해 요청됩니다 (`--edit` 옵션 참조).

-m <msg>;;
--message=<msg>;;
	주어진 `msg`를 커밋 메시지로 사용합니다. 이 옵션은 `--edit` 옵션을 비활성화합니다.

-F <filename>;;
--file=<filename>;;
	주어진 파일에서 커밋 메시지를 가져옵니다. 이 옵션은 `--edit` 옵션을 비활성화합니다.

'info'::
	`svn info`와 유사하게 파일 또는 디렉터리에 대한 정보를 표시합니다.
	현재 -r/--revision 인수를 지원하지 않습니다. --url 옵션을 사용하여 'URL:' 필드의 값만 출력합니다.

'proplist'::
	주어진 파일 또는 디렉터리에 대해 Subversion 저장소에 저장된 속성을 나열합니다.
	특정 Subversion 리비전을 참조하려면 -r/--revision을 사용합니다.

'propget'::
	첫 번째 인수로 주어진 Subversion 속성을 파일에 대해 가져옵니다.
	특정 리비전은 -r/--revision으로 지정할 수 있습니다.

'propset'::
	첫 번째 인수로 주어진 Subversion 속성을 세 번째 인수로 주어진 파일에 대해 두 번째 인수로 주어진 값으로 설정합니다.
+
예시:
+
------------------------------------------------------------------------
git svn propset svn:keywords "FreeBSD=%H" devel/py-tipper/Makefile
------------------------------------------------------------------------
+
이는 'devel/py-tipper/Makefile' 파일에 대해 'svn:keywords' 속성을 'FreeBSD=%H'로 설정합니다.

'show-externals'::
	Subversion externals를 표시합니다. 특정 리비전을 지정하려면 -r/--revision을 사용합니다.

'gc'::
	$GIT_DIR/svn/<refname>/unhandled.log 파일을 압축하고 $GIT_DIR/svn/<refname>/index 파일을 제거합니다.

'reset'::
	지정된 리비전까지 'fetch'의 효과를 취소합니다.
	이를 통해 SVN 리비전을 다시 'fetch' 할 수 있습니다.
	일반적으로 SVN 리비전의 내용은 결코 변경되지 않아야 하며 'reset'은 필요하지 않아야 합니다.
	그러나 SVN 권한이 변경되거나 --ignore-paths 옵션을 수정하면, 'fetch'가 "commit에 없음"(이전에 보이지 않던 파일) 또는
	"checksum 불일치"(수정 누락)로 실패할 수 있습니다.
	문제 파일이 영구적으로 무시될 수 없는 경우 ( --ignore-paths 사용), 저장소를 복구하는 유일한 방법은 'reset'을 사용하는 것입니다.
+
rev_map과 refs/remotes/git-svn만 변경됩니다 (자세한 내용은 아래 FILES 섹션의
'$GIT_DIR/svn/\**/.rev_map.*' 참조).
	'reset' 후 'fetch'를 실행하고 'git reset' 또는 'git rebase'를 실행하여 로컬 브랜치를 새 트리로 이동합니다.

-r <n>;;
--revision=<n>;;
	유지하려는 가장 최근 리비전을 지정합니다. 모든 후속 리비전은 폐기됩니다.
-p;;
--parent;;
	지정된 리비전도 폐기하고 가장 가까운 부모를 보존합니다.
Example:;;
"master"에 로컬 변경 사항이 있지만 "r2"를 다시 가져와야 한다고 가정합니다.
+
------------
    r1---r2---r3 remotes/git-svn
                \
                 A---B master
------------
+
"r2"가 불완전하게 된 이유인 ignore-paths 또는 SVN 권한 문제를 수정합니다. 그런 다음:
+
[verse]
git svn reset -r2 -p
git svn fetch
+
------------
    r1---r2'--r3' remotes/git-svn
      \
       r2---r3---A---B master
------------
+
그런 다음 'git rebase'로 "master"를 수정합니다.
	'git merge'를 사용하지 마십시오. 그렇지 않으면 기록이 향후 'dcommit'과 호환되지 않습니다!
+
[verse]
git rebase --onto remotes/git-svn A^ master
+
------------
    r1---r2'--r3' remotes/git-svn
                \
                 A'--B' master
------------

OPTIONS
-------

--shared[=(false|true|umask|group|all|world|everybody)]::
--template=<template-directory>::
	'init' 명령과 함께만 사용됩니다.
	'git init'으로 직접 전달됩니다.

-r <arg>::
--revision <arg>::
	   'fetch' 명령과 함께 사용됩니다.
+
	이는 부분/정제된 기록에 대한 리비전 범위를 지원할 수 있게 합니다.
	$NUMBER, $NUMBER1:$NUMBER2 (숫자 범위), $NUMBER:HEAD, 및 BASE:$NUMBER 모두 지원됩니다.
+
	이를 통해 fetch 중에 부분 미러를 만들 수 있지만, 기록이 건너뛰고 손실될 수 있으므로 일반적으로 권장되지 않습니다.

-::
--stdin::
	'set-tree' 명령과 함께만 사용됩니다.
+
	표준 입력에서 커밋 목록을 읽고 역순으로 커밋합니다.
	각 줄에서는 선행 sha1만 읽으므로, 'git rev-list --pretty=oneline' 출력을 사용할 수 있습니다.

--rmdir::
	'dcommit', 'set-tree' 및 'commit-diff' 명령과 함께만 사용됩니다.
+
	파일이 남아 있지 않은 디렉터리는 SVN 트리에서 제거합니다.
	SVN은 빈 디렉터리를 버전 관리할 수 있으며, 비어 있더라도 기본적으로 제거되지 않습니다.
	Git은 빈 디렉터리를 버전 관리할 수 없습니다. 이 플래그를 활성화하면
	SVN으로의 커밋이 Git처럼 작동합니다.
+
[verse]
config key: svn.rmdir

-e::
--edit::
	'dcommit', 'set-tree' 및 'commit-diff' 명령과 함께만 사용됩니다.
+
	SVN에 커밋하기 전에 커밋 메시지를 편집합니다.
	커밋 객체의 경우 기본적으로 꺼져 있으며, 트리 객체를 커밋할 때는 강제로 켜집니다.
+
[verse]
config key: svn.edit

-l<num>::
--find-copies-harder::
	'dcommit', 'set-tree' 및 'commit-diff' 명령과 함께만 사용됩니다.
+
	둘 다 'git diff-tree'로 직접 전달됩니다. 자세한 정보는
	linkgit:git-diff-tree[1]을 참조하십시오.
+
[verse]
config key: svn.l
config key: svn.findcopiesharder

-A<filename>::
--authors-file=<filename>::
	구문은 'git cvsimport'에서 사용되는 파일과 호환되지만, '<>'를 사용하여 빈 이메일 주소를 제공할 수 있습니다.
+
------------------------------------------------------------------------
	loginname = Joe User <user@example.com>
------------------------------------------------------------------------
+
이 옵션이 지정되고 'git svn'이 authors-file에 존재하지 않는 SVN 커미터 이름을 발견하면, 'git svn'은 작업을 중단합니다.
	사용자는 적절한 항목을 추가해야 합니다. authors-file이 수정된 후 이전 'git svn' 명령을 다시 실행하면 작업이 계속됩니다.
+
[verse]
config key: svn.authorsfile

--authors-prog=<filename>::
	이 옵션이 지정된 경우, authors 파일에 존재하지 않는 각 SVN 커미터 이름에 대해,
	주어진 파일이 커미터 이름을 첫 번째 인수로 실행됩니다.
	프로그램은 "Name <email>" 또는 "Name <>" 형태의 단일 줄을 반환해야 하며,
	이는 authors 파일에 포함된 것처럼 처리됩니다.
+
역사적 이유로 상대 'filename'은 'init' 및 'clone'의 경우 현재 디렉터리에 대해,
	'fetch'의 경우 워킹 트리 루트에 대해 먼저 검색됩니다.
	'filename'을 찾을 수 없으면