git-mailinfo(1)
===============

NAME
----
git-mailinfo - 단일 이메일 메시지에서 패치 및 작성자 정보 추출


SYNOPSIS
--------
[verse]
'git mailinfo' [-k|-b] [-u | --encoding=<encoding> | -n]
	       [--[no-]scissors] [--quoted-cr=<action>]
	       <msg> <patch>


DESCRIPTION
-----------
표준 입력에서 단일 이메일 메시지를 읽어, <msg> 파일에 커밋 로그 메시지를,
<patch> 파일에 패치를 씁니다. 작성자 이름, 이메일 주소, 이메일 제목은
표준 출력으로 작성되어 'git am'이 커밋을 생성하는 데 사용됩니다.
일반적으로 이 명령을 직접 사용하는 것은 필요하지 않습니다. 대신
linkgit:git-am[1]을 참조하십시오.


OPTIONS
-------
-k::
	일반적으로 프로그램은 Subject: 헤더 줄에서 이메일 관련 불필요한 부분을
	제거하여 커밋 로그 메시지의 제목 줄을 추출합니다. 이 옵션은 이러한
	처리 과정을 방지하며, 'git format-patch -k' 출력을 다시 읽을 때
	가장 유용합니다.
+
구체적으로, 다음 항목들은 더 이상 남아있지 않을 때까지 제거됩니다:
+
--
*	앞뒤 공백.

*	앞에 오는 `Re:`, `re:`, 그리고 `:`.

*	앞에 오는 대괄호로 묶인 문자열 ( `[` 와 `]` 사이, 보통 `[PATCH]`).
--
+
마지막으로, 연속된 공백은 단일 ASCII 공백 문자로 정규화됩니다.

-b::
	-k가 비활성화된 경우, `[`와 `]` 쌍으로 묶인 모든 선행 문자열이 제거됩니다.
	이 옵션은 대괄호로 묶인 문자열에 "PATCH"라는 단어를 포함하는 쌍에만
	제거를 제한합니다.

-u::
	커밋 로그 메시지, 작성자 이름, 작성자 이메일은 이메일에서 가져와,
	최소한의 MIME 전송 인코딩을 디코딩한 후, `i18n.commitEncoding`
	(기본값은 UTF-8)으로 지정된 문자셋으로 재부호화하여 옮겨씁니다.
	이전에는 선택 사항이었지만 이제는 기본값입니다.
+
이 플래그를 사용하더라도 패치는 문자셋 변환 없이 항상 그대로 사용됩니다.

--encoding=<encoding>::
	-u와 유사합니다. 하지만 재부호화할 때, `i18n.commitEncoding` 또는 UTF-8로
	지정된 대신 여기에 지정된 문자셋이 사용됩니다.

-n::
	메타데이터의 모든 문자셋 재부호화를 비활성화합니다.

-m::
--message-id::
	Message-ID 헤더를 커밋 메시지 끝에 복사합니다. 이는 커밋을
	메일링 리스트 토론과 연관시키는 데 유용합니다.

--scissors::
	scissors 줄 (예: "-- >8 --") 이전의 본문 내용을 모두 제거합니다.
	이 줄은 가위와 천공 표시를 나타내며, 독자에게 해당 줄에서 메시지를
	자르도록 요청하는 데 사용됩니다. 이 줄이 메시지 본문에서 패치 이전에
	나타나면, 이 옵션이 사용될 때 그 이전 내용 (가위 줄 자체 포함)은
	무시됩니다.
+
이는 토론 스레드에서 응답하는 메시지에 대한 주석과 제안으로 메시지를 시작하고,
토론과 제안된 커밋 로그 메시지의 시작을 가위 줄로 구분하여 패치 제출로
마무리하고 싶을 때 유용합니다.
+
이것은 `mailinfo.scissors` 설정 옵션으로 기본적으로 활성화될 수 있습니다.

--no-scissors::
	scissors 줄을 무시합니다. mailinfo.scissors 설정을 재정의할 때 유용합니다.

--quoted-cr=<action>::
	base64 또는 quoted-printable 인코딩으로 전송된 이메일 메시지를 처리할 때,
	디코딩된 줄이 단순 LF 대신 CRLF로 끝나는 경우의 동작입니다.
+
유효한 동작은 다음과 같습니다:
+
--
*	`nowarn`: Git은 이러한 CRLF가 발견되어도 아무것도 하지 않습니다.
*	`warn`: Git은 이러한 CRLF가 발견되면 각 메시지에 대해 경고를 발합니다.
*	`strip`: Git은 해당 CRLF를 LF로 변환합니다.
--
+
기본 동작은 `mailinfo.quotedCR` 설정 옵션으로 설정될 수 있습니다.
해당 설정 옵션이 설정되지 않은 경우, `warn`이 사용됩니다.

<msg>::
	이메일에서 추출된 커밋 로그 메시지. 보통 이메일 제목에서 오는
	제목 줄은 제외됩니다.

<patch>::
	이메일에서 추출된 패치.

CONFIGURATION
-------------

include::includes/cmd-config-section-all.adoc[]

include::config/mailinfo.adoc[]

GIT
---
linkgit:git[1] 세트의 일부