git-index-pack(1)
=================

NAME
----
git-index-pack - 기존에 압축된 아카이브를 위한 팩 인덱스 파일 빌드


SYNOPSIS
--------
[verse]
'git index-pack' [-v] [-o <index-file>] [--[no-]rev-index] <pack-file>
'git index-pack' --stdin [--fix-thin] [--keep] [-v] [-o <index-file>]
		  [--[no-]rev-index] [<pack-file>]


DESCRIPTION
-----------
지정된 파일에서 압축된 아카이브(.pack)를 읽고, 해당 파일에 대한 팩 인덱스 파일(.idx)을 빌드하며,
선택적으로 지정된 팩에 대한 리버스 인덱스(.rev)를 씁니다. 이렇게 생성된 압축된 아카이브와 팩 인덱스는
Git 저장소의 objects/pack/ 디렉토리에 배치될 수 있습니다.


OPTIONS
-------
-v::
	진행 상황을 포함하여 자세한 정보를 출력합니다.

-o <index-file>::
	생성된 팩 인덱스를 지정된 파일에 씁니다. 이 옵션이 없으면 팩 인덱스 파일의 이름은
	압축된 아카이브 파일의 이름을 `.pack`으로 끝나도록 하여 구성됩니다. (`.pack`으로 끝나지 않으면 프로그램이 실패합니다.)

--rev-index::
--no-rev-index::
	이 플래그가 제공되면 주어진 팩에 해당하는 리버스 인덱스(`.rev` 파일)를 생성합니다.
	`--verify`가 제공되면 기존 리버스 인덱스가 정확한지 확인합니다.
	`pack.writeReverseIndex`보다 우선 순위를 가집니다.

--stdin::
	이 플래그가 제공되면 팩은 대신 stdin에서 읽혀지며, 그 복사본이 <pack-file>에 기록됩니다.
	<pack-file>이 지정되지 않으면 팩은 현재 Git 저장소의 objects/pack/ 디렉토리에
	팩 내용에서 결정된 기본 이름으로 기록됩니다.
	<pack-file>이 지정되지 않은 경우, 이 프로세스와 'git repack' 사이의 경쟁 조건을 방지하기 위해 --keep 사용을 고려하십시오.

--fix-thin::
	`git pack-objects --thin`에 의해 생성된 "thin" 팩을 수정합니다.
	(자세한 내용은 linkgit:git-pack-objects[1] 참조)
	팩에 포함된 델타 객체의 기반이 되는 제외된 객체를 팩에 추가합니다.
	이 옵션은 --stdin과 함께 사용될 때만 의미가 있습니다.

--keep::
	인덱스를 최종 대상으로 이동하기 전에 관련 팩 파일에 대해 빈 .keep 파일을 생성합니다.
	이 옵션은 일반적으로 --stdin과 함께 필요한데, 이는 동시 'git repack' 프로세스가
	새로 구성된 팩과 인덱스를 삭제하는 것을 방지하기 위함입니다.

--keep=<msg>::
	--keep와 유사하게, 인덱스를 최종 대상으로 이동하기 전에 .keep 파일을 생성합니다.
	하지만 빈 파일을 생성하는 대신 '<msg>' 뒤에 LF를 붙여 .keep 파일에 기록합니다.
	이 '<msg>' 메시지는 나중에 유용성이 다한 .keep 파일을 찾기 위해 모든 .keep 파일 내에서 검색될 수 있습니다.

--index-version=<version>[,<offset>]::
	테스트 스위트 전용입니다. 생성된 팩 인덱스의 버전을 강제로 지정하고,
	주어진 오프셋 위에 있는 객체에 대해 64비트 인덱스 항목을 강제할 수 있습니다.

--strict[=<msg-id>=<severity>...]::
	팩에 깨진 객체나 링크가 포함되어 있으면 종료합니다.
	일부 가능한 문제의 심각도를 변경하기 위해 `<msg-id>=<severity>`의
	쉼표로 구분된 선택적 목록을 전달할 수 있습니다. 예:
	 `--strict="missingEmail=ignore,badTagName=error"`.
	`<msg-id>` 및 `<severity>`의 가능한 값에 대한 자세한 내용은
	linkgit:git-fsck[1]의 `fsck.<msg-id>` 구성 옵션 항목을 참조하십시오.

--progress-title::
	내부 사용 전용입니다.
+
진행률 표시줄의 제목을 설정합니다. 기본 제목은 "Receiving objects"이며
`--stdin`이 지정되면 "Indexing objects"입니다.

--check-self-contained-and-connected::
	팩에 깨진 링크가 포함되어 있으면 종료합니다. 내부 사용 전용입니다.

--fsck-objects[=<msg-id>=<severity>...]::
	팩에 깨진 객체가 포함되어 있으면 종료하지만, `--strict`와 달리 깨진 링크에 대해서는
	종료하지 않습니다. 팩에 존재하지 않는 .gitmodules 블롭을 가리키는 트리 (tree)가 포함되어 있는 경우,
	팩/idx 파일 이름에 들어가는 해시 뒤에 해당 블롭의 해시를 출력합니다 ( "Notes" 참조).
+
일부 가능한 문제의 심각도를 변경하기 위해 `<msg-id>=<severity>`의
	쉼표로 구분된 선택적 목록을 전달할 수 있습니다. 예:
	`--fsck-objects="missingEmail=ignore,badTagName=ignore"`.
	`<msg-id>` 및 `<severity>`의 가능한 값에 대한 자세한 내용은
	linkgit:git-fsck[1]의 `fsck.<msg-id>` 구성 옵션 항목을 참조하십시오.

--threads=<n>::
	델타를 해결할 때 생성할 스레드 수를 지정합니다.
	이것은 index-pack이 pthreads로 컴파일된 경우에 필요하며, 그렇지 않으면 이 옵션은 경고와 함께 무시됩니다.
	이는 다중 프로세서 기계에서 패킹 시간을 줄이기 위한 것입니다.
	그러나 델타 검색 창에 필요한 메모리 양은 스레드 수만큼 곱해집니다.
	0을 지정하면 Git이 CPU 수를 자동으로 감지하고 최대 3개의 스레드를 사용합니다.

--max-input-size=<size>::
	팩이 <size>보다 크면 종료합니다.

--object-format=<hash-algorithm>::
	팩에 대해 지정된 객체 형식(해시 알고리즘)을 지정합니다. 유효한
	값은 'sha1' 및 (활성화된 경우) 'sha256'입니다. 기본값은 현재 저장소의 알고리즘입니다
	(`extensions.objectFormat`으로 설정됨) 또는 값이 설정되지 않았거나 저장소 외부에 있는 경우 'sha1'입니다.
+
이 옵션은 --stdin과 함께 사용할 수 없습니다.
+
include::object-format-disclaimer.adoc[]

--promisor[=<message>]::
	팩-인덱스를 커밋하기 전에 이 팩에 대해 .promisor 파일을 생성합니다.
	특히 --fix-thin으로 프로미저 팩을 쓸 때 유용합니다. 팩의 이름은 팩이 완전히 기록될 때까지 확정되지 않기 때문입니다.
	`<message>`가 제공되면 해당 내용은 향후 참조를 위해 .promisor 파일에 기록됩니다.
	자세한 내용은 link:technical/partial-clone.html[partial clone]을 참조하십시오.
+
또한, 주어진 팩에 프로미저가 아닌 객체(저장소 내)를 참조하는 객체가 있는 경우,
	해당 프로미저가 아닌 객체들을 프로미저 팩으로 다시 팩합니다.
	이는 저장소에 프로미저 객체를 통해 접근 가능한 프로미저가 아닌 객체가 있는 상황을 피하기 위한 것입니다.
+
<pack-file>이 지정되지 않아야 합니다.

NOTES
-----

인덱스가 생성되면 팩/idx 파일 이름에 들어가는 해시가 stdout으로 출력됩니다.
--stdin도 함께 사용되었다면, 이는 "pack\t" 또는 새 .keep 파일이 성공적으로 생성된 경우 "keep\t"로 접두사가 붙습니다.
이는 위에서 언급한 'git repack'과의 경쟁을 방지하기 위해 사용된 .keep 파일을 제거하는 데 유용합니다.

GIT
---
linkgit:git[1] 스위트의 일부