git-pack-objects(1)
===================

NAME
----
git pack-objects - 객체의 압축된 아카이브를 생성합니다.


SYNOPSIS
--------
[verse]
'git pack-objects' [-q | --progress | --all-progress] [--all-progress-implied]
		   [--no-reuse-delta] [--delta-base-offset] [--non-empty]
		   [--local] [--incremental] [--window=<n>] [--depth=<n>]
		   [--revs [--unpacked | --all]] [--keep-pack=<pack-name>]
		   [--cruft] [--cruft-expiration=<time>]
		   [--stdout [--filter=<filter-spec>] | <base-name>]
		   [--shallow] [--keep-true-parents] [--[no-]sparse]
		   [--name-hash-version=<n>] [--path-walk] < <object-list>


DESCRIPTION
-----------
표준 입력에서 객체 목록을 읽어, 지정된 기본 이름으로 하나 이상의 압축된 아카이브를 디스크에 쓰거나, 압축된 아카이브를 표준 출력으로 씁니다.

압축된 아카이브는 두 저장소 간에 객체 세트를 효율적으로 전송하는 방법이며, 접근 효율적인 아카이브 형식입니다. 압축된 아카이브에서 객체는 압축된 전체 또는 다른 객체와의 차이로 저장됩니다. 후자를 종종 델타라고 합니다.

압축된 아카이브 형식(.pack)은 추가 정보 없이도 풀 수 있도록 자체 포함되도록 설계되었습니다. 따라서 델타가 의존하는 각 객체는 팩 내에 존재해야 합니다.

팩 인덱스 파일(.idx)은 팩 내 객체에 대한 빠른 임의 접근을 위해 생성됩니다. 인덱스 파일(.idx)과 압축 아카이브(.pack)를 모두 $GIT_OBJECT_DIRECTORY의 pack/ 하위 디렉토리(또는 $GIT_ALTERNATE_OBJECT_DIRECTORIES의 디렉토리)에 배치하면 Git에서 압축 아카이브를 읽을 수 있습니다.

'git unpack-objects' 명령은 압축 아카이브를 읽고 팩에 포함된 객체를 "one-file one-object" 형식으로 확장할 수 있습니다. 이는 일반적으로 피어가 효율적인 네트워크 전송을 위해 온플라이로 팩을 생성할 때 smart-pull 명령에서 수행됩니다.


OPTIONS
-------
base-name::
	<base-name>을 사용하여 생성된 파일의 이름을 결정하는
	.pack 및 .idx 쌍 파일에 씁니다.
	이 옵션을 사용하면 쌍의 두 파일은
	<base-name>-<SHA-1>.{pack,idx} 파일에 기록됩니다. <SHA-1>은
	팩 콘텐츠를 기반으로 한 해시이며 명령의 표준 출력에 기록됩니다.

--stdout::
	팩 내용을 ( .pack 파일에 기록될 내용) 표준 출력으로 씁니다.

--revs::
	개별 객체 이름 대신 표준 입력에서 수정(revision) 인수를
	읽습니다. 수정 인수는 'git rev-list'가 `--objects` 플래그를
	사용할 때 출력할 객체 목록을 빌드하기 위해 `commit` 인수를
	사용하는 것과 동일한 방식으로 처리됩니다. 결과 목록의 객체가
	압축됩니다.
	수정 외에도 `--not` 또는 `--shallow <SHA-1>` 줄도 허용됩니다.

--unpacked::
	이것은 `--revs`를 의미합니다. 표준 입력에서 읽은 수정
	인수 목록을 처리할 때, 이미 압축되지 않은 객체로 압축할
	객체를 제한합니다.

--all::
	이것은 `--revs`를 의미합니다. 표준 입력에서 읽은 수정
	인수 목록에 추가로, `refs/` 아래의 모든 ref가 포함되도록
	명시된 것처럼 가장합니다.

--include-tag::
	참조하는 객체가 결과 packfile에 포함된 경우 요청되지 않은
	주석 태그를 포함합니다. 이는 새 태그를 네이티브 Git 클라이언트에
	보내는 데 유용할 수 있습니다.

--stdin-packs[=<mode>]::
	객체 이름이나 수정 인수 대신 표준 입력에서 팩파일의 기본 이름을
	(예: `pack-1234abcd.pack`) 읽습니다. 결과 팩은 포함된 팩에
	나열된 모든 객체( `^`로 시작하지 않는)를 포함하며, 제외된 팩에
	나열된 객체( `^`로 시작하는)를 제외합니다.
+
`mode`가 "follow"일 때 팩은 추가로 `!`로 접두사가 붙을 수 있으며,
이는 제외되었지만 도달 가능성에 반드시 닫혀 있지는 않음을 나타냅니다.
포함된 팩의 객체 외에도 결과 팩은 다음을 기반으로 추가 객체를 포함할 수 있습니다.
+
--
* `!`로 표시된 팩이 있는 경우, 해당 팩이나 제외된 팩 외부의 객체를 통해
  포함된 팩에서 도달 가능한 객체가 포함됩니다. 이 경우 모든 `^` 팩은
  도달 가능성에 닫힌 것으로 처리됩니다.
* 그렇지 않은 경우( `!` 팩이 없는 경우), 나열되지 않은 팩 내의 객체는
  (1) 포함된 팩에서 도달 가능하고 (2) 제외된 팩에 없습니다.
--
+
이 모드는 예를 들어, 제외된 팩으로 설정된 경계를 넘어 도달 가능성으로 닫힌
팩을 생성하기 위해 이전에 도달 불가능했던 객체를 복원하는 데 유용합니다.
+
`--revs` 또는 `--revs`를 의미하는 옵션(예: `--all`)과는 호환되지 않지만,
`--unpacked`와는 호환됩니다.

--cruft::
	도달 불가능한 객체를 별도의 "cruft" 팩으로 압축합니다. 이는
	`.mtimes` 파일의 존재로 표시됩니다. 일반적으로 `git
	repack --cruft`에서 사용됩니다. 호출자는 팩 이름을 목록으로 제공하고
	어떤 팩이 저장소에 남아 있을지, 어떤 팩이 삭제될지 ( `-` 접두사로 표시)
	를 나타냅니다. cruft 팩의 내용은 생존 팩에 포함되지 않고 유예 기간을
	초과하지 않은 (아래 `--cruft-expiration` 참조) 모든 객체, 또는
	유예 기간을 초과했지만 아직 초과하지 않은 다른 객체에서 도달 가능한
	모든 객체입니다.
+
입력이 모든 도달 가능한 객체를 포함하는 팩(그리고 삭제될 모든 다른 팩을 나열하는)을
나열할 때, 해당 cruft 팩은 유예 기간보다 최신 mtime을 가진 모든 도달 불가능한
객체와 유예 기간보다 오래된 mtime을 가지지만 최신 mtime을 가진 다른 도달 불가능한
객체에서 도달 가능한 모든 객체를 포함합니다.
+
`--unpack-unreachable`, `--keep-unreachable`, `--pack-loose-unreachable`, `--stdin-packs`와
`--revs`를 의미하는 기타 옵션과는 호환되지 않습니다.

--cruft-expiration=<approxidate>::
	지정된 경우, 객체는 mtime이 `<approxidate>`보다 오래된 경우 cruft 팩에서
	제거됩니다. 지정되지 않은 경우( `--cruft`가 주어짐), 객체가 제거되지
	않습니다.

--window=<n>::
--depth=<n>::
	이 두 옵션은 팩에 포함된 객체가 델타 압축을 사용하여 어떻게
	저장되는지에 영향을 미칩니다. 객체는 먼저 유형, 크기 및 선택적으로
	이름별로 내부적으로 정렬되고 --window 내의 다른 객체와 비교되어
	델타 압축이 공간을 절약하는지 확인합니다. --depth는 최대 델타 깊이를
	제한합니다. 너무 깊게 만들면 언패커 측의 성능에 영향을 미칩니다.
	왜냐하면 델타 데이터를 필요한 객체에 도달하기 위해 그만큼 많이
	적용해야 하기 때문입니다.
+
--window의 기본값은 10이고 --depth는 50입니다. 최대 깊이는 4095입니다.

--window-memory=<n>::
	이 옵션은 `--window` 위에 추가 제한을 제공합니다. 창 크기는
	'<n>' 바이트 이상의 메모리를 사용하지 않도록 동적으로 조정됩니다.
	이는 대형 및 소형 객체가 혼합된 저장소에서 대형 창으로 인해
	메모리가 부족하지 않도록 하고, 소형 객체에 대해서는 대형 창의
	이점을 여전히 활용할 수 있도록 하는 데 유용합니다. 크기는 "k", "m" 또는
	"g"로 접미사를 붙일 수 있습니다.
	`--window-memory=0`은 메모리 사용량을 무제한으로 합니다. 기본값은
	`pack.windowMemory` 구성 변수에서 가져옵니다.

--max-pack-size=<n>::
	특이한 시나리오에서는 파일 시스템에서 특정 크기보다 큰 파일을
	만들 수 없는 경우가 있을 수 있으며, 이 옵션을 사용하여 출력
	packfile을 지정된 크기보다 크지 않은 여러 개의 독립적인 packfile로
	분할하도록 명령에 알릴 수 있습니다. 크기는 "k", "m" 또는 "g"로
	접미사를 붙일 수 있습니다. 최소 허용 크기는 1 MiB로 제한됩니다.
	기본값은 무제한이지만, `pack.packSizeLimit` 구성 변수가
	설정되지 않은 경우입니다. 이 옵션은 저장소를 더 크고 느리게 만들 수
	있습니다. `pack.packSizeLimit`의 토론을 참조하십시오.

--honor-pack-keep::
	이 플래그는 이미 로컬 팩에 있고 `.keep` 파일이 있는 객체를
	건너뛰게 합니다. 해당 객체가 그렇지 않았다면 패킹되었더라도
	무시됩니다.

--keep-pack=<pack-name>::
	이 플래그는 이미 지정된 팩에 있는 객체를 건너뛰게 합니다.
	해당 객체가 그렇지 않았다면 패킹되었더라도 무시됩니다.
	`<pack-name>`은 선행 디렉토리를 제외한 팩 파일 이름입니다 (예:
	`pack-123.pack`). 이 옵션은 여러 팩을 유지하기 위해 여러 번
	지정될 수 있습니다.

--incremental::
	이 플래그는 이미 팩에 있는 객체를 건너뛰게 합니다.
	해당 객체가 그렇지 않았다면 패킹되었더라도 무시됩니다.

--local::
	이 플래그는 대체 객체 저장소에서 빌려온 객체를 건너뛰게 합니다.
	해당 객체가 그렇지 않았다면 패킹되었더라도 무시됩니다.

--non-empty::
	패킹된 아카이브에 객체가 하나 이상 포함될 경우에만 생성합니다.

--progress::
	-q가 지정되지 않은 경우, 진행 상태는 기본적으로 터미널에 연결된
	경우 표준 오류 스트림에 보고됩니다. 이 플래그는 표준 오류 스트림이
	터미널로 리디렉션되지 않은 경우에도 진행 상태를 강제합니다.

--all-progress::
	--stdout이 지정되면 객체 수집 및 압축 단계 중에 진행 보고서가
	표시되지만 쓰기 단계 중에는 억제됩니다. 그 이유는 일부 경우에
	출력 스트림이 들어오는 팩 데이터를 처리하는 자체 진행 상태를
	표시하려는 다른 명령에 직접 연결되기 때문입니다.
	이 플래그는 --progress와 유사하지만 --stdout이 사용되는 경우에도
	쓰기 단계에 대한 진행 보고를 강제한다는 점을 제외하고는 동일합니다.

--all-progress-implied::
	진행 표시가 활성화될 때마다 --all-progress를 암시하는 데 사용됩니다.
	--all-progress와 달리 이 플래그는 자체적으로 진행 표시를 강제하지
	않습니다.

-q::
	이 플래그는 명령이 표준 오류 스트림에 진행 상태를 보고하지 않도록
	합니다.

--no-reuse-delta::
	기존 팩이 있는 저장소에서 압축된 아카이브를 생성할 때, 명령은
	기존 델타를 재사용합니다.
	이것은 때때로 약간 최적이 아닌 팩을 생성합니다.
	이 플래그는 명령에게 기존 델타를 재사용하지 않고 처음부터
	계산하도록 지시합니다.

--no-reuse-object::
	이 플래그는 델타로 지정되지 않은 객체를 포함하여 기존 객체 데이터를
	전혀 재사용하지 않고 모든 것을 다시 압축하도록 명령에 지시합니다.
	이것은 --no-reuse-delta를 의미합니다. 패킹된 데이터에 대한
	전면적인 압축 수준 적용을 원하는 경우에만 유용합니다.

--compression=<n>::
	생성된 팩에서 새로 압축된 데이터에 대한 압축 수준을 지정합니다.
	지정되지 않은 경우, 팩 압축 수준은 먼저 pack.compression,
	그다음 core.compression에 의해 결정되며, 둘 다 설정되지 않은 경우
	zlib 기본값인 -1로 기본 설정됩니다.
	모든 데이터에 대해 일관된 압축 수준을 강제하려면 --no-reuse-object를
	추가하십시오.

--sparse::
--no-sparse::
	"--revs" 옵션과 함께 사용할 때 팩에 포함할 객체를 결정하는
	"sparse" 알고리즘을 전환합니다. 이 알고리즘은 새 객체를 도입하는
	경로만 탐색합니다.
	작은 변경 사항을 보내기 위한 팩을 계산할 때 상당한 성능 이득을
	가질 수 있습니다. 그러나 포함된 커밋에 특정 유형의 직접적인 이름 바꾸기가
	포함된 경우 pack-file에 추가 객체가 추가될 수 있습니다. 이 옵션이
	포함되지 않으면 `pack.useSparse`의 값으로 기본 설정되며, 이는
	다르게 지정되지 않는 한 true입니다.

--thin::
	송신자와 수신자 간의 공통 객체를 생략하여 네트워크 전송을 줄이는
	"thin" 팩을 생성합니다. 이 옵션은 --stdout과 함께 사용할 때만
	의미가 있습니다.
+
참고: thin 팩은 필수 객체를 생략하여 압축된 아카이브 형식 위반이며,
따라서 self-contained 상태로 만들지 않고는 Git에서 사용할 수 없습니다.
self-contained 속성을 복원하려면 `git index-pack --fix-thin`
(linkgit:git-index-pack[1] 참조)을 사용하십시오.

--shallow::
	얕은 저장소를 가진 클라이언트에 제공될 팩을 최적화합니다.
	이 옵션은 --thin과 함께 사용하면 속도를 희생하는 대신 더 작은
	팩을 생성할 수 있습니다.

--delta-base-offset::
	압축된 아카이브는 델타의 기본 객체를 20바이트 객체 이름 또는
	스트림의 오프셋으로 표현할 수 있지만, 이전 버전의 Git은 후자를
	이해하지 못합니다. 기본적으로 'git pack-objects'는 호환성을
	위해 전자의 형식만 사용합니다. 이 옵션을 사용하면 명령이
	압축성을 위해 후자의 형식을 사용할 수 있습니다.
	평균 델타 체인 길이에 따라 이 옵션은 일반적으로 결과
	packfile을 3-5% 축소합니다.
+
참고: `git gc` (linkgit:git-gc[1]), `git repack` (linkgit:git-repack[1])와
같은 포셀린 명령은 최신 Git에서 기본적으로 이 옵션을 객체를
팩 파일에 넣을 때 전달합니다. `git bundle` (linkgit:git-bundle[1])도
번들을 생성할 때 동일하게 전달합니다.

--threads=<n>::
	최적의 델타 일치를 찾는 데 스폰할 스레드 수를 지정합니다.
	이것은 pack-objects가 pthreads로 컴파일되어야 하며, 그렇지 않으면
	이 옵션은 경고와 함께 무시됩니다.
	이것은 다중 프로세서 기계에서 패킹 시간을 줄이기 위한 것입니다.
	하지만 델타 검색 창에 필요한 메모리 양은 스레드 수에 의해 곱해집니다.
	0을 지정하면 Git이 CPU 수를 자동 감지하여 스레드 수를 그에 맞게
	설정합니다.

--index-version=<version>[,<offset>]::
	이것은 테스트 스위트 전용입니다. 생성된 팩 인덱스의 버전을
	강제하고 주어진 오프셋 위에 있는 객체에 대해 64비트 인덱스 항목을
	강제할 수 있습니다.

--keep-true-parents::
	이 옵션을 사용하면 grafts에 의해 숨겨진 부모들도 함께 패킹됩니다.

--filter=<filter-spec>::
	결과 packfile에서 특정 객체(일반적으로 blob)를 생략합니다.
	유효한 `<filter-spec>` 형식은 linkgit:git-rev-list[1]을 참조하십시오.

--no-filter::
	이전의 모든 `--filter=` 인수를 비활성화합니다.

--missing=<missing-action>::
	향후 "partial clone" 개발을 돕기 위한 디버그 옵션입니다.
	이 옵션은 누락된 객체가 어떻게 처리되는지 지정합니다.
+
`--missing=error` 형식은 누락된 객체가 발견되면 pack-objects가 오류로
중단하도록 요청합니다. 저장소가 partial clone인 경우, 누락된 객체가
감지되기 전에 해당 객체를 페치하려는 시도가 이루어집니다. 이것이 기본
동작입니다.
+
`--missing=allow-any` 형식은 누락된 객체가 발견되어도 객체 탐색을
계속 진행하도록 허용합니다. 누락된 객체 페치는 발생하지 않습니다.
누락된 객체는 조용히 결과에서 생략됩니다.
+
`--missing=allow-promisor` 형식은 `allow-any`와 유사하지만
예상되는 promisor 누락 객체에 대해서만 객체 탐색을 계속 진행하도록
허용합니다. 누락된 객체 페치는 발생하지 않습니다. 예상치 못한
누락 객체는 오류를 발생시킵니다.

--exclude-promisor-objects::
	Promisor 원격에 있는 것으로 알려진 객체를 생략합니다. (이 옵션은
	로컬에서 생성된 객체만 작동하도록 하는 목적입니다. 따라서 우리가
	다시 패킹할 때 로컬에서 생성된 객체(.promisor 없음)와 promisor
	원격의 객체(.promisor 있음) 간의 구분을 유지합니다.) 이는 partial
	clone과 함께 사용됩니다.

--keep-unreachable::
	--unpacked= 옵션으로 이름이 지정된 팩의 ref에서 도달 불가능한
	객체는 도달 가능한 객체 외에 결과 팩에 추가됩니다. 이는 `--revs`를
	의미합니다.

--pack-loose-unreachable::
	도달 불가능한 느슨한 객체를 패킹합니다(해당 느슨한 객체는 제거됨).
	이는 `--revs`를 의미합니다.

--unpack-unreachable::
	도달 불가능한 객체를 느슨한 형식으로 유지합니다. 이는 `--revs`를
	의미합니다.

--delta-islands::
	"islands"를 기반으로 델타 일치를 제한합니다. 아래 DELTA ISLANDS 참조.

--name-hash-version=<n>::
	델타 압축을 수행하는 동안 Git은 객체의 경로를 사용하는 휴리스틱을
	기반으로 유사할 수 있는 객체를 그룹화합니다. 정확한 경로 일치로
	객체를 그룹화하는 것은 버전이 많은 경로에 좋지만, 다른 전체 경로에서
	델타 쌍을 찾는 데 이점이 있습니다. Git은 객체를 유형별로, 그런 다음
	경로의 "이름 해시"별로, 그런 다음 크기별로 수집하여 함께 잘 압축될
	객체를 그룹화하려고 합니다.
+
기본 이름 해시 버전은 `1`이며, 경로의 마지막 바이트를 해시 함수에
최대 크기를 제공하는 것으로 간주하여 해시 지역성을 우선합니다. 이 버전은
짧은 경로를 구별하고 디렉토리 간 이름 바꾸기를 찾는 데 탁월합니다. 그러나
해시 함수는 주로 경로의 마지막 16바이트에 의존합니다. 저장소에 마지막 16바이트가
같고 상위 디렉토리만 다른 경로가 많은 경우, 이 이름 해시는 너무 많은
충돌을 유발하여 좋지 않은 결과를 초래할 수 있습니다. 현재 이 버전은
도달 가능성 비트맵 파일을 `--write-bitmap-index`로 작성할 때 필요합니다.
+
이름 해시 버전 `2`는 버전 `1`과 유사한 지역성 기능을 가지고 있지만,
각 경로 구성 요소를 별도로 고려하고 해시를 시프트와 함께 오버레이합니다.
이는 여전히 경로의 마지막 바이트를 우선하지만, 부모 디렉토리 이름을
사용하여 해시의 하위 비트를 "솔트"합니다. 이 방법은 버전 `1`의
지역성 이점 중 일부를 제공하는 동시에 다른 디렉토리에 나타나는 유사한
이름의 파일 충돌을 대부분 깨뜨립니다. 현재 이 버전은 `--write-bitmap-index`로
도달 가능성 비트맵 파일을 작성할 때 허용되지 않으며 버전 `1`로 자동
변경됩니다.

--path-walk::
	객체를 경로별로 먼저 구성하고, 두 번째 패스에서 경로를 일반적인
	방식으로 압축하는 방식으로 압축을 수행합니다. 이는 Git의 기본
	이름 해시 알고리즘에서 충돌을 유발하는 파일 이름이 있는 경우 델타
	압축을 향상시킬 잠재력이 있습니다.
+
`--delta-islands`, `--shallow` 또는 `--filter`와 호환되지 않습니다.
`--use-bitmap-index` 옵션은 `--path-walk`가 있는 경우 무시됩니다.


DELTA ISLANDS
-------------

가능한 경우, `pack-objects`는 기존 온디스크 델타를 재사용하여
온플라이로 새 델타를 검색할 필요성을 피하려고 합니다. 이것은 페치를
서빙하는 데 중요한 최적화입니다. 왜냐하면 서버가 대부분의 객체를
팽창시키지 않고 디스크에서 직접 바이트를 보낼 수 있기 때문입니다.
객체가 수신자가 가지고 있지 않거나(그리고 우리가 아직 보내고 있지 않은)
기반에 대한 델타로 저장될 때 이 최적화는 작동할 수 없습니다. 그런 경우
서버는 델타를 "깨뜨리고" 새로운 델타를 찾아야 하며, 이는 높은 CPU 비용이
듭니다. 따라서 성능을 위해 온디스크 델타 관계의 객체 집합이 클라이언트가
가져올 것과 일치하는 것이 중요합니다.

정상적인 저장소에서는 일반적으로 자동으로 작동합니다. 객체는 대부분
브랜치와 태그에서 도달 가능하며, 이는 클라이언트가 가져오는 것입니다.
서버에서 찾는 델타는 클라이언트가 가지고 있거나 가질 객체 간의 것일
가능성이 높습니다.

하지만 일부 저장소 설정에서는 여러 관련성이 있지만 별개의 ref tip 그룹이
있을 수 있으며, 클라이언트는 이러한 그룹을 독립적으로 가져오는 경향이
있습니다. 예를 들어, 단일 공유 객체 저장소에서 여러 "포크" 저장소를
호스팅하고 `GIT_NAMESPACE` 또는 대체 메커니즘을 사용하는 별도의 저장소를
통해 클라이언트가 별도의 저장소로 볼 수 있다고 상상해 보세요. 단순한
다시 패킹은 객체에 대한 최적의 델타가 다른 포크에만 있는 기반에 대한
것임을 발견할 수 있습니다. 그러나 클라이언트가 가져올 때, 그들은 기반
객체를 가지고 있지 않으므로, 우리는 온플라이로 새 델타를 찾아야 합니다.

`refs/heads/` 및 `refs/tags/` 외부의 많은 ref(예: 일부 호스팅
공급자가 사용하는 `refs/pull` 또는 `refs/changes`)를 관련 객체에
가리키는 경우에도 유사한 상황이 발생할 수 있습니다. 기본적으로 클라이언트는
heads와 tags만 가져오며, 이러한 다른 그룹에만 있는 객체에 대한 델타는
그대로 보낼 수 없습니다.

Delta islands는 이러한 문제를 해결하기 위해 ref를 별도의 "islands"로
그룹화할 수 있도록 합니다. Pack-objects는 어떤 객체가 어떤 island에서
도달 가능한지 계산하고, 객체 `A`에 대해 `A`의 모든 island에 존재하지 않는
기반에 대한 델타를 만드는 것을 거부합니다. 이는 약간 더 큰 팩을 생성하지만
(일부 델타 기회를 놓치기 때문에), 하나의 island를 가져올 때 island 경계를
넘어 델타를 다시 계산해야 할 필요가 없음을 보장합니다.

델타 island를 사용하는 다시 패킹 시 델타 창은 구성에 의해 금지된
후보로 막히는 경향이 있습니다. 큰 `--window`로 다시 패킹하면 도움이 됩니다
(그리고 콘텐츠에 대한 계산을 수행하기 전에 일부 객체 쌍을 거부할 수 있기
때문에 이전만큼 시간이 오래 걸리지 않을 수 있습니다).

Island는 `pack.island` 옵션을 통해 구성되며, 여러 번 지정할 수 있습니다.
각 값은 refname을 일치시키는 왼쪽으로 고정된 정규 표현식입니다. 예를 들어:

-------------------------------------------
[pack]
island = refs/heads/
island = refs/tags/
-------------------------------------------

은 heads와 tags를 island(이름은 빈 문자열, 아래에서 명명에 대해 더 자세히
설명)에 넣습니다. 이러한 정규 표현식과 일치하지 않는 ref(예: `refs/pull/123`)는
어떤 island에도 속하지 않습니다. `refs/pull/`에서만 도달 가능한
(하지만 heads 또는 tags는 아님) 객체는 따라서 `refs/heads/`의 기반으로
사용될 후보가 아닙니다.

Ref는 "이름"을 기반으로 island로 그룹화되며, 동일한 이름을 생성하는
두 개의 regex는 같은 island에 있는 것으로 간주됩니다. 이름은 regex에서
캡처 그룹을 밑줄(-)로 연결하여 계산됩니다. (캡처 그룹이 없으면 이름은
위의 예에서와 같이 빈 문자열입니다.) 이를 통해 임의 개수의 island를
생성할 수 있습니다. 그러나 최대 14개의 이러한 캡처 그룹만 지원됩니다.

예를 들어, 각 포크의 ref를 `refs/virtual/ID`에 저장한다고 가정해 봅시다.
여기서 `ID`는 숫자 식별자입니다. 그런 다음 다음과 같이 구성할 수 있습니다.

-------------------------------------------
[pack]
island = refs/virtual/([0-9]+)/heads/
island = refs/virtual/([0-9]+)/tags/
island = refs/virtual/([0-9]+)/(pull)/
-------------------------------------------

이는 각 포크의 heads와 tags를 자체 island( "1234" 또는 유사한 이름)에
넣고, 각 포크의 pull ref를 자체 "1234-pull"로 넣습니다.

참고로 "마지막 승자" 순서(기본 구성을 넘어선 리포지토리별 구성이 우선하도록
함)를 사용하여 각 regex에 대해 단일 island를 선택합니다.


CONFIGURATION
-------------

다양한 구성 변수가 패킹에 영향을 미칩니다. linkgit:git-config[1]
( "pack" 및 "delta" 검색)을 참조하십시오.

특히, 델타 압축은 `core.bigFileThreshold` 구성 변수보다 큰 객체나
`delta` 속성이 false로 설정된 파일에는 사용되지 않습니다.

SEE ALSO
--------
linkgit:git-rev-list[1]
linkgit:git-repack[1]
linkgit:git-prune-packed[1]

GIT
---
linkgit:git[1] 제품군의 일부